USPDesigner: C:/USPDesig/PROP.CPP File Reference
C:/USPDesig/PROP.CPP File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "genfunc_.h"
#include "analise_.h"
#include "prop.h"
#include "mancommd.h"
Functions
real MSD_highNamePropriedadeArea (char *name)
real MSD_highPropriedadeArea (Id sn)
double MSD_lowPropriedadeArea (SPTYPE s)
double MSD_lowPropriedadeAreaFace (FPTYPE f)
double MSD_lowPropriedadeAreaLaco (LPTYPE l)
void MSD_execManipulatePropriedade (void)
Function Documentation
void MSD_execManipulatePropriedade (void)
Definition at line 20 of file PROP.CPP.
References lineins(), MSD_highNamePropriedadeArea(), optin(), and restbuf.
real MSD_highNamePropriedadeArea (char * name)
Definition at line 80 of file PROP.CPP.
References ERROR, MSD_getSolidIdFromName(), and MSD_highArea().
Referenced by MSD_execManipulatePropriedade().
real MSD_highPropriedadeArea (Id sn)
Definition at line 91 of file PROP.CPP.
References MSD_getSolid(), MSD_lowPropriedadeArea(), SNIL, and SPTYPE.
double MSD_lowPropriedadeArea (SPTYPE s)
Definition at line 102 of file PROP.CPP.
References DNIL, DPTYPE, FacNextF, FNIL, FPTYPE, MSD_lowPropriedadeAreaFace(), SheNextD, SheSFaces, and SolSShells.
Referenced by MSD_highPropriedadeArea().
double MSD_lowPropriedadeAreaFace (FPTYPE f)
Definition at line 114 of file PROP.CPP.
References FacFLoops, FacFLOut, LNIL, LooNextL, LPTYPE, and MSD_lowPropriedadeAreaLaco().
Referenced by MSD_lowPropriedadeArea().
double MSD_lowPropriedadeAreaLaco (LPTYPE l)
Definition at line 127 of file PROP.CPP.
References cross(), dot(), FacFeq, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLFace, veccopy(), vecminus(), vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_lowPropriedadeAreaFace().