USPDesigner: C:/USPDesig/ANA/anaaproj.cpp File Reference
C:/USPDesig/ANA/anaaproj.cpp File Reference
#include <stdio.h>
#include <graphics.h>
#include <conio.h>
#include <math.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "analise_.h"
#include "basrov__.h"
#include "shpshape.h"
#include "sethmain.h"
Functions
double MSD_lowSolidAreaProjetada (SPTYPE s)
void MSD_execNameAreaProjetada (void)
int MSD_highNameAreaProjetada (char *name, real dx, real dy, real dz, real *area, real *dim)
int MSD_highAreaProjetada (Id sn, real dx, real dy, real dz, real *area, real *dim)
int MSD_lowAreaProjetada (SPTYPE s, real dx, real dy, real dz, real *area, real *dim, int flag)
void MSD_lowMakeUnion (FPTYPE f, vector dir)
void MSD_lowMoveFace (FPTYPE f, vector dir)
SPTYPE MSD_CriaListaDePoligonosCoplanares (SPTYPE s, vector dir)
int MSD_lowMaximaDirecao (vector p)
void MSD_lowRebatePontoNoPlano (vector p2, vector pp, vector dir)
real MSD_lowModuloReal (real num)
double MSD_lowSolidDimensaoPrincipal (SPTYPE s, vector normal)
Function Documentation
SPTYPE MSD_CriaListaDePoligonosCoplanares (SPTYPE s, vector dir)
Definition at line 247 of file anaaproj.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacFlag, FPTYPE, MSD_lowFindSolidByName(), MSD_lowMoveFace(), and SheSFaces.
Referenced by MSD_lowAreaProjetada().
void MSD_execNameAreaProjetada (void)
Definition at line 65 of file anaaproj.cpp.
References lineins(), MSD_highNameAreaProjetada(), and restbuf.
int MSD_highAreaProjetada (Id sn, real dx, real dy, real dz, real * area, real * dim)
Definition at line 96 of file anaaproj.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowAreaProjetada(), NAM_AreaProjetada, SNIL, and SPTYPE.
Referenced by MSD_highNameAreaProjetada().
int MSD_highNameAreaProjetada (char * name, real dx, real dy, real dz, real * area, real * dim)
Definition at line 83 of file anaaproj.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highAreaProjetada(), and NAM_AreaProjetada.
Referenced by MSD_execNameAreaProjetada().
int MSD_lowAreaProjetada (SPTYPE s, real dx, real dy, real dz, real * area, real * dim, int flag)
Definition at line 109 of file anaaproj.cpp.
References makevec(), MSD_CriaListaDePoligonosCoplanares(), MSD_highNameSoftRemove(), MSD_lowSolidAreaProjetada(), MSD_lowSolidDimensaoPrincipal(), SPTYPE, and SUCCESS.
Referenced by MSD_CalculaParametrosInterferencia(), MSD_highAreaProjetada(), and MSD_lowAreaProjetadaTotal().
void MSD_lowMakeUnion (FPTYPE f, vector dir)
Definition at line 128 of file anaaproj.cpp.
References AllLoopsFace, dot(), EPS, FacFeq, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_getSolidIdFromName(), MSD_highNameDifference(), MSD_highNameMakePrism(), MSD_highNameRenameSolid(), MSD_highNameUnion(), MSD_lowRebatePontoNoPlano(), VerVCoord, XY::x, and XY::y.
Referenced by MSD_lowMoveFace().
int MSD_lowMaximaDirecao (vector p)
Definition at line 265 of file anaaproj.cpp.
References MSD_lowModuloReal().
real MSD_lowModuloReal (real num)
Definition at line 304 of file anaaproj.cpp.
Referenced by MSD_lowMaximaDirecao().
void MSD_lowMoveFace (FPTYPE f, vector dir)
Definition at line 207 of file anaaproj.cpp.
References AllLoopsFace, FacFlag, FacFLOut, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, mate, MSD_lowMakeUnion(), and MSD_lowMoveFace().
Referenced by MSD_CriaListaDePoligonosCoplanares(), and MSD_lowMoveFace().
void MSD_lowRebatePontoNoPlano (vector p2, vector pp, vector dir)
Definition at line 282 of file anaaproj.cpp.
References cross(), dot(), makevec(), normalize(), rotmat(), and vecmult().
Referenced by MSD_lowMakeUnion(), and MSD_lowSetVariaveisImpressao().
double MSD_lowSolidAreaProjetada (SPTYPE s)
Definition at line 309 of file anaaproj.cpp.
References AllFacesShell, AllShellsSolid, dot(), DPTYPE, FacFeq, FPTYPE, makevec(), and MSD_lowFaceArea().
Referenced by MSD_lowAreaProjetada(), and MSD_lowAreaProjetadaTotal().
double MSD_lowSolidDimensaoPrincipal (SPTYPE s, vector normal)
Definition at line 331 of file anaaproj.cpp.
References AllFacesShell, AllShellsSolid, dot(), DPTYPE, FacFeq, FacFLoops, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, veccopy(), vecd(), and VerVCoord.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_lowAreaProjetada(), and MSD_lowAreaProjetadaTotal().