USPDesigner: C:/USPDesig/ANA/anaarea_.cpp File Reference
C:/USPDesig/ANA/anaarea_.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "genfunc_.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameArea (void)
real MSD_highNameArea (char *name)
real MSD_highArea (Id sn)
real MSD_lowLoopArea (LPTYPE l)
real MSD_lowFaceArea (FPTYPE f)
real MSD_lowSolidArea (SPTYPE s)
Function Documentation
void MSD_execNameArea (void)
Definition at line 53 of file anaarea_.cpp.
References lineins(), MSD_highNameArea(), and restbuf.
real MSD_highArea (Id sn)
Definition at line 98 of file anaarea_.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSolidArea(), NAM_Area, SNIL, and SPTYPE.
Referenced by MSD_highNameArea(), and MSD_highNamePropriedadeArea().
real MSD_highNameArea (char * name)
Definition at line 68 of file anaarea_.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highArea(), and NAM_Area.
Referenced by MSD_execNameArea().
real MSD_lowFaceArea (FPTYPE f)
Definition at line 133 of file anaarea_.cpp.
References FacFLoops, LNIL, LooNextL, LPTYPE, and MSD_lowLoopArea().
Referenced by MSD_lowSolidArea(), and MSD_lowSolidAreaProjetada().
real MSD_lowLoopArea (LPTYPE l)
Definition at line 111 of file anaarea_.cpp.
References cross(), dot(), FacFeq, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLFace, veccopy(), vecminus(), vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_lowFaceArea().
real MSD_lowSolidArea (SPTYPE s)
Definition at line 145 of file anaarea_.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, and MSD_lowFaceArea().
Referenced by MSD_highArea().