USPDesigner: C:/USPDesig/ANA/anacgtot.cpp File Reference
C:/USPDesig/ANA/anacgtot.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execCentroMassaTotal (void)
void MSD_lowCentroMassaTotal (vector ctotal)
Function Documentation
void MSD_execCentroMassaTotal (void)
Definition at line 52 of file anacgtot.cpp.
References MSD_lowCentroMassaTotal().
void MSD_lowCentroMassaTotal (vector ctotal)
Definition at line 60 of file anacgtot.cpp.
References AllSolids, MSD_lowCentroDeGravidade(), MSD_lowMassa(), MSD_lowMassaTotal(), SolDensRel, SPTYPE, and veczer().
Referenced by MSD_execCentroMassaTotal(), and MSD_lowAnaliseShow().