USPDesigner: C:/USPDesig/ANA/anacentg.cpp File Reference
C:/USPDesig/ANA/anacentg.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "analise_.h"
Functions
void MSD_execNameCentroDeGravidade (void)
int MSD_highNameCentroDeGravidade (char *name, vector vec)
int MSD_highCentroDeGravidade (Id sn, vector vec)
int MSD_lowCentroDeGravidade (SPTYPE s, vector centg)
Function Documentation
void MSD_execNameCentroDeGravidade (void)
Definition at line 53 of file anacentg.cpp.
References lineins(), MSD_highNameCentroDeGravidade(), and restbuf.
int MSD_highCentroDeGravidade (Id sn, vector vec)
Definition at line 84 of file anacentg.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroDeGravidade(), NAM_CentroGravidade, SNIL, and SPTYPE.
int MSD_highNameCentroDeGravidade (char * name, vector vec)
Definition at line 72 of file anacentg.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCentroCarena(), and NAM_CentroGravidade.
Referenced by MSD_execNameCentroDeGravidade().
int MSD_lowCentroDeGravidade (SPTYPE s, vector centg)
Definition at line 97 of file anacentg.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowVolume(), SUCCESS, vecminus(), veczer(), and VerVCoord.
Referenced by MSD_highCentroDeGravidade(), MSD_highMatrizInercia(), MSD_lowCentroCarena(), MSD_lowCentroMassaTotal(), and MSD_lowCriaListaEstudo().