USPDesigner: C:/USPDesig/ANA/anacaren.cpp File Reference
C:/USPDesig/ANA/anacaren.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameCentroCarena (void)
int MSD_highNameCentroCarena (char *name, vector vec)
int MSD_highCentroCarena (Id sn, vector vec)
int MSD_lowCentroCarena (SPTYPE s, vector ctotal)
Function Documentation
void MSD_execNameCentroCarena (void)
Definition at line 53 of file anacaren.cpp.
References lineins(), MSD_highNameCentroCarena(), and restbuf.
int MSD_highCentroCarena (Id sn, vector vec)
Definition at line 83 of file anacaren.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroCarena(), NAM_CentroCarena, SNIL, and SPTYPE.
Referenced by MSD_highNameCentroCarena(), and MSD_highNameCentroDeGravidade().
int MSD_highNameCentroCarena (char * name, vector vec)
Definition at line 71 of file anacaren.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCentroCarena(), and NAM_CentroCarena.
Referenced by MSD_execNameCentroCarena().
int MSD_lowCentroCarena (SPTYPE s, vector ctotal)
Definition at line 95 of file anacaren.cpp.
References MSD_lowCentroDeGravidade(), and SUCCESS.
Referenced by MSD_highCentroCarena(), and MSD_lowCentroCarenaTotal().