USPDesigner: C:/USPDesig/ANA/anadensa.cpp File Reference
C:/USPDesig/ANA/anadensa.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameDensidadeAbsoluta (void)
int MSD_highNameDensidadeAbsoluta (char *name, real densrel)
int MSD_highDensidadeAbsoluta (Id sn, real densrel)
int MSD_lowDensidadeAbsoluta (SPTYPE s, real densrel)
Function Documentation
void MSD_execNameDensidadeAbsoluta (void)
Definition at line 53 of file anadensa.cpp.
References lineins(), MSD_highNameDensidadeAbsoluta(), and restbuf.
int MSD_highDensidadeAbsoluta (Id sn, real densrel)
Definition at line 81 of file anadensa.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowDensidadeAbsoluta(), NAM_DensAbs, SNIL, and SPTYPE.
Referenced by MSD_highNameDensidadeAbsoluta().
int MSD_highNameDensidadeAbsoluta (char * name, real densrel)
Definition at line 69 of file anadensa.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDensidadeAbsoluta(), and NAM_DensAbs.
Referenced by MSD_execNameDensidadeAbsoluta().
int MSD_lowDensidadeAbsoluta (SPTYPE s, real densrel)
Definition at line 93 of file anadensa.cpp.
References ERROR, SolDensAbs, SolDensRel, and SUCCESS.
Referenced by MSD_highDensidadeAbsoluta().