USPDesigner: C:/USPDesig/ANA/anadensi.cpp File Reference
C:/USPDesig/ANA/anadensi.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameDensidadeRelativa (void)
int MSD_highNameDensidadeRelativa (char *name, real densrel)
int MSD_highDensidadeRelativa (Id sn, real densrel)
int MSD_lowDensidadeRelativa (SPTYPE s, real densrel)
Function Documentation
void MSD_execNameDensidadeRelativa (void)
Definition at line 53 of file anadensi.cpp.
References lineins(), MSD_highNameDensidadeRelativa(), and restbuf.
int MSD_highDensidadeRelativa (Id sn, real densrel)
Definition at line 81 of file anadensi.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowDensidadeRelativa(), NAM_DensRel, SNIL, and SPTYPE.
Referenced by MSD_highNameDensidadeRelativa().
int MSD_highNameDensidadeRelativa (char * name, real densrel)
Definition at line 69 of file anadensi.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDensidadeRelativa(), and NAM_DensRel.
Referenced by MSD_execNameDensidadeRelativa().
int MSD_lowDensidadeRelativa (SPTYPE s, real densrel)
Definition at line 93 of file anadensi.cpp.
References ERROR, SolDensAbs, SolDensRel, and SUCCESS.
Referenced by MSD_highDensidadeRelativa().