USPDesigner: C:/USPDesig/ANA/anaintot.cpp File Reference
C:/USPDesig/ANA/anaintot.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execMatrizInerciaTotal (void)
void MSD_lowMatrizInerciaTotal (matrix mat)
Function Documentation
void MSD_execMatrizInerciaTotal (void)
Definition at line 52 of file anaintot.cpp.
References MSD_lowMatrizInerciaTotal().
void MSD_lowMatrizInerciaTotal (matrix mat)
Definition at line 65 of file anaintot.cpp.
References AllSolids, matplus(), matzer(), MSD_lowCentroCarenaTotal(), MSD_lowMatrizInercia(), SolDensRel, and SPTYPE.
Referenced by MSD_execMatrizInerciaTotal(), and MSD_lowAnaliseShow().