USPDesigner: C:/USPDesig/INC/analise_.h File Reference
C:/USPDesig/INC/analise_.h File Reference
Typedefs
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
Functions
void MSD_execArea (void)
void MSD_execNameArea (void)
real MSD_highArea (Id sn)
real MSD_highNameArea (char *name)
real MSD_lowLoopArea (LPTYPE l)
real MSD_lowFaceArea (FPTYPE f)
real MSD_lowSolidArea (SPTYPE s)
void MSD_execNameAreaProjetada (void)
int MSD_highNameAreaProjetada (char *name, real dx, real dy, real dz, real *area, real *dim)
int MSD_highAreaProjetada (Id sn, real dx, real dy, real dz, real *area, real *dim)
int MSD_lowAreaProjetada (SPTYPE s, real dx, real dy, real dz, real *area, real *dim, int flag)
void MSD_lowMakeUnion (FPTYPE f, vector dir)
void MSD_lowMoveFace (FPTYPE f, vector dir)
SPTYPE MSD_CriaListaDePoligonosCoplanares (SPTYPE s, vector dir)
real MSD_Calcula_Area_da_Uniao (SPTYPE s)
void MSD_lowRebatePontoNoPlano (vector p2, vector pp, vector dir)
real MSD_lowModuloReal (real num)
int MSD_lowMaximaDirecao (vector p)
real MSD_lowSolidDimensaoPrincipal (SPTYPE s, vector normal)
void MSD_execNameCentroCarena (void)
int MSD_highNameCentroCarena (char *name, vector vec)
int MSD_highCentroCarena (Id sn, vector vec)
int MSD_lowCentroCarena (SPTYPE s, vector ctotal)
void MSD_execCentroCarenaTotal (void)
void MSD_lowCentroCarenaTotal (vector ctotal)
void MSD_execNameCentroDeGravidade (void)
int MSD_highNameCentroDeGravidade (char *name, vector centro)
int MSD_highCentroDeGravidade (Id sn, vector vec)
int MSD_lowCentroDeGravidade (SPTYPE s, vector centro)
void MSD_execCentroMassaTotal (void)
void MSD_lowCentroMassaTotal (vector ctotal)
void MSD_execNameDensidadeAbsoluta (void)
int MSD_highNameDensidadeAbsoluta (char *name, real densrel)
int MSD_highDensidadeAbsoluta (Id sn, real densrel)
int MSD_lowDensidadeAbsoluta (SPTYPE s, real densrel)
void MSD_execNameDensidadeRelativa (void)
int MSD_highNameDensidadeRelativa (char *name, real densrel)
int MSD_highDensidadeRelativa (Id sn, real densrel)
int MSD_lowDensidadeRelativa (SPTYPE s, real densrel)
void MSD_execDensidadeFluido (void)
void MSD_lowDensidadeFluido (real dens)
void MSD_execEmpuxoTotal (void)
real MSD_lowEmpuxoTotal (void)
void MSD_execMatrizInerciaTotal (void)
void MSD_lowMatrizInerciaTotal (matrix mat)
void MSD_execNameMassa (void)
real MSD_highNameMassa (char *name)
real MSD_highMassa (Id sn)
real MSD_lowMassa (SPTYPE s)
void MSD_execNameMatrizInercia (void)
int MSD_highNameMatrizInercia (char *name, matrix mat)
int MSD_highMatrizInercia (Id sn, matrix mat)
int MSD_lowMatrizInercia (SPTYPE s, matrix mat, vector cg)
void MSD_execMassaTotal (void)
real MSD_lowMassaTotal (void)
void MSD_execPesoTotal (void)
real MSD_lowPesoTotal (void)
void MSD_execAnaliseShow (void)
void MSD_lowAnaliseShow (char *name)
void MSD_execVolumeFlutuabilidadeTotal (void)
real MSD_lowVolumeFlutuabilidadeTotal (void)
void MSD_execNameVolume (void)
void MSD_execVolume (void)
real MSD_highNameVolume (char *)
real MSD_highVolume (Id sn)
real MSD_lowVolume (SPTYPE s)
void MSD_execVolumeTotal (void)
real MSD_lowVolumeTotal (void)
Typedef Documentation
typedef struct edge ETYPE
Definition at line 63 of file analise_.h.
typedef struct face FTYPE
Definition at line 55 of file analise_.h.
typedef struct halfedge HTYPE
Definition at line 67 of file analise_.h.
typedef struct loop LTYPE
Definition at line 59 of file analise_.h.
typedef struct solid STYPE
Definition at line 51 of file analise_.h.
typedef real vector[4]
Definition at line 47 of file analise_.h.
typedef struct vertex VTYPE
Definition at line 71 of file analise_.h.
Function Documentation
real MSD_Calcula_Area_da_Uniao (SPTYPE s)
SPTYPE MSD_CriaListaDePoligonosCoplanares (SPTYPE s, vector dir)
Definition at line 247 of file anaaproj.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacFlag, FPTYPE, MSD_lowFindSolidByName(), MSD_lowMoveFace(), and SheSFaces.
Referenced by MSD_lowAreaProjetada().
void MSD_execAnaliseShow (void)
Definition at line 53 of file anashow_.cpp.
References lineins(), MSD_lowAnaliseShow(), and restbuf.
void MSD_execArea (void)
void MSD_execCentroCarenaTotal (void)
Definition at line 52 of file anacatot.cpp.
References MSD_lowCentroCarenaTotal().
void MSD_execCentroMassaTotal (void)
Definition at line 52 of file anacgtot.cpp.
References MSD_lowCentroMassaTotal().
void MSD_execDensidadeFluido (void)
Definition at line 52 of file anadflui.cpp.
References lineins(), MSD_lowDensidadeFluido(), and restbuf.
void MSD_execEmpuxoTotal (void)
Definition at line 52 of file anaemtot.cpp.
References MSD_lowEmpuxoTotal().
void MSD_execMassaTotal (void)
Definition at line 52 of file anamtot_.cpp.
References MSD_lowMassaTotal().
void MSD_execMatrizInerciaTotal (void)
Definition at line 52 of file anaintot.cpp.
References MSD_lowMatrizInerciaTotal().
void MSD_execNameArea (void)
Definition at line 53 of file anaarea_.cpp.
References lineins(), MSD_highNameArea(), and restbuf.
void MSD_execNameAreaProjetada (void)
Definition at line 65 of file anaaproj.cpp.
References lineins(), MSD_highNameAreaProjetada(), and restbuf.
void MSD_execNameCentroCarena (void)
Definition at line 53 of file anacaren.cpp.
References lineins(), MSD_highNameCentroCarena(), and restbuf.
void MSD_execNameCentroDeGravidade (void)
Definition at line 53 of file anacentg.cpp.
References lineins(), MSD_highNameCentroDeGravidade(), and restbuf.
void MSD_execNameDensidadeAbsoluta (void)
Definition at line 53 of file anadensa.cpp.
References lineins(), MSD_highNameDensidadeAbsoluta(), and restbuf.
void MSD_execNameDensidadeRelativa (void)
Definition at line 53 of file anadensi.cpp.
References lineins(), MSD_highNameDensidadeRelativa(), and restbuf.
void MSD_execNameMassa (void)
Definition at line 53 of file anamassa.cpp.
References lineins(), MSD_highNameMassa(), and restbuf.
void MSD_execNameMatrizInercia (void)
Definition at line 53 of file anaminrc.cpp.
References lineins(), MSD_highNameMatrizInercia(), and restbuf.
void MSD_execNameVolume (void)
Definition at line 53 of file anavolum.cpp.
References lineins(), MSD_highNameVolume(), and restbuf.
void MSD_execPesoTotal (void)
Definition at line 52 of file anapesot.cpp.
References MSD_lowPesoTotal().
void MSD_execVolume (void)
void MSD_execVolumeFlutuabilidadeTotal (void)
Definition at line 52 of file anavftot.cpp.
References MSD_lowVolumeFlutuabilidadeTotal().
void MSD_execVolumeTotal (void)
Definition at line 52 of file anavtot_.cpp.
References MSD_lowVolumeTotal().
real MSD_highArea (Id sn)
Definition at line 98 of file anaarea_.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSolidArea(), NAM_Area, SNIL, and SPTYPE.
Referenced by MSD_highNameArea(), and MSD_highNamePropriedadeArea().
int MSD_highAreaProjetada (Id sn, real dx, real dy, real dz, real * area, real * dim)
Definition at line 96 of file anaaproj.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowAreaProjetada(), NAM_AreaProjetada, SNIL, and SPTYPE.
Referenced by MSD_highNameAreaProjetada().
int MSD_highCentroCarena (Id sn, vector vec)
Definition at line 83 of file anacaren.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroCarena(), NAM_CentroCarena, SNIL, and SPTYPE.
Referenced by MSD_highNameCentroCarena(), and MSD_highNameCentroDeGravidade().
int MSD_highCentroDeGravidade (Id sn, vector vec)
Definition at line 84 of file anacentg.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroDeGravidade(), NAM_CentroGravidade, SNIL, and SPTYPE.
int MSD_highDensidadeAbsoluta (Id sn, real densrel)
Definition at line 81 of file anadensa.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowDensidadeAbsoluta(), NAM_DensAbs, SNIL, and SPTYPE.
Referenced by MSD_highNameDensidadeAbsoluta().
int MSD_highDensidadeRelativa (Id sn, real densrel)
Definition at line 81 of file anadensi.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowDensidadeRelativa(), NAM_DensRel, SNIL, and SPTYPE.
Referenced by MSD_highNameDensidadeRelativa().
real MSD_highMassa (Id sn)
Definition at line 80 of file anamassa.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowMassa(), NAM_Massa, SNIL, and SPTYPE.
Referenced by MSD_highNameMassa().
int MSD_highMatrizInercia (Id sn, matrix mat)
Definition at line 85 of file anaminrc.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroDeGravidade(), MSD_lowMatrizInercia(), NAM_Inercia, SNIL, and SPTYPE.
Referenced by MSD_highNameMatrizInercia().
real MSD_highNameArea (char * name)
Definition at line 68 of file anaarea_.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highArea(), and NAM_Area.
Referenced by MSD_execNameArea().
int MSD_highNameAreaProjetada (char * name, real dx, real dy, real dz, real * area, real * dim)
Definition at line 83 of file anaaproj.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highAreaProjetada(), and NAM_AreaProjetada.
Referenced by MSD_execNameAreaProjetada().
int MSD_highNameCentroCarena (char * name, vector vec)
Definition at line 71 of file anacaren.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCentroCarena(), and NAM_CentroCarena.
Referenced by MSD_execNameCentroCarena().
int MSD_highNameCentroDeGravidade (char * name, vector centro)
Definition at line 72 of file anacentg.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCentroCarena(), and NAM_CentroGravidade.
Referenced by MSD_execNameCentroDeGravidade().
int MSD_highNameDensidadeAbsoluta (char * name, real densrel)
Definition at line 69 of file anadensa.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDensidadeAbsoluta(), and NAM_DensAbs.
Referenced by MSD_execNameDensidadeAbsoluta().
int MSD_highNameDensidadeRelativa (char * name, real densrel)
Definition at line 69 of file anadensi.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDensidadeRelativa(), and NAM_DensRel.
Referenced by MSD_execNameDensidadeRelativa().
real MSD_highNameMassa (char * name)
Definition at line 68 of file anamassa.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMassa(), and NAM_Massa.
Referenced by MSD_execNameMassa().
int MSD_highNameMatrizInercia (char * name, matrix mat)
Definition at line 73 of file anaminrc.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMatrizInercia(), and NAM_Inercia.
Referenced by MSD_execNameMatrizInercia().
real MSD_highNameVolume (char *)
Definition at line 68 of file anavolum.cpp.
References MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highVolume(), and NAM_Volume.
Referenced by MSD_execNameVolume().
real MSD_highVolume (Id sn)
Definition at line 98 of file anavolum.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowVolume(), NAM_Volume, SNIL, and SPTYPE.
Referenced by MSD_highNameVolume().
void MSD_lowAnaliseShow (char * name)
Definition at line 68 of file anashow_.cpp.
References MSD_lowCentroCarenaTotal(), MSD_lowCentroMassaTotal(), MSD_lowMassaTotal(), MSD_lowMatrizInerciaTotal(), MSD_lowVolumeFlutuabilidadeTotal(), MSD_lowVolumeTotal(), and NIL.
Referenced by MSD_execAnaliseShow().
int MSD_lowAreaProjetada (SPTYPE s, real dx, real dy, real dz, real * area, real * dim, int flag)
Definition at line 109 of file anaaproj.cpp.
References makevec(), MSD_CriaListaDePoligonosCoplanares(), MSD_highNameSoftRemove(), MSD_lowSolidAreaProjetada(), MSD_lowSolidDimensaoPrincipal(), SPTYPE, and SUCCESS.
Referenced by MSD_CalculaParametrosInterferencia(), MSD_highAreaProjetada(), and MSD_lowAreaProjetadaTotal().
int MSD_lowCentroCarena (SPTYPE s, vector ctotal)
Definition at line 95 of file anacaren.cpp.
References MSD_lowCentroDeGravidade(), and SUCCESS.
Referenced by MSD_highCentroCarena(), and MSD_lowCentroCarenaTotal().
void MSD_lowCentroCarenaTotal (vector ctotal)
Definition at line 60 of file anacatot.cpp.
References AllSolids, MSD_lowCentroCarena(), SolDensRel, SPTYPE, vecplus(), and veczer().
Referenced by MSD_execCentroCarenaTotal(), MSD_lowAnaliseShow(), and MSD_lowMatrizInerciaTotal().
int MSD_lowCentroDeGravidade (SPTYPE s, vector centro)
Definition at line 97 of file anacentg.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowVolume(), SUCCESS, vecminus(), veczer(), and VerVCoord.
Referenced by MSD_highCentroDeGravidade(), MSD_highMatrizInercia(), MSD_lowCentroCarena(), MSD_lowCentroMassaTotal(), and MSD_lowCriaListaEstudo().
void MSD_lowCentroMassaTotal (vector ctotal)
Definition at line 60 of file anacgtot.cpp.
References AllSolids, MSD_lowCentroDeGravidade(), MSD_lowMassa(), MSD_lowMassaTotal(), SolDensRel, SPTYPE, and veczer().
Referenced by MSD_execCentroMassaTotal(), and MSD_lowAnaliseShow().
int MSD_lowDensidadeAbsoluta (SPTYPE s, real densrel)
Definition at line 93 of file anadensa.cpp.
References ERROR, SolDensAbs, SolDensRel, and SUCCESS.
Referenced by MSD_highDensidadeAbsoluta().
void MSD_lowDensidadeFluido (real dens)
Definition at line 67 of file anadflui.cpp.
References AllSolids, SolDensAbs, SolDensRel, and SPTYPE.
Referenced by MSD_execDensidadeFluido().
int MSD_lowDensidadeRelativa (SPTYPE s, real densrel)
Definition at line 93 of file anadensi.cpp.
References ERROR, SolDensAbs, SolDensRel, and SUCCESS.
Referenced by MSD_highDensidadeRelativa().
real MSD_lowEmpuxoTotal (void)
Definition at line 57 of file anaemtot.cpp.
References GRAVIDADE, and MSD_lowVolumeFlutuabilidadeTotal().
Referenced by MSD_execEmpuxoTotal().
real MSD_lowFaceArea (FPTYPE f)
Definition at line 133 of file anaarea_.cpp.
References FacFLoops, LNIL, LooNextL, LPTYPE, and MSD_lowLoopArea().
Referenced by MSD_lowSolidArea(), and MSD_lowSolidAreaProjetada().
real MSD_lowLoopArea (LPTYPE l)
Definition at line 111 of file anaarea_.cpp.
References cross(), dot(), FacFeq, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLFace, veccopy(), vecminus(), vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_lowFaceArea().
void MSD_lowMakeUnion (FPTYPE f, vector dir)
Definition at line 128 of file anaaproj.cpp.
References AllLoopsFace, dot(), EPS, FacFeq, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_getSolidIdFromName(), MSD_highNameDifference(), MSD_highNameMakePrism(), MSD_highNameRenameSolid(), MSD_highNameUnion(), MSD_lowRebatePontoNoPlano(), VerVCoord, XY::x, and XY::y.
Referenced by MSD_lowMoveFace().
real MSD_lowMassa (SPTYPE s)
Definition at line 92 of file anamassa.cpp.
References MSD_lowVolume(), and SolDensRel.
Referenced by MSD_highMassa(), and MSD_lowCentroMassaTotal().
real MSD_lowMassaTotal (void)
Definition at line 57 of file anamtot_.cpp.
References AllSolids, MSD_lowVolume(), SolDensRel, and SPTYPE.
Referenced by MSD_execMassaTotal(), MSD_lowAnaliseShow(), MSD_lowCentroMassaTotal(), and MSD_lowPesoTotal().
int MSD_lowMatrizInercia (SPTYPE s, matrix mat, vector cg)
Definition at line 100 of file anaminrc.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, matzer(), SolDensRel, SUCCESS, vecminus(), and VerVCoord.
Referenced by MSD_highMatrizInercia(), and MSD_lowMatrizInerciaTotal().
void MSD_lowMatrizInerciaTotal (matrix mat)
Definition at line 65 of file anaintot.cpp.
References AllSolids, matplus(), matzer(), MSD_lowCentroCarenaTotal(), MSD_lowMatrizInercia(), SolDensRel, and SPTYPE.
Referenced by MSD_execMatrizInerciaTotal(), and MSD_lowAnaliseShow().
int MSD_lowMaximaDirecao (vector p)
Definition at line 265 of file anaaproj.cpp.
References MSD_lowModuloReal().
real MSD_lowModuloReal (real num)
Definition at line 304 of file anaaproj.cpp.
Referenced by MSD_lowMaximaDirecao().
void MSD_lowMoveFace (FPTYPE f, vector dir)
Definition at line 207 of file anaaproj.cpp.
References AllLoopsFace, FacFlag, FacFLOut, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, mate, MSD_lowMakeUnion(), and MSD_lowMoveFace().
Referenced by MSD_CriaListaDePoligonosCoplanares(), and MSD_lowMoveFace().
real MSD_lowPesoTotal (void)
Definition at line 57 of file anapesot.cpp.
References GRAVIDADE, and MSD_lowMassaTotal().
Referenced by MSD_execPesoTotal().
void MSD_lowRebatePontoNoPlano (vector p2, vector pp, vector dir)
Definition at line 282 of file anaaproj.cpp.
References cross(), dot(), makevec(), normalize(), rotmat(), and vecmult().
Referenced by MSD_lowMakeUnion(), and MSD_lowSetVariaveisImpressao().
real MSD_lowSolidArea (SPTYPE s)
Definition at line 145 of file anaarea_.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, and MSD_lowFaceArea().
Referenced by MSD_highArea().
real MSD_lowSolidDimensaoPrincipal (SPTYPE s, vector normal)
Definition at line 331 of file anaaproj.cpp.
References AllFacesShell, AllShellsSolid, dot(), DPTYPE, FacFeq, FacFLoops, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, veccopy(), vecd(), and VerVCoord.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_lowAreaProjetada(), and MSD_lowAreaProjetadaTotal().
real MSD_lowVolume (SPTYPE s)
Definition at line 111 of file anavolum.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, AllVerticesShell, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, vecminus(), vecplus(), VerVCoord, and VPTYPE.
Referenced by MSD_highVolume(), MSD_lowCentroDeGravidade(), MSD_lowMassa(), MSD_lowMassaTotal(), MSD_lowVolumeFlutuabilidadeTotal(), and MSD_lowVolumeTotal().
real MSD_lowVolumeFlutuabilidadeTotal (void)
Definition at line 58 of file anavftot.cpp.
References AllSolids, MSD_lowVolume(), SolDensRel, and SPTYPE.
Referenced by MSD_execVolumeFlutuabilidadeTotal(), MSD_lowAnaliseShow(), and MSD_lowEmpuxoTotal().
real MSD_lowVolumeTotal (void)
Definition at line 57 of file anavtot_.cpp.
References AllSolids, MSD_lowVolume(), and SPTYPE.
Referenced by MSD_execVolumeTotal(), and MSD_lowAnaliseShow().