USPDesigner: C:/USPDesig/ANA/anamassa.cpp File Reference
C:/USPDesig/ANA/anamassa.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameMassa (void)
real MSD_highNameMassa (char *name)
real MSD_highMassa (Id sn)
real MSD_lowMassa (SPTYPE s)
Function Documentation
void MSD_execNameMassa (void)
Definition at line 53 of file anamassa.cpp.
References lineins(), MSD_highNameMassa(), and restbuf.
real MSD_highMassa (Id sn)
Definition at line 80 of file anamassa.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowMassa(), NAM_Massa, SNIL, and SPTYPE.
Referenced by MSD_highNameMassa().
real MSD_highNameMassa (char * name)
Definition at line 68 of file anamassa.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMassa(), and NAM_Massa.
Referenced by MSD_execNameMassa().
real MSD_lowMassa (SPTYPE s)
Definition at line 92 of file anamassa.cpp.
References MSD_lowVolume(), and SolDensRel.
Referenced by MSD_highMassa(), and MSD_lowCentroMassaTotal().