USPDesigner: C:/USPDesig/ANA/anaminrc.cpp File Reference
C:/USPDesig/ANA/anaminrc.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameMatrizInercia (void)
int MSD_highNameMatrizInercia (char *name, matrix mat)
int MSD_highMatrizInercia (Id sn, matrix mat)
int MSD_lowMatrizInercia (SPTYPE s, matrix mat, vector cg)
Function Documentation
void MSD_execNameMatrizInercia (void)
Definition at line 53 of file anaminrc.cpp.
References lineins(), MSD_highNameMatrizInercia(), and restbuf.
int MSD_highMatrizInercia (Id sn, matrix mat)
Definition at line 85 of file anaminrc.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCentroDeGravidade(), MSD_lowMatrizInercia(), NAM_Inercia, SNIL, and SPTYPE.
Referenced by MSD_highNameMatrizInercia().
int MSD_highNameMatrizInercia (char * name, matrix mat)
Definition at line 73 of file anaminrc.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMatrizInercia(), and NAM_Inercia.
Referenced by MSD_execNameMatrizInercia().
int MSD_lowMatrizInercia (SPTYPE s, matrix mat, vector cg)
Definition at line 100 of file anaminrc.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, matzer(), SolDensRel, SUCCESS, vecminus(), and VerVCoord.
Referenced by MSD_highMatrizInercia(), and MSD_lowMatrizInerciaTotal().