USPDesigner: C:/USPDesig/ANA/anavolum.cpp File Reference
C:/USPDesig/ANA/anavolum.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "vectorop.h"
#include "eulerops.h"
#include "analise_.h"
#include "mancommd.h"
Functions
void MSD_execNameVolume (void)
real MSD_highNameVolume (char *name)
real MSD_highVolume (Id sn)
real MSD_lowVolume (SPTYPE s)
Function Documentation
void MSD_execNameVolume (void)
Definition at line 53 of file anavolum.cpp.
References lineins(), MSD_highNameVolume(), and restbuf.
real MSD_highNameVolume (char * name)
Definition at line 68 of file anavolum.cpp.
References MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highVolume(), and NAM_Volume.
Referenced by MSD_execNameVolume().
real MSD_highVolume (Id sn)
Definition at line 98 of file anavolum.cpp.
References MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowVolume(), NAM_Volume, SNIL, and SPTYPE.
Referenced by MSD_highNameVolume().
real MSD_lowVolume (SPTYPE s)
Definition at line 111 of file anavolum.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, AllVerticesShell, cross(), dot(), DPTYPE, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, vecminus(), vecplus(), VerVCoord, and VPTYPE.
Referenced by MSD_highVolume(), MSD_lowCentroDeGravidade(), MSD_lowMassa(), MSD_lowMassaTotal(), MSD_lowVolumeFlutuabilidadeTotal(), and MSD_lowVolumeTotal().