USPDesigner: C:/USPDesig/ANI/anicreat.cpp File Reference
C:/USPDesig/ANI/anicreat.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <malloc.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "hiegroup.h"
#include "vectorop.h"
#include "disdispl.h"
#include "animatio.h"
#include "mancommd.h"
Functions
void animatio (void)
void MSD_selectAllObjects (void)
void MSD_resetAllObjects (void)
void MSD_selectElement (char *name)
void MSD_resetElement (char *name)
void MSD_selectGroup (char *name)
void MSD_resetGroup (char *name)
void MSD_selectObject (char *name)
void MSD_resetObject (char *name)
void MSD_addAxisToMovementStructure (char *eaname, real edesl)
void MSD_addCameraToMovementStructure (char *aname, real ex, real ey, real ez, real rx, real ry, real rz, real desl)
void AddCamAni (char *aname, vector eeye, vector eref, real edesl)
FILE * OpenIndexAni (char *AnimeName)
void CriaFrame (FILE *FrameIndexFile, char *AnimeName, int framect)
void MSD_createAnimation (int opcao, int nframes, char *AnimeName, char *ecname)
char * InitFrameCount (char *AnimeName, char *FrameFile, int framect)
void PurificaAni (char *AnimeName, int opcao)
void PurificaFrame (int NumVectors, char *AnimeName, char *FrameFileName, int opcao)
int compara (real x, real y, real eps)
Function Documentation
void AddCamAni (char * aname, vector eeye, vector eref, real edesl)
Definition at line 259 of file anicreat.cpp.
References AddElementAni(), movcam::cam, CreateElementAni(), movcam::eye, movunion::mc, MovimentoCamera, MSD_lowFindCameraByName(), Move::mu, NIL, movcam::ref, movcam::scale, and veccopy().
Referenced by MSD_addCameraToMovementStructure().
void animatio (void)
Definition at line 60 of file anicreat.cpp.
References lineins(), MSD_addAxisToMovementStructure(), MSD_addCameraToMovementStructure(), MSD_clearAnimationList(), MSD_createAnimation(), optin(), PrintListAni(), and restbuf.
int compara (real x, real y, real eps)
Definition at line 619 of file anicreat.cpp.
References FALSE, and TRUE.
Referenced by PurificaFrame().
void CriaFrame (FILE * FrameIndexFile, char * AnimeName, int framect)
Definition at line 296 of file anicreat.cpp.
References AllSolids, movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::auxscale, movaxs::axs, movcam::cam, camptr, cameratp::dash, Draw, dspfwptr, cameratp::eye, FALSE, framenum, g_clear(), cameratp::hid, InitFrameCount(), movunion::ma, movunion::mc, cameratp::mode, movhead, MovimentoCamera, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_highNameTransformUsingAxis(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowDisplayWriteFile(), MSD_lowSetCamera(), Move::mu, Move::next, NIL, cameratp::ref, cameratp::scale, cameratp::smooth, SolDsp, SPTYPE, Move::tipo, TRUE, and vecplus().
Referenced by MSD_createAnimation().
char* InitFrameCount (char * AnimeName, char * FrameFile, int framect)
Definition at line 434 of file anicreat.cpp.
Referenced by CriaFrame(), and MSD_createAnimation().
void MSD_addAxisToMovementStructure (char * eaname, real edesl)
Definition at line 229 of file anicreat.cpp.
References AddElementAni(), ANIL, APTYPE, movaxs::axs, CreateElementAni(), movaxs::desl, movunion::ma, MovimentoAxis, MSD_lowFindAxisByName(), Move::mu, and NIL.
Referenced by animatio().
void MSD_addCameraToMovementStructure (char * aname, real ex, real ey, real ez, real rx, real ry, real rz, real desl)
Definition at line 249 of file anicreat.cpp.
References AddCamAni(), and makevec().
Referenced by animatio().
void MSD_createAnimation (int opcao, int nframes, char * AnimeName, char * ecname)
Definition at line 354 of file anicreat.cpp.
References movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::auxscale, movcam::cam, camptr, CriaFrame(), movaxs::desl, Draw, dspfwptr, cameratp::eye, movcam::eye, FALSE, framenum, g_clear(), cameratp::hid, InitFrameCount(), movunion::ma, movunion::mc, movhead, MovimentoCamera, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowDisplayWriteFile(), MSD_lowFindCameraByName(), Move::mu, Move::next, NIL, OpenIndexAni(), PurificaAni(), cameratp::ref, movcam::ref, cameratp::scale, movcam::scale, Move::tipo, TRUE, vecesc(), and vecminus().
Referenced by animatio().
void MSD_resetAllObjects (void)
Definition at line 129 of file anicreat.cpp.
References AllSolids, FALSE, and SolDsp.
void MSD_resetElement (char * name)
Definition at line 153 of file anicreat.cpp.
References MSD_getTypeByName(), MSD_resetGroup(), and MSD_resetObject().
void MSD_resetGroup (char * name)
Definition at line 188 of file anicreat.cpp.
References AllSolids, FALSE, GNIL, GPTYPE, MSD_lowFindGroupByName(), MSD_lowIsAncestorGroup(), SolDsp, SolGroup, and SPTYPE.
Referenced by MSD_resetElement().
void MSD_resetObject (char * name)
Definition at line 219 of file anicreat.cpp.
References FALSE, MSD_lowFindSolidByName(), SNIL, SolDsp, and SPTYPE.
Referenced by MSD_resetElement().
void MSD_selectAllObjects (void)
Definition at line 119 of file anicreat.cpp.
References AllSolids, SolDsp, and TRUE.
void MSD_selectElement (char * name)
Definition at line 139 of file anicreat.cpp.
References MSD_getTypeByName(), MSD_selectGroup(), and MSD_selectObject().
void MSD_selectGroup (char * name)
Definition at line 167 of file anicreat.cpp.
References AllSolids, GNIL, GPTYPE, MSD_lowFindGroupByName(), MSD_lowIsAncestorGroup(), SolDsp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_selectElement().
void MSD_selectObject (char * name)
Definition at line 209 of file anicreat.cpp.
References MSD_lowFindSolidByName(), SNIL, SolDsp, SPTYPE, and TRUE.
Referenced by MSD_selectElement().
FILE* OpenIndexAni (char * AnimeName)
Definition at line 281 of file anicreat.cpp.
References NIL.
Referenced by MSD_createAnimation().
void PurificaAni (char * AnimeName, int opcao)
Definition at line 491 of file anicreat.cpp.
References NIL, and PurificaFrame().
Referenced by MSD_createAnimation().
void PurificaFrame (int NumVectors, char * AnimeName, char * FrameFileName, int opcao)
Definition at line 512 of file anicreat.cpp.
References compara(), FloVector::cor, FILTERPRECISION, MAXVECTORS, NIL, FloVector::px1, FloVector::px2, FloVector::py1, FloVector::py2, and FloVector::tlinha.
Referenced by PurificaAni().