USPDesigner: C:/USPDesig/ANI/aniexibe.cpp File Reference
C:/USPDesig/ANI/aniexibe.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <bios.h>
#include <stdlib.h>
#include <graphics.h>
#include <time.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "animatio.h"
#include "mancommd.h"
#include "gphgraph.h"
Functions
void cinema (void)
void MSD_loadAnimation (char *AnimeName, int frini, int frfim, int frpasso)
void DrawLine (INTVECTOR *auxpt)
void ExibeFrame (int p)
void MSD_displayLoadedAnimation (int num)
void LoadFrame (int FrameNum, int NumVectors, char *FrameFileName)
int FindFrameNum (char *nome)
void MSD_freeCinemaStructure (void)
Variables
int NumVec [100]
INTVECTOR * ListFrames [100]
Function Documentation
void cinema (void)
Definition at line 78 of file aniexibe.cpp.
References lineins(), MSD_displayLoadedAnimation(), MSD_freeCinemaStructure(), MSD_loadAnimation(), optin(), and restbuf.
void DrawLine (INTVECTOR * auxpt)
Definition at line 164 of file aniexibe.cpp.
References IntVector::cor, g_iline(), g_pcolor(), IntVector::px1, IntVector::px2, IntVector::py1, IntVector::py2, and IntVector::tlinha.
Referenced by ExibeFrame(), and MSD_displayLoadedAnimation().
void ExibeFrame (int p)
Definition at line 180 of file aniexibe.cpp.
References DrawLine(), g_clear(), and NumVec.
Referenced by MSD_displayLoadedAnimation().
int FindFrameNum (char * nome)
Definition at line 312 of file aniexibe.cpp.
References NIL.
Referenced by MSD_loadAnimation().
void LoadFrame (int FrameNum, int NumVectors, char * FrameFileName)
Definition at line 230 of file aniexibe.cpp.
References IntVector::cor, gdcpos(), NIL, NumVec, IntVector::px1, IntVector::px2, IntVector::py1, IntVector::py2, and IntVector::tlinha.
Referenced by MSD_loadAnimation().
void MSD_displayLoadedAnimation (int num)
Definition at line 199 of file aniexibe.cpp.
References DrawLine(), ExibeFrame(), g_clear(), NumeroFrames, and NumVec.
Referenced by cinema().
void MSD_freeCinemaStructure (void)
Definition at line 317 of file aniexibe.cpp.
References NumeroFrames.
Referenced by cinema(), and MSD_AnimationReset().
void MSD_loadAnimation (char * AnimeName, int frini, int frfim, int frpasso)
Definition at line 122 of file aniexibe.cpp.
References FindFrameNum(), LoadFrame(), MAXNUMFRAMES, NIL, and NumeroFrames.
Referenced by cinema().
Variable Documentation
INTVECTOR* ListFrames[100]
Definition at line 76 of file aniexibe.cpp.
int NumVec[100]
Definition at line 75 of file aniexibe.cpp.
Referenced by ExibeFrame(), LoadFrame(), and MSD_displayLoadedAnimation().