USPDesigner: C:/USPDesig/ANI/animlist.cpp File Reference
C:/USPDesig/ANI/animlist.cpp File Reference
#include <stdio.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "vectorop.h"
#include "disdispl.h"
#include "animatio.h"
Functions
MOVE * CreateElementAni (Mov cod)
void AddElementAni (MOVE *e)
void RemElementAni (MOVE *p)
void MSD_AnimationReset (int cod)
void MSD_clearAnimationList (void)
void PrintListAni (void)
void InitListAni (int nframes)
Function Documentation
void AddElementAni (MOVE * e)
Definition at line 89 of file animlist.cpp.
References movhead, Move::next, and NIL.
Referenced by AddCamAni(), and MSD_addAxisToMovementStructure().
MOVE* CreateElementAni (Mov cod)
Definition at line 55 of file animlist.cpp.
References movunion::ma, movunion::mc, MovimentoAxis, MovimentoCamera, Move::mu, Move::next, NIL, RemElementAni(), and Move::tipo.
Referenced by AddCamAni(), and MSD_addAxisToMovementStructure().
void InitListAni (int nframes)
Definition at line 188 of file animlist.cpp.
References movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::cam, movaxs::desl, cameratp::eye, movcam::eye, movunion::ma, movunion::mc, movhead, MovimentoCamera, Move::mu, Move::next, NIL, cameratp::ref, movcam::ref, cameratp::scale, movcam::scale, Move::tipo, vecesc(), and vecminus().
void MSD_AnimationReset (int cod)
Definition at line 123 of file animlist.cpp.
References MSD_clearAnimationList(), and MSD_freeCinemaStructure().
void MSD_clearAnimationList (void)
Definition at line 133 of file animlist.cpp.
References movunion::ma, movunion::mc, movhead, MovimentoAxis, MovimentoCamera, Move::mu, Move::next, NIL, and Move::tipo.
Referenced by animatio(), and MSD_AnimationReset().
void PrintListAni (void)
Definition at line 160 of file animlist.cpp.
References movaxs::axs, movcam::cam, cameratp::cname, movaxs::desl, movcam::eye, movunion::ma, movunion::mc, movhead, MovimentoCamera, Move::mu, Move::next, NIL, movcam::ref, movcam::scale, and Move::tipo.
Referenced by animatio().
void RemElementAni (MOVE * p)
Definition at line 106 of file animlist.cpp.
References movhead, Move::next, and NIL.
Referenced by CreateElementAni().