USPDesigner: C:/USPDesig/INC/animatio.h File Reference
C:/USPDesig/INC/animatio.h File Reference
#include <stdio.h>
Classes
struct IntVector
struct FloVector
struct movcam
struct movaxs
union movunion
struct Move
struct FrameList
Defines
#define EXTERN extern
#define MAXTIME 0.1
#define MAXTIME2 1
#define MAXVECTORS 600
#define MAXNUMFRAMES 150
#define FILTERPRECISION 0.003
Typedefs
typedef real vector [4]
typedef real vect2 [3]
typedef struct cameratp CTYPE
typedef struct axistp ATYPE
typedef enum movimento Mov
typedef struct movcam MOVCAM
typedef struct movaxs MOVAXS
typedef union movunion MOVUNION
typedef struct Move MOVE
typedef struct IntVector INTVECTOR
typedef struct FloVector FLOVECTOR
typedef struct FrameList FRAMEPT
Enumerations
enum movimento { MovimentoAxis, MovimentoCamera }
Functions
void animatio (void)
void MSD_selectAllObjects (void)
void MSD_selectElement (char *name)
void MSD_selectGroup (char *name)
void MSD_selectObject (char *name)
void MSD_resetAllObjects (void)
void MSD_resetObject (char *name)
void MSD_resetGroup (char *name)
void MSD_resetElement (char *name)
void MSD_addAxisToMovementStructure (char *eaname, real edesl)
void MSD_addCameraToMovementStructure (char *aname, real ex, real ey, real ez, real rx, real ry, real rz, real desl)
void AddCamAni (char *aname, vector eeye, vector eref, real edesl)
FILE * OpenIndexAni (char *arqnam)
void CriaFrame (FILE *arqaux, char *arqnam, int framect)
void MSD_createAnimation (int opcao, int nframes, char *AnimeName, char *ecname)
char * InitFrameCount (char *nome, char *aux, int framect)
void PurificaAni (char *arqnam, int opcao)
void PurificaFrame (int num, char *arqname, char *filename, int opcao)
int compara (real x, real y, real eps)
void cinema (void)
void MSD_loadAnimation (char *AnimeName, int frini, int frfim, int frpasso)
void DrawLine (INTVECTOR *auxpt)
void ExibeFrame (int p)
void MSD_displayLoadedAnimation (int num)
void LoadFrame (int count, int num, char *filename)
int FindFrameNum (char *nome)
void MSD_freeCinemaStructure (void)
MOVE * CreateElementAni (Mov mov)
void AddElementAni (MOVE *e)
void RemElementAni (MOVE *p)
void MSD_clearAnimationList (void)
void PrintListAni (void)
void InitListAni (int nframes)
Variables
EXTERN MOVE * movhead
EXTERN int framenum
EXTERN int NumeroFrames
Define Documentation
#define EXTERN extern
Definition at line 49 of file animatio.h.
#define FILTERPRECISION 0.003
Definition at line 79 of file animatio.h.
Referenced by PurificaFrame().
#define MAXNUMFRAMES 150
Definition at line 78 of file animatio.h.
Referenced by MSD_loadAnimation().
#define MAXTIME 0.1
Definition at line 75 of file animatio.h.
#define MAXTIME2 1
Definition at line 76 of file animatio.h.
#define MAXVECTORS 600
Definition at line 77 of file animatio.h.
Referenced by PurificaFrame().
Typedef Documentation
typedef struct axistp ATYPE
Definition at line 68 of file animatio.h.
typedef struct cameratp CTYPE
Definition at line 65 of file animatio.h.
typedef struct FloVector FLOVECTOR
Definition at line 86 of file animatio.h.
typedef struct FrameList FRAMEPT
Definition at line 87 of file animatio.h.
typedef struct IntVector INTVECTOR
Definition at line 85 of file animatio.h.
typedef enum movimento Mov
Definition at line 71 of file animatio.h.
typedef struct movaxs MOVAXS
Definition at line 82 of file animatio.h.
typedef struct movcam MOVCAM
Definition at line 81 of file animatio.h.
typedef struct Move MOVE
Definition at line 84 of file animatio.h.
typedef union movunion MOVUNION
Definition at line 83 of file animatio.h.
typedef real vect2[3]
Definition at line 61 of file animatio.h.
typedef real vector[4]
Definition at line 57 of file animatio.h.
Enumeration Type Documentation
enum movimento
Enumerator:
MovimentoAxis
MovimentoCamera
Definition at line 133 of file animatio.h.
Function Documentation
void AddCamAni (char * aname, vector eeye, vector eref, real edesl)
Definition at line 259 of file anicreat.cpp.
References AddElementAni(), movcam::cam, CreateElementAni(), movcam::eye, movunion::mc, MovimentoCamera, MSD_lowFindCameraByName(), Move::mu, NIL, movcam::ref, movcam::scale, and veccopy().
Referenced by MSD_addCameraToMovementStructure().
void AddElementAni (MOVE * e)
Definition at line 89 of file animlist.cpp.
References movhead, Move::next, and NIL.
Referenced by AddCamAni(), and MSD_addAxisToMovementStructure().
void animatio (void)
Definition at line 60 of file anicreat.cpp.
References lineins(), MSD_addAxisToMovementStructure(), MSD_addCameraToMovementStructure(), MSD_clearAnimationList(), MSD_createAnimation(), optin(), PrintListAni(), and restbuf.
void cinema (void)
Definition at line 78 of file aniexibe.cpp.
References lineins(), MSD_displayLoadedAnimation(), MSD_freeCinemaStructure(), MSD_loadAnimation(), optin(), and restbuf.
int compara (real x, real y, real eps)
Definition at line 619 of file anicreat.cpp.
References FALSE, and TRUE.
Referenced by PurificaFrame().
MOVE* CreateElementAni (Mov mov)
Definition at line 55 of file animlist.cpp.
References movunion::ma, movunion::mc, MovimentoAxis, MovimentoCamera, Move::mu, Move::next, NIL, RemElementAni(), and Move::tipo.
Referenced by AddCamAni(), and MSD_addAxisToMovementStructure().
void CriaFrame (FILE * arqaux, char * arqnam, int framect)
Definition at line 296 of file anicreat.cpp.
References AllSolids, movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::auxscale, movaxs::axs, movcam::cam, camptr, cameratp::dash, Draw, dspfwptr, cameratp::eye, FALSE, framenum, g_clear(), cameratp::hid, InitFrameCount(), movunion::ma, movunion::mc, cameratp::mode, movhead, MovimentoCamera, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_highNameTransformUsingAxis(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowDisplayWriteFile(), MSD_lowSetCamera(), Move::mu, Move::next, NIL, cameratp::ref, cameratp::scale, cameratp::smooth, SolDsp, SPTYPE, Move::tipo, TRUE, and vecplus().
Referenced by MSD_createAnimation().
void DrawLine (INTVECTOR * auxpt)
Definition at line 164 of file aniexibe.cpp.
References IntVector::cor, g_iline(), g_pcolor(), IntVector::px1, IntVector::px2, IntVector::py1, IntVector::py2, and IntVector::tlinha.
Referenced by ExibeFrame(), and MSD_displayLoadedAnimation().
void ExibeFrame (int p)
Definition at line 180 of file aniexibe.cpp.
References DrawLine(), g_clear(), and NumVec.
Referenced by MSD_displayLoadedAnimation().
int FindFrameNum (char * nome)
Definition at line 312 of file aniexibe.cpp.
References NIL.
Referenced by MSD_loadAnimation().
char* InitFrameCount (char * nome, char * aux, int framect)
Definition at line 434 of file anicreat.cpp.
Referenced by CriaFrame(), and MSD_createAnimation().
void InitListAni (int nframes)
Definition at line 188 of file animlist.cpp.
References movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::cam, movaxs::desl, cameratp::eye, movcam::eye, movunion::ma, movunion::mc, movhead, MovimentoCamera, Move::mu, Move::next, NIL, cameratp::ref, movcam::ref, cameratp::scale, movcam::scale, Move::tipo, vecesc(), and vecminus().
void LoadFrame (int count, int num, char * filename)
Definition at line 230 of file aniexibe.cpp.
References IntVector::cor, gdcpos(), NIL, NumVec, IntVector::px1, IntVector::px2, IntVector::py1, IntVector::py2, and IntVector::tlinha.
Referenced by MSD_loadAnimation().
void MSD_addAxisToMovementStructure (char * eaname, real edesl)
Definition at line 229 of file anicreat.cpp.
References AddElementAni(), ANIL, APTYPE, movaxs::axs, CreateElementAni(), movaxs::desl, movunion::ma, MovimentoAxis, MSD_lowFindAxisByName(), Move::mu, and NIL.
Referenced by animatio().
void MSD_addCameraToMovementStructure (char * aname, real ex, real ey, real ez, real rx, real ry, real rz, real desl)
Definition at line 249 of file anicreat.cpp.
References AddCamAni(), and makevec().
Referenced by animatio().
void MSD_clearAnimationList (void)
Definition at line 133 of file animlist.cpp.
References movunion::ma, movunion::mc, movhead, MovimentoAxis, MovimentoCamera, Move::mu, Move::next, NIL, and Move::tipo.
Referenced by animatio(), and MSD_AnimationReset().
void MSD_createAnimation (int opcao, int nframes, char * AnimeName, char * ecname)
Definition at line 354 of file anicreat.cpp.
References movaxs::auxdesl, movcam::auxeye, movcam::auxref, movcam::auxscale, movcam::cam, camptr, CriaFrame(), movaxs::desl, Draw, dspfwptr, cameratp::eye, movcam::eye, FALSE, framenum, g_clear(), cameratp::hid, InitFrameCount(), movunion::ma, movunion::mc, movhead, MovimentoCamera, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowDisplayWriteFile(), MSD_lowFindCameraByName(), Move::mu, Move::next, NIL, OpenIndexAni(), PurificaAni(), cameratp::ref, movcam::ref, cameratp::scale, movcam::scale, Move::tipo, TRUE, vecesc(), and vecminus().
Referenced by animatio().
void MSD_displayLoadedAnimation (int num)
Definition at line 199 of file aniexibe.cpp.
References DrawLine(), ExibeFrame(), g_clear(), NumeroFrames, and NumVec.
Referenced by cinema().
void MSD_freeCinemaStructure (void)
Definition at line 317 of file aniexibe.cpp.
References NumeroFrames.
Referenced by cinema(), and MSD_AnimationReset().
void MSD_loadAnimation (char * AnimeName, int frini, int frfim, int frpasso)
Definition at line 122 of file aniexibe.cpp.
References FindFrameNum(), LoadFrame(), MAXNUMFRAMES, NIL, and NumeroFrames.
Referenced by cinema().
void MSD_resetAllObjects (void)
Definition at line 129 of file anicreat.cpp.
References AllSolids, FALSE, and SolDsp.
void MSD_resetElement (char * name)
Definition at line 153 of file anicreat.cpp.
References MSD_getTypeByName(), MSD_resetGroup(), and MSD_resetObject().
void MSD_resetGroup (char * name)
Definition at line 188 of file anicreat.cpp.
References AllSolids, FALSE, GNIL, GPTYPE, MSD_lowFindGroupByName(), MSD_lowIsAncestorGroup(), SolDsp, SolGroup, and SPTYPE.
Referenced by MSD_resetElement().
void MSD_resetObject (char * name)
Definition at line 219 of file anicreat.cpp.
References FALSE, MSD_lowFindSolidByName(), SNIL, SolDsp, and SPTYPE.
Referenced by MSD_resetElement().
void MSD_selectAllObjects (void)
Definition at line 119 of file anicreat.cpp.
References AllSolids, SolDsp, and TRUE.
void MSD_selectElement (char * name)
Definition at line 139 of file anicreat.cpp.
References MSD_getTypeByName(), MSD_selectGroup(), and MSD_selectObject().
void MSD_selectGroup (char * name)
Definition at line 167 of file anicreat.cpp.
References AllSolids, GNIL, GPTYPE, MSD_lowFindGroupByName(), MSD_lowIsAncestorGroup(), SolDsp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_selectElement().
void MSD_selectObject (char * name)
Definition at line 209 of file anicreat.cpp.
References MSD_lowFindSolidByName(), SNIL, SolDsp, SPTYPE, and TRUE.
Referenced by MSD_selectElement().
FILE* OpenIndexAni (char * arqnam)
Definition at line 281 of file anicreat.cpp.
References NIL.
Referenced by MSD_createAnimation().
void PrintListAni (void)
Definition at line 160 of file animlist.cpp.
References movaxs::axs, movcam::cam, cameratp::cname, movaxs::desl, movcam::eye, movunion::ma, movunion::mc, movhead, MovimentoCamera, Move::mu, Move::next, NIL, movcam::ref, movcam::scale, and Move::tipo.
Referenced by animatio().
void PurificaAni (char * arqnam, int opcao)
Definition at line 491 of file anicreat.cpp.
References NIL, and PurificaFrame().
Referenced by MSD_createAnimation().
void PurificaFrame (int num, char * arqname, char * filename, int opcao)
Definition at line 512 of file anicreat.cpp.
References compara(), FloVector::cor, FILTERPRECISION, MAXVECTORS, NIL, FloVector::px1, FloVector::px2, FloVector::py1, FloVector::py2, and FloVector::tlinha.
Referenced by PurificaAni().
void RemElementAni (MOVE * p)
Definition at line 106 of file animlist.cpp.
References movhead, Move::next, and NIL.
Referenced by CreateElementAni().
Variable Documentation
EXTERN int framenum
Definition at line 153 of file animatio.h.
Referenced by CriaFrame(), g_frame(), g_tline(), and MSD_createAnimation().
EXTERN MOVE* movhead
Definition at line 152 of file animatio.h.
Referenced by AddElementAni(), CriaFrame(), InitListAni(), MSD_clearAnimationList(), MSD_createAnimation(), PrintListAni(), and RemElementAni().
EXTERN int NumeroFrames
Definition at line 154 of file animatio.h.
Referenced by MSD_displayLoadedAnimation(), MSD_freeCinemaStructure(), and MSD_loadAnimation().