USPDesigner: C:/USPDesig/INC/basrov__.h File Reference
C:/USPDesig/INC/basrov__.h File Reference
Classes
struct ListaOrdenada
Defines
#define EXTERN extern
#define SOLIDO_TIPO_BARRA 0x01
#define SOLIDO_TIPO_SOLID 0x02
#define SOLIDO_TIPO_PLACA 0x03
#define BARRA_GEOM_CIRCULO 0x01
#define BARRA_GEOM_QUADRADO 0x02
#define BARRA_GEOM_TRIANGULO 0x03
#define BARRA_GEOM_RETANGULO 0x04
#define BARRA_GEOM_ELIPSE 0x05
#define BARRA_GEOM_PERFIL_L 0x06
#define BARRA_GEOM_PERFIL_T 0x07
#define BARRA_GEOM_PERFIL_I 0x08
#define SOLIDO_GEOM_ESFERA 0x20
#define SOLIDO_GEOM_CUBO 0x21
#define SOLIDO_GEOM_PRISMA 0x22
#define SOLIDO_GEOM_PIRAMIDE 0x23
#define SOLIDO_GEOM_CONE 0x24
#define FRONTEIRA_A 0x01
#define FRONTEIRA_CV 0x02
Typedefs
typedef struct ListaOrdenada LOPType
Functions
void MSD_execNameMakeCirculo (void)
void MSD_execNameMakeCubo (void)
void MSD_execNameMakePlaca (void)
void MSD_execNameMakePiramide (void)
void MSD_execNameMakeEsfera (void)
void MSD_execNameMakePerfilI (void)
void MSD_execNameMakePerfilL (void)
void MSD_execNameMakePerfilT (void)
void MSD_execNameMakePrisma (void)
void MSD_execNameMakeQuadrado (void)
void MSD_execNameMakeRetangulo (void)
void MSD_execNameMakeTriangulo (void)
void MSD_execNameDimensaoPrincipal (void)
real MSD_determinaDimensaoPrincipal (SPTYPE s, vector dir, real dim)
real MSD_determinaDistanciaParametrica (vector cc, vector dir, vector pp)
real MSD_determinaMaiorDimensao (SPTYPE s)
void MSD_execNameRotaciona (void)
void MSD_execNameDesloca (void)
void MSD_execOrdena (void)
void MSD_execProjetadaTotal (void)
Variables
EXTERN vector DirecaoEscoamento
EXTERN LOPType * ListaEscoamento
EXTERN int NumListaEscoamento
Define Documentation
#define BARRA_GEOM_CIRCULO 0x01
Definition at line 57 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeCirculo(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_ELIPSE 0x05
Definition at line 61 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_PERFIL_I 0x08
Definition at line 64 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakePerfilI(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_PERFIL_L 0x06
Definition at line 62 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakePerfilL(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_PERFIL_T 0x07
Definition at line 63 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakePerfilT(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_QUADRADO 0x02
Definition at line 58 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeQuadrado(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_RETANGULO 0x04
Definition at line 60 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeRetangulo(), and MSD_lowSetVariaveisImpressao().
#define BARRA_GEOM_TRIANGULO 0x03
Definition at line 59 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeTriangulo(), and MSD_lowSetVariaveisImpressao().
#define EXTERN extern
Definition at line 49 of file basrov__.h.
#define FRONTEIRA_A 0x01
Definition at line 72 of file basrov__.h.
Referenced by MSD_highNameMakeCirculo(), MSD_highNameMakeEsfera(), and MSD_highNameMakeROVCone().
#define FRONTEIRA_CV 0x02
Definition at line 73 of file basrov__.h.
Referenced by MSD_highNameMakeCubo(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), and MSD_highNameMakeTriangulo().
#define SOLIDO_GEOM_CONE 0x24
Definition at line 70 of file basrov__.h.
Referenced by MSD_highNameMakeROVCone(), MSD_highRotaciona(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_GEOM_CUBO 0x21
Definition at line 67 of file basrov__.h.
Referenced by MSD_highNameMakeCubo(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_GEOM_ESFERA 0x20
Definition at line 66 of file basrov__.h.
Referenced by MSD_highNameMakeEsfera(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_GEOM_PIRAMIDE 0x23
Definition at line 69 of file basrov__.h.
Referenced by MSD_highNameMakePiramide(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_GEOM_PRISMA 0x22
Definition at line 68 of file basrov__.h.
Referenced by MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_TIPO_BARRA 0x01
Definition at line 53 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeCirculo(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeTriangulo(), MSD_highRotaciona(), MSD_lowImprimeListaEstudo(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_TIPO_PLACA 0x03
Definition at line 55 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakePlaca(), MSD_highRotaciona(), and MSD_lowSetVariaveisImpressao().
#define SOLIDO_TIPO_SOLID 0x02
Definition at line 54 of file basrov__.h.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_highNameMakeCubo(), MSD_highNameMakeEsfera(), MSD_highNameMakePiramide(), MSD_highNameMakePrisma(), MSD_highNameMakeROVCone(), MSD_highRotaciona(), MSD_lowAreaProjetadaTotal(), MSD_lowCriaListaEstudo(), and MSD_lowSetVariaveisImpressao().
Typedef Documentation
typedef struct ListaOrdenada LOPType
Definition at line 75 of file basrov__.h.
Function Documentation
real MSD_determinaDimensaoPrincipal (SPTYPE s, vector dir, real dim)
Definition at line 138 of file rovdist_.cpp.
References BARRA_GEOM_CIRCULO, BARRA_GEOM_ELIPSE, BARRA_GEOM_PERFIL_I, BARRA_GEOM_PERFIL_L, BARRA_GEOM_PERFIL_T, BARRA_GEOM_QUADRADO, BARRA_GEOM_RETANGULO, BARRA_GEOM_TRIANGULO, comp(), cross(), dot(), FacFeq, MSD_determinaDimensaoPrincipalBarra(), MSD_getFace(), MSD_getSolid(), MSD_lowSolidDimensaoPrincipal(), SNIL, SolGeometria, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolParam1, SolParam2, SolPerfil, SolPrincDir, SolType, SPTYPE, veccopy(), and vecnull().
Referenced by MSD_CalculaParametrosInterferencia(), and MSD_highDimensaoPrincipal().
real MSD_determinaDistanciaParametrica (vector cc, vector dir, vector pp)
Definition at line 60 of file rovdist_.cpp.
References dot().
Referenced by MSD_determinaDimensaoPrincipalBarra(), MSD_lowCalculaDimensoesRelativas(), and MSD_lowCriaListaEstudo().
real MSD_determinaMaiorDimensao (SPTYPE s)
Definition at line 102 of file rovdist_.cpp.
References BARRA_GEOM_CIRCULO, BARRA_GEOM_ELIPSE, BARRA_GEOM_PERFIL_I, BARRA_GEOM_PERFIL_L, BARRA_GEOM_PERFIL_T, BARRA_GEOM_QUADRADO, BARRA_GEOM_RETANGULO, BARRA_GEOM_TRIANGULO, SolGeometria, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolParam2, SolParam3, SolParam4, and SolType.
Referenced by MSD_CalculaParametrosInterferencia().
void MSD_execNameDesloca (void)
Definition at line 55 of file rovtrnds.cpp.
References lineins(), MSD_highNameDesloca(), and restbuf.
void MSD_execNameDimensaoPrincipal (void)
Definition at line 57 of file rovdmprc.cpp.
References lineins(), MSD_highNameDimensaoPrincipal(), and restbuf.
void MSD_execNameMakeCirculo (void)
Definition at line 55 of file rovcirc_.cpp.
References lineins(), MSD_highNameMakeCirculo(), and restbuf.
void MSD_execNameMakeCubo (void)
Definition at line 55 of file rovcubo_.cpp.
References lineins(), MSD_highNameMakeCubo(), and restbuf.
void MSD_execNameMakeEsfera (void)
Definition at line 55 of file rovesfer.cpp.
References lineins(), MSD_highNameMakeEsfera(), and restbuf.
void MSD_execNameMakePerfilI (void)
Definition at line 56 of file rovperi_.cpp.
References lineins(), MSD_highNameMakePerfilI(), and restbuf.
void MSD_execNameMakePerfilL (void)
Definition at line 56 of file rovperl_.cpp.
References lineins(), MSD_highNameMakePerfilL(), and restbuf.
void MSD_execNameMakePerfilT (void)
Definition at line 56 of file rovpert_.cpp.
References lineins(), MSD_highNameMakePerfilT(), and restbuf.
void MSD_execNameMakePiramide (void)
Definition at line 55 of file rovpyram.cpp.
References lineins(), MSD_highNameMakePiramide(), restbuf, and setvtpi().
void MSD_execNameMakePlaca (void)
Definition at line 55 of file rovplaca.cpp.
References lineins(), MSD_highNameMakePlaca(), and restbuf.
void MSD_execNameMakePrisma (void)
Definition at line 55 of file rovprism.cpp.
References lineins(), MSD_highNameMakePrisma(), and restbuf.
void MSD_execNameMakeQuadrado (void)
Definition at line 55 of file rovquad_.cpp.
References lineins(), MSD_highNameMakeQuadrado(), and restbuf.
void MSD_execNameMakeRetangulo (void)
Definition at line 55 of file rovretan.cpp.
References lineins(), MSD_highNameMakeRetangulo(), and restbuf.
void MSD_execNameMakeTriangulo (void)
Definition at line 56 of file rovtrian.cpp.
References lineins(), MSD_highNameMakeTriangulo(), and restbuf.
void MSD_execNameRotaciona (void)
Definition at line 56 of file rovtrntr.cpp.
References lineins(), MSD_highNameRotaciona(), and restbuf.
void MSD_execOrdena (void)
Definition at line 87 of file rovorden.cpp.
References lineins(), ListaEscoamento, MSD_lowOrdena(), NumListaEscoamento, restbuf, SolName, and SolSolidNo.
void MSD_execProjetadaTotal (void)
Definition at line 70 of file rovorden.cpp.
References lineins(), MSD_lowAreaProjetadaTotal(), and restbuf.
Variable Documentation
EXTERN vector DirecaoEscoamento
Definition at line 87 of file basrov__.h.
EXTERN LOPType* ListaEscoamento
Definition at line 88 of file basrov__.h.
Referenced by maninit(), MSD_CalculaParametrosInterferencia(), MSD_execOrdena(), MSD_lowCalculaDimensoesRelativas(), MSD_lowCriaListaEstudo(), MSD_lowImprimeListaEstudo(), MSD_lowOrdenaListaEstudo(), and MSD_lowSetVariaveisImpressao().
EXTERN int NumListaEscoamento
Definition at line 89 of file basrov__.h.
Referenced by maninit(), MSD_CalculaParametrosInterferencia(), MSD_execOrdena(), MSD_lowCriaListaEstudo(), MSD_lowImprimeListaEstudo(), and MSD_lowOrdenaListaEstudo().