USPDesigner: C:/USPDesig/CAM/camaltpr.cpp File Reference
C:/USPDesig/CAM/camaltpr.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
#include "vectorop.h"
Functions
int MSD_highNameAlteraCamera (char opt, char *name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_highAlteraCamera (char opt, Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_lowAlteraCamera (char opt, CTYPE *cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Function Documentation
int MSD_highAlteraCamera (char opt, Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 69 of file camaltpr.cpp.
References ERROR, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowAlteraCamera(), NAM_AlteraCamara, and NIL.
Referenced by MSD_highNameAlteraCamera().
int MSD_highNameAlteraCamera (char opt, char * name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 52 of file camaltpr.cpp.
References ERROR, MEN_CamaraNomeNaoEncontrada, MSD_getCameraIdFromName(), MSD_highAlteraCamera(), and NAM_AlteraCamara.
Referenced by MSD_execCamera().
int MSD_lowAlteraCamera (char opt, CTYPE * cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 85 of file camaltpr.cpp.
References cameratp::dash, cameratp::eye, FALSE, cameratp::hid, makevec(), MEN_CamaraParametroIncorreto, cameratp::mode, MSD_lowCheckCamera(), MSD_lowSetCamera(), NAM_AlteraCamara, cameratp::ref, cameratp::scale, cameratp::smooth, TRUE, and veccopy().
Referenced by MSD_highAlteraCamera(), and MSD_highAlteraCurrentCamera().