USPDesigner: C:/USPDesig/CAM/camcheck.cpp File Reference
C:/USPDesig/CAM/camcheck.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "vectorop.h"
Functions
int MSD_highCheckCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_lowCheckCamera (vector eye, vector ref, real scale, int mode, int hidtype, int dash, int smooth)
void MSD_highSetCamera (CTYPE *cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
void MSD_lowSetCamera (CTYPE *cptr, vector eye, vector ref, real scale, int mode, int hidtype, int dash, int smooth)
void MSD_lowSetCameraTransformation (CTYPE *cptr)
void MSD_lowSetCamera3View (int type, CTYPE *cptr)
Function Documentation
int MSD_highCheckCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 55 of file camcheck.cpp.
References makevec(), and MSD_lowCheckCamera().
Referenced by MSD_lowCreateCamera().
void MSD_highSetCamera (CTYPE * cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 96 of file camcheck.cpp.
References makevec(), and MSD_lowSetCamera().
Referenced by MSD_lowCreateCamera(), and MSD_lowTranslateCurrentCamera().
int MSD_lowCheckCamera (vector eye, vector ref, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 66 of file camcheck.cpp.
References abseps, FALSE, releps, TRUE, and vecd().
Referenced by MSD_highCheckCamera(), and MSD_lowAlteraCamera().
void MSD_lowSetCamera (CTYPE * cptr, vector eye, vector ref, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 107 of file camcheck.cpp.
References cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, MSD_lowSetCameraTransformation(), cameratp::ref, cameratp::scale, cameratp::smooth, and veccopy().
Referenced by CriaFrame(), MSD_highSetCamera(), MSD_lowAlteraCamera(), and MSD_lowSetCamera3View().
void MSD_lowSetCamera3View (int type, CTYPE * cptr)
Definition at line 153 of file camcheck.cpp.
References camptr, cameratp::cdis, cameratp::dash, dwindbox, cameratp::hid, MSD_lowSetCamera(), cameratp::ref, cameratp::scale, cameratp::smooth, veccopy(), and windbox.
Referenced by MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), and MSD_lowCameraDisplayIntersection().
void MSD_lowSetCameraTransformation (CTYPE * cptr)
Definition at line 120 of file camcheck.cpp.
References abseps, cameratp::cdis, cameratp::drot, cameratp::eye, cameratp::eyedir, matident(), normalize(), cameratp::ref, vecd(), vecd2(), and vecminus().
Referenced by MSD_lowSetCamera().