USPDesigner: C:/USPDesig/CAM/camcopy_.cpp File Reference
C:/USPDesig/CAM/camcopy_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameCopyCamera (char *name1, char *name2)
int MSD_highCopyCamera (int cn)
int MSD_lowCopyCamera (CTYPE *cptr, Id cn)
Function Documentation
int MSD_highCopyCamera (int cn)
Definition at line 113 of file camcopy_.cpp.
References ERROR, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_getMaxCameraId(), MSD_lowCopyCamera(), NAM_CopyCamara, and NIL.
Referenced by MSD_highNameCopyCamera().
int MSD_highNameCopyCamera (char * name1, char * name2)
Definition at line 69 of file camcopy_.cpp.
References cameratp::cname, ERROR, MEN_CamaraJaExiste, MEN_CamaraNomeNaoEncontrada, MSD_getCamera(), MSD_getCameraIdFromName(), MSD_highCopyCamera(), NAM_CopyCamara, and SUCCESS.
int MSD_lowCopyCamera (CTYPE * cptr, Id cn)
Definition at line 128 of file camcopy_.cpp.
References cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, MSD_lowCreateCamera(), NIL, cameratp::ref, cameratp::scale, and cameratp::smooth.
Referenced by MSD_highCopyCamera().