USPDesigner: C:/USPDesig/CAM/camlist_.cpp File Reference
C:/USPDesig/CAM/camlist_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameListCameraName (char *name)
int MSD_lowNameListCameraName (CTYPE *cptr)
void MSD_lowListAllCamera (void)
void MSD_lowListAllCameraName (void)
Function Documentation
int MSD_highNameListCameraName (char * name)
Definition at line 69 of file camlist_.cpp.
References ERROR, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowNameListCameraName(), NAM_ListCamara, and NIL.
void MSD_lowListAllCamera (void)
Definition at line 105 of file camlist_.cpp.
References AllCamera, and MSD_lowNameListCameraName().
Referenced by MSD_execShow().
void MSD_lowListAllCameraName (void)
Definition at line 115 of file camlist_.cpp.
References AllCamera, and cameratp::cname.
Referenced by MSD_execListElement().
int MSD_lowNameListCameraName (CTYPE * cptr)
Definition at line 82 of file camlist_.cpp.
References cameratp::cname, cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, cameratp::ref, cameratp::scale, cameratp::smooth, and TRUE.
Referenced by MSD_execShow(), MSD_highNameListCameraName(), and MSD_lowListAllCamera().