USPDesigner: C:/USPDesig/CAM/cammanip.cpp File Reference
C:/USPDesig/CAM/cammanip.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
int MSD_getNumberOfCameras (void)
char ** MSD_putCameraNameInList (char **list)
CTYPE * MSD_lowFindCameraByName (char *nam)
CTYPE * MSD_getCamera (Id cn)
int MSD_getCameraIdFromName (char *cname)
int MSD_getMaxCameraId (void)
Function Documentation
CTYPE* MSD_getCamera (Id cn)
Definition at line 89 of file cammanip.cpp.
References AllCamera, cameratp::cn, and NIL.
Referenced by MSD_highAlteraCamera(), MSD_highCopyCamera(), MSD_highNameCopyCamera(), MSD_highNameCreateCamera(), MSD_highRemoveCamera(), and MSD_highSetCurrentCamera().
int MSD_getCameraIdFromName (char * cname)
Definition at line 103 of file cammanip.cpp.
References AllCamera, cameratp::cn, and cameratp::cname.
Referenced by MSD_highNameAlteraCamera(), MSD_highNameCopyCamera(), and MSD_highNameCreateCamera().
int MSD_getMaxCameraId (void)
Definition at line 117 of file cammanip.cpp.
References AllCamera, camary, cameratp::cn, and NIL.
Referenced by MSD_highCopyCamera(), and MSD_highCreateCamera().
int MSD_getNumberOfCameras (void)
Definition at line 50 of file cammanip.cpp.
References AllCamera.
CTYPE* MSD_lowFindCameraByName (char * nam)
Definition at line 75 of file cammanip.cpp.
References AllCamera, cameratp::cname, and NIL.
Referenced by AddCamAni(), MSD_createAnimation(), MSD_execShow(), MSD_getTypeByName(), MSD_highMonitor(), MSD_highNameDisplay(), MSD_highNameListCameraName(), MSD_highNameRemoveCamera(), MSD_highNameRenameCamera(), and MSD_highNameSetCurrentCamera().
char** MSD_putCameraNameInList (char ** list)
Definition at line 62 of file cammanip.cpp.
References AllCamera, and cameratp::cname.