USPDesigner: C:/USPDesig/CAM/camnew__.cpp File Reference
C:/USPDesig/CAM/camnew__.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameCreateCamera (char *name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_highCreateCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_middleCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
CTYPE * MSD_lowCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Function Documentation
int MSD_highCreateCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 120 of file camnew__.cpp.
References MSD_getMaxCameraId(), MSD_lowCreateCamera(), and NIL.
Referenced by MSD_highNameCreateCamera().
int MSD_highNameCreateCamera (char * name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 76 of file camnew__.cpp.
References cameratp::cname, ERROR, MEN_CamaraJaExiste, MSD_getCamera(), MSD_getCameraIdFromName(), MSD_highCreateCamera(), NAM_CreateCamara, and SUCCESS.
Referenced by MSD_execCamera().
CTYPE* MSD_lowCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 139 of file camnew__.cpp.
References camary, camused, cameratp::cn, MEN_CamaraParametroIncorreto, MSD_highCheckCamera(), MSD_highSetCamera(), NAM_CreateCamara, NIL, and cameratp::nxt.
Referenced by MSD_highCreateCamera(), MSD_lowCopyCamera(), and MSD_middleCreateCamera().
int MSD_middleCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 131 of file camnew__.cpp.
References MSD_lowCreateCamera(), and NIL.