USPDesigner: C:/USPDesig/CAM/camremov.cpp File Reference
C:/USPDesig/CAM/camremov.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameRemoveCamera (char *name)
int MSD_highRemoveCamera (Id cn)
int MSD_lowRemoveCamera (CTYPE *cptr)
Function Documentation
int MSD_highNameRemoveCamera (char * name)
Definition at line 73 of file camremov.cpp.
References camptr, FALSE, MEN_CamaraNomeCorrente, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowSetCurrentCamera(), NAM_RemoveCamara, and NIL.
Referenced by MSD_highNameDeleteElement().
int MSD_highRemoveCamera (Id cn)
Definition at line 110 of file camremov.cpp.
References camptr, FALSE, MEN_CamaraIdCorrente, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowRemoveCamera(), NAM_RemoveCamara, and NIL.
int MSD_lowRemoveCamera (CTYPE * cptr)
Definition at line 129 of file camremov.cpp.
References camary, camused, cameratp::nxt, and TRUE.
Referenced by MSD_highRemoveCamera().