USPDesigner: C:/USPDesig/CAM/camrenam.cpp File Reference
C:/USPDesig/CAM/camrenam.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameRenameCamera (char *name1, char *name2)
int MSD_lowNameRenameCamera (CTYPE *cptr, char *name2)
Function Documentation
int MSD_highNameRenameCamera (char * name1, char * name2)
Definition at line 69 of file camrenam.cpp.
References ERROR, MEN_CamaraJaExiste, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowNameRenameCamera(), NAM_RenameCamara, and NIL.
Referenced by MSD_highNameRenameElement().
int MSD_lowNameRenameCamera (CTYPE * cptr, char * name2)
Definition at line 88 of file camrenam.cpp.
References cameratp::cname, and SUCCESS.
Referenced by MSD_highNameRenameCamera().