USPDesigner: C:/USPDesig/CAM/camsetcr.cpp File Reference
C:/USPDesig/CAM/camsetcr.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
Functions
int MSD_highNameSetCurrentCamera (char *name)
int MSD_highSetCurrentCamera (Id cn)
int MSD_lowSetCurrentCamera (CTYPE *cptr)
Function Documentation
int MSD_highNameSetCurrentCamera (char * name)
Definition at line 69 of file camsetcr.cpp.
References FALSE, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowSetCurrentCamera(), NAM_SetCamaraCorrente, and NIL.
int MSD_highSetCurrentCamera (Id cn)
Definition at line 100 of file camsetcr.cpp.
References FALSE, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowSetCurrentCamera(), NAM_SetCamaraCorrente, and NIL.
int MSD_lowSetCurrentCamera (CTYPE * cptr)
Definition at line 113 of file camsetcr.cpp.
References camptr, and TRUE.
Referenced by MSD_highNameRemoveCamera(), MSD_highNameSetCurrentCamera(), and MSD_highSetCurrentCamera().