USPDesigner: C:/USPDesig/DIS/disbreak.cpp File Reference
C:/USPDesig/DIS/disbreak.cpp File Reference
#include <stdio.h>
#include <dos.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_lowSetBreakInterruption (void)
void interrupt far MSD_lowBreakFunction (...)
void MSD_lowSetBreakResident (void)
Variables
int breakchk = FALSE
Function Documentation
void interrupt far MSD_lowBreakFunction (...)
Definition at line 66 of file disbreak.cpp.
References breakflg, FALSE, and TRUE.
Referenced by MSD_lowSetBreakInterruption().
void MSD_lowSetBreakInterruption (void)
Definition at line 54 of file disbreak.cpp.
References breakchk, breakflg, FALSE, MSD_lowBreakFunction(), and TRUE.
Referenced by main(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowSetBreakResident (void)
Definition at line 82 of file disbreak.cpp.
References breakchk, breakflg, FALSE, and instream.
Referenced by MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
Variable Documentation
int breakchk = FALSE
Definition at line 51 of file disbreak.cpp.
Referenced by MSD_lowSetBreakInterruption(), and MSD_lowSetBreakResident().