USPDesigner: C:/USPDesig/DIS/discdisp.cpp File Reference
C:/USPDesig/DIS/discdisp.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <graphics.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "genfunc_.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Defines
#define __discdisp_c
Functions
void MSD_execDisplay (void)
int MSD_highNameDisplay (char *cname, char *olist)
int MSD_highNameSetDisplay (char *oname)
void MSD_highDisplayAllEdges (void)
void MSD_lowDisplayAllEdges (void)
void MSD_highDisplayLocalHidden (void)
void MSD_lowDisplayLocalHidden (CTYPE *cptr)
void MSD_lowDisplayLine (int l, vector sv, vector ev)
void MSD_lowDisplayVertex (int l, vector v)
Define Documentation
#define __discdisp_c
Definition at line 41 of file discdisp.cpp.
Function Documentation
void MSD_execDisplay (void)
Definition at line 64 of file discdisp.cpp.
References lineins(), MSD_highNameDisplay(), NIL, restbuf, skipnext(), and workbuf.
void MSD_highDisplayAllEdges (void)
Definition at line 206 of file discdisp.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayAllEdges(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_highDisplayLocalHidden (void)
Definition at line 271 of file discdisp.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayLocalHidden(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
int MSD_highNameDisplay (char * cname, char * olist)
Definition at line 95 of file discdisp.cpp.
References camptr, dspfwptr, FALSE, cameratp::hid, MEN_CamaraNomeNaoEncontrada, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_highNameSetDisplay(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowFindCameraByName(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), NAM_Display, NIL, and TRUE.
Referenced by MSD_execDisplay(), and MSD_lowAreaProjetadaTotal().
int MSD_highNameSetDisplay (char * oname)
Definition at line 146 of file discdisp.cpp.
References AllSolids, def_grpptr, FALSE, GPTYPE, MEN_ElementoNaoEncontrado, MSD_getTypeByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), MSD_lowIsAncestorGroup(), NAM_Display, SolDsp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_highNameDisplay().
void MSD_lowDisplayAllEdges (void)
Definition at line 230 of file discdisp.cpp.
References AllEdgesShell, AllShellsSolid, AllSolids, AllVerticesShell, breakflg, DPTYPE, EdgHe1, EdgHe2, EPTYPE, g_frame(), g_pcolor(), HalVtx, MSD_lowDisplayLine(), MSD_lowDisplayVertex(), MSD_lowGetSolidColor(), SolDsp, SPTYPE, TRUE, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_highDisplayAllEdges().
void MSD_lowDisplayLine (int l, vector sv, vector ev)
Definition at line 347 of file discdisp.cpp.
References g_tline(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayEdge(), and MSD_lowDisplayLocalHidden().
void MSD_lowDisplayLocalHidden (CTYPE * cptr)
Definition at line 295 of file discdisp.cpp.
References _VISIBLE, AllEdgesShell, AllFacesShell, AllShellsSolid, AllSolids, breakflg, cameratp::dash, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFVisi, FPTYPE, g_frame(), g_pcolor(), HalVtx, INVISIBLE, MSD_lowDisplayLine(), MSD_lowGetSolidColor(), MSD_lowIsEdgeVisible(), MSD_lowIsFaceVisible(), SolDsp, SPTYPE, TRUE, veccopy(), and VerVCoord.
Referenced by MSD_highDisplayLocalHidden().
void MSD_lowDisplayVertex (int l, vector v)
Definition at line 357 of file discdisp.cpp.
References g_tpoint(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAllEdges().