USPDesigner: C:/USPDesig/DIS/discfile.cpp File Reference
C:/USPDesig/DIS/discfile.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execDisplayFile (void)
int MSD_highDisplayFile (char rw, char *fname)
int MSD_lowDisplayReadFile (char *fname)
int MSD_lowDisplayWriteFile (char *fname)
Function Documentation
void MSD_execDisplayFile (void)
Definition at line 51 of file discfile.cpp.
References lineins(), MSD_highDisplayFile(), NAM_DisplayFile, optin(), and restbuf.
int MSD_highDisplayFile (char rw, char * fname)
Definition at line 75 of file discfile.cpp.
References FALSE, MSD_lowDisplayReadFile(), and MSD_lowDisplayWriteFile().
Referenced by MSD_execDisplayFile().
int MSD_lowDisplayReadFile (char * fname)
Definition at line 88 of file discfile.cpp.
References dspfrptr, FALSE, h_line(), MEN_NaoAbriuArquivo, NAM_DisplayFile, NIL, and TRUE.
Referenced by MSD_highDisplayFile().
int MSD_lowDisplayWriteFile (char * fname)
Definition at line 117 of file discfile.cpp.
References dspfwptr, FALSE, MEN_NaoAbriuArquivo, NAM_DisplayFile, NIL, and TRUE.
Referenced by CriaFrame(), MSD_createAnimation(), and MSD_highDisplayFile().