USPDesigner: C:/USPDesig/DIS/discamer.cpp File Reference
C:/USPDesig/DIS/discamer.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "mancommd.h"
Functions
void MSD_execCamera (void)
Function Documentation
void MSD_execCamera (void)
Definition at line 51 of file discamer.cpp.
References lineins(), MSD_highNameAlteraCamera(), MSD_highNameCreateCamera(), optin(), and restbuf.