USPDesigner: C:/USPDesig/DIS/disccolr.cpp File Reference
C:/USPDesig/DIS/disccolr.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "gphgraph.h"
#include "mancommd.h"
#include "eulerops.h"
Functions
void MSD_execColor (void)
int MSD_lowSetFrameColor (int color)
int MSD_lowSetDefaultColor (int color)
int MSD_lowGetIntersectionColor (SPTYPE o1ptr, SPTYPE o2ptr)
int MSD_lowGetSolidColor (SPTYPE optr)
Variables
int MaxColors
Function Documentation
void MSD_execColor (void)
Definition at line 56 of file disccolr.cpp.
References lineins(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), MSD_lowSetDefaultColor(), MSD_lowSetFrameColor(), optin(), and restbuf.
int MSD_lowGetIntersectionColor (SPTYPE o1ptr, SPTYPE o2ptr)
Definition at line 197 of file disccolr.cpp.
References MSD_lowGetSolidColor().
Referenced by MSD_lowDisplayIntersection().
int MSD_lowGetSolidColor (SPTYPE optr)
Definition at line 206 of file disccolr.cpp.
References defltcol, GNIL, GPTYPE, GrpGColor, GrpParent, SolColor, and SolGroup.
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), MSD_lowDisplayLocalHidden(), and MSD_lowGetIntersectionColor().
int MSD_lowSetDefaultColor (int color)
Definition at line 120 of file disccolr.cpp.
References defltcol, FALSE, MaxColors, MEN_CorInvalida, NAM_SetDefaultColor, and TRUE.
Referenced by MSD_execColor().
int MSD_lowSetFrameColor (int color)
Definition at line 109 of file disccolr.cpp.
References FALSE, framecol, MaxColors, MEN_CorInvalida, NAM_SetFrameColor, and TRUE.
Referenced by MSD_execColor().
Variable Documentation
int MaxColors
Definition at line 81 of file gphlintf.cpp.