USPDesigner: C:/USPDesig/DIS/disclip3.cpp File Reference
C:/USPDesig/DIS/disclip3.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
int MSD_lowClip3Dimension (vector v1, vector v2)
int MSD_lowCheckClipDisplay (vector t1, vector t2)
int MSD_lowClipingPlane (vector v1, vector v2, vector normal, real d)
void MSD_lowEdgeClip (EPTYPE eptr)
void MSD_lowDetermineVisibility (CTYPE *cptr)
Function Documentation
int MSD_lowCheckClipDisplay (vector t1, vector t2)
Definition at line 111 of file disclip3.cpp.
References abseps, FALSE, TRUE, and veccopy().
Referenced by MSD_lowClip3Dimension().
int MSD_lowClip3Dimension (vector v1, vector v2)
Definition at line 50 of file disclip3.cpp.
References camptr, cameratp::cdis, FALSE, cameratp::mode, MSD_lowCheckClipDisplay(), MSD_lowClipingPlane(), normalize(), cameratp::scale, TRUE, and xyratio.
Referenced by MSD_lowClipDisplayTransformation(), and MSD_lowExecDisplayTransformation().
int MSD_lowClipingPlane (vector v1, vector v2, vector normal, real d)
Definition at line 141 of file disclip3.cpp.
References calc_p(), dot(), FALSE, and TRUE.
Referenced by MSD_lowClip3Dimension().
void MSD_lowDetermineVisibility (CTYPE * cptr)
Definition at line 182 of file disclip3.cpp.
References AllEdgesShell, AllFacesShell, AllShellsSolid, AllSolids, breakflg, DPTYPE, EdgEVis, EPTYPE, FacFVisi, FPTYPE, MSD_lowEdgeClip(), MSD_lowIsEdgeVisible(), MSD_lowIsFaceVisible(), SolDsp, SPTYPE, and TRUE.
Referenced by MSD_lowDisplayHidden().
void MSD_lowEdgeClip (EPTYPE eptr)
Definition at line 161 of file disclip3.cpp.
References EdgEClp, EdgEVClp2, EdgEVClp3, EdgHe1, EdgHe2, EdgSVClp2, EdgSVClp3, HalVtx, MSD_lowClipDisplayTransformation(), MSD_lowExecDisplayTransformation(), TRUE, vec2cp(), veccopy(), and VerVCoord.
Referenced by MSD_lowDetermineVisibility().