USPDesigner: C:/USPDesig/DIS/discaxis.cpp File Reference
C:/USPDesig/DIS/discaxis.cpp File Reference
#include <stdio.h>
#include <graphics.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "mancommd.h"
Functions
void MSD_execDisplayCoordinates (void)
int MSD_highDisplayCoordinates (int opt, int dir, real dis, real l, real dl, int acolor, int mcolor)
int MSD_lowDisplayAxis (real len, int acolor)
int MSD_lowDisplayMesh (int dir, real dis, real len, real dl, int acolor, int mcolor)
void MSD_lowDisplayLineCoordinates (int lt, vector sv, vector ev)
Variables
int MaxColors
Function Documentation
void MSD_execDisplayCoordinates (void)
Definition at line 61 of file discaxis.cpp.
References lineins(), MEN_CoordenadasParametros, MSD_highDisplayCoordinates(), NAM_DisplayCoordinates, optin(), restbuf, and skipsp().
int MSD_highDisplayCoordinates (int opt, int dir, real dis, real l, real dl, int acolor, int mcolor)
Definition at line 122 of file discaxis.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_NenhumaCamaraMonitora, MEN_ParametrosIncorretos, monicptr, MSD_lowDisplayAxis(), MSD_lowDisplayMesh(), NAM_DisplayCoordinates, and TRUE.
Referenced by MSD_execDisplayCoordinates().
int MSD_lowDisplayAxis (real len, int acolor)
Definition at line 148 of file discaxis.cpp.
References camptr, g_pcolor(), monicptr, MSD_lowDisplayLineCoordinates(), and TRUE.
Referenced by MSD_highDisplayCoordinates().
void MSD_lowDisplayLineCoordinates (int lt, vector sv, vector ev)
Definition at line 221 of file discaxis.cpp.
References g_tline(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAxis(), and MSD_lowDisplayMesh().
int MSD_lowDisplayMesh (int dir, real dis, real len, real dl, int acolor, int mcolor)
Definition at line 176 of file discaxis.cpp.
References abseps, camptr, g_pcolor(), monicptr, MSD_lowDisplayLineCoordinates(), and TRUE.
Referenced by MSD_highDisplayCoordinates().
Variable Documentation
int MaxColors
Definition at line 81 of file gphlintf.cpp.
Referenced by g_open(), MSD_highDisplayCoordinates(), MSD_highNameColor(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), MSD_lowSetDefaultColor(), and MSD_lowSetFrameColor().