USPDesigner: C:/USPDesig/INC/disdispl.h File Reference
C:/USPDesig/INC/disdispl.h File Reference
#include <stdio.h>
Classes
struct cameratp
struct DEDGTYPE
Defines
#define EXTERN extern
Typedefs
typedef double real
typedef real vector [4]
typedef real vect2 [3]
typedef real matrix [4][4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct grouptp GTYPE
typedef struct box BTYPE
typedef struct cameratp CTYPE
Functions
int MSD_highAlteraCurrentCamera (char opt, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_highNameAlteraCamera (char opt, char *name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_highAlteraCamera (char opt, Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_lowAlteraCamera (char opt, CTYPE *cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_highCheckCamera (real, real, real, real, real, real, real, int, int, int, int)
int MSD_lowCheckCamera (vector, vector, real, int, int, int, int)
void MSD_highSetCamera (CTYPE *, real, real, real, real, real, real, real, int, int, int, int)
void MSD_lowSetCamera (CTYPE *, vector, vector, real, int, int, int, int)
void MSD_lowSetCameraTransformation (CTYPE *cptr)
void MSD_lowSetCamera3View (int type, CTYPE *cptr)
void MSD_execNameCopyCamera (void)
int MSD_highNameCopyCamera (char *name1, char *name2)
void MSD_execCopyCamera (void)
int MSD_highCopyCamera (int cn)
int MSD_lowCopyCamera (CTYPE *cptr, Id cn)
void MSD_execGetCurrentCameraParameters (void)
int MSD_getCurrentCameraParameters (real *Ex, real *Ey, real *Ez, real *Rx, real *Ry, real *Rz, real *ampl, int *mode, int *elim, int *hash, int *edge)
void MSD_execNameListCameraName (void)
int MSD_highNameListCameraName (char *name)
int MSD_lowNameListCameraName (CTYPE *cptr)
void MSD_lowListAllCamera (void)
void MSD_lowListAllCameraName (void)
int MSD_getNumberOfCameras (void)
char ** MSD_putCameraNameInList (char **list)
CTYPE * MSD_getCamera (Id cn)
Id MSD_getCameraIdFromName (char *nam)
CTYPE * MSD_lowFindCameraByName (char *nam)
CTYPE * MSD_lowFindCamera (Id cn)
Id MSD_getMaxCameraId (void)
void MSD_execNameCreateCamera (void)
int MSD_highNameCreateCamera (char *name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
void MSD_execCreateCamera (void)
int MSD_highCreateCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
int MSD_middleCreateCamera (int cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
CTYPE * MSD_lowCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
void MSD_execNameRemoveCamera (void)
int MSD_highNameRemoveCamera (char *name)
void MSD_execRemoveCamera (void)
int MSD_highRemoveCamera (Id cn)
int MSD_lowRemoveCamera (CTYPE *cptr)
void MSD_execNameRenameCamera (void)
int MSD_highNameRenameCamera (char *name1, char *name2)
int MSD_lowNameRenameCamera (CTYPE *cptr, char *name2)
void MSD_execNameSetCurrentCamera (void)
int MSD_highNameSetCurrentCamera (char *name)
void MSD_execSetCurrentCamera (void)
int MSD_highSetCurrentCamera (Id cn)
int MSD_lowSetCurrentCamera (CTYPE *cptr)
void MSD_execTranslateCurrentCamera (void)
void MSD_lowTranslateCurrentCamera (real dEx, real dEy, real dEz)
void MSD_lowSetBreakInterruption (void)
void interrupt far MSD_lowBreakFunction (...)
void MSD_lowSetBreakResident (void)
void MSD_execCamera (void)
void MSD_execDisplayCoordinates (void)
int MSD_highDisplayCoordinates (int opt, int dir, real dis, real l, real dl, int acolor, int mcolor)
int MSD_lowDisplayAxis (real len, int acolor)
int MSD_lowDisplayMesh (int dir, real dis, real len, real dl, int acolor, int mcolor)
void MSD_lowDisplayLineCoordinates (int lt, vector sv, vector ev)
void MSD_execColor (void)
int MSD_lowSetFrameColor (int color)
int MSD_lowSetDefaultColor (int color)
int MSD_lowGetIntersectionColor (SPTYPE o1ptr, SPTYPE o2ptr)
int MSD_lowGetSolidColor (SPTYPE optr)
void MSD_execDisplay (void)
int MSD_highNameDisplay (char *cname, char *olist)
int MSD_highNameSetDisplay (char *oname)
void MSD_highDisplayAllEdges (void)
void MSD_lowDisplayAllEdges (void)
void MSD_highDisplayLocalHidden (void)
void MSD_lowDisplayLocalHidden (CTYPE *cptr)
void MSD_lowDisplayLine (int l, vector sv, vector ev)
void MSD_lowDisplayVertex (int l, vector v)
void MSD_execDisplayFile (void)
int MSD_highDisplayFile (char rw, char *fname)
int MSD_lowDisplayReadFile (char *fname)
int MSD_lowDisplayWriteFile (char *fname)
int MSD_lowClip3Dimension (vector v1, vector v2)
int MSD_lowCheckClipDisplay (vector t1, vector t2)
int MSD_lowClipingPlane (vector v1, vector v2, vector normal, real d)
void MSD_lowDetermineVisibility (CTYPE *cptr)
void MSD_lowEdgeClip (EPTYPE eptr)
void MSD_execDisplayEdge (void)
void MSD_highDisplayEdge (Id s, Id e, int color)
void MSD_lowDisplayEdge (EPTYPE eptr, int color)
void MSD_lowEdgeEdgeIntersection (SPTYPE optr, EPTYPE eptr, FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowEdgeEdgeCheck (SPTYPE xoptr, SPTYPE optr, EPTYPE xeptr, EPTYPE eptr, real sbox[][2], FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowEdgeEdgeCheckStep2 (vector a1, vector a2, vector b1, vector b2, real *u, real *v)
int MSD_lowEdgeEdgeCheckStep3 (vector s0, vector s1, vector v0, vector v1, real u, vector p)
void MSD_lowEdgeFaceIntersection (SPTYPE o1ptr, SPTYPE o2ptr, FPTYPE f1ptr, FPTYPE f2ptr)
void MSD_lowAddEdgeDivision (vector pos)
void MSD_lowSetEdgeVisibility (char, FPTYPE, FPTYPE, vector)
int MSD_lowIntersectionCheck (vector, FPTYPE, FPTYPE)
int MSD_lowIntersectionCheckStep1 (vector, FPTYPE, FPTYPE)
int MSD_lowPositionalVisibility (char, vector, FPTYPE, FPTYPE, vector)
int MSD_lowEdgePlaneIntersection (vector, vector, FPTYPE, real *, real *)
void MSD_lowCameraDisplayHidden (void)
void MSD_lowDisplayHidden (CTYPE *cptr)
int MSD_lowIsInsideFace (vector pos, FPTYPE xfptr, HPTYPE *ei)
int MSD_lowIsInsideLoop (vector pos, LPTYPE lptr, HPTYPE *ei)
void MSD_lowCameraDisplayIntersection (void)
void MSD_lowDisplayIntersection (void)
void MSD_lowIntersectionFaceFace (SPTYPE, FPTYPE, SPTYPE, FPTYPE)
int MSD_lowIntersectionParallelFaces (FPTYPE f1ptr, FPTYPE f2ptr)
void MSD_lowIntersectionFaceEdge (FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowIntersectionSeparateMinMax (void)
void MSD_lowIntersectionClipDropCoord (int idx)
void MSD_lowSortDividedEdge (void)
int MSD_lowIsEdgeVisible (CTYPE *cptr, EPTYPE eptr)
int MSD_lowIsFaceVisible (CTYPE *cptr, FPTYPE fptr)
int MSD_lowIsInvertedEdge (int isleft, vector dir, FPTYPE fp, vector edir)
void MSD_lowDisplayDividedEdge (CTYPE *cptr, EPTYPE eptr)
void g_frame (void)
void g_tpoint (int lt, vect2 v)
void g_tline (int lt, vect2 sv, vect2 ev)
void g_iline (int lt, int *sv, int *ev)
void h_line (void)
void g_open (void)
void g_filbox (int color, vect2 v0, vect2 v1)
void g_clear (void)
void g_pcolor (int color)
void g_close (void)
void gdcpos (vect2 npos, int *dpos)
void MSD_lowDisplayTransformation (vector, vector)
void MSD_lowInverseDisplayTransformation (vector, vector)
void MSD_lowApplyDisplayTransformation (matrix, vector, vector)
void MSD_lowExecInverseDisplayTransformation (vect2, vect2, vector, vector)
char MSD_lowExecDisplayTransformation (vector, vector, vect2, vect2)
void MSD_lowDisplayTransformationScale (vector, vector, vector, vector)
char MSD_lowClipDisplayTransformation (vector, vector, vector, vector)
void MSD_execMonitor (void)
int MSD_highMonitor (char *name)
int MSD_lowMonitor (CTYPE *cptr, int flag)
void MSD_lowDisplayMonitor (int t, SPTYPE optr, GPTYPE gptr)
void MSD_lowDisplayMonitorSolid (SPTYPE op)
void MSD_lowDisplayMonitorGroup (GPTYPE gptr)
void MSD_lowDisplayMonitorAxis (void)
Variables
EXTERN int MAX_COLOR_NUMBER
EXTERN DEDGTYPE * divedge
EXTERN DEDGTYPE * divedptr
EXTERN int divednum
EXTERN vector desvtx
EXTERN vector deevtx
EXTERN BTYPE debox
EXTERN int Draw
EXTERN int NumCinema
EXTERN FILE * dspfwptr
EXTERN FILE * dspfrptr
EXTERN int breakflg
EXTERN real abseps
EXTERN real xyratio
EXTERN CTYPE camera3
EXTERN CTYPE * camary
EXTERN CTYPE * camptr
EXTERN int camused
EXTERN real angsmooth
EXTERN char monisw
EXTERN CTYPE * monicptr
EXTERN int defltcol
EXTERN int framecol
EXTERN int lncolor
EXTERN int lntype
Define Documentation
#define EXTERN extern
Definition at line 49 of file disdispl.h.
Typedef Documentation
typedef struct box BTYPE
Definition at line 93 of file disdispl.h.
typedef struct cameratp CTYPE
Definition at line 97 of file disdispl.h.
typedef struct edge ETYPE
Definition at line 81 of file disdispl.h.
typedef struct face FTYPE
Definition at line 77 of file disdispl.h.
typedef struct grouptp GTYPE
Definition at line 89 of file disdispl.h.
typedef struct halfedge HTYPE
Definition at line 85 of file disdispl.h.
typedef real matrix[4][4]
Definition at line 69 of file disdispl.h.
typedef double real
Definition at line 57 of file disdispl.h.
typedef struct solid STYPE
Definition at line 73 of file disdispl.h.
typedef real vect2[3]
Definition at line 65 of file disdispl.h.
typedef real vector[4]
Definition at line 61 of file disdispl.h.
Function Documentation
void g_clear (void)
Definition at line 378 of file gphlintf.cpp.
Referenced by CriaFrame(), ExibeFrame(), g_open(), maninit(), MSD_createAnimation(), MSD_displayLoadedAnimation(), MSD_execClear(), and MSD_lowAreaProjetadaTotal().
void g_close (void)
Definition at line 406 of file gphlintf.cpp.
Referenced by endfunc().
void g_filbox (int color, vect2 v0, vect2 v1)
Definition at line 349 of file gphlintf.cpp.
References gdcpos().
Referenced by MSD_lowClearWindow().
void g_frame (void)
Definition at line 85 of file gphlintf.cpp.
References Draw, dspfwptr, dwindbox, framecol, framenum, MaxX, MaxY, and xyratio.
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), and MSD_lowDisplayLocalHidden().
void g_iline (int lt, int * sv, int * ev)
Definition at line 164 of file gphlintf.cpp.
References Draw, and lncolor.
Referenced by DrawLine().
void g_open (void)
Definition at line 295 of file gphlintf.cpp.
References FALSE, g_clear(), GraphDriver, GraphError, GraphMode, MaxColors, MaxX, and MaxY.
Referenced by main().
void g_pcolor (int color)
Definition at line 401 of file gphlintf.cpp.
References lncolor.
Referenced by DrawLine(), MSD_lowDisplayAllEdges(), MSD_lowDisplayAxis(), MSD_lowDisplayEdge(), MSD_lowDisplayHidden(), MSD_lowDisplayIntersection(), MSD_lowDisplayLocalHidden(), and MSD_lowDisplayMesh().
void g_tline (int lt, vect2 sv, vect2 ev)
Definition at line 216 of file gphlintf.cpp.
References Draw, dspfwptr, framenum, gdcpos(), lncolor, and lntype.
Referenced by h_line(), MSD_lowDisplayDividedEdge(), MSD_lowDisplayHidden(), MSD_lowDisplayLine(), and MSD_lowDisplayLineCoordinates().
void g_tpoint (int lt, vect2 v)
Definition at line 148 of file gphlintf.cpp.
References Draw, gdcpos(), and lncolor.
Referenced by MSD_lowDisplayVertex().
void gdcpos (vect2 npos, int * dpos)
Definition at line 419 of file gphlintf.cpp.
References dwindbox, MaxX, MaxY, and xyratio.
Referenced by g_filbox(), g_tline(), g_tpoint(), and LoadFrame().
void h_line (void)
Definition at line 278 of file gphlintf.cpp.
References dspfrptr, g_tline(), and lncolor.
Referenced by MSD_lowDisplayReadFile().
void MSD_execCamera (void)
Definition at line 51 of file discamer.cpp.
References lineins(), MSD_highNameAlteraCamera(), MSD_highNameCreateCamera(), optin(), and restbuf.
void MSD_execColor (void)
Definition at line 56 of file disccolr.cpp.
References lineins(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), MSD_lowSetDefaultColor(), MSD_lowSetFrameColor(), optin(), and restbuf.
void MSD_execCopyCamera (void)
void MSD_execCreateCamera (void)
void MSD_execDisplay (void)
Definition at line 64 of file discdisp.cpp.
References lineins(), MSD_highNameDisplay(), NIL, restbuf, skipnext(), and workbuf.
void MSD_execDisplayCoordinates (void)
Definition at line 61 of file discaxis.cpp.
References lineins(), MEN_CoordenadasParametros, MSD_highDisplayCoordinates(), NAM_DisplayCoordinates, optin(), restbuf, and skipsp().
void MSD_execDisplayEdge (void)
void MSD_execDisplayFile (void)
Definition at line 51 of file discfile.cpp.
References lineins(), MSD_highDisplayFile(), NAM_DisplayFile, optin(), and restbuf.
void MSD_execGetCurrentCameraParameters (void)
void MSD_execMonitor (void)
Definition at line 53 of file dismonit.cpp.
References lineins(), MSD_highMonitor(), NAM_Monitor, and restbuf.
void MSD_execNameCopyCamera (void)
void MSD_execNameCreateCamera (void)
void MSD_execNameListCameraName (void)
void MSD_execNameRemoveCamera (void)
void MSD_execNameRenameCamera (void)
void MSD_execNameSetCurrentCamera (void)
void MSD_execRemoveCamera (void)
void MSD_execSetCurrentCamera (void)
void MSD_execTranslateCurrentCamera (void)
CTYPE* MSD_getCamera (Id cn)
Definition at line 89 of file cammanip.cpp.
References AllCamera, cameratp::cn, and NIL.
Referenced by MSD_highAlteraCamera(), MSD_highCopyCamera(), MSD_highNameCopyCamera(), MSD_highNameCreateCamera(), MSD_highRemoveCamera(), and MSD_highSetCurrentCamera().
Id MSD_getCameraIdFromName (char * nam)
Definition at line 103 of file cammanip.cpp.
References AllCamera, cameratp::cn, and cameratp::cname.
Referenced by MSD_highNameAlteraCamera(), MSD_highNameCopyCamera(), and MSD_highNameCreateCamera().
int MSD_getCurrentCameraParameters (real * Ex, real * Ey, real * Ez, real * Rx, real * Ry, real * Rz, real * ampl, int * mode, int * elim, int * hash, int * edge)
Definition at line 80 of file camgetpr.cpp.
References camptr, cameratp::dash, cameratp::eye, FALSE, cameratp::hid, cameratp::mode, NIL, cameratp::ref, cameratp::scale, cameratp::smooth, and TRUE.
Id MSD_getMaxCameraId (void)
Definition at line 117 of file cammanip.cpp.
References AllCamera, camary, cameratp::cn, and NIL.
Referenced by MSD_highCopyCamera(), and MSD_highCreateCamera().
int MSD_getNumberOfCameras (void)
Definition at line 50 of file cammanip.cpp.
References AllCamera.
int MSD_highAlteraCamera (char opt, Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 69 of file camaltpr.cpp.
References ERROR, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowAlteraCamera(), NAM_AlteraCamara, and NIL.
Referenced by MSD_highNameAlteraCamera().
int MSD_highAlteraCurrentCamera (char opt, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 51 of file camaltcr.cpp.
References camptr, ERROR, MEN_NenhumaCamaraCorrente, MSD_lowAlteraCamera(), NAM_AlteraCamaraCorrente, and NIL.
int MSD_highCheckCamera (real , real , real , real , real , real , real , int , int , int , int)
Definition at line 55 of file camcheck.cpp.
References makevec(), and MSD_lowCheckCamera().
Referenced by MSD_lowCreateCamera().
int MSD_highCopyCamera (int cn)
Definition at line 113 of file camcopy_.cpp.
References ERROR, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_getMaxCameraId(), MSD_lowCopyCamera(), NAM_CopyCamara, and NIL.
Referenced by MSD_highNameCopyCamera().
int MSD_highCreateCamera (real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 120 of file camnew__.cpp.
References MSD_getMaxCameraId(), MSD_lowCreateCamera(), and NIL.
Referenced by MSD_highNameCreateCamera().
void MSD_highDisplayAllEdges (void)
Definition at line 206 of file discdisp.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayAllEdges(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
int MSD_highDisplayCoordinates (int opt, int dir, real dis, real l, real dl, int acolor, int mcolor)
Definition at line 122 of file discaxis.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_NenhumaCamaraMonitora, MEN_ParametrosIncorretos, monicptr, MSD_lowDisplayAxis(), MSD_lowDisplayMesh(), NAM_DisplayCoordinates, and TRUE.
Referenced by MSD_execDisplayCoordinates().
void MSD_highDisplayEdge (Id s, Id e, int color)
Definition at line 80 of file disedge_.cpp.
References ENIL, EPTYPE, MEN_NaoEncontrouAresta, MSD_getSolid(), MSD_lowDisplayEdge(), MSD_lowShowFindEdge(), and NAM_DisplayEdge.
int MSD_highDisplayFile (char rw, char * fname)
Definition at line 75 of file discfile.cpp.
References FALSE, MSD_lowDisplayReadFile(), and MSD_lowDisplayWriteFile().
Referenced by MSD_execDisplayFile().
void MSD_highDisplayLocalHidden (void)
Definition at line 271 of file discdisp.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayLocalHidden(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
int MSD_highMonitor (char * name)
Definition at line 68 of file dismonit.cpp.
References FALSE, MEN_ParametrosIncorretos, MSD_lowFindCameraByName(), MSD_lowMonitor(), NAM_Monitor, NIL, and strlower().
Referenced by MSD_execMonitor().
int MSD_highNameAlteraCamera (char opt, char * name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 52 of file camaltpr.cpp.
References ERROR, MEN_CamaraNomeNaoEncontrada, MSD_getCameraIdFromName(), MSD_highAlteraCamera(), and NAM_AlteraCamara.
Referenced by MSD_execCamera().
int MSD_highNameCopyCamera (char * name1, char * name2)
Definition at line 69 of file camcopy_.cpp.
References cameratp::cname, ERROR, MEN_CamaraJaExiste, MEN_CamaraNomeNaoEncontrada, MSD_getCamera(), MSD_getCameraIdFromName(), MSD_highCopyCamera(), NAM_CopyCamara, and SUCCESS.
int MSD_highNameCreateCamera (char * name, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 76 of file camnew__.cpp.
References cameratp::cname, ERROR, MEN_CamaraJaExiste, MSD_getCamera(), MSD_getCameraIdFromName(), MSD_highCreateCamera(), NAM_CreateCamara, and SUCCESS.
Referenced by MSD_execCamera().
int MSD_highNameDisplay (char * cname, char * olist)
Definition at line 95 of file discdisp.cpp.
References camptr, dspfwptr, FALSE, cameratp::hid, MEN_CamaraNomeNaoEncontrada, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_highNameSetDisplay(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowFindCameraByName(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), NAM_Display, NIL, and TRUE.
Referenced by MSD_execDisplay(), and MSD_lowAreaProjetadaTotal().
int MSD_highNameListCameraName (char * name)
Definition at line 69 of file camlist_.cpp.
References ERROR, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowNameListCameraName(), NAM_ListCamara, and NIL.
int MSD_highNameRemoveCamera (char * name)
Definition at line 73 of file camremov.cpp.
References camptr, FALSE, MEN_CamaraNomeCorrente, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowSetCurrentCamera(), NAM_RemoveCamara, and NIL.
Referenced by MSD_highNameDeleteElement().
int MSD_highNameRenameCamera (char * name1, char * name2)
Definition at line 69 of file camrenam.cpp.
References ERROR, MEN_CamaraJaExiste, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowNameRenameCamera(), NAM_RenameCamara, and NIL.
Referenced by MSD_highNameRenameElement().
int MSD_highNameSetCurrentCamera (char * name)
Definition at line 69 of file camsetcr.cpp.
References FALSE, MEN_CamaraNomeNaoEncontrada, MSD_lowFindCameraByName(), MSD_lowSetCurrentCamera(), NAM_SetCamaraCorrente, and NIL.
int MSD_highNameSetDisplay (char * oname)
Definition at line 146 of file discdisp.cpp.
References AllSolids, def_grpptr, FALSE, GPTYPE, MEN_ElementoNaoEncontrado, MSD_getTypeByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), MSD_lowIsAncestorGroup(), NAM_Display, SolDsp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_highNameDisplay().
int MSD_highRemoveCamera (Id cn)
Definition at line 110 of file camremov.cpp.
References camptr, FALSE, MEN_CamaraIdCorrente, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowRemoveCamera(), NAM_RemoveCamara, and NIL.
void MSD_highSetCamera (CTYPE * , real , real , real , real , real , real , real , int , int , int , int)
Definition at line 96 of file camcheck.cpp.
References makevec(), and MSD_lowSetCamera().
Referenced by MSD_lowCreateCamera(), and MSD_lowTranslateCurrentCamera().
int MSD_highSetCurrentCamera (Id cn)
Definition at line 100 of file camsetcr.cpp.
References FALSE, MEN_CamaraIdNaoEncontrada, MSD_getCamera(), MSD_lowSetCurrentCamera(), NAM_SetCamaraCorrente, and NIL.
void MSD_lowAddEdgeDivision (vector pos)
Definition at line 337 of file dishediv.cpp.
References DEDGTYPE::devis, divednum, divedptr, and veccopy().
Referenced by MSD_lowDisplayHidden(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionFaceEdge(), and MSD_lowIntersectionSeparateMinMax().
int MSD_lowAlteraCamera (char opt, CTYPE * cptr, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 85 of file camaltpr.cpp.
References cameratp::dash, cameratp::eye, FALSE, cameratp::hid, makevec(), MEN_CamaraParametroIncorreto, cameratp::mode, MSD_lowCheckCamera(), MSD_lowSetCamera(), NAM_AlteraCamara, cameratp::ref, cameratp::scale, cameratp::smooth, TRUE, and veccopy().
Referenced by MSD_highAlteraCamera(), and MSD_highAlteraCurrentCamera().
void MSD_lowApplyDisplayTransformation (matrix , vector , vector)
Definition at line 67 of file disltrns.cpp.
Referenced by MSD_lowDisplayTransformation().
void interrupt far MSD_lowBreakFunction (...)
Definition at line 66 of file disbreak.cpp.
References breakflg, FALSE, and TRUE.
Referenced by MSD_lowSetBreakInterruption().
void MSD_lowCameraDisplayHidden (void)
Definition at line 59 of file dishidde.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayHidden(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowCameraDisplayIntersection (void)
Definition at line 51 of file dishintr.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayHidden(), MSD_lowDisplayIntersection(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
int MSD_lowCheckCamera (vector , vector , real , int , int , int , int)
Definition at line 66 of file camcheck.cpp.
References abseps, FALSE, releps, TRUE, and vecd().
Referenced by MSD_highCheckCamera(), and MSD_lowAlteraCamera().
int MSD_lowCheckClipDisplay (vector t1, vector t2)
Definition at line 111 of file disclip3.cpp.
References abseps, FALSE, TRUE, and veccopy().
Referenced by MSD_lowClip3Dimension().
int MSD_lowClip3Dimension (vector v1, vector v2)
Definition at line 50 of file disclip3.cpp.
References camptr, cameratp::cdis, FALSE, cameratp::mode, MSD_lowCheckClipDisplay(), MSD_lowClipingPlane(), normalize(), cameratp::scale, TRUE, and xyratio.
Referenced by MSD_lowClipDisplayTransformation(), and MSD_lowExecDisplayTransformation().
char MSD_lowClipDisplayTransformation (vector , vector , vector , vector)
Definition at line 155 of file disltrns.cpp.
References FALSE, MSD_lowClip3Dimension(), MSD_lowDisplayTransformation(), MSD_lowInverseDisplayTransformation(), TRUE, and veccopy().
Referenced by MSD_lowEdgeClip(), and MSD_lowIntersectionSeparateMinMax().
int MSD_lowClipingPlane (vector v1, vector v2, vector normal, real d)
Definition at line 141 of file disclip3.cpp.
References calc_p(), dot(), FALSE, and TRUE.
Referenced by MSD_lowClip3Dimension().
int MSD_lowCopyCamera (CTYPE * cptr, Id cn)
Definition at line 128 of file camcopy_.cpp.
References cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, MSD_lowCreateCamera(), NIL, cameratp::ref, cameratp::scale, and cameratp::smooth.
Referenced by MSD_highCopyCamera().
CTYPE* MSD_lowCreateCamera (Id cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 139 of file camnew__.cpp.
References camary, camused, cameratp::cn, MEN_CamaraParametroIncorreto, MSD_highCheckCamera(), MSD_highSetCamera(), NAM_CreateCamara, NIL, and cameratp::nxt.
Referenced by MSD_highCreateCamera(), MSD_lowCopyCamera(), and MSD_middleCreateCamera().
void MSD_lowDetermineVisibility (CTYPE * cptr)
Definition at line 182 of file disclip3.cpp.
References AllEdgesShell, AllFacesShell, AllShellsSolid, AllSolids, breakflg, DPTYPE, EdgEVis, EPTYPE, FacFVisi, FPTYPE, MSD_lowEdgeClip(), MSD_lowIsEdgeVisible(), MSD_lowIsFaceVisible(), SolDsp, SPTYPE, and TRUE.
Referenced by MSD_lowDisplayHidden().
void MSD_lowDisplayAllEdges (void)
Definition at line 230 of file discdisp.cpp.
References AllEdgesShell, AllShellsSolid, AllSolids, AllVerticesShell, breakflg, DPTYPE, EdgHe1, EdgHe2, EPTYPE, g_frame(), g_pcolor(), HalVtx, MSD_lowDisplayLine(), MSD_lowDisplayVertex(), MSD_lowGetSolidColor(), SolDsp, SPTYPE, TRUE, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_highDisplayAllEdges().
int MSD_lowDisplayAxis (real len, int acolor)
Definition at line 148 of file discaxis.cpp.
References camptr, g_pcolor(), monicptr, MSD_lowDisplayLineCoordinates(), and TRUE.
Referenced by MSD_highDisplayCoordinates().
void MSD_lowDisplayDividedEdge (CTYPE * cptr, EPTYPE eptr)
Definition at line 56 of file disledge.cpp.
References cameratp::dash, DEDGTYPE::devis, DEDGTYPE::devtx, divedge, divednum, divedptr, EdgEVis, ENIL, FALSE, g_tline(), INVISIBLE, MSD_lowExecDisplayTransformation(), and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
void MSD_lowDisplayEdge (EPTYPE eptr, int color)
Definition at line 93 of file disedge_.cpp.
References EdgHe1, EdgHe2, g_pcolor(), HalVtx, MSD_lowDisplayLine(), and VerVCoord.
Referenced by MSD_highDisplayEdge().
void MSD_lowDisplayHidden (CTYPE * cptr)
Definition at line 87 of file dishidde.cpp.
References _VISIBLE, AllEdgesShell, AllShellsSolid, AllSolids, breakflg, cameratp::dash, deevtx, desvtx, divedge, divednum, divedptr, DPTYPE, EdgEClp, EdgEVClp2, EdgEVClp3, EdgEVis, EdgHe1, EdgHe2, EdgSVClp2, EdgSVClp3, EPTYPE, FPTYPE, g_frame(), g_pcolor(), g_tline(), HalVtx, HalWLoop, INVISIBLE, LooLFace, MSD_lowAddEdgeDivision(), MSD_lowDetermineVisibility(), MSD_lowDisplayDividedEdge(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowGetSolidColor(), MSD_lowSetEdgeVisibility(), MSD_lowSortDividedEdge(), MSD_lowUpdateDEBox(), normalize(), SNIL, SolDsp, SPTYPE, TRUE, veccopy(), vecminus(), VerVCoord, and workbuf.
Referenced by MSD_lowCameraDisplayHidden(), and MSD_lowCameraDisplayIntersection().
void MSD_lowDisplayIntersection (void)
Definition at line 84 of file dishintr.cpp.
References AllFacesShell, AllShellsSolid, AllSolids, breakflg, camptr, cameratp::dash, DPTYPE, FacBox, FacFVisi, FALSE, FPTYPE, g_pcolor(), MSD_lowBoxBoxIntersection(), MSD_lowGetIntersectionColor(), MSD_lowIntersectionFaceFace(), SNIL, SolBox, SolDsp, SolNxt, and SPTYPE.
Referenced by MSD_lowCameraDisplayIntersection().
void MSD_lowDisplayLine (int l, vector sv, vector ev)
Definition at line 347 of file discdisp.cpp.
References g_tline(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayEdge(), and MSD_lowDisplayLocalHidden().
void MSD_lowDisplayLineCoordinates (int lt, vector sv, vector ev)
Definition at line 221 of file discaxis.cpp.
References g_tline(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAxis(), and MSD_lowDisplayMesh().
void MSD_lowDisplayLocalHidden (CTYPE * cptr)
Definition at line 295 of file discdisp.cpp.
References _VISIBLE, AllEdgesShell, AllFacesShell, AllShellsSolid, AllSolids, breakflg, cameratp::dash, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFVisi, FPTYPE, g_frame(), g_pcolor(), HalVtx, INVISIBLE, MSD_lowDisplayLine(), MSD_lowGetSolidColor(), MSD_lowIsEdgeVisible(), MSD_lowIsFaceVisible(), SolDsp, SPTYPE, TRUE, veccopy(), and VerVCoord.
Referenced by MSD_highDisplayLocalHidden().
int MSD_lowDisplayMesh (int dir, real dis, real len, real dl, int acolor, int mcolor)
Definition at line 176 of file discaxis.cpp.
References abseps, camptr, g_pcolor(), monicptr, MSD_lowDisplayLineCoordinates(), and TRUE.
Referenced by MSD_highDisplayCoordinates().
void MSD_lowDisplayMonitor (int t, SPTYPE optr, GPTYPE gptr)
Definition at line 121 of file dismonit.cpp.
References camptr, monicptr, monisw, MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
Referenced by MSD_highDifference(), MSD_highIntersection(), MSD_highMakeCone(), MSD_highMakeCube(), MSD_highMakeCylinder(), MSD_highMakePrism(), MSD_highMakePyramid(), MSD_highMakeRevolve(), MSD_highMakeSphere(), MSD_highMakeSWEEP(), MSD_highMakeTorus(), MSD_highSplit(), and MSD_highUnion().
void MSD_lowDisplayMonitorAxis (void)
Definition at line 217 of file dismonit.cpp.
References cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowSetBreakInterruption(), and MSD_lowSetBreakResident().
Referenced by MSD_lowDisplayMonitor().
void MSD_lowDisplayMonitorGroup (GPTYPE gptr)
Definition at line 180 of file dismonit.cpp.
References AllSolids, cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowIsAncestorGroup(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), SolDsp, SolGroup, and SPTYPE.
Referenced by MSD_lowDisplayMonitor().
void MSD_lowDisplayMonitorSolid (SPTYPE op)
Definition at line 143 of file dismonit.cpp.
References AllSolids, cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), SolDsp, and SPTYPE.
Referenced by MSD_lowDisplayMonitor().
int MSD_lowDisplayReadFile (char * fname)
Definition at line 88 of file discfile.cpp.
References dspfrptr, FALSE, h_line(), MEN_NaoAbriuArquivo, NAM_DisplayFile, NIL, and TRUE.
Referenced by MSD_highDisplayFile().
void MSD_lowDisplayTransformation (vector , vector)
Definition at line 49 of file disltrns.cpp.
References camptr, cameratp::drot, cameratp::eye, MSD_lowApplyDisplayTransformation(), and vecminus().
Referenced by MSD_lowClipDisplayTransformation(), MSD_lowDisplayTransformationScale(), and MSD_lowExecDisplayTransformation().
void MSD_lowDisplayTransformationScale (vector , vector , vector , vector)
Definition at line 133 of file disltrns.cpp.
References camptr, cameratp::cdis, cameratp::mode, MSD_lowDisplayTransformation(), and cameratp::scale.
void MSD_lowDisplayVertex (int l, vector v)
Definition at line 357 of file discdisp.cpp.
References g_tpoint(), and MSD_lowExecDisplayTransformation().
Referenced by MSD_lowDisplayAllEdges().
int MSD_lowDisplayWriteFile (char * fname)
Definition at line 117 of file discfile.cpp.
References dspfwptr, FALSE, MEN_NaoAbriuArquivo, NAM_DisplayFile, NIL, and TRUE.
Referenced by CriaFrame(), MSD_createAnimation(), and MSD_highDisplayFile().
void MSD_lowEdgeClip (EPTYPE eptr)
Definition at line 161 of file disclip3.cpp.
References EdgEClp, EdgEVClp2, EdgEVClp3, EdgHe1, EdgHe2, EdgSVClp2, EdgSVClp3, HalVtx, MSD_lowClipDisplayTransformation(), MSD_lowExecDisplayTransformation(), TRUE, vec2cp(), veccopy(), and VerVCoord.
Referenced by MSD_lowDetermineVisibility().
int MSD_lowEdgeEdgeCheck (SPTYPE xoptr, SPTYPE optr, EPTYPE xeptr, EPTYPE eptr, real sbox[][2], FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 126 of file dishediv.cpp.
References EdgEClp, EdgEVClp2, EdgHe1, EdgHe2, EdgSVClp2, FacFVisi, FALSE, FPTYPE, HalVtx, HalWLoop, LooLFace, and TRUE.
Referenced by MSD_lowEdgeEdgeIntersection().
int MSD_lowEdgeEdgeCheckStep2 (vector a1, vector a2, vector b1, vector b2, real * u, real * v)
Definition at line 225 of file dishediv.cpp.
References FALSE, releps, and TRUE.
Referenced by MSD_lowEdgeEdgeIntersection().
int MSD_lowEdgeEdgeCheckStep3 (vector s0, vector s1, vector v0, vector v1, real u, vector p)
Definition at line 253 of file dishediv.cpp.
References calc_p(), camptr, cross(), cameratp::eye, FALSE, cameratp::mode, releps, TRUE, and vecminus().
Referenced by MSD_lowEdgeEdgeIntersection().
void MSD_lowEdgeEdgeIntersection (SPTYPE optr, EPTYPE eptr, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 51 of file dishediv.cpp.
References _VISIBLE, abseps, AllEdgesShell, AllShellsSolid, AllSolids, camptr, deevtx, desvtx, DPTYPE, EdgEVClp2, EdgEVClp3, EdgEVis, EdgSVClp2, EdgSVClp3, EPTYPE, cameratp::eye, MSD_lowAddEdgeDivision(), MSD_lowEdgeEdgeCheck(), MSD_lowEdgeEdgeCheckStep2(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowExecDisplayTransformation(), MSD_lowExecInverseDisplayTransformation(), releps, SolDsp, SPTYPE, TRUE, vec2cp(), veccopy(), and vecd().
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
void MSD_lowEdgeFaceIntersection (SPTYPE o1ptr, SPTYPE o2ptr, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 286 of file dishediv.cpp.
References abseps, AllFacesShell, AllShellsSolid, AllSolids, calc_p(), debox, deevtx, desvtx, DONTSHOW, dot(), DPTYPE, FacBox, FacFeq, FacFVisi, FPTYPE, HPTYPE, MSD_lowAddEdgeDivision(), MSD_lowBoxBoxIntersection(), MSD_lowIsInsideFace(), SolBox, SolDsp, SPTYPE, and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
int MSD_lowEdgePlaneIntersection (vector , vector , FPTYPE , real * , real *)
Definition at line 249 of file dishevis.cpp.
References abseps, calc_p(), dot(), FacFeq, FALSE, and TRUE.
Referenced by MSD_lowPositionalVisibility().
char MSD_lowExecDisplayTransformation (vector , vector , vect2 , vect2)
Definition at line 105 of file disltrns.cpp.
References camptr, cameratp::cdis, FALSE, cameratp::mode, MSD_lowClip3Dimension(), MSD_lowDisplayTransformation(), cameratp::scale, and TRUE.
Referenced by MSD_lowDisplayDividedEdge(), MSD_lowDisplayLine(), MSD_lowDisplayLineCoordinates(), MSD_lowDisplayVertex(), MSD_lowEdgeClip(), and MSD_lowEdgeEdgeIntersection().
void MSD_lowExecInverseDisplayTransformation (vect2 , vect2 , vector , vector)
Definition at line 78 of file disltrns.cpp.
References camptr, cameratp::cdis, cameratp::mode, MSD_lowInverseDisplayTransformation(), and cameratp::scale.
Referenced by MSD_lowEdgeEdgeIntersection().
CTYPE* MSD_lowFindCamera (Id cn)
CTYPE* MSD_lowFindCameraByName (char * nam)
Definition at line 75 of file cammanip.cpp.
References AllCamera, cameratp::cname, and NIL.
Referenced by AddCamAni(), MSD_createAnimation(), MSD_execShow(), MSD_getTypeByName(), MSD_highMonitor(), MSD_highNameDisplay(), MSD_highNameListCameraName(), MSD_highNameRemoveCamera(), MSD_highNameRenameCamera(), and MSD_highNameSetCurrentCamera().
int MSD_lowGetIntersectionColor (SPTYPE o1ptr, SPTYPE o2ptr)
Definition at line 197 of file disccolr.cpp.
References MSD_lowGetSolidColor().
Referenced by MSD_lowDisplayIntersection().
int MSD_lowGetSolidColor (SPTYPE optr)
Definition at line 206 of file disccolr.cpp.
References defltcol, GNIL, GPTYPE, GrpGColor, GrpParent, SolColor, and SolGroup.
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), MSD_lowDisplayLocalHidden(), and MSD_lowGetIntersectionColor().
int MSD_lowIntersectionCheck (vector , FPTYPE , FPTYPE)
Definition at line 77 of file dishevis.cpp.
References DEDGTYPE::devis, divedptr, DONTSHOW, FacFVisi, FALSE, MSD_lowIntersectionCheckStep1(), and TRUE.
Referenced by MSD_lowSetEdgeVisibility().
int MSD_lowIntersectionCheckStep1 (vector , FPTYPE , FPTYPE)
Definition at line 95 of file dishevis.cpp.
References cross(), DEDGTYPE::devis, divedptr, DONTSHOW, dot(), FacFeq, FALSE, HalNxt, HalVtx, HalWLoop, HPTYPE, INVISIBLE, LooLFace, mate, MSD_lowIsInsideFace(), normalize(), releps, TRUE, veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_lowIntersectionCheck().
void MSD_lowIntersectionClipDropCoord (int idx)
Definition at line 302 of file dishintr.cpp.
References deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, and veccopy().
Referenced by MSD_lowIntersectionSeparateMinMax().
void MSD_lowIntersectionFaceEdge (FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 218 of file dishintr.cpp.
References abseps, calc_p(), dot(), FacFeq, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, MSD_lowAddEdgeDivision(), MSD_lowIsInsideFace(), veccopy(), and VerVCoord.
Referenced by MSD_lowIntersectionFaceFace().
void MSD_lowIntersectionFaceFace (SPTYPE , FPTYPE , SPTYPE , FPTYPE)
Definition at line 169 of file dishintr.cpp.
References camptr, divedge, divednum, divedptr, ENIL, FALSE, MSD_lowDisplayDividedEdge(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionFaceEdge(), MSD_lowIntersectionParallelFaces(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSetEdgeVisibility(), MSD_lowSortDividedEdge(), MSD_lowUpdateDEBox(), NIL, SNIL, TRUE, and workbuf.
Referenced by MSD_lowDisplayIntersection().
int MSD_lowIntersectionParallelFaces (FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 196 of file dishintr.cpp.
References abseps, dot(), FacFeq, FALSE, TRUE, veccopy(), vecminus(), and vecplus().
Referenced by MSD_lowIntersectionFaceFace().
int MSD_lowIntersectionSeparateMinMax (void)
Definition at line 254 of file dishintr.cpp.
References abseps, deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, FALSE, MSD_lowAddEdgeDivision(), MSD_lowClipDisplayTransformation(), MSD_lowIntersectionClipDropCoord(), and TRUE.
Referenced by MSD_lowIntersectionFaceFace().
void MSD_lowInverseDisplayTransformation (vector , vector)
Definition at line 57 of file disltrns.cpp.
References camptr, cameratp::drot, cameratp::eye, vecmult(), and vecplus().
Referenced by MSD_lowClipDisplayTransformation(), and MSD_lowExecInverseDisplayTransformation().
int MSD_lowIsEdgeVisible (CTYPE * cptr, EPTYPE eptr)
Definition at line 51 of file dishvisb.cpp.
References _VISIBLE, angsmooth, DONTSHOW, EdgAngle, EdgHe1, EdgHe2, cameratp::eye, FacFVisi, FALSE, FPTYPE, HalVtx, HalWLoop, INVISIBLE, LooLFace, cameratp::mode, MSD_lowIsInvertedEdge(), normalize(), cameratp::ref, cameratp::smooth, TRUE, veccopy(), vecminus(), VerVCoord, and VPTYPE.
Referenced by MSD_lowDetermineVisibility(), and MSD_lowDisplayLocalHidden().
int MSD_lowIsFaceVisible (CTYPE * cptr, FPTYPE fptr)
Definition at line 106 of file dishvisb.cpp.
References _VISIBLE, abseps, DONTSHOW, dot(), cameratp::drot, cameratp::eye, FacFeq, INVISIBLE, cameratp::mode, and veccopy().
Referenced by MSD_lowDetermineVisibility(), and MSD_lowDisplayLocalHidden().
int MSD_lowIsInsideFace (vector pos, FPTYPE xfptr, HPTYPE * ei)
Definition at line 50 of file dishinfc.cpp.
References _VISIBLE, AllLoopsFace, DONTSHOW, FacFLOut, INVISIBLE, LPTYPE, and MSD_lowIsInsideLoop().
Referenced by MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionFaceEdge(), and MSD_lowPositionalVisibility().
int MSD_lowIsInsideLoop (vector pos, LPTYPE lptr, HPTYPE * ei)
Definition at line 76 of file dishinfc.cpp.
References _VISIBLE, abseps, DONTSHOW, FacFeq, HalNxt, HalVtx, HPTYPE, INVISIBLE, LooLEdg, LooLFace, VerVCoord, and VPTYPE.
Referenced by MSD_lowIsInsideFace().
int MSD_lowIsInvertedEdge (int isleft, vector dir, FPTYPE fp, vector edir)
Definition at line 124 of file dishvisb.cpp.
References cross(), dot(), FacFeq, normalize(), releps, and TRUE.
Referenced by MSD_lowIsEdgeVisible().
void MSD_lowListAllCamera (void)
Definition at line 105 of file camlist_.cpp.
References AllCamera, and MSD_lowNameListCameraName().
Referenced by MSD_execShow().
void MSD_lowListAllCameraName (void)
Definition at line 115 of file camlist_.cpp.
References AllCamera, and cameratp::cname.
Referenced by MSD_execListElement().
int MSD_lowMonitor (CTYPE * cptr, int flag)
Definition at line 89 of file dismonit.cpp.
References camptr, FALSE, MEN_NenhumaCamaraMonitora, monicptr, monisw, NAM_Monitor, NIL, and TRUE.
Referenced by MSD_highMonitor().
int MSD_lowNameListCameraName (CTYPE * cptr)
Definition at line 82 of file camlist_.cpp.
References cameratp::cname, cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, cameratp::ref, cameratp::scale, cameratp::smooth, and TRUE.
Referenced by MSD_execShow(), MSD_highNameListCameraName(), and MSD_lowListAllCamera().
int MSD_lowNameRenameCamera (CTYPE * cptr, char * name2)
Definition at line 88 of file camrenam.cpp.
References cameratp::cname, and SUCCESS.
Referenced by MSD_highNameRenameCamera().
int MSD_lowPositionalVisibility (char , vector , FPTYPE , FPTYPE , vector)
Definition at line 129 of file dishevis.cpp.
References _VISIBLE, abseps, AllFacesShell, AllShellsSolid, AllSolids, camptr, cameratp::cdis, cross(), DONTSHOW, dot(), DPTYPE, EdgEVis, EdgHe1, EdgHe2, cameratp::eye, cameratp::eyedir, FacBox, FacFeq, FacFVisi, FALSE, FPTYPE, HalEdg, HalWLoop, HPTYPE, INVISIBLE, LooLFace, box::max, box::min, cameratp::mode, MSD_lowBoxBoxIntersection(), MSD_lowEdgePlaneIntersection(), MSD_lowIsInsideFace(), releps, SolBox, SolDsp, SPTYPE, TRUE, and veccopy().
Referenced by MSD_lowSetEdgeVisibility().
int MSD_lowRemoveCamera (CTYPE * cptr)
Definition at line 129 of file camremov.cpp.
References camary, camused, cameratp::nxt, and TRUE.
Referenced by MSD_highRemoveCamera().
void MSD_lowSetBreakInterruption (void)
Definition at line 54 of file disbreak.cpp.
References breakchk, breakflg, FALSE, MSD_lowBreakFunction(), and TRUE.
Referenced by main(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowSetBreakResident (void)
Definition at line 82 of file disbreak.cpp.
References breakchk, breakflg, FALSE, and instream.
Referenced by MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowSetCamera (CTYPE * , vector , vector , real , int , int , int , int)
Definition at line 107 of file camcheck.cpp.
References cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, MSD_lowSetCameraTransformation(), cameratp::ref, cameratp::scale, cameratp::smooth, and veccopy().
Referenced by CriaFrame(), MSD_highSetCamera(), MSD_lowAlteraCamera(), and MSD_lowSetCamera3View().
void MSD_lowSetCamera3View (int type, CTYPE * cptr)
Definition at line 153 of file camcheck.cpp.
References camptr, cameratp::cdis, cameratp::dash, dwindbox, cameratp::hid, MSD_lowSetCamera(), cameratp::ref, cameratp::scale, cameratp::smooth, veccopy(), and windbox.
Referenced by MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), and MSD_lowCameraDisplayIntersection().
void MSD_lowSetCameraTransformation (CTYPE * cptr)
Definition at line 120 of file camcheck.cpp.
References abseps, cameratp::cdis, cameratp::drot, cameratp::eye, cameratp::eyedir, matident(), normalize(), cameratp::ref, vecd(), vecd2(), and vecminus().
Referenced by MSD_lowSetCamera().
int MSD_lowSetCurrentCamera (CTYPE * cptr)
Definition at line 113 of file camsetcr.cpp.
References camptr, and TRUE.
Referenced by MSD_highNameRemoveCamera(), MSD_highNameSetCurrentCamera(), and MSD_highSetCurrentCamera().
int MSD_lowSetDefaultColor (int color)
Definition at line 120 of file disccolr.cpp.
References defltcol, FALSE, MaxColors, MEN_CorInvalida, NAM_SetDefaultColor, and TRUE.
Referenced by MSD_execColor().
void MSD_lowSetEdgeVisibility (char , FPTYPE , FPTYPE , vector)
Definition at line 51 of file dishevis.cpp.
References calc_p(), DEDGTYPE::devis, DEDGTYPE::devtx, divedge, divednum, divedptr, FALSE, MSD_lowIntersectionCheck(), MSD_lowPositionalVisibility(), and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
int MSD_lowSetFrameColor (int color)
Definition at line 109 of file disccolr.cpp.
References FALSE, framecol, MaxColors, MEN_CorInvalida, NAM_SetFrameColor, and TRUE.
Referenced by MSD_execColor().
void MSD_lowSortDividedEdge (void)
Definition at line 49 of file dishsore.cpp.
References abseps, deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, and veccopy().
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
void MSD_lowTranslateCurrentCamera (real dEx, real dEy, real dEz)
Definition at line 71 of file camtrncr.cpp.
References camptr, cameratp::dash, cameratp::eye, cameratp::hid, cameratp::mode, MSD_highSetCamera(), cameratp::ref, cameratp::scale, and cameratp::smooth.
int MSD_middleCreateCamera (int cn, real Ex, real Ey, real Ez, real Rx, real Ry, real Rz, real scale, int mode, int hidtype, int dash, int smooth)
Definition at line 131 of file camnew__.cpp.
References MSD_lowCreateCamera(), and NIL.
char** MSD_putCameraNameInList (char ** list)
Definition at line 62 of file cammanip.cpp.
References AllCamera, and cameratp::cname.
Variable Documentation
EXTERN real abseps
Definition at line 137 of file disdispl.h.
Referenced by maninit(), MSD_lowCheckCamera(), MSD_lowCheckClipDisplay(), MSD_lowDisplayMesh(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowEdgePlaneIntersection(), MSD_lowIntersectionFaceEdge(), MSD_lowIntersectionParallelFaces(), MSD_lowIntersectionSeparateMinMax(), MSD_lowIsFaceVisible(), MSD_lowIsInsideLoop(), MSD_lowPositionalVisibility(), MSD_lowSetCameraTransformation(), MSD_lowSortDividedEdge(), and MSD_lowUpdateDEBox().
EXTERN real angsmooth
Definition at line 143 of file disdispl.h.
Referenced by maninit(), and MSD_lowIsEdgeVisible().
EXTERN int breakflg
Definition at line 136 of file disdispl.h.
Referenced by maninit(), MSD_lowBreakFunction(), MSD_lowDetermineVisibility(), MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), MSD_lowDisplayIntersection(), MSD_lowDisplayLocalHidden(), MSD_lowSetBreakInterruption(), and MSD_lowSetBreakResident().
EXTERN CTYPE* camary
Definition at line 140 of file disdispl.h.
Referenced by maninit(), MSD_getMaxCameraId(), MSD_lowCreateCamera(), and MSD_lowRemoveCamera().
EXTERN CTYPE camera3
Definition at line 139 of file disdispl.h.
Referenced by MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), and MSD_lowCameraDisplayIntersection().
EXTERN CTYPE* camptr
Definition at line 141 of file disdispl.h.
Referenced by CriaFrame(), maninit(), MSD_createAnimation(), MSD_getCurrentCameraParameters(), MSD_highAlteraCurrentCamera(), MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_highNameDisplay(), MSD_highNameRemoveCamera(), MSD_highRemoveCamera(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowClip3Dimension(), MSD_lowDisplayAxis(), MSD_lowDisplayIntersection(), MSD_lowDisplayMesh(), MSD_lowDisplayMonitor(), MSD_lowDisplayTransformation(), MSD_lowDisplayTransformationScale(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowEdgeEdgeIntersection(), MSD_lowExecDisplayTransformation(), MSD_lowExecInverseDisplayTransformation(), MSD_lowIntersectionFaceFace(), MSD_lowInverseDisplayTransformation(), MSD_lowMonitor(), MSD_lowPositionalVisibility(), MSD_lowSetCamera3View(), MSD_lowSetCurrentCamera(), and MSD_lowTranslateCurrentCamera().
EXTERN int camused
Definition at line 142 of file disdispl.h.
Referenced by maninit(), MSD_lowCreateCamera(), MSD_lowListNumberOfElements(), and MSD_lowRemoveCamera().
EXTERN BTYPE debox
Definition at line 130 of file disdispl.h.
Referenced by MSD_lowEdgeFaceIntersection(), and MSD_lowUpdateDEBox().
EXTERN vector deevtx
Definition at line 129 of file disdispl.h.
Referenced by MSD_lowDisplayHidden(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionClipDropCoord(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSortDividedEdge(), and MSD_lowUpdateDEBox().
EXTERN int defltcol
Definition at line 147 of file disdispl.h.
Referenced by maninit(), MSD_lowGetSolidColor(), and MSD_lowSetDefaultColor().
EXTERN vector desvtx
Definition at line 128 of file disdispl.h.
Referenced by MSD_lowDisplayHidden(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionClipDropCoord(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSortDividedEdge(), and MSD_lowUpdateDEBox().
EXTERN DEDGTYPE* divedge
Definition at line 125 of file disdispl.h.
Referenced by MSD_lowDisplayDividedEdge(), MSD_lowDisplayHidden(), MSD_lowIntersectionClipDropCoord(), MSD_lowIntersectionFaceFace(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSetEdgeVisibility(), and MSD_lowSortDividedEdge().
EXTERN int divednum
Definition at line 127 of file disdispl.h.
Referenced by MSD_lowAddEdgeDivision(), MSD_lowDisplayDividedEdge(), MSD_lowDisplayHidden(), MSD_lowIntersectionClipDropCoord(), MSD_lowIntersectionFaceFace(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSetEdgeVisibility(), and MSD_lowSortDividedEdge().
EXTERN DEDGTYPE* divedptr
Definition at line 126 of file disdispl.h.
Referenced by MSD_lowAddEdgeDivision(), MSD_lowDisplayDividedEdge(), MSD_lowDisplayHidden(), MSD_lowIntersectionCheck(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionFaceFace(), and MSD_lowSetEdgeVisibility().
EXTERN int Draw
Definition at line 132 of file disdispl.h.
Referenced by CriaFrame(), g_frame(), g_iline(), g_tline(), g_tpoint(), maninit(), and MSD_createAnimation().
EXTERN FILE* dspfrptr
Definition at line 135 of file disdispl.h.
Referenced by h_line(), maninit(), and MSD_lowDisplayReadFile().
EXTERN FILE* dspfwptr
Definition at line 134 of file disdispl.h.
Referenced by CriaFrame(), g_frame(), g_tline(), maninit(), MSD_createAnimation(), MSD_highNameDisplay(), and MSD_lowDisplayWriteFile().
EXTERN int framecol
Definition at line 148 of file disdispl.h.
Referenced by g_frame(), maninit(), and MSD_lowSetFrameColor().
EXTERN int lncolor
Definition at line 149 of file disdispl.h.
Referenced by g_iline(), g_pcolor(), g_tline(), g_tpoint(), h_line(), and maninit().
EXTERN int lntype
Definition at line 150 of file disdispl.h.
Referenced by g_tline(), and maninit().
EXTERN int MAX_COLOR_NUMBER
Definition at line 100 of file disdispl.h.
EXTERN CTYPE* monicptr
Definition at line 145 of file disdispl.h.
Referenced by maninit(), MSD_highDisplayCoordinates(), MSD_lowDisplayAxis(), MSD_lowDisplayMesh(), MSD_lowDisplayMonitor(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), MSD_lowDisplayMonitorSolid(), and MSD_lowMonitor().
EXTERN char monisw
Definition at line 144 of file disdispl.h.
Referenced by maninit(), MSD_lowDisplayMonitor(), and MSD_lowMonitor().
EXTERN int NumCinema
Definition at line 133 of file disdispl.h.
EXTERN real xyratio
Definition at line 138 of file disdispl.h.
Referenced by g_frame(), gdcpos(), maninit(), MSD_lowClearWindow(), and MSD_lowClip3Dimension().