USPDesigner: C:/USPDesig/DIS/disedge_.cpp File Reference
C:/USPDesig/DIS/disedge_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <graphics.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "genfunc_.h"
#include "shpshape.h"
#include "mancommd.h"
Functions
void MSD_highDisplayEdge (Id s, Id e, int color)
void MSD_lowDisplayEdge (EPTYPE eptr, int color)
Function Documentation
void MSD_highDisplayEdge (Id s, Id e, int color)
Definition at line 80 of file disedge_.cpp.
References ENIL, EPTYPE, MEN_NaoEncontrouAresta, MSD_getSolid(), MSD_lowDisplayEdge(), MSD_lowShowFindEdge(), and NAM_DisplayEdge.
void MSD_lowDisplayEdge (EPTYPE eptr, int color)
Definition at line 93 of file disedge_.cpp.
References EdgHe1, EdgHe2, g_pcolor(), HalVtx, MSD_lowDisplayLine(), and VerVCoord.
Referenced by MSD_highDisplayEdge().