USPDesigner: C:/USPDesig/DIS/dishinfc.cpp File Reference
C:/USPDesig/DIS/dishinfc.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
int MSD_lowIsInsideFace (vector pos, FPTYPE xfptr, HPTYPE *ei)
int MSD_lowIsInsideLoop (vector pos, LPTYPE lptr, HPTYPE *ei)
Function Documentation
int MSD_lowIsInsideFace (vector pos, FPTYPE xfptr, HPTYPE * ei)
Definition at line 50 of file dishinfc.cpp.
References _VISIBLE, AllLoopsFace, DONTSHOW, FacFLOut, INVISIBLE, LPTYPE, and MSD_lowIsInsideLoop().
Referenced by MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionFaceEdge(), and MSD_lowPositionalVisibility().
int MSD_lowIsInsideLoop (vector pos, LPTYPE lptr, HPTYPE * ei)
Definition at line 76 of file dishinfc.cpp.
References _VISIBLE, abseps, DONTSHOW, FacFeq, HalNxt, HalVtx, HPTYPE, INVISIBLE, LooLEdg, LooLFace, VerVCoord, and VPTYPE.
Referenced by MSD_lowIsInsideFace().