USPDesigner: C:/USPDesig/DIS/dishsore.cpp File Reference
C:/USPDesig/DIS/dishsore.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
void MSD_lowSortDividedEdge (void)
Function Documentation
void MSD_lowSortDividedEdge (void)
Definition at line 49 of file dishsore.cpp.
References abseps, deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, and veccopy().
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().