USPDesigner: C:/USPDesig/DIS/dishintr.cpp File Reference
C:/USPDesig/DIS/dishintr.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "shpshape.h"
#include "disdispl.h"
Functions
void MSD_lowCameraDisplayIntersection (void)
void MSD_lowDisplayIntersection (void)
void MSD_lowIntersectionFaceFace (SPTYPE o1ptr, FPTYPE f1ptr, SPTYPE o2ptr, FPTYPE f2ptr)
int MSD_lowIntersectionParallelFaces (FPTYPE f1ptr, FPTYPE f2ptr)
void MSD_lowIntersectionFaceEdge (FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowIntersectionSeparateMinMax (void)
void MSD_lowIntersectionClipDropCoord (int idx)
Function Documentation
void MSD_lowCameraDisplayIntersection (void)
Definition at line 51 of file dishintr.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayHidden(), MSD_lowDisplayIntersection(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowDisplayIntersection (void)
Definition at line 84 of file dishintr.cpp.
References AllFacesShell, AllShellsSolid, AllSolids, breakflg, camptr, cameratp::dash, DPTYPE, FacBox, FacFVisi, FALSE, FPTYPE, g_pcolor(), MSD_lowBoxBoxIntersection(), MSD_lowGetIntersectionColor(), MSD_lowIntersectionFaceFace(), SNIL, SolBox, SolDsp, SolNxt, and SPTYPE.
Referenced by MSD_lowCameraDisplayIntersection().
void MSD_lowIntersectionClipDropCoord (int idx)
Definition at line 302 of file dishintr.cpp.
References deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, and veccopy().
Referenced by MSD_lowIntersectionSeparateMinMax().
void MSD_lowIntersectionFaceEdge (FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 218 of file dishintr.cpp.
References abseps, calc_p(), dot(), FacFeq, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, MSD_lowAddEdgeDivision(), MSD_lowIsInsideFace(), veccopy(), and VerVCoord.
Referenced by MSD_lowIntersectionFaceFace().
void MSD_lowIntersectionFaceFace (SPTYPE o1ptr, FPTYPE f1ptr, SPTYPE o2ptr, FPTYPE f2ptr)
Definition at line 169 of file dishintr.cpp.
References camptr, divedge, divednum, divedptr, ENIL, FALSE, MSD_lowDisplayDividedEdge(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionFaceEdge(), MSD_lowIntersectionParallelFaces(), MSD_lowIntersectionSeparateMinMax(), MSD_lowSetEdgeVisibility(), MSD_lowSortDividedEdge(), MSD_lowUpdateDEBox(), NIL, SNIL, TRUE, and workbuf.
Referenced by MSD_lowDisplayIntersection().
int MSD_lowIntersectionParallelFaces (FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 196 of file dishintr.cpp.
References abseps, dot(), FacFeq, FALSE, TRUE, veccopy(), vecminus(), and vecplus().
Referenced by MSD_lowIntersectionFaceFace().
int MSD_lowIntersectionSeparateMinMax (void)
Definition at line 254 of file dishintr.cpp.
References abseps, deevtx, desvtx, DEDGTYPE::devtx, divedge, divednum, FALSE, MSD_lowAddEdgeDivision(), MSD_lowClipDisplayTransformation(), MSD_lowIntersectionClipDropCoord(), and TRUE.
Referenced by MSD_lowIntersectionFaceFace().