USPDesigner: C:/USPDesig/DIS/dishediv.cpp File Reference
C:/USPDesig/DIS/dishediv.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "gphgraph.h"
#include "disdispl.h"
Functions
void MSD_lowEdgeEdgeIntersection (SPTYPE optr, EPTYPE eptr, FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowEdgeEdgeCheck (SPTYPE xoptr, SPTYPE optr, EPTYPE xeptr, EPTYPE eptr, real sbox[][2], FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowEdgeEdgeCheckStep2 (vector a1, vector a2, vector b1, vector b2, real *u, real *v)
int MSD_lowEdgeEdgeCheckStep3 (vector s0, vector s1, vector v0, vector v1, real u, vector p)
void MSD_lowEdgeFaceIntersection (SPTYPE o1ptr, SPTYPE o2ptr, FPTYPE f1ptr, FPTYPE f2ptr)
void MSD_lowAddEdgeDivision (vector pos)
Function Documentation
void MSD_lowAddEdgeDivision (vector pos)
Definition at line 337 of file dishediv.cpp.
References DEDGTYPE::devis, divednum, divedptr, and veccopy().
Referenced by MSD_lowDisplayHidden(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowIntersectionFaceEdge(), and MSD_lowIntersectionSeparateMinMax().
int MSD_lowEdgeEdgeCheck (SPTYPE xoptr, SPTYPE optr, EPTYPE xeptr, EPTYPE eptr, real sbox[][2], FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 126 of file dishediv.cpp.
References EdgEClp, EdgEVClp2, EdgHe1, EdgHe2, EdgSVClp2, FacFVisi, FALSE, FPTYPE, HalVtx, HalWLoop, LooLFace, and TRUE.
Referenced by MSD_lowEdgeEdgeIntersection().
int MSD_lowEdgeEdgeCheckStep2 (vector a1, vector a2, vector b1, vector b2, real * u, real * v)
Definition at line 225 of file dishediv.cpp.
References FALSE, releps, and TRUE.
Referenced by MSD_lowEdgeEdgeIntersection().
int MSD_lowEdgeEdgeCheckStep3 (vector s0, vector s1, vector v0, vector v1, real u, vector p)
Definition at line 253 of file dishediv.cpp.
References calc_p(), camptr, cross(), cameratp::eye, FALSE, cameratp::mode, releps, TRUE, and vecminus().
Referenced by MSD_lowEdgeEdgeIntersection().
void MSD_lowEdgeEdgeIntersection (SPTYPE optr, EPTYPE eptr, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 51 of file dishediv.cpp.
References _VISIBLE, abseps, AllEdgesShell, AllShellsSolid, AllSolids, camptr, deevtx, desvtx, DPTYPE, EdgEVClp2, EdgEVClp3, EdgEVis, EdgSVClp2, EdgSVClp3, EPTYPE, cameratp::eye, MSD_lowAddEdgeDivision(), MSD_lowEdgeEdgeCheck(), MSD_lowEdgeEdgeCheckStep2(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowExecDisplayTransformation(), MSD_lowExecInverseDisplayTransformation(), releps, SolDsp, SPTYPE, TRUE, vec2cp(), veccopy(), and vecd().
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
void MSD_lowEdgeFaceIntersection (SPTYPE o1ptr, SPTYPE o2ptr, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 286 of file dishediv.cpp.
References abseps, AllFacesShell, AllShellsSolid, AllSolids, calc_p(), debox, deevtx, desvtx, DONTSHOW, dot(), DPTYPE, FacBox, FacFeq, FacFVisi, FPTYPE, HPTYPE, MSD_lowAddEdgeDivision(), MSD_lowBoxBoxIntersection(), MSD_lowIsInsideFace(), SolBox, SolDsp, SPTYPE, and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().