USPDesigner: C:/USPDesig/DIS/dishevis.cpp File Reference
C:/USPDesig/DIS/dishevis.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "gphgraph.h"
Functions
void MSD_lowSetEdgeVisibility (char t, FPTYPE f1ptr, FPTYPE f2ptr, vector edir)
int MSD_lowIntersectionCheck (vector mid, FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowIntersectionCheckStep1 (vector mid, FPTYPE f1ptr, FPTYPE f2ptr)
int MSD_lowPositionalVisibility (char tp, vector v, FPTYPE f1, FPTYPE f2, vector edir)
int MSD_lowEdgePlaneIntersection (vector v1, vector v2, FPTYPE xf, real *pos, real *t)
Function Documentation
int MSD_lowEdgePlaneIntersection (vector v1, vector v2, FPTYPE xf, real * pos, real * t)
Definition at line 249 of file dishevis.cpp.
References abseps, calc_p(), dot(), FacFeq, FALSE, and TRUE.
Referenced by MSD_lowPositionalVisibility().
int MSD_lowIntersectionCheck (vector mid, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 77 of file dishevis.cpp.
References DEDGTYPE::devis, divedptr, DONTSHOW, FacFVisi, FALSE, MSD_lowIntersectionCheckStep1(), and TRUE.
Referenced by MSD_lowSetEdgeVisibility().
int MSD_lowIntersectionCheckStep1 (vector mid, FPTYPE f1ptr, FPTYPE f2ptr)
Definition at line 95 of file dishevis.cpp.
References cross(), DEDGTYPE::devis, divedptr, DONTSHOW, dot(), FacFeq, FALSE, HalNxt, HalVtx, HalWLoop, HPTYPE, INVISIBLE, LooLFace, mate, MSD_lowIsInsideFace(), normalize(), releps, TRUE, veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_lowIntersectionCheck().
int MSD_lowPositionalVisibility (char tp, vector v, FPTYPE f1, FPTYPE f2, vector edir)
Definition at line 129 of file dishevis.cpp.
References _VISIBLE, abseps, AllFacesShell, AllShellsSolid, AllSolids, camptr, cameratp::cdis, cross(), DONTSHOW, dot(), DPTYPE, EdgEVis, EdgHe1, EdgHe2, cameratp::eye, cameratp::eyedir, FacBox, FacFeq, FacFVisi, FALSE, FPTYPE, HalEdg, HalWLoop, HPTYPE, INVISIBLE, LooLFace, box::max, box::min, cameratp::mode, MSD_lowBoxBoxIntersection(), MSD_lowEdgePlaneIntersection(), MSD_lowIsInsideFace(), releps, SolBox, SolDsp, SPTYPE, TRUE, and veccopy().
Referenced by MSD_lowSetEdgeVisibility().
void MSD_lowSetEdgeVisibility (char t, FPTYPE f1ptr, FPTYPE f2ptr, vector edir)
Definition at line 51 of file dishevis.cpp.
References calc_p(), DEDGTYPE::devis, DEDGTYPE::devtx, divedge, divednum, divedptr, FALSE, MSD_lowIntersectionCheck(), MSD_lowPositionalVisibility(), and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().