USPDesigner: C:/USPDesig/DIS/dishidde.cpp File Reference
C:/USPDesig/DIS/dishidde.cpp File Reference
#include <stdio.h>
#include <graphics.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "shpshape.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "gphgraph.h"
Functions
void MSD_lowCameraDisplayHidden (void)
void MSD_lowDisplayHidden (CTYPE *cptr)
Function Documentation
void MSD_lowCameraDisplayHidden (void)
Definition at line 59 of file dishidde.cpp.
References camera3, camptr, cameratp::mode, MSD_lowDisplayHidden(), and MSD_lowSetCamera3View().
Referenced by CriaFrame(), MSD_createAnimation(), MSD_highNameDisplay(), MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
void MSD_lowDisplayHidden (CTYPE * cptr)
Definition at line 87 of file dishidde.cpp.
References _VISIBLE, AllEdgesShell, AllShellsSolid, AllSolids, breakflg, cameratp::dash, deevtx, desvtx, divedge, divednum, divedptr, DPTYPE, EdgEClp, EdgEVClp2, EdgEVClp3, EdgEVis, EdgHe1, EdgHe2, EdgSVClp2, EdgSVClp3, EPTYPE, FPTYPE, g_frame(), g_pcolor(), g_tline(), HalVtx, HalWLoop, INVISIBLE, LooLFace, MSD_lowAddEdgeDivision(), MSD_lowDetermineVisibility(), MSD_lowDisplayDividedEdge(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowGetSolidColor(), MSD_lowSetEdgeVisibility(), MSD_lowSortDividedEdge(), MSD_lowUpdateDEBox(), normalize(), SNIL, SolDsp, SPTYPE, TRUE, veccopy(), vecminus(), VerVCoord, and workbuf.
Referenced by MSD_lowCameraDisplayHidden(), and MSD_lowCameraDisplayIntersection().