USPDesigner: C:/USPDesig/DIS/dishvisb.cpp File Reference
C:/USPDesig/DIS/dishvisb.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "gphgraph.h"
Functions
int MSD_lowIsEdgeVisible (CTYPE *cptr, EPTYPE eptr)
int MSD_lowIsFaceVisible (CTYPE *cptr, FPTYPE fptr)
int MSD_lowIsInvertedEdge (int isleft, vector dir, FPTYPE fp, vector edir)
Function Documentation
int MSD_lowIsEdgeVisible (CTYPE * cptr, EPTYPE eptr)
Definition at line 51 of file dishvisb.cpp.
References _VISIBLE, angsmooth, DONTSHOW, EdgAngle, EdgHe1, EdgHe2, cameratp::eye, FacFVisi, FALSE, FPTYPE, HalVtx, HalWLoop, INVISIBLE, LooLFace, cameratp::mode, MSD_lowIsInvertedEdge(), normalize(), cameratp::ref, cameratp::smooth, TRUE, veccopy(), vecminus(), VerVCoord, and VPTYPE.
Referenced by MSD_lowDetermineVisibility(), and MSD_lowDisplayLocalHidden().
int MSD_lowIsFaceVisible (CTYPE * cptr, FPTYPE fptr)
Definition at line 106 of file dishvisb.cpp.
References _VISIBLE, abseps, DONTSHOW, dot(), cameratp::drot, cameratp::eye, FacFeq, INVISIBLE, cameratp::mode, and veccopy().
Referenced by MSD_lowDetermineVisibility(), and MSD_lowDisplayLocalHidden().
int MSD_lowIsInvertedEdge (int isleft, vector dir, FPTYPE fp, vector edir)
Definition at line 124 of file dishvisb.cpp.
References cross(), dot(), FacFeq, normalize(), releps, and TRUE.
Referenced by MSD_lowIsEdgeVisible().