USPDesigner: C:/USPDesig/DIS/disledge.cpp File Reference
C:/USPDesig/DIS/disledge.cpp File Reference
#include <stdio.h>
#include <graphics.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "disdispl.h"
#include "gphgraph.h"
Functions
void MSD_lowDisplayDividedEdge (CTYPE *cptr, EPTYPE eptr)
Function Documentation
void MSD_lowDisplayDividedEdge (CTYPE * cptr, EPTYPE eptr)
Definition at line 56 of file disledge.cpp.
References cameratp::dash, DEDGTYPE::devis, DEDGTYPE::devtx, divedge, divednum, divedptr, EdgEVis, ENIL, FALSE, g_tline(), INVISIBLE, MSD_lowExecDisplayTransformation(), and TRUE.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().