USPDesigner: C:/USPDesig/DIS/disltrns.cpp File Reference
C:/USPDesig/DIS/disltrns.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
void MSD_lowDisplayTransformation (vector wpos, vector cpos)
void MSD_lowInverseDisplayTransformation (vector cpos, vector wpos)
void MSD_lowApplyDisplayTransformation (matrix mat, vector v, vector res)
void MSD_lowExecInverseDisplayTransformation (vect2 s1, vector s2, vect2 v1, vector v2)
char MSD_lowExecDisplayTransformation (vector v1, vector v2, vect2 s1, vect2 s2)
void MSD_lowDisplayTransformationScale (vector v1, vector v2, vector s1, vector s2)
char MSD_lowClipDisplayTransformation (vector vs, vector ve, vector dvs, vector dve)
Function Documentation
void MSD_lowApplyDisplayTransformation (matrix mat, vector v, vector res)
Definition at line 67 of file disltrns.cpp.
Referenced by MSD_lowDisplayTransformation().
char MSD_lowClipDisplayTransformation (vector vs, vector ve, vector dvs, vector dve)
Definition at line 155 of file disltrns.cpp.
References FALSE, MSD_lowClip3Dimension(), MSD_lowDisplayTransformation(), MSD_lowInverseDisplayTransformation(), TRUE, and veccopy().
Referenced by MSD_lowEdgeClip(), and MSD_lowIntersectionSeparateMinMax().
void MSD_lowDisplayTransformation (vector wpos, vector cpos)
Definition at line 49 of file disltrns.cpp.
References camptr, cameratp::drot, cameratp::eye, MSD_lowApplyDisplayTransformation(), and vecminus().
Referenced by MSD_lowClipDisplayTransformation(), MSD_lowDisplayTransformationScale(), and MSD_lowExecDisplayTransformation().
void MSD_lowDisplayTransformationScale (vector v1, vector v2, vector s1, vector s2)
Definition at line 133 of file disltrns.cpp.
References camptr, cameratp::cdis, cameratp::mode, MSD_lowDisplayTransformation(), and cameratp::scale.
char MSD_lowExecDisplayTransformation (vector v1, vector v2, vect2 s1, vect2 s2)
Definition at line 105 of file disltrns.cpp.
References camptr, cameratp::cdis, FALSE, cameratp::mode, MSD_lowClip3Dimension(), MSD_lowDisplayTransformation(), cameratp::scale, and TRUE.
Referenced by MSD_lowDisplayDividedEdge(), MSD_lowDisplayLine(), MSD_lowDisplayLineCoordinates(), MSD_lowDisplayVertex(), MSD_lowEdgeClip(), and MSD_lowEdgeEdgeIntersection().
void MSD_lowExecInverseDisplayTransformation (vect2 s1, vector s2, vect2 v1, vector v2)
Definition at line 78 of file disltrns.cpp.
References camptr, cameratp::cdis, cameratp::mode, MSD_lowInverseDisplayTransformation(), and cameratp::scale.
Referenced by MSD_lowEdgeEdgeIntersection().
void MSD_lowInverseDisplayTransformation (vector cpos, vector wpos)
Definition at line 57 of file disltrns.cpp.
References camptr, cameratp::drot, cameratp::eye, vecmult(), and vecplus().
Referenced by MSD_lowClipDisplayTransformation(), and MSD_lowExecInverseDisplayTransformation().