USPDesigner: C:/USPDesig/DIS/dismonit.cpp File Reference
C:/USPDesig/DIS/dismonit.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "disdispl.h"
#include "mancommd.h"
#include "vectorop.h"
Functions
void MSD_execMonitor (void)
int MSD_highMonitor (char *name)
int MSD_lowMonitor (CTYPE *cptr, int flag)
void MSD_lowDisplayMonitor (int t, SPTYPE optr, GPTYPE gptr)
void MSD_lowDisplayMonitorSolid (SPTYPE op)
void MSD_lowDisplayMonitorGroup (GPTYPE gptr)
void MSD_lowDisplayMonitorAxis (void)
Function Documentation
void MSD_execMonitor (void)
Definition at line 53 of file dismonit.cpp.
References lineins(), MSD_highMonitor(), NAM_Monitor, and restbuf.
int MSD_highMonitor (char * name)
Definition at line 68 of file dismonit.cpp.
References FALSE, MEN_ParametrosIncorretos, MSD_lowFindCameraByName(), MSD_lowMonitor(), NAM_Monitor, NIL, and strlower().
Referenced by MSD_execMonitor().
void MSD_lowDisplayMonitor (int t, SPTYPE optr, GPTYPE gptr)
Definition at line 121 of file dismonit.cpp.
References camptr, monicptr, monisw, MSD_lowDisplayMonitorAxis(), MSD_lowDisplayMonitorGroup(), and MSD_lowDisplayMonitorSolid().
Referenced by MSD_highDifference(), MSD_highIntersection(), MSD_highMakeCone(), MSD_highMakeCube(), MSD_highMakeCylinder(), MSD_highMakePrism(), MSD_highMakePyramid(), MSD_highMakeRevolve(), MSD_highMakeSphere(), MSD_highMakeSWEEP(), MSD_highMakeTorus(), MSD_highSplit(), and MSD_highUnion().
void MSD_lowDisplayMonitorAxis (void)
Definition at line 217 of file dismonit.cpp.
References cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowSetBreakInterruption(), and MSD_lowSetBreakResident().
Referenced by MSD_lowDisplayMonitor().
void MSD_lowDisplayMonitorGroup (GPTYPE gptr)
Definition at line 180 of file dismonit.cpp.
References AllSolids, cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowIsAncestorGroup(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), SolDsp, SolGroup, and SPTYPE.
Referenced by MSD_lowDisplayMonitor().
void MSD_lowDisplayMonitorSolid (SPTYPE op)
Definition at line 143 of file dismonit.cpp.
References AllSolids, cameratp::hid, monicptr, MSD_highDisplayAllEdges(), MSD_highDisplayLocalHidden(), MSD_lowCameraDisplayHidden(), MSD_lowCameraDisplayIntersection(), MSD_lowSetBreakInterruption(), MSD_lowSetBreakResident(), SolDsp, and SPTYPE.
Referenced by MSD_lowDisplayMonitor().
int MSD_lowMonitor (CTYPE * cptr, int flag)
Definition at line 89 of file dismonit.cpp.
References camptr, FALSE, MEN_NenhumaCamaraMonitora, monicptr, monisw, NAM_Monitor, NIL, and TRUE.
Referenced by MSD_highMonitor().