USPDesigner: C:/USPDesig/EUL/eulcolor.cpp File Reference
C:/USPDesig/EUL/eulcolor.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "genfunc_.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highNameColor (char *name, int color)
int MSD_highNameSolidColor (char *name, int col)
int MSD_highNameGroupColor (char *name, int col)
int MSD_highColor (Id sn, int color, int cod)
void MSD_lowSolidColor (SPTYPE s, int color)
void MSD_lowGroupColor (GPTYPE g, int color)
int MSD_execStructColor (EulerOp *op)
void MSD_printStructColor (FILE *f, EulerOp *op)
int MSD_readStructColor (FILE *f, EulerOp *op)
int MSD_modifyStructColor (EulerOp *op)
Variables
int MaxColors
Function Documentation
int MSD_execStructColor (EulerOp * op)
Definition at line 171 of file eulcolor.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highColor(), SOLID, and eulerop::solidno.
int MSD_highColor (Id sn, int color, int cod)
Definition at line 117 of file eulcolor.cpp.
References ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getGroup(), MSD_getSolid(), MSD_lowGroupColor(), MSD_lowSolidColor(), NAM_Color, SNIL, SOLID, SPTYPE, and SUCCESS.
Referenced by MSD_execStructColor().
int MSD_highNameColor (char * name, int color)
Definition at line 57 of file eulcolor.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_getTypeByName(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), and NAM_Color.
int MSD_highNameGroupColor (char * name, int col)
Definition at line 99 of file eulcolor.cpp.
References FALSE, GNIL, GPTYPE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_lowFindGroupByName(), MSD_lowGroupColor(), NAM_Color, NAM_SetElementColor, and TRUE.
Referenced by MSD_execColor(), and MSD_highNameColor().
int MSD_highNameSolidColor (char * name, int col)
Definition at line 80 of file eulcolor.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_lowFindSolidByName(), MSD_lowSolidColor(), NAM_Color, NAM_SetElementColor, SNIL, SPTYPE, and TRUE.
Referenced by MSD_execColor(), and MSD_highNameColor().
void MSD_lowGroupColor (GPTYPE g, int color)
Definition at line 157 of file eulcolor.cpp.
References COLOR, Gdoinversion, GROUP, GrpGColor, GrpGroupNo, MSD_lowAddEulerOp(), and SNIL.
Referenced by MSD_highColor(), MSD_highNameGroupColor(), and MSD_lowRemoveOneGroup().
void MSD_lowSolidColor (SPTYPE s, int color)
Definition at line 143 of file eulcolor.cpp.
References COLOR, Gdoinversion, MSD_lowAddEulerOp(), SolColor, SOLID, and SolSolidNo.
Referenced by MSD_highColor(), MSD_highNameSolidColor(), and MSD_lowSoftRemove().
int MSD_modifyStructColor (EulerOp * op)
Definition at line 208 of file eulcolor.cpp.
References GROUP, eulerop::ip1, eulerop::ip3, MSD_lowCheckTranslatorTable(), SOLID, and SUCCESS.
void MSD_printStructColor (FILE * f, EulerOp * op)
Definition at line 181 of file eulcolor.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::ip3.
int MSD_readStructColor (FILE * f, EulerOp * op)
Definition at line 193 of file eulcolor.cpp.
References eulerop::CommandCount, ERROR, eulerop::ip1, eulerop::ip2, eulerop::ip3, and SUCCESS.
Variable Documentation
int MaxColors
Definition at line 81 of file gphlintf.cpp.