USPDesigner: C:/USPDesig/EUL/eulerops.cpp File Reference
C:/USPDesig/EUL/eulerops.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "curvgeom.h"
#include "eulerops.h"
#include "mancommd.h"
Classes
struct eulercod
Typedefs
typedef struct eulercod EuCode
Functions
void MSD_lowAddEulerOp (SPTYPE s, OpCode code, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, Id ip7, Id ip8, real fp1, real fp2, real fp3, real fp4)
void MSD_lowAddEulerOpRedo (SPTYPE s, OpCode code, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, Id ip7, Id ip8, real fp1, real fp2, real fp3, real fp4)
void MSD_lowAddMatrix (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
void MSD_lowAddMatrixRedo (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
Variables
EuCode ematrix []
Typedef Documentation
typedef struct eulercod EuCode
Definition at line 54 of file eulerops.cpp.
Function Documentation
void MSD_lowAddEulerOp (SPTYPE s, OpCode code, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, Id ip7, Id ip8, real fp1, real fp2, real fp3, real fp4)
Definition at line 433 of file eulerops.cpp.
References CommandCount, EulerCommandCount, EulerCount, EulerFp1, EulerFp2, EulerFp3, EulerFp4, EulerIp1, EulerIp2, EulerIp3, EulerIp4, EulerIp5, EulerIp6, EulerIp7, EulerIp8, EulerOpCode, EulerSolidNo, MEN_NaoPossuiMemoria, NAM_AddEulerOperator, NIL, OpCount, OpHead, eulerop::opnext, SNIL, and SolSolidNo.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowAddMatrix(), MSD_lowAllRingMove(), MSD_lowAssociaGroupAxis(), MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowAssociaSolidAxis(), MSD_lowAxisName(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCreateGroup(), MSD_lowGroupColor(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowLoadSolid(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMoveAxis(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowRotateAxis(), MSD_lowScale(), MSD_lowSetGroupCurrent(), MSD_lowShellDetach(), MSD_lowSolidColor(), MSD_lowSolidName(), MSD_lowTransformation(), and MSD_lowTranslate().
void MSD_lowAddEulerOpRedo (SPTYPE s, OpCode code, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, Id ip7, Id ip8, real fp1, real fp2, real fp3, real fp4)
Definition at line 473 of file eulerops.cpp.
References CommandCount, EulerCommandCountRedo, EulerCountRedo, EulerFp1Redo, EulerFp2Redo, EulerFp3Redo, EulerFp4Redo, EulerIp1Redo, EulerIp2Redo, EulerIp3Redo, EulerIp4Redo, EulerIp5Redo, EulerIp6Redo, EulerIp7Redo, EulerIp8Redo, EulerOpCodeRedo, EulerSolidNoRedo, MEN_NaoPossuiMemoria, NAM_AddEulerOperator, NIL, OpCountRedo, OpHeadRedo, eulerop::opnext, SNIL, and SolSolidNo.
Referenced by MSD_lowAddMatrixRedo(), MSD_lowAxisName(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowScale(), MSD_lowShellDetach(), MSD_lowSolidName(), MSD_lowTransformation(), and MSD_lowTranslate().
void MSD_lowAddMatrix (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
Definition at line 513 of file eulerops.cpp.
References MSD_lowAddEulerOp().
Referenced by MSD_lowTransformation().
void MSD_lowAddMatrixRedo (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
Definition at line 527 of file eulerops.cpp.
References MSD_lowAddEulerOpRedo().
Referenced by MSD_lowTransformation().
Variable Documentation
EuCode ematrix[]
Definition at line 67 of file eulerops.cpp.