USPDesigner: C:/USPDesig/INC/eulerops.h File Reference
C:/USPDesig/INC/eulerops.h File Reference
#include <stdio.h>
Classes
struct eulerop
Defines
#define EXTERN extern
Typedefs
typedef double real
typedef int Id
typedef real matrix [4][4]
typedef struct eulerop EulerOp
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
typedef enum opcode OpCode
Enumerations
enum opcode {
MVSF, KVSF, MEV, KEV,
MEF, KEF, KEMR, MEKR,
KFMRH, MFKRH, MSFKR, KSFMR,
HARDREM, RMOVE, NEWLOC, REVERT,
MODIFYNAMES, MERGE, DETACH, TRANS,
ROTAT, SCALE, TRANSFORM, ASSOCIATE,
CRTAXSTRS, CRTAXSROT, CRTGRP, REMAXS,
REMGRP, MOVAXIS, ROTAXIS, SETGRP,
COLOR, NAME, MAXCODE
}
Functions
int MSD_highNameColor (char *name, int color)
int MSD_highNameSolidColor (char *name, int col)
int MSD_highNameGroupColor (char *name, int col)
int MSD_highColor (Id sn, int color, int cod)
void MSD_lowSolidColor (SPTYPE s, int color)
void MSD_lowGroupColor (GPTYPE g, int color)
int MSD_execStructColor (EulerOp *op)
void MSD_printStructColor (FILE *f, EulerOp *op)
int MSD_readStructColor (FILE *f, EulerOp *op)
int MSD_modifyStructColor (EulerOp *op)
void MSD_execNome (void)
int MSD_highName (Id sn, char *nome, int cod)
void MSD_lowSolidName (SPTYPE s, char *nome)
void MSD_lowGroupName (GPTYPE g, char *nome)
void MSD_lowAxisName (APTYPE a, char *nome)
int MSD_execStructName (EulerOp *op)
void MSD_printStructName (FILE *f, EulerOp *op)
int MSD_readStructName (FILE *f, EulerOp *op)
int MSD_modifyStructName (EulerOp *op)
void MSD_execSetDoInverse (void)
void MSD_lowSetDoInverse (void)
void MSD_lowAddEulerOp (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, Id i, Id j, real k, real l, real m, real n)
void MSD_lowAddEulerOpRedo (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, Id i, Id j, real k, real l, real m, real n)
void MSD_lowAddMatrix (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, matrix i)
void MSD_lowAddMatrixRedo (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
void MSD_execKEF (void)
int MSD_highKEF (Id sn, Id v1, Id v2, Id fn)
void MSD_execKEF2 (void)
int MSD_highKEF2 (Id sn, Id v1, Id v2, Id f1, Id f2)
void MSD_lowKEF (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEF (EulerOp *op)
void MSD_printStructKEF (FILE *f, EulerOp *op)
int MSD_readStructKEF (FILE *f, EulerOp *op)
int MSD_modifyStructKEF (EulerOp *op)
void MSD_execKEMR (void)
int MSD_highKEMR (Id sn, Id fn, Id v1, Id v2)
void MSD_lowKEMR (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEMR (EulerOp *op)
void MSD_printStructKEMR (FILE *f, EulerOp *op)
int MSD_readStructKEMR (FILE *f, EulerOp *op)
int MSD_modifyStructKEMR (EulerOp *op)
void MSD_execKEV (void)
int MSD_highKEV (Id sn, Id fn, Id v1, Id v2)
void MSD_execJVKE (void)
int MSD_highJVKE (Id sn, Id v1, Id v2, Id f)
void MSD_execJEKV (void)
int MSD_highJEKV (Id sn, Id v1, Id v2)
void MSD_execKEV2 (void)
int MSD_highKEV2 (Id sn, Id v1, Id v2, Id f1, Id f2)
void MSD_lowKEV (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEV (EulerOp *op)
void MSD_printStructKEV (FILE *f, EulerOp *op)
int MSD_readStructKEV (FILE *f, EulerOp *op)
int MSD_modifyStructKEV (EulerOp *op)
void MSD_execKFMRH (void)
int MSD_highKFMRH (Id sn, Id fn1, Id fn2)
void MSD_lowKFMRH (FPTYPE f1, FPTYPE f2)
int MSD_execStructKFMRH (EulerOp *op)
void MSD_printStructKFMRH (FILE *f, EulerOp *op)
int MSD_readStructKFMRH (FILE *f, EulerOp *op)
int MSD_modifyStructKFMRH (EulerOp *op)
void MSD_execKSFMR (void)
int MSD_highKSFMR (Id sn, Id fn1, Id fn2)
void MSD_lowKSFMR (FPTYPE f1, FPTYPE f2)
int MSD_execStructKSFMR (EulerOp *op)
void MSD_printStructKSFMR (FILE *f, EulerOp *op)
int MSD_readStructKSFMR (FILE *f, EulerOp *op)
int MSD_modifyStructKSFMR (EulerOp *op)
void MSD_execKVSF (void)
int MSD_highKVSF (Id sn, Id fn)
void MSD_lowKVSF (SPTYPE s)
int MSD_execStructKVSF (EulerOp *op)
void MSD_printStructKVSF (FILE *f, EulerOp *op)
int MSD_readStructKVSF (FILE *f, EulerOp *op)
int MSD_modifyStructKVSF (EulerOp *op)
void MSD_execMEF (void)
int MSD_highMEF (Id sn, Id v1, Id v2, Id f1, Id f2)
void MSD_execMEF2 (void)
int MSD_highMEF2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4)
FPTYPE MSD_lowMEF (HPTYPE he1, HPTYPE he2, Id fn)
int MSD_execStructMEF (EulerOp *op)
void MSD_printStructMEF (FILE *f, EulerOp *op)
int MSD_readStructMEF (FILE *f, EulerOp *op)
int MSD_modifyStructMEF (EulerOp *op)
void MSD_execMEKR (void)
int MSD_highMEKR (Id sn, Id fn, Id v1, Id v2)
void MSD_execMEKR2 (void)
int MSD_highMEKR2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3)
void MSD_lowMEKR (HPTYPE he1, HPTYPE he2)
int MSD_execStructMEKR (EulerOp *op)
void MSD_printStructMEKR (FILE *f, EulerOp *op)
int MSD_readStructMEKR (FILE *f, EulerOp *op)
int MSD_modifyStructMEKR (EulerOp *op)
void MSD_execMEV (void)
int MSD_highMEV (Id sn, Id fn, Id v1, Id v2, real x, real y, real z)
void MSD_execSEMV (void)
int MSD_highSEMV (Id sn, Id v1, Id v2, Id v3, real x, real y, real z)
void MSD_execSVME (void)
int MSD_highSVME (Id sn, Id v1, Id v2, Id f1, Id f2, real x, real y, real z)
void MSD_execSVME2 (void)
int MSD_highSVME2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, real x, real y, real z)
void MSD_execSVME3 (void)
int MSD_highSVME3 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4, real x, real y, real z)
void MSD_lowMEV (HPTYPE he1, HPTYPE he2, Id vn, real x, real y, real z)
int MSD_execStructMEV (EulerOp *op)
void MSD_printStructMEV (FILE *f, EulerOp *op)
int MSD_readStructMEV (FILE *f, EulerOp *op)
int MSD_modifyStructMEV (EulerOp *op)
void MSD_execMFKRH (void)
int MSD_highMFKRH (Id sn, Id f1, Id f2)
void MSD_execMFKRH2 (void)
int MSD_highMFKRH2 (Id sn, Id f1, Id f2, Id v1, Id v2)
FPTYPE MSD_lowMFKRH (FPTYPE f, LPTYPE l, Id fn)
int MSD_execStructMFKRH (EulerOp *op)
void MSD_printStructMFKRH (FILE *f, EulerOp *op)
int MSD_readStructMFKRH (FILE *f, EulerOp *op)
int MSD_modifyStructMFKRH (EulerOp *op)
SPTYPE MSD_lowModifyEulerOp (EulerOp *op)
int MSD_modifyStructError (EulerOp *op)
void MSD_lowIniciaTranslatorTable (void)
int MSD_lowCheckTranslatorTable (int elemno, int code)
void MSD_lowSetTranslatorTable (int elemnoold, int elemno, int code)
void MSD_execMSFKR (void)
int MSD_highMSFKR (Id sn, Id ff, Id fn, Id dn)
void MSD_execMSFKR2 (void)
int MSD_highMSFKR2 (Id sn, Id ff, Id fn, Id dn, Id v1, Id v2)
FPTYPE MSD_lowMSFKR (LPTYPE l, Id fn, Id dn)
int MSD_execStructMSFKR (EulerOp *op)
void MSD_printStructMSFKR (FILE *f, EulerOp *op)
int MSD_readStructMSFKR (FILE *f, EulerOp *op)
int MSD_modifyStructMSFKR (EulerOp *op)
void markface (FPTYPE f, DPTYPE d)
void redo (DPTYPE shell, DPTYPE oldshell)
int sfindv (DPTYPE d, VPTYPE v)
int sfinde (DPTYPE d, EPTYPE e)
void MSD_execMVSF (void)
SPTYPE MSD_highMVSF (Id fn, Id vn, Id dn, real xx, real yy, real zz)
SPTYPE MSD_lowMVSF (Id sn, Id fn, Id vn, Id dn, real xx, real yy, real zz)
int MSD_execStructMVSF (EulerOp *op)
void MSD_printStructMVSF (FILE *f, EulerOp *op)
int MSD_readStructMVSF (FILE *f, EulerOp *op)
int MSD_modifyStructMVSF (EulerOp *op)
void MSD_highPrintAllOps (void)
void MSD_highPrintAllRedoOps (void)
void MSD_lowPrintEulerOp (FILE *f, EulerOp *op)
void MSD_printStructError (FILE *f, EulerOp *op)
int MSD_lowScanEulerOperator (FILE *f, EulerOp *op)
int MSD_readStructError (FILE *f, EulerOp *op)
void MSD_setEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
void MSD_addEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
void MSD_execUndoOp (void)
void MSD_highUndoOp (void)
SPTYPE MSD_lowUndoOp (void)
SPTYPE MSD_lowApplyEulerOp (EulerOp *op, int *cont)
int MSD_execStructError (EulerOp *op)
void MSD_lowFreeUndoLog (PEulerOp EndOp)
void MSD_lowGetMatrix (EulerOp *op, matrix m)
void MSD_execCleanSolid (void)
void MSD_execNameCleanSolid (void)
int MSD_highNameCleanSolid (char *)
int MSD_highCleanSolid (Id sn)
void MSD_lowCleanSolid (SPTYPE s)
void MSD_execDetach (void)
int MSD_highDetach (Id sn, Id sn1, Id dn, Id newd, int addf, int addv)
SPTYPE MSD_lowDetach (SPTYPE s, Id sn, DPTYPE d, Id newd, int addf, int addv)
void MSD_lowShellDetach (SPTYPE s, SPTYPE s1, DPTYPE d, Id newd, int addf, int addv)
int MSD_execStructDetach (EulerOp *op)
void MSD_printStructDetach (FILE *f, EulerOp *op)
int MSD_readStructDetach (FILE *f, EulerOp *op)
int MSD_modifyStructDetach (EulerOp *op)
void MSD_execGlue (void)
int MSD_highGlue (Id sn1, Id sn2)
void MSD_lowGlue (SPTYPE s1, SPTYPE s2)
void MSD_lowFaceGlue (SPTYPE s1, SPTYPE s2, FPTYPE f1, FPTYPE f2)
int MSD_lowLoopGlue (FPTYPE f)
void MSD_execNameMerge (void)
void MSD_execMerge (void)
int MSD_highNameMerge (char *, char *)
int MSD_highMerge (Id sn1, Id sn2)
void MSD_lowMerge (SPTYPE s1, SPTYPE s2)
void MSD_execModifyIds (void)
int MSD_highModifyIds (Id sn, Id snew)
void MSD_lowModifyIds (SPTYPE s, Id snew)
int MSD_execStructModifyIds (EulerOp *op)
void MSD_printStructModifyIds (FILE *f, EulerOp *op)
int MSD_readStructModifyIds (FILE *f, EulerOp *op)
int MSD_modifyStructModifyIds (EulerOp *op)
void MSD_execNewVertexLocation (void)
int MSD_highNewVertexLocation (Id sn, Id vn, real x, real y, real z)
void MSD_lowNewVertexLocation (SPTYPE s, VPTYPE v, real x, real y, real z)
int MSD_execStructNewVertexLocation (EulerOp *op)
void MSD_printStructNewVertexLocation (FILE *f, EulerOp *op)
int MSD_readStructNewVertexLocation (FILE *f, EulerOp *op)
int MSD_modifyStructNewVertexLocation (EulerOp *op)
void MSD_execRevert (void)
int MSD_highRevert (Id sn, Id dn)
int MSD_lowRevert (DPTYPE d)
int MSD_execStructRevert (EulerOp *op)
void MSD_printStructRevert (FILE *f, EulerOp *op)
int MSD_readStructRevert (FILE *f, EulerOp *op)
int MSD_modifyStructRevert (EulerOp *op)
void MSD_execRingMove (void)
int MSD_highRingMove (Id sn, Id v1, Id v2, Id f1, Id f2, int out)
int MSD_lowRingMove (FPTYPE f1, FPTYPE f2, LPTYPE l, int out)
int MSD_execStructRingMove (EulerOp *op)
void MSD_printStructRingMove (FILE *f, EulerOp *op)
int MSD_readStructRingMove (FILE *f, EulerOp *op)
int MSD_modifyStructRingMove (EulerOp *op)
void MSD_execAllRingMove (void)
int MSD_highAllRingMove (Id sn, Id f1, Id f2)
int MSD_lowAllRingMove (FPTYPE f1, FPTYPE f2)
void MSD_execHardRemove (void)
int MSD_highHardRemove (Id sn)
int MSD_lowHardRemove (SPTYPE s)
int MSD_execStructHardRemove (EulerOp *op)
void MSD_printStructHardRemove (FILE *f, EulerOp *op)
int MSD_readStructHardRemove (FILE *f, EulerOp *op)
int MSD_modifyStructHardRemove (EulerOp *op)
void MSD_execNameSoftRemove (void)
int MSD_highNameSoftRemove (char *name)
void MSD_execSoftRemove (void)
int MSD_highSoftRemove (Id sn)
int MSD_lowSoftRemove (SPTYPE s)
void MSD_lowShellRemove (SPTYPE s)
void MSD_lowEdgeRemove (SPTYPE s)
void MSD_lowFaceRemove (SPTYPE s)
Variables
EXTERN EulerOp * OpHead
EXTERN EulerOp * OpHeadRedo
EXTERN int OpCount
EXTERN int OpCountRedo
EXTERN int Gdoinversion
EXTERN int Gdodirect
EXTERN int CommandCount
Define Documentation
#define EXTERN extern
Definition at line 49 of file eulerops.h.
Typedef Documentation
typedef struct edge ETYPE
Definition at line 85 of file eulerops.h.
typedef struct eulerop EulerOp
Definition at line 69 of file eulerops.h.
typedef struct face FTYPE
Definition at line 77 of file eulerops.h.
typedef struct halfedge HTYPE
Definition at line 89 of file eulerops.h.
typedef int Id
Definition at line 61 of file eulerops.h.
typedef struct loop LTYPE
Definition at line 81 of file eulerops.h.
typedef real matrix[4][4]
Definition at line 65 of file eulerops.h.
typedef enum opcode OpCode
Definition at line 96 of file eulerops.h.
typedef double real
Definition at line 57 of file eulerops.h.
typedef struct solid STYPE
Definition at line 73 of file eulerops.h.
typedef struct vertex VTYPE
Definition at line 93 of file eulerops.h.
Enumeration Type Documentation
enum opcode
Enumerator:
MVSF
KVSF
MEV
KEV
MEF
KEF
KEMR
MEKR
KFMRH
MFKRH
MSFKR
KSFMR
HARDREM
RMOVE
NEWLOC
REVERT
MODIFYNAMES
MERGE
DETACH
TRANS
ROTAT
SCALE
TRANSFORM
ASSOCIATE
CRTAXSTRS
CRTAXSROT
CRTGRP
REMAXS
REMGRP
MOVAXIS
ROTAXIS
SETGRP
COLOR
NAME
MAXCODE
Definition at line 112 of file eulerops.h.
Function Documentation
void markface (FPTYPE f, DPTYPE d)
Definition at line 280 of file eulmsfkr.cpp.
References AllLoopsFace, FacFShell, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, markface(), and mate.
Referenced by markface(), and MSD_lowMSFKR().
void MSD_addEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
Definition at line 65 of file eulscoef.cpp.
References eulerco::edgen, solid::eucoef, eulerco::facen, eulerco::holen, eulerco::ringn, eulerco::shelln, and eulerco::vertexn.
Referenced by MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), and MSD_lowShellDetach().
void MSD_execAllRingMove (void)
void MSD_execCleanSolid (void)
void MSD_execDetach (void)
void MSD_execGlue (void)
void MSD_execHardRemove (void)
void MSD_execJEKV (void)
void MSD_execJVKE (void)
void MSD_execKEF (void)
void MSD_execKEF2 (void)
void MSD_execKEMR (void)
void MSD_execKEV (void)
void MSD_execKEV2 (void)
void MSD_execKFMRH (void)
void MSD_execKSFMR (void)
void MSD_execKVSF (void)
void MSD_execMEF (void)
void MSD_execMEF2 (void)
void MSD_execMEKR (void)
void MSD_execMEKR2 (void)
void MSD_execMerge (void)
void MSD_execMEV (void)
void MSD_execMFKRH (void)
void MSD_execMFKRH2 (void)
void MSD_execModifyIds (void)
void MSD_execMSFKR (void)
void MSD_execMSFKR2 (void)
void MSD_execMVSF (void)
void MSD_execNameCleanSolid (void)
void MSD_execNameMerge (void)
void MSD_execNameSoftRemove (void)
void MSD_execNewVertexLocation (void)
void MSD_execNome (void)
void MSD_execRevert (void)
void MSD_execRingMove (void)
void MSD_execSEMV (void)
void MSD_execSetDoInverse (void)
Definition at line 48 of file euldoinv.cpp.
References MSD_lowSetDoInverse().
void MSD_execSoftRemove (void)
int MSD_execStructColor (EulerOp * op)
Definition at line 171 of file eulcolor.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highColor(), SOLID, and eulerop::solidno.
int MSD_execStructDetach (EulerOp * op)
Definition at line 204 of file topdetac.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highDetach(), and eulerop::solidno.
int MSD_execStructError (EulerOp * op)
Definition at line 139 of file eulxundo.cpp.
References ERROR, MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_ApplyEulerOp.
int MSD_execStructHardRemove (EulerOp * op)
Definition at line 130 of file topremhr.cpp.
References MSD_highHardRemove(), and eulerop::solidno.
int MSD_execStructKEF (EulerOp * op)
Definition at line 301 of file eulkef__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highKEF2(), and eulerop::solidno.
int MSD_execStructKEMR (EulerOp * op)
Definition at line 201 of file eulkemr_.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highKEMR(), and eulerop::solidno.
int MSD_execStructKEV (EulerOp * op)
Definition at line 375 of file eulkev__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highKEV2(), and eulerop::solidno.
int MSD_execStructKFMRH (EulerOp * op)
Definition at line 155 of file eulkfmrh.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highKFMRH(), and eulerop::solidno.
int MSD_execStructKSFMR (EulerOp * op)
Definition at line 169 of file eulksfmr.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highKSFMR(), and eulerop::solidno.
int MSD_execStructKVSF (EulerOp * op)
Definition at line 164 of file eulkvsf_.cpp.
References eulerop::ip1, MSD_highKVSF(), and eulerop::solidno.
int MSD_execStructMEF (EulerOp * op)
Definition at line 282 of file eulmef__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highMEF2(), and eulerop::solidno.
int MSD_execStructMEKR (EulerOp * op)
Definition at line 263 of file eulmekr_.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, MSD_highMEKR2(), and eulerop::solidno.
int MSD_execStructMEV (EulerOp * op)
Definition at line 433 of file eulmev__.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highSVME3(), and eulerop::solidno.
int MSD_execStructMFKRH (EulerOp * op)
Definition at line 191 of file eulmfkrh.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highMFKRH2(), and eulerop::solidno.
int MSD_execStructModifyIds (EulerOp * op)
Definition at line 100 of file topmodif.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highModifyIds(), and eulerop::solidno.
int MSD_execStructMSFKR (EulerOp * op)
Definition at line 218 of file eulmsfkr.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highMSFKR2(), eulerop::solidno, and SUCCESS.
int MSD_execStructMVSF (EulerOp * op)
Definition at line 138 of file eulmvsf_.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_lowMVSF(), eulerop::solidno, SolSBits, SPTYPE, and SUCCESS.
int MSD_execStructName (EulerOp * op)
Definition at line 196 of file eulnome_.cpp.
References EulerIp3, EulerIp4, EulerIp5, EulerIp6, EulerIp7, EulerIp8, EulerOpNext, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highName(), PEulerOp, and TRUE.
int MSD_execStructNewVertexLocation (EulerOp * op)
Definition at line 117 of file topnewlc.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, MSD_highNewVertexLocation(), and eulerop::solidno.
int MSD_execStructRevert (EulerOp * op)
Definition at line 157 of file toprever.cpp.
References eulerop::ip1, MSD_highRevert(), and eulerop::solidno.
int MSD_execStructRingMove (EulerOp * op)
Definition at line 160 of file topringm.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highRingMove(), and eulerop::solidno.
void MSD_execSVME (void)
void MSD_execSVME2 (void)
void MSD_execSVME3 (void)
void MSD_execUndoOp (void)
Definition at line 70 of file eulxundo.cpp.
References MSD_highUndoOp().
int MSD_highAllRingMove (Id sn, Id f1, Id f2)
Definition at line 241 of file topringm.cpp.
References ERROR, FNIL, FPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowAllRingMove(), NAM_AllRingMove, SNIL, and SPTYPE.
int MSD_highCleanSolid (Id sn)
Definition at line 101 of file topclean.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCleanSolid(), NAM_CleanSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCleanSolid().
int MSD_highColor (Id sn, int color, int cod)
Definition at line 117 of file eulcolor.cpp.
References ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getGroup(), MSD_getSolid(), MSD_lowGroupColor(), MSD_lowSolidColor(), NAM_Color, SNIL, SOLID, SPTYPE, and SUCCESS.
Referenced by MSD_execStructColor().
int MSD_highDetach (Id sn, Id sn1, Id dn, Id newd, int addf, int addv)
Definition at line 72 of file topdetac.cpp.
References DNIL, DPTYPE, ERROR, MEN_NaoEncontrouShell, MEN_NaoEncontrouSolido, MSD_getShell(), MSD_getSolid(), MSD_lowDetach(), NAM_Detach, SNIL, and SPTYPE.
Referenced by MSD_execStructDetach().
int MSD_highGlue (Id sn1, Id sn2)
Definition at line 70 of file toplglue.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowGlue(), NAM_Glue, SNIL, SPTYPE, and SUCCESS.
int MSD_highHardRemove (Id sn)
Definition at line 69 of file topremhr.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowHardRemove(), NAM_HardRemove, SNIL, and SPTYPE.
Referenced by MSD_execStructHardRemove().
int MSD_highJEKV (Id sn, Id v1, Id v2)
Definition at line 183 of file eulkev__.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, ERROR, FPTYPE, HalNxt, HalPrv, HPTYPE, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getSolid(), MSD_lowKEV(), NAM_JEKV, SNIL, SPTYPE, and SUCCESS.
int MSD_highJVKE (Id sn, Id v1, Id v2, Id f)
Definition at line 135 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HalNxt, HPTYPE, LNIL, mate, MEN_ArestaCircular, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEV(), NAM_JVKE, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEF (Id sn, Id v1, Id v2, Id fn)
Definition at line 72 of file eulkef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEF(), NAM_KEF, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEF2 (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 118 of file eulkef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowKEF(), NAM_KEF, NAM_KEF2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEF().
int MSD_highKEMR (Id sn, Id fn, Id v1, Id v2)
Definition at line 72 of file eulkemr_.cpp.
References ERROR, FNIL, FPTYPE, HalWLoop, HPTYPE, LNIL, mate, MEN_NaoArestaPonte, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEMR(), NAM_KEMR, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEMR().
int MSD_highKEV (Id sn, Id fn, Id v1, Id v2)
Definition at line 76 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HalNxt, HalWLoop, HPTYPE, LNIL, MEN_NaoArestaPonte, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoVerticeTerminal, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEV(), NAM_KEV, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEV2 (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 236 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowKEV(), NAM_KEV2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEV().
int MSD_highKFMRH (Id sn, Id fn1, Id fn2)
Definition at line 71 of file eulkfmrh.cpp.
References ERROR, FacFLoops, FNIL, FPTYPE, LNIL, LooNextL, MEN_FaceSemLoop, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKFMRH(), NAM_KFMRH, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKFMRH().
int MSD_highKSFMR (Id sn, Id fn1, Id fn2)
Definition at line 71 of file eulksfmr.cpp.
References ERROR, FacFLoops, FNIL, FPTYPE, LNIL, LooNextL, MEN_FaceSemLoop, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKSFMR(), NAM_KSFMR, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKSFMR().
int MSD_highKVSF (Id sn, Id fn)
Definition at line 75 of file eulkvsf_.cpp.
References ENIL, ERROR, FacFLoops, FNIL, FPTYPE, HalEdg, LNIL, LooLEdg, LooNextL, MEN_FaceSemLoop, MEN_FaceSemVertice, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKVSF(), NAM_KVSF, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKVSF().
int MSD_highMEF (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 72 of file eulmef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEF(), NAM_MEF, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), and MSD_lowMakePolygon().
int MSD_highMEF2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4)
Definition at line 123 of file eulmef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaF, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEF(), NAM_MEF2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEF().
int MSD_highMEKR (Id sn, Id fn, Id v1, Id v2)
Definition at line 71 of file eulmekr_.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MEN_VerticesEmLoopsDistintos, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEKR(), NAM_MEKR, SNIL, SPTYPE, and SUCCESS.
int MSD_highMEKR2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3)
Definition at line 128 of file eulmekr_.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEKR(), NAM_MEKR2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEKR().
int MSD_highMerge (Id sn1, Id sn2)
Definition at line 105 of file topmerge.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowMerge(), NAM_MergeSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMerge().
int MSD_highMEV (Id sn, Id fn, Id v1, Id v2, real x, real y, real z)
Definition at line 80 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEV(), NAM_MEV, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeArc(), MSD_lowMakeCube(), MSD_lowMakeCube0(), and MSD_lowMakePolygon().
int MSD_highMFKRH (Id sn, Id f1, Id f2)
Definition at line 71 of file eulmfkrh.cpp.
References ERROR, FacFLoops, FacFLOut, FNIL, FPTYPE, LooNextL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowMFKRH(), NAM_MFKRH, SNIL, SPTYPE, and SUCCESS.
int MSD_highMFKRH2 (Id sn, Id f1, Id f2, Id v1, Id v2)
Definition at line 113 of file eulmfkrh.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMFKRH(), NAM_MFKRH2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMFKRH().
int MSD_highModifyIds (Id sn, Id snew)
Definition at line 69 of file topmodif.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowModifyIds(), NAM_ModifyIds, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructModifyIds().
int MSD_highMSFKR (Id sn, Id ff, Id fn, Id dn)
Definition at line 71 of file eulmsfkr.cpp.
References ERROR, FacFLoops, FacFLOut, FNIL, FPTYPE, LooNextL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowMSFKR(), NAM_MSFKR, SNIL, SPTYPE, and SUCCESS.
int MSD_highMSFKR2 (Id sn, Id ff, Id fn, Id dn, Id v1, Id v2)
Definition at line 114 of file eulmsfkr.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMSFKR(), NAM_MSFKR2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMSFKR().
SPTYPE MSD_highMVSF (Id fn, Id vn, Id dn, real xx, real yy, real zz)
Definition at line 77 of file eulmvsf_.cpp.
References MSD_getMaxSolidId(), and MSD_lowMVSF().
int MSD_highName (Id sn, char * nome, int cod)
Definition at line 75 of file eulnome_.cpp.
References ANIL, APTYPE, AXIS, ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getAxis(), MSD_getGroup(), MSD_getSolid(), MSD_lowAxisName(), MSD_lowGroupName(), MSD_lowSolidName(), NAM_Name, SNIL, SOLID, SPTYPE, and SUCCESS.
Referenced by MSD_execStructName(), MSD_highNameDifference(), MSD_highNameIntersection(), MSD_highNameMakeCone(), MSD_highNameMakeCube(), MSD_highNameMakeCylinder(), MSD_highNameMakePrism(), MSD_highNameMakePyramid(), MSD_highNameMakeRevolve(), MSD_highNameMakeSphere(), MSD_highNameMakeTorus(), MSD_highNameSplit(), MSD_highNameUnion(), and MSD_lowNameRenameSolid().
int MSD_highNameCleanSolid (char *)
Definition at line 71 of file topclean.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCleanSolid(), and NAM_CleanSolid.
int MSD_highNameColor (char * name, int color)
Definition at line 57 of file eulcolor.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_getTypeByName(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), and NAM_Color.
int MSD_highNameGroupColor (char * name, int col)
Definition at line 99 of file eulcolor.cpp.
References FALSE, GNIL, GPTYPE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_lowFindGroupByName(), MSD_lowGroupColor(), NAM_Color, NAM_SetElementColor, and TRUE.
Referenced by MSD_execColor(), and MSD_highNameColor().
int MSD_highNameMerge (char * , char *)
Definition at line 70 of file topmerge.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMerge(), and NAM_MergeSolid.
int MSD_highNameSoftRemove (char * name)
Definition at line 70 of file topremsf.cpp.
References FALSE, MEN_NaoEncontrouSolidNome, MSD_lowFindSolidByName(), MSD_lowSoftRemove(), NAM_SoftRemove, SNIL, and SPTYPE.
Referenced by MSD_highNameDeleteElement(), MSD_lowAreaProjetada(), and MSD_lowAreaProjetadaTotal().
int MSD_highNameSolidColor (char * name, int col)
Definition at line 80 of file eulcolor.cpp.
References FALSE, MaxColors, MEN_CorInvalida, MEN_ElementoNaoEncontrado, MSD_lowFindSolidByName(), MSD_lowSolidColor(), NAM_Color, NAM_SetElementColor, SNIL, SPTYPE, and TRUE.
Referenced by MSD_execColor(), and MSD_highNameColor().
int MSD_highNewVertexLocation (Id sn, Id vn, real x, real y, real z)
Definition at line 70 of file topnewlc.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, ERROR, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getSolid(), MSD_lowNewVertexLocation(), NAM_NewLocation, SNIL, SPTYPE, SUCCESS, VerVertexNo, and VPTYPE.
Referenced by MSD_execStructNewVertexLocation().
void MSD_highPrintAllOps (void)
Definition at line 66 of file eulprint.cpp.
References EulerOpNext, EULEROPS, EuNIL, MSD_lowPrintEulerOp(), OpHead, and PEulerOp.
void MSD_highPrintAllRedoOps (void)
Definition at line 107 of file eulprint.cpp.
References EulerOpNextRedo, EULEROPSREDO, EuNIL, MSD_lowPrintEulerOp(), OpHeadRedo, and PEulerOp.
int MSD_highRevert (Id sn, Id dn)
Definition at line 71 of file toprever.cpp.
References DNIL, DPTYPE, ERROR, MEN_NaoEncontrouShell, MEN_NaoEncontrouSolido, MSD_getShell(), MSD_getSolid(), MSD_lowRevert(), NAM_Revert, SNIL, and SPTYPE.
Referenced by MSD_execStructRevert().
int MSD_highRingMove (Id sn, Id v1, Id v2, Id f1, Id f2, int out)
Definition at line 74 of file topringm.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowRingMove(), NAM_RingMove, SNIL, and SPTYPE.
Referenced by MSD_execStructRingMove().
int MSD_highSEMV (Id sn, Id v1, Id v2, Id v3, real x, real y, real z)
Definition at line 125 of file eulmev__.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, ERROR, FPTYPE, HalNxt, HPTYPE, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getSolid(), MSD_lowMEV(), NAM_SEMV, SNIL, SPTYPE, and SUCCESS.
int MSD_highSoftRemove (Id sn)
Definition at line 100 of file topremsf.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSoftRemove(), NAM_SoftRemove, SNIL, and SPTYPE.
int MSD_highSVME (Id sn, Id v1, Id v2, Id f1, Id f2, real x, real y, real z)
Definition at line 181 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME, SNIL, SPTYPE, and SUCCESS.
int MSD_highSVME2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, real x, real y, real z)
Definition at line 238 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME2, SNIL, SPTYPE, and SUCCESS.
int MSD_highSVME3 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4, real x, real y, real z)
Definition at line 296 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaF, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME3, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEV().
void MSD_highUndoOp (void)
Definition at line 75 of file eulxundo.cpp.
References MSD_lowUndoOp().
Referenced by MSD_execUndoOp().
void MSD_lowAddEulerOp (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, Id i, Id j, real k, real l, real m, real n)
Definition at line 433 of file eulerops.cpp.
References CommandCount, EulerCommandCount, EulerCount, EulerFp1, EulerFp2, EulerFp3, EulerFp4, EulerIp1, EulerIp2, EulerIp3, EulerIp4, EulerIp5, EulerIp6, EulerIp7, EulerIp8, EulerOpCode, EulerSolidNo, MEN_NaoPossuiMemoria, NAM_AddEulerOperator, NIL, OpCount, OpHead, eulerop::opnext, SNIL, and SolSolidNo.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowAddMatrix(), MSD_lowAllRingMove(), MSD_lowAssociaGroupAxis(), MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowAssociaSolidAxis(), MSD_lowAxisName(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCreateGroup(), MSD_lowGroupColor(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowLoadSolid(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMoveAxis(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowRotateAxis(), MSD_lowScale(), MSD_lowSetGroupCurrent(), MSD_lowShellDetach(), MSD_lowSolidColor(), MSD_lowSolidName(), MSD_lowTransformation(), and MSD_lowTranslate().
void MSD_lowAddEulerOpRedo (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, Id i, Id j, real k, real l, real m, real n)
Definition at line 473 of file eulerops.cpp.
References CommandCount, EulerCommandCountRedo, EulerCountRedo, EulerFp1Redo, EulerFp2Redo, EulerFp3Redo, EulerFp4Redo, EulerIp1Redo, EulerIp2Redo, EulerIp3Redo, EulerIp4Redo, EulerIp5Redo, EulerIp6Redo, EulerIp7Redo, EulerIp8Redo, EulerOpCodeRedo, EulerSolidNoRedo, MEN_NaoPossuiMemoria, NAM_AddEulerOperator, NIL, OpCountRedo, OpHeadRedo, eulerop::opnext, SNIL, and SolSolidNo.
Referenced by MSD_lowAddMatrixRedo(), MSD_lowAxisName(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowScale(), MSD_lowShellDetach(), MSD_lowSolidName(), MSD_lowTransformation(), and MSD_lowTranslate().
void MSD_lowAddMatrix (SPTYPE a, OpCode b, Id c, Id d, Id e, Id f, Id g, Id h, matrix i)
Definition at line 513 of file eulerops.cpp.
References MSD_lowAddEulerOp().
Referenced by MSD_lowTransformation().
void MSD_lowAddMatrixRedo (SPTYPE s, OpCode opcode, Id ip1, Id ip2, Id ip3, Id ip4, Id ip5, Id ip6, matrix m)
Definition at line 527 of file eulerops.cpp.
References MSD_lowAddEulerOpRedo().
Referenced by MSD_lowTransformation().
int MSD_lowAllRingMove (FPTYPE f1, FPTYPE f2)
Definition at line 265 of file topringm.cpp.
References FacFaceNo, FacFeq, FacFLoops, FacFLOut, FacFShell, FALSE, Gdoinversion, getdrop(), HalEdg, HalNxt, HalVtx, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowFaceEq(), MSD_lowFacVtxCoordContainment(), NAM_AllRingMove, NPTYPE, RMOVE, SetTrace, SheSSolids, SPTYPE, SUCCESS, TraceSolid(), TRUE, and VerVertexNo.
Referenced by MSD_highAllRingMove(), MSD_lowJoin(), and MSD_lowSetOpJoin().
SPTYPE MSD_lowApplyEulerOp (EulerOp * op, int * cont)
Definition at line 119 of file eulxundo.cpp.
References eulercod::ecode, eulercod::eop, ERROR, MEN_ParametrosIncorretos, MSD_getSolid(), NAM_ApplyEulerOp, eulercod::num, eulerop::opcode, SNIL, eulerop::solidno, and eulercod::xeop.
Referenced by MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowSaveSolid(), and MSD_lowUndoOp().
void MSD_lowAxisName (APTYPE a, char * nome)
Definition at line 168 of file eulnome_.cpp.
References AXIS, AxsAxisNo, AxsName, Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, and SNIL.
Referenced by MSD_highName(), and MSD_lowRemoveAxis().
int MSD_lowCheckTranslatorTable (int elemno, int code)
Definition at line 113 of file eulmodif.cpp.
References ATableMax, AXIS, GROUP, GTableMax, MSD_getMaxAxisId(), MSD_getMaxGroupId(), MSD_getMaxSolidId(), TransTable::NewNo, TransTable::OldNo, SOLID, and STableMax.
Referenced by MSD_modifyStructAssociate(), MSD_modifyStructColor(), MSD_modifyStructCreateGroup(), MSD_modifyStructCrtAxsRotation(), MSD_modifyStructCrtAxsTranslation(), MSD_modifyStructDetach(), MSD_modifyStructHardRemove(), MSD_modifyStructKEF(), MSD_modifyStructKEMR(), MSD_modifyStructKEV(), MSD_modifyStructKFMRH(), MSD_modifyStructKSFMR(), MSD_modifyStructKVSF(), MSD_modifyStructMEF(), MSD_modifyStructMEKR(), MSD_modifyStructMEV(), MSD_modifyStructMFKRH(), MSD_modifyStructModifyIds(), MSD_modifyStructMoveAxis(), MSD_modifyStructMSFKR(), MSD_modifyStructMVSF(), MSD_modifyStructName(), MSD_modifyStructNewVertexLocation(), MSD_modifyStructRemoveAxis(), MSD_modifyStructRemoveOneGroup(), MSD_modifyStructRevert(), MSD_modifyStructRingMove(), MSD_modifyStructRotate(), MSD_modifyStructRotateAxis(), MSD_modifyStructScale(), MSD_modifyStructSetGroupCurrent(), MSD_modifyStructTransformation(), and MSD_modifyStructTranslate().
void MSD_lowCleanSolid (SPTYPE s)
Definition at line 114 of file topclean.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, EdgHe1, EdgHe2, EdgNextE, ENIL, EPS, EPTYPE, FacFeq, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, getdrop(), HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLEdg, LooLFace, LooNextL, LPTYPE, mate, MSD_lowEdgEdgColinear(), MSD_lowFacFacEqualEqs(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowLooVtxContainment(), MSD_lowMakeFaceToPoint(), MSD_lowMEKR(), MSD_lowSetEdgeAngle(), MSD_lowSetNormal(), MSD_lowVtxVtxContainment(), SheSEdges, SheSFaces, SheSVerts, TRUE, vecnull(), VerNextV, VerVEdge, VNIL, and VPTYPE.
Referenced by MSD_highCleanSolid(), MSD_highDifference(), MSD_highIntersection(), and MSD_highUnion().
SPTYPE MSD_lowDetach (SPTYPE s, Id sn, DPTYPE d, Id newd, int addf, int addv)
Definition at line 90 of file topdetac.cpp.
References MSD_getSolid(), MSD_lowNewElement(), MSD_lowShellDetach(), NNIL, SheSSolids, SNIL, SOLID, SolSolidNo, and SPTYPE.
Referenced by MSD_highDetach(), MSD_lowSetOpFinish(), and MSD_lowSplitFinish().
void MSD_lowEdgeRemove (SPTYPE s)
Definition at line 146 of file topremsf.cpp.
References EdgHe1, EdgHe2, ENIL, EPTYPE, FacFLOut, HalNxt, HalWLoop, LooLFace, LPTYPE, maxf, MSD_getMaxFaceId(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowMFKRH(), SheSEdges, and SolSShells.
Referenced by MSD_lowSoftRemove().
void MSD_lowFaceGlue (SPTYPE s1, SPTYPE s2, FPTYPE f1, FPTYPE f2)
Definition at line 196 of file toplglue.cpp.
References MSD_lowKSFMR(), MSD_lowLoopGlue(), and MSD_lowMerge().
void MSD_lowFaceRemove (SPTYPE s)
Definition at line 184 of file topremsf.cpp.
References AllFacesShell, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, HPTYPE, LNIL, LooLEdg, LooNextL, LPTYPE, mate, MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowMEKR(), SheSFaces, and SolSShells.
Referenced by MSD_lowSoftRemove().
void MSD_lowFreeUndoLog (PEulerOp EndOp)
Definition at line 147 of file eulxundo.cpp.
References NIL, OpCount, OpHead, and eulerop::opnext.
Referenced by MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), and MSD_lowSaveSolid().
void MSD_lowGetMatrix (EulerOp * op, matrix m)
Definition at line 167 of file eulxundo.cpp.
References EulerFp1, EulerFp2, EulerFp3, EulerFp4, EulerOpNext, and PEulerOp.
Referenced by MSD_execStructTransformation().
void MSD_lowGlue (SPTYPE s1, SPTYPE s2)
Definition at line 89 of file toplglue.cpp.
References AllFacesShell, AllShellsSolid, DNIL, DPTYPE, FacFShell, FacNextF, FNIL, FPTYPE, MSD_lowFacFacContainment(), MSD_lowFacFacIdentical(), MSD_lowFacFacOppositeEqs(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowLoopGlue(), MSD_lowMerge(), SheNextD, and SheSFaces.
Referenced by MSD_highGlue().
void MSD_lowGroupColor (GPTYPE g, int color)
Definition at line 157 of file eulcolor.cpp.
References COLOR, Gdoinversion, GROUP, GrpGColor, GrpGroupNo, MSD_lowAddEulerOp(), and SNIL.
Referenced by MSD_highColor(), MSD_highNameGroupColor(), and MSD_lowRemoveOneGroup().
void MSD_lowGroupName (GPTYPE g, char * nome)
Definition at line 140 of file eulnome_.cpp.
References Gdodirect, Gdoinversion, GROUP, GrpGroupNo, GrpName, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, and SNIL.
Referenced by MSD_highName(), and MSD_lowRemoveOneGroup().
int MSD_lowHardRemove (SPTYPE s)
Definition at line 81 of file topremhr.cpp.
References DNIL, DPTYPE, EDGE, EdgHe1, ENIL, FACE, FacFLoops, FALSE, FNIL, FPTYPE, HalEdg, HALFEDGE, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LOOP, LPTYPE, MSD_lowDelElement(), NNIL, NPTYPE, SetTrace, SHELL, SheSFaces, SOLID, SolSShells, SUCCESS, VERTEX, and VerVEdge.
Referenced by MSD_highHardRemove(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakePolygon(), MSD_lowMakePrism(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), and MSD_lowMakeTorus().
void MSD_lowIniciaTranslatorTable (void)
Definition at line 108 of file eulmodif.cpp.
References ATableMax, GTableMax, and STableMax.
Referenced by MSD_lowCopyGroup().
void MSD_lowKEF (HPTYPE he1, HPTYPE he2)
Definition at line 150 of file eulkef__.cpp.
References AllLoopsFace, assert1, DPTYPE, EDGE, ENIL, EPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FALSE, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEF, LNIL, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEF, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowDelList(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEV(), NAM_KEF, NIL, NPTYPE, RMOVE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), TRUE, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by EdgeAttached_vertexfase1(), edv1(), edv2(), edv3(), edv4(), MSD_highKEF(), MSD_highKEF2(), MSD_lowCleanSolid(), MSD_lowCut(), MSD_lowEdgeRemove(), MSD_lowKEF(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowSetOpCutA(), and MSD_lowSetOpCutB().
void MSD_lowKEMR (HPTYPE he1, HPTYPE he2)
Definition at line 102 of file eulkemr_.cpp.
References assert1, DPTYPE, EDGE, ENIL, EPTYPE, FacFaceNo, FacFShell, findes(), Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEMR, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEKR, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowNewElement(), NAM_KEMR, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VerVEdge, and VerVertexNo.
Referenced by MSD_highKEMR(), MSD_lowCleanSolid(), MSD_lowCut(), MSD_lowEdgeRemove(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), and MSD_lowSetOpMakeRing().
void MSD_lowKEV (HPTYPE he1, HPTYPE he2)
Definition at line 267 of file eulkev__.cpp.
References assert1, DPTYPE, EDGE, ENIL, FacFaceNo, FacFShell, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEV, LooLEdg, LooLength, LooLFace, LPTYPE, mate, MEN_MSDAbortou, MEV, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowKEV(), MSD_lowMEV(), NAM_KEV, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by EdgeAttached_vertexfase1(), edv1(), edv2(), edv4(), MSD_highJEKV(), MSD_highJVKE(), MSD_highKEV(), MSD_highKEV2(), MSD_lowCleanSolid(), MSD_lowEdgeRemove(), MSD_lowFaceRemove(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), and MSD_lowTouchWire().
void MSD_lowKFMRH (FPTYPE f1, FPTYPE f2)
Definition at line 101 of file eulkfmrh.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, Gdodirect, Gdoinversion, HalNxt, HalVtx, KFMRH, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MFKRH, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), NAM_KFMRH, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by MSD_highKFMRH(), MSD_lowFaceRemove(), MSD_lowGlue(), MSD_lowMakeRotationalSweep(), and MSD_lowSetOpFinish().
void MSD_lowKSFMR (FPTYPE f1, FPTYPE f2)
Definition at line 101 of file eulksfmr.cpp.
References assert1, DPTYPE, EDGE, ENIL, EPTYPE, FACE, FacFaceNo, FacFLoops, FacFShell, FNIL, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KSFMR, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), MSFKR, NAM_KSFMR, NPTYPE, SetTrace, SHELL, SheSEdges, SheSFaces, SheShellNo, SheSSolids, SheSVerts, SPTYPE, TraceSolid(), VERTEX, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_highKSFMR(), MSD_lowFaceGlue(), MSD_lowGlue(), MSD_lowSetOpFinish(), and MSD_lowShellRemove().
void MSD_lowKVSF (SPTYPE s)
Definition at line 104 of file eulkvsf_.cpp.
References assert1, DNIL, DPTYPE, ENIL, FACE, FacFaceNo, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, Gdodirect, Gdoinversion, HALFEDGE, KVSF, LNIL, LooLEdg, LooNextL, LOOP, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MVSF, NAM_KVSF, NIL, NNIL, NPTYPE, SetTrace, SHELL, SheNextD, SheSEdges, SheSFaces, SheShellNo, SheSVerts, SOLID, SolSBits, SolSShells, TraceSolid(), VerNextV, VERTEX, VerVCoord, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_highKVSF(), and MSD_lowSoftRemove().
int MSD_lowLoopGlue (FPTYPE f)
Definition at line 203 of file toplglue.cpp.
References assert, assert1, FacFLoops, FALSE, HalNxt, HalPrv, HalVtx, HPTYPE, LNIL, LooLEdg, LooNextL, mate, maxf, MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowVtxVtxContainment(), and SUCCESS.
Referenced by MSD_lowFaceGlue(), MSD_lowGlue(), MSD_lowMakeRotationalSweep(), and MSD_lowSetOpFinish().
FPTYPE MSD_lowMEF (HPTYPE he1, HPTYPE he2, Id fn)
Definition at line 166 of file eulmef__.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FACE, FacFaceNo, FacFLOut, FacFShell, findf(), findl(), FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KEF, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEF, MEN_MSDAbortou, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowNewElement(), NAM_MEF, NIL, NPTYPE, PLUS, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by edv3(), edv4(), GenerationEdges_nvertices(), MakeEdgeConvexCorner(), MSD_highMEF(), MSD_highMEF2(), MSD_lowJoin(), MSD_lowLoopGlue(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), and MSD_lowSetOpJoin().
void MSD_lowMEKR (HPTYPE he1, HPTYPE he2)
Definition at line 171 of file eulmekr_.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FacFaceNo, FacFLOut, FacFShell, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEMR, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEKR, MEN_MSDAbortou, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowDelElement(), MSD_lowNewElement(), NAM_MEKR2, NPTYPE, PLUS, RMOVE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), TRUE, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by MSD_highMEKR(), MSD_highMEKR2(), MSD_lowCleanSolid(), MSD_lowFaceRemove(), MSD_lowJoin(), MSD_lowLoopGlue(), and MSD_lowSetOpJoin().
void MSD_lowMerge (SPTYPE s1, SPTYPE s2)
Definition at line 124 of file topmerge.cpp.
References DNIL, DPTYPE, maxd, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxShellId(), MSD_getMaxVertexId(), MSD_lowShellDetach(), and SolSShells.
Referenced by MSD_highMerge(), MSD_lowFaceGlue(), and MSD_lowGlue().
void MSD_lowMEV (HPTYPE he1, HPTYPE he2, Id vn, real x, real y, real z)
Definition at line 346 of file eulmev__.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FacFaceNo, FacFShell, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KEV, LooLFace, mate, MEN_MSDAbortou, MEV, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowNewElement(), NAM_MEV, NIL, NPTYPE, PLUS, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_highMEV(), MSD_highSEMV(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_lowInsertNullEdges(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), and MSD_lowSplitGenerate().
FPTYPE MSD_lowMFKRH (FPTYPE f, LPTYPE l, Id fn)
Definition at line 139 of file eulmfkrh.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KFMRH, LNIL, LooLEdg, LooLFace, LooNextL, LOOP, MEN_MSDAbortou, MFKRH, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowNewElement(), NAM_MFKRH, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by MSD_highMFKRH(), MSD_highMFKRH2(), MSD_lowEdgeRemove(), and MSD_lowSetOpFinish().
SPTYPE MSD_lowModifyEulerOp (EulerOp * op)
Definition at line 81 of file eulmodif.cpp.
References eulercod::ecode, eulercod::eop, ERROR, MEN_ParametrosIncorretos, eulercod::meop, MSD_getSolid(), NAM_ModifyEulerOp, eulerop::opcode, SNIL, and eulerop::solidno.
Referenced by MSD_lowCopyGroup().
void MSD_lowModifyIds (SPTYPE s, Id snew)
Definition at line 82 of file topmodif.cpp.
References Gdodirect, Gdoinversion, MODIFYNAMES, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), and SolSolidNo.
Referenced by MSD_highDifference(), MSD_highIntersection(), MSD_highModifyIds(), and MSD_highUnion().
FPTYPE MSD_lowMSFKR (LPTYPE l, Id fn, Id dn)
Definition at line 140 of file eulmsfkr.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FacNextF, FNIL, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KSFMR, LNIL, LooLEdg, LooLFace, LooNextL, LOOP, markface(), MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowListSolid(), MSD_lowNewElement(), MSFKR, NAM_MSFKR, NPTYPE, redo(), SetTrace, SHELL, SheSFaces, SheShellNo, SheSSolids, SPTYPE, trace, TraceSolid(), and VerVertexNo.
Referenced by MSD_highMSFKR(), MSD_highMSFKR2(), MSD_lowSetOpFinish(), and MSD_lowSplitFinish().
SPTYPE MSD_lowMVSF (Id sn, Id fn, Id vn, Id dn, real xx, real yy, real zz)
Definition at line 82 of file eulmvsf_.cpp.
References DPTYPE, ENIL, FACE, FacFaceNo, FacFLOut, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HALFEDGE, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KVSF, LooLEdg, LooLength, LOOP, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowNewElement(), MSD_setEulCoef(), MVSF, NAM_MVSF, NNIL, NPTYPE, SetTrace, SHELL, SheShellNo, SOLID, SolSolidNo, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVertexNo, and VPTYPE.
Referenced by MSD_execStructMVSF(), MSD_highMVSF(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakePolygon(), and MSD_lowMakeSphere().
void MSD_lowNewVertexLocation (SPTYPE s, VPTYPE v, real x, real y, real z)
Definition at line 96 of file topnewlc.cpp.
References Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NEWLOC, VerVCoord, and VerVertexNo.
Referenced by EdgeAttached_vertexfase1(), edv2(), and MSD_highNewVertexLocation().
void MSD_lowPrintEulerOp (FILE * f, EulerOp * op)
Definition at line 84 of file eulprint.cpp.
References eulercod::ecode, eulercod::eop, eulerop::opcode, and eulercod::peop.
Referenced by MSD_highPrintAllOps(), MSD_highPrintAllRedoOps(), and MSD_lowSaveSolid().
int MSD_lowRevert (DPTYPE d)
Definition at line 89 of file toprever.cpp.
References AllFacesShell, AllLoopsFace, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAM_Revert, REVERT, SetTrace, SheShellNo, SheSSolids, SPTYPE, SUCCESS, TraceSolid(), VerVEdge, and VPTYPE.
Referenced by MSD_highRevert(), MSD_lowRotate(), MSD_lowScale(), MSD_lowSetOpFinish(), and MSD_lowTransformation().
int MSD_lowRingMove (FPTYPE f1, FPTYPE f2, LPTYPE l, int out)
Definition at line 107 of file topringm.cpp.
References ArrayBottom, assert, ENIL, FacFaceNo, FacFLOut, FacFShell, FALSE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalVtx, InnerLoop, LooLEdg, LooLFace, LOOP, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), NAM_RingMove, NPTYPE, RMOVE, SetTrace, SheSSolids, SOLID, SolSolidNo, SPTYPE, SUCCESS, TraceSolid(), TRUE, and VerVertexNo.
Referenced by MSD_highRingMove().
int MSD_lowScanEulerOperator (FILE * f, EulerOp * op)
Definition at line 68 of file eulread_.cpp.
References eulercod::ecode, eulercod::eop, ERROR, MEN_ParametrosIncorretos, NAM_ScanEulerOp, eulerop::opcode, eulercod::reop, strupper(), and SUCCESS.
Referenced by MSD_lowLoadSolid().
void MSD_lowSetDoInverse (void)
Definition at line 53 of file euldoinv.cpp.
References Gdoinversion.
Referenced by MSD_execSetDoInverse().
void MSD_lowSetTranslatorTable (int elemnoold, int elemno, int code)
Definition at line 163 of file eulmodif.cpp.
References ATableMax, AXIS, GROUP, GTableMax, TransTable::NewNo, TransTable::OldNo, SOLID, and STableMax.
Referenced by MSD_lowCopyGroup().
void MSD_lowShellDetach (SPTYPE s, SPTYPE s1, DPTYPE d, Id newd, int addf, int addv)
Definition at line 107 of file topdetac.cpp.
References AllEdgesShell, AllFacesShell, AllLoopsFace, AllVerticesShell, DETACH, DNIL, EPTYPE, FacFaceNo, FPTYPE, Gdodirect, Gdoinversion, LPTYPE, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), NAM_Detach, NNIL, NPTYPE, SetTrace, SHELL, SheShellNo, SolEuCoef, SOLID, SolSolidNo, SolSShells, TraceSolid(), VerVertexNo, and VPTYPE.
Referenced by MSD_lowDetach(), and MSD_lowMerge().
void MSD_lowShellRemove (SPTYPE s)
Definition at line 136 of file topremsf.cpp.
References DNIL, DPTYPE, MSD_lowKSFMR(), SheNextD, SheSFaces, and SolSShells.
Referenced by MSD_lowSoftRemove().
int MSD_lowSoftRemove (SPTYPE s)
Definition at line 112 of file topremsf.cpp.
References DNIL, GNIL, GrpGroupNo, MSD_highDesassociaGroupSolid(), MSD_lowEdgeRemove(), MSD_lowFaceRemove(), MSD_lowKVSF(), MSD_lowShellRemove(), MSD_lowSolidColor(), MSD_lowSolidName(), SolColor, SolGroup, SolName, SolSolidNo, SolSShells, and SUCCESS.
Referenced by MSD_highNameSoftRemove(), MSD_highSoftRemove(), MSD_lowCopySolid(), MSD_lowRemoveGroup(), MSD_lowSaveSolid(), and MSD_lowSetOp().
void MSD_lowSolidColor (SPTYPE s, int color)
Definition at line 143 of file eulcolor.cpp.
References COLOR, Gdoinversion, MSD_lowAddEulerOp(), SolColor, SOLID, and SolSolidNo.
Referenced by MSD_highColor(), MSD_highNameSolidColor(), and MSD_lowSoftRemove().
void MSD_lowSolidName (SPTYPE s, char * nome)
Definition at line 111 of file eulnome_.cpp.
References Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, SOLID, SolName, and SolSolidNo.
Referenced by MSD_highName(), and MSD_lowSoftRemove().
SPTYPE MSD_lowUndoOp (void)
Definition at line 80 of file eulxundo.cpp.
References eulerop::CommandCount, EulerOpNext, EULEROPS, EuNIL, Gdoinversion, MSD_lowApplyEulerOp(), OpCount, OpHead, SNIL, and SPTYPE.
Referenced by MSD_highUndoOp().
int MSD_modifyStructColor (EulerOp * op)
Definition at line 208 of file eulcolor.cpp.
References GROUP, eulerop::ip1, eulerop::ip3, MSD_lowCheckTranslatorTable(), SOLID, and SUCCESS.
int MSD_modifyStructDetach (EulerOp * op)
Definition at line 258 of file topdetac.cpp.
References eulerop::ip1, MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructError (EulerOp * op)
Definition at line 100 of file eulmodif.cpp.
References ERROR, MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_ModifyEulerOp.
int MSD_modifyStructHardRemove (EulerOp * op)
Definition at line 173 of file topremhr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKEF (EulerOp * op)
Definition at line 352 of file eulkef__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKEMR (EulerOp * op)
Definition at line 250 of file eulkemr_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKEV (EulerOp * op)
Definition at line 426 of file eulkev__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKFMRH (EulerOp * op)
Definition at line 202 of file eulkfmrh.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKSFMR (EulerOp * op)
Definition at line 216 of file eulksfmr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructKVSF (EulerOp * op)
Definition at line 199 of file eulkvsf_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMEF (EulerOp * op)
Definition at line 343 of file eulmef__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMEKR (EulerOp * op)
Definition at line 322 of file eulmekr_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMEV (EulerOp * op)
Definition at line 504 of file eulmev__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMFKRH (EulerOp * op)
Definition at line 242 of file eulmfkrh.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructModifyIds (EulerOp * op)
Definition at line 146 of file topmodif.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMSFKR (EulerOp * op)
Definition at line 271 of file eulmsfkr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructMVSF (EulerOp * op)
Definition at line 202 of file eulmvsf_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructName (EulerOp * op)
Definition at line 281 of file eulnome_.cpp.
References AXIS, GROUP, eulerop::ip1, eulerop::ip2, MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructNewVertexLocation (EulerOp * op)
Definition at line 171 of file topnewlc.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructRevert (EulerOp * op)
Definition at line 190 of file toprever.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructRingMove (EulerOp * op)
Definition at line 214 of file topringm.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructColor (FILE * f, EulerOp * op)
Definition at line 181 of file eulcolor.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::ip3.
void MSD_printStructDetach (FILE * f, EulerOp * op)
Definition at line 217 of file topdetac.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
void MSD_printStructError (FILE * f, EulerOp * op)
Definition at line 98 of file eulprint.cpp.
References MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_PrintEulerOp.
void MSD_printStructHardRemove (FILE * f, EulerOp * op)
Definition at line 138 of file topremhr.cpp.
References eulerop::CommandCount, and eulerop::solidno.
void MSD_printStructKEF (FILE * f, EulerOp * op)
Definition at line 313 of file eulkef__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
void MSD_printStructKEMR (FILE * f, EulerOp * op)
Definition at line 212 of file eulkemr_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
void MSD_printStructKEV (FILE * f, EulerOp * op)
Definition at line 387 of file eulkev__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
void MSD_printStructKFMRH (FILE * f, EulerOp * op)
Definition at line 165 of file eulkfmrh.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::solidno.
void MSD_printStructKSFMR (FILE * f, EulerOp * op)
Definition at line 179 of file eulksfmr.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::solidno.
void MSD_printStructKVSF (FILE * f, EulerOp * op)
Definition at line 169 of file eulkvsf_.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::solidno.
void MSD_printStructMEF (FILE * f, EulerOp * op)
Definition at line 298 of file eulmef__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, and eulerop::solidno.
void MSD_printStructMEKR (FILE * f, EulerOp * op)
Definition at line 278 of file eulmekr_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, and eulerop::solidno.
void MSD_printStructMEV (FILE * f, EulerOp * op)
Definition at line 454 of file eulmev__.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, and eulerop::solidno.
void MSD_printStructMFKRH (FILE * f, EulerOp * op)
Definition at line 203 of file eulmfkrh.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
void MSD_printStructModifyIds (FILE * f, EulerOp * op)
Definition at line 110 of file topmodif.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::ip2.
void MSD_printStructMSFKR (FILE * f, EulerOp * op)
Definition at line 232 of file eulmsfkr.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
void MSD_printStructMVSF (FILE * f, EulerOp * op)
Definition at line 159 of file eulmvsf_.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
void MSD_printStructName (FILE * f, EulerOp * op)
Definition at line 228 of file eulnome_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, and eulerop::ip8.
void MSD_printStructNewVertexLocation (FILE * f, EulerOp * op)
Definition at line 130 of file topnewlc.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and eulerop::solidno.
void MSD_printStructRevert (FILE * f, EulerOp * op)
Definition at line 162 of file toprever.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::solidno.
void MSD_printStructRingMove (FILE * f, EulerOp * op)
Definition at line 173 of file topringm.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
int MSD_readStructColor (FILE * f, EulerOp * op)
Definition at line 193 of file eulcolor.cpp.
References eulerop::CommandCount, ERROR, eulerop::ip1, eulerop::ip2, eulerop::ip3, and SUCCESS.
int MSD_readStructDetach (FILE * f, EulerOp * op)
Definition at line 232 of file topdetac.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructError (FILE * f, EulerOp * op)
Definition at line 96 of file eulread_.cpp.
References ERROR, MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_ScanEulerOp.
int MSD_readStructHardRemove (FILE * f, EulerOp * op)
Definition at line 148 of file topremhr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKEF (FILE * f, EulerOp * op)
Definition at line 327 of file eulkef__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKEMR (FILE * f, EulerOp * op)
Definition at line 225 of file eulkemr_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKEV (FILE * f, EulerOp * op)
Definition at line 401 of file eulkev__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKFMRH (FILE * f, EulerOp * op)
Definition at line 177 of file eulkfmrh.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKSFMR (FILE * f, EulerOp * op)
Definition at line 191 of file eulksfmr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructKVSF (FILE * f, EulerOp * op)
Definition at line 174 of file eulkvsf_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMEF (FILE * f, EulerOp * op)
Definition at line 317 of file eulmef__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMEKR (FILE * f, EulerOp * op)
Definition at line 296 of file eulmekr_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMEV (FILE * f, EulerOp * op)
Definition at line 477 of file eulmev__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMFKRH (FILE * f, EulerOp * op)
Definition at line 217 of file eulmfkrh.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructModifyIds (FILE * f, EulerOp * op)
Definition at line 121 of file topmodif.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMSFKR (FILE * f, EulerOp * op)
Definition at line 247 of file eulmsfkr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.
int MSD_readStructMVSF (FILE * f, EulerOp * op)
Definition at line 177 of file eulmvsf_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.
int MSD_readStructName (FILE * f, EulerOp * op)
Definition at line 259 of file eulnome_.cpp.
References eulerop::CommandCount, ERROR, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructNewVertexLocation (FILE * f, EulerOp * op)
Definition at line 145 of file topnewlc.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructRevert (FILE * f, EulerOp * op)
Definition at line 167 of file toprever.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.
int MSD_readStructRingMove (FILE * f, EulerOp * op)
Definition at line 188 of file topringm.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
void MSD_setEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
Definition at line 47 of file eulscoef.cpp.
References eulerco::edgen, solid::eucoef, eulerco::facen, eulerco::holen, eulerco::ringn, eulerco::shelln, and eulerco::vertexn.
Referenced by MSD_lowMVSF().
void redo (DPTYPE shell, DPTYPE oldshell)
Definition at line 302 of file eulmsfkr.cpp.
References AllFacesShell, AllLoopsFace, EDGE, EdgHe1, ENIL, FPTYPE, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowAddList(), MSD_lowDelList(), NPTYPE, VERTEX, and VerVEdge.
Referenced by MSD_lowMSFKR().
int sfinde (DPTYPE d, EPTYPE e)
Definition at line 353 of file eulmsfkr.cpp.
References AllEdgesShell, EPTYPE, FALSE, and TRUE.
int sfindv (DPTYPE d, VPTYPE v)
Definition at line 339 of file eulmsfkr.cpp.
References AllVerticesShell, FALSE, TRUE, and VPTYPE.
Variable Documentation
EXTERN int CommandCount
Definition at line 109 of file eulerops.h.
Referenced by MSD_highAffine(), MSD_highRotate(), MSD_highRotateSolidAxis(), MSD_highScale(), MSD_highTransformation(), MSD_highTranslate(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeTorus(), MSD_lowSetOp(), and MSD_lowSplit().
EXTERN int Gdodirect
Definition at line 108 of file eulerops.h.
Referenced by maninit(), MSD_lowAxisName(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowSaveSolid(), MSD_lowScale(), MSD_lowShellDetach(), MSD_lowSolidName(), MSD_lowTransformation(), and MSD_lowTranslate().
EXTERN int Gdoinversion
Definition at line 107 of file eulerops.h.
Referenced by main(), maninit(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowAllRingMove(), MSD_lowAssociaGroupAxis(), MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowAssociaSolidAxis(), MSD_lowAxisName(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCreateGroup(), MSD_lowGroupColor(), MSD_lowGroupName(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowModifyIds(), MSD_lowMoveAxis(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowNewVertexLocation(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowRotate(), MSD_lowRotateAxis(), MSD_lowSaveSolid(), MSD_lowScale(), MSD_lowSetDoInverse(), MSD_lowSetGroupCurrent(), MSD_lowShellDetach(), MSD_lowSolidColor(), MSD_lowSolidName(), MSD_lowTransformation(), MSD_lowTranslate(), and MSD_lowUndoOp().
EXTERN int OpCount
Definition at line 105 of file eulerops.h.
Referenced by MSD_lowAddEulerOp(), MSD_lowFreeUndoLog(), and MSD_lowUndoOp().
EXTERN int OpCountRedo
Definition at line 106 of file eulerops.h.
Referenced by MSD_lowAddEulerOpRedo().
EXTERN EulerOp* OpHead
Definition at line 99 of file eulerops.h.
Referenced by main(), maninit(), MSD_highPrintAllOps(), MSD_lowAddEulerOp(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowFreeUndoLog(), MSD_lowLoadSolid(), MSD_lowSaveSolid(), and MSD_lowUndoOp().
EXTERN EulerOp* OpHeadRedo
Definition at line 100 of file eulerops.h.
Referenced by maninit(), MSD_highPrintAllRedoOps(), and MSD_lowAddEulerOpRedo().