USPDesigner: C:/USPDesig/EUL/eulksfmr.cpp File Reference
C:/USPDesig/EUL/eulksfmr.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highKSFMR (Id sn, Id fn1, Id fn2)
void MSD_lowKSFMR (FPTYPE f1, FPTYPE f2)
int MSD_execStructKSFMR (EulerOp *op)
void MSD_printStructKSFMR (FILE *f, EulerOp *op)
int MSD_readStructKSFMR (FILE *f, EulerOp *op)
int MSD_modifyStructKSFMR (EulerOp *op)
Function Documentation
int MSD_execStructKSFMR (EulerOp * op)
Definition at line 169 of file eulksfmr.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highKSFMR(), and eulerop::solidno.
int MSD_highKSFMR (Id sn, Id fn1, Id fn2)
Definition at line 71 of file eulksfmr.cpp.
References ERROR, FacFLoops, FNIL, FPTYPE, LNIL, LooNextL, MEN_FaceSemLoop, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKSFMR(), NAM_KSFMR, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKSFMR().
void MSD_lowKSFMR (FPTYPE f1, FPTYPE f2)
Definition at line 101 of file eulksfmr.cpp.
References assert1, DPTYPE, EDGE, ENIL, EPTYPE, FACE, FacFaceNo, FacFLoops, FacFShell, FNIL, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KSFMR, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), MSFKR, NAM_KSFMR, NPTYPE, SetTrace, SHELL, SheSEdges, SheSFaces, SheShellNo, SheSSolids, SheSVerts, SPTYPE, TraceSolid(), VERTEX, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_highKSFMR(), MSD_lowFaceGlue(), MSD_lowGlue(), MSD_lowSetOpFinish(), and MSD_lowShellRemove().
int MSD_modifyStructKSFMR (EulerOp * op)
Definition at line 216 of file eulksfmr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKSFMR (FILE * f, EulerOp * op)
Definition at line 179 of file eulksfmr.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::solidno.
int MSD_readStructKSFMR (FILE * f, EulerOp * op)
Definition at line 191 of file eulksfmr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.