USPDesigner: C:/USPDesig/EUL/eulkfmrh.cpp File Reference
C:/USPDesig/EUL/eulkfmrh.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highKFMRH (Id sn, Id fn1, Id fn2)
void MSD_lowKFMRH (FPTYPE f1, FPTYPE f2)
int MSD_execStructKFMRH (EulerOp *op)
void MSD_printStructKFMRH (FILE *f, EulerOp *op)
int MSD_readStructKFMRH (FILE *f, EulerOp *op)
int MSD_modifyStructKFMRH (EulerOp *op)
Function Documentation
int MSD_execStructKFMRH (EulerOp * op)
Definition at line 155 of file eulkfmrh.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highKFMRH(), and eulerop::solidno.
int MSD_highKFMRH (Id sn, Id fn1, Id fn2)
Definition at line 71 of file eulkfmrh.cpp.
References ERROR, FacFLoops, FNIL, FPTYPE, LNIL, LooNextL, MEN_FaceSemLoop, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKFMRH(), NAM_KFMRH, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKFMRH().
void MSD_lowKFMRH (FPTYPE f1, FPTYPE f2)
Definition at line 101 of file eulkfmrh.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, Gdodirect, Gdoinversion, HalNxt, HalVtx, KFMRH, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MFKRH, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), NAM_KFMRH, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by MSD_highKFMRH(), MSD_lowFaceRemove(), MSD_lowGlue(), MSD_lowMakeRotationalSweep(), and MSD_lowSetOpFinish().
int MSD_modifyStructKFMRH (EulerOp * op)
Definition at line 202 of file eulkfmrh.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKFMRH (FILE * f, EulerOp * op)
Definition at line 165 of file eulkfmrh.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, and eulerop::solidno.
int MSD_readStructKFMRH (FILE * f, EulerOp * op)
Definition at line 177 of file eulkfmrh.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.