USPDesigner: C:/USPDesig/EUL/eulkef__.cpp File Reference
C:/USPDesig/EUL/eulkef__.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highKEF (Id sn, Id v1, Id v2, Id fn)
int MSD_highKEF2 (Id sn, Id v1, Id v2, Id f1, Id f2)
void MSD_lowKEF (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEF (EulerOp *op)
void MSD_printStructKEF (FILE *f, EulerOp *op)
int MSD_readStructKEF (FILE *f, EulerOp *op)
int MSD_modifyStructKEF (EulerOp *op)
Function Documentation
int MSD_execStructKEF (EulerOp * op)
Definition at line 301 of file eulkef__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highKEF2(), and eulerop::solidno.
int MSD_highKEF (Id sn, Id v1, Id v2, Id fn)
Definition at line 72 of file eulkef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEF(), NAM_KEF, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEF2 (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 118 of file eulkef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowKEF(), NAM_KEF, NAM_KEF2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEF().
void MSD_lowKEF (HPTYPE he1, HPTYPE he2)
Definition at line 150 of file eulkef__.cpp.
References AllLoopsFace, assert1, DPTYPE, EDGE, ENIL, EPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FALSE, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEF, LNIL, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEF, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowDelList(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEV(), NAM_KEF, NIL, NPTYPE, RMOVE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), TRUE, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by EdgeAttached_vertexfase1(), edv1(), edv2(), edv3(), edv4(), MSD_highKEF(), MSD_highKEF2(), MSD_lowCleanSolid(), MSD_lowCut(), MSD_lowEdgeRemove(), MSD_lowKEF(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowSetOpCutA(), and MSD_lowSetOpCutB().
int MSD_modifyStructKEF (EulerOp * op)
Definition at line 352 of file eulkef__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKEF (FILE * f, EulerOp * op)
Definition at line 313 of file eulkef__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
int MSD_readStructKEF (FILE * f, EulerOp * op)
Definition at line 327 of file eulkef__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.