USPDesigner: C:/USPDesig/EUL/eulkvsf_.cpp File Reference
C:/USPDesig/EUL/eulkvsf_.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highKVSF (Id sn, Id fn)
void MSD_lowKVSF (SPTYPE s)
int MSD_execStructKVSF (EulerOp *op)
void MSD_printStructKVSF (FILE *f, EulerOp *op)
int MSD_readStructKVSF (FILE *f, EulerOp *op)
int MSD_modifyStructKVSF (EulerOp *op)
Function Documentation
int MSD_execStructKVSF (EulerOp * op)
Definition at line 164 of file eulkvsf_.cpp.
References eulerop::ip1, MSD_highKVSF(), and eulerop::solidno.
int MSD_highKVSF (Id sn, Id fn)
Definition at line 75 of file eulkvsf_.cpp.
References ENIL, ERROR, FacFLoops, FNIL, FPTYPE, HalEdg, LNIL, LooLEdg, LooNextL, MEN_FaceSemLoop, MEN_FaceSemVertice, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowKVSF(), NAM_KVSF, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKVSF().
void MSD_lowKVSF (SPTYPE s)
Definition at line 104 of file eulkvsf_.cpp.
References assert1, DNIL, DPTYPE, ENIL, FACE, FacFaceNo, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, Gdodirect, Gdoinversion, HALFEDGE, KVSF, LNIL, LooLEdg, LooNextL, LOOP, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MVSF, NAM_KVSF, NIL, NNIL, NPTYPE, SetTrace, SHELL, SheNextD, SheSEdges, SheSFaces, SheShellNo, SheSVerts, SOLID, SolSBits, SolSShells, TraceSolid(), VerNextV, VERTEX, VerVCoord, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_highKVSF(), and MSD_lowSoftRemove().
int MSD_modifyStructKVSF (EulerOp * op)
Definition at line 199 of file eulkvsf_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKVSF (FILE * f, EulerOp * op)
Definition at line 169 of file eulkvsf_.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::solidno.
int MSD_readStructKVSF (FILE * f, EulerOp * op)
Definition at line 174 of file eulkvsf_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.