USPDesigner: C:/USPDesig/EUL/eulkemr_.cpp File Reference
C:/USPDesig/EUL/eulkemr_.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highKEMR (Id sn, Id fn, Id v1, Id v2)
void MSD_lowKEMR (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEMR (EulerOp *op)
void MSD_printStructKEMR (FILE *f, EulerOp *op)
int MSD_readStructKEMR (FILE *f, EulerOp *op)
int MSD_modifyStructKEMR (EulerOp *op)
Function Documentation
int MSD_execStructKEMR (EulerOp * op)
Definition at line 201 of file eulkemr_.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highKEMR(), and eulerop::solidno.
int MSD_highKEMR (Id sn, Id fn, Id v1, Id v2)
Definition at line 72 of file eulkemr_.cpp.
References ERROR, FNIL, FPTYPE, HalWLoop, HPTYPE, LNIL, mate, MEN_NaoArestaPonte, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEMR(), NAM_KEMR, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEMR().
void MSD_lowKEMR (HPTYPE he1, HPTYPE he2)
Definition at line 102 of file eulkemr_.cpp.
References assert1, DPTYPE, EDGE, ENIL, EPTYPE, FacFaceNo, FacFShell, findes(), Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEMR, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEKR, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowNewElement(), NAM_KEMR, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VerVEdge, and VerVertexNo.
Referenced by MSD_highKEMR(), MSD_lowCleanSolid(), MSD_lowCut(), MSD_lowEdgeRemove(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), and MSD_lowSetOpMakeRing().
int MSD_modifyStructKEMR (EulerOp * op)
Definition at line 250 of file eulkemr_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKEMR (FILE * f, EulerOp * op)
Definition at line 212 of file eulkemr_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
int MSD_readStructKEMR (FILE * f, EulerOp * op)
Definition at line 225 of file eulkemr_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.