USPDesigner: C:/USPDesig/EUL/eulkev__.cpp File Reference
C:/USPDesig/EUL/eulkev__.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highKEV (Id sn, Id fn, Id v1, Id v2)
int MSD_highJVKE (Id sn, Id v1, Id v2, Id f)
int MSD_highJEKV (Id sn, Id v1, Id v2)
int MSD_highKEV2 (Id sn, Id v1, Id v2, Id f1, Id f2)
void MSD_lowKEV (HPTYPE he1, HPTYPE he2)
int MSD_execStructKEV (EulerOp *op)
void MSD_printStructKEV (FILE *f, EulerOp *op)
int MSD_readStructKEV (FILE *f, EulerOp *op)
int MSD_modifyStructKEV (EulerOp *op)
Function Documentation
int MSD_execStructKEV (EulerOp * op)
Definition at line 375 of file eulkev__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highKEV2(), and eulerop::solidno.
int MSD_highJEKV (Id sn, Id v1, Id v2)
Definition at line 183 of file eulkev__.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, ERROR, FPTYPE, HalNxt, HalPrv, HPTYPE, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getSolid(), MSD_lowKEV(), NAM_JEKV, SNIL, SPTYPE, and SUCCESS.
int MSD_highJVKE (Id sn, Id v1, Id v2, Id f)
Definition at line 135 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HalNxt, HPTYPE, LNIL, mate, MEN_ArestaCircular, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEV(), NAM_JVKE, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEV (Id sn, Id fn, Id v1, Id v2)
Definition at line 76 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HalNxt, HalWLoop, HPTYPE, LNIL, MEN_NaoArestaPonte, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoVerticeTerminal, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowKEV(), NAM_KEV, SNIL, SPTYPE, and SUCCESS.
int MSD_highKEV2 (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 236 of file eulkev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowKEV(), NAM_KEV2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructKEV().
void MSD_lowKEV (HPTYPE he1, HPTYPE he2)
Definition at line 267 of file eulkev__.cpp.
References assert1, DPTYPE, EDGE, ENIL, FacFaceNo, FacFShell, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEV, LooLEdg, LooLength, LooLFace, LPTYPE, mate, MEN_MSDAbortou, MEV, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowDelElement(), MSD_lowDelHE(), MSD_lowKEV(), MSD_lowMEV(), NAM_KEV, NIL, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by EdgeAttached_vertexfase1(), edv1(), edv2(), edv4(), MSD_highJEKV(), MSD_highJVKE(), MSD_highKEV(), MSD_highKEV2(), MSD_lowCleanSolid(), MSD_lowEdgeRemove(), MSD_lowFaceRemove(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), and MSD_lowTouchWire().
int MSD_modifyStructKEV (EulerOp * op)
Definition at line 426 of file eulkev__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructKEV (FILE * f, EulerOp * op)
Definition at line 387 of file eulkev__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
int MSD_readStructKEV (FILE * f, EulerOp * op)
Definition at line 401 of file eulkev__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.