USPDesigner: C:/USPDesig/EUL/eulmev__.cpp File Reference
C:/USPDesig/EUL/eulmev__.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highMEV (Id sn, Id fn, Id v1, Id v2, real x, real y, real z)
int MSD_highSEMV (Id sn, Id v1, Id v2, Id v3, real x, real y, real z)
int MSD_highSVME (Id sn, Id v1, Id v2, Id f1, Id f2, real x, real y, real z)
int MSD_highSVME2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, real x, real y, real z)
int MSD_highSVME3 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4, real x, real y, real z)
void MSD_lowMEV (HPTYPE he1, HPTYPE he2, Id vn, real x, real y, real z)
int MSD_execStructMEV (EulerOp *op)
void MSD_printStructMEV (FILE *f, EulerOp *op)
int MSD_readStructMEV (FILE *f, EulerOp *op)
int MSD_modifyStructMEV (EulerOp *op)
Function Documentation
int MSD_execStructMEV (EulerOp * op)
Definition at line 433 of file eulmev__.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highSVME3(), and eulerop::solidno.
int MSD_highMEV (Id sn, Id fn, Id v1, Id v2, real x, real y, real z)
Definition at line 80 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEV(), NAM_MEV, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeArc(), MSD_lowMakeCube(), MSD_lowMakeCube0(), and MSD_lowMakePolygon().
int MSD_highSEMV (Id sn, Id v1, Id v2, Id v3, real x, real y, real z)
Definition at line 125 of file eulmev__.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, ERROR, FPTYPE, HalNxt, HPTYPE, mate, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getSolid(), MSD_lowMEV(), NAM_SEMV, SNIL, SPTYPE, and SUCCESS.
int MSD_highSVME (Id sn, Id v1, Id v2, Id f1, Id f2, real x, real y, real z)
Definition at line 181 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME, SNIL, SPTYPE, and SUCCESS.
int MSD_highSVME2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, real x, real y, real z)
Definition at line 238 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME2, SNIL, SPTYPE, and SUCCESS.
int MSD_highSVME3 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4, real x, real y, real z)
Definition at line 296 of file eulmev__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaF, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEV(), NAM_SVME3, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEV().
void MSD_lowMEV (HPTYPE he1, HPTYPE he2, Id vn, real x, real y, real z)
Definition at line 346 of file eulmev__.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FacFaceNo, FacFShell, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KEV, LooLFace, mate, MEN_MSDAbortou, MEV, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowNewElement(), NAM_MEV, NIL, NPTYPE, PLUS, SetTrace, SheSSolids, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_highMEV(), MSD_highSEMV(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_lowInsertNullEdges(), MSD_lowKEF(), MSD_lowKEV(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), and MSD_lowSplitGenerate().
int MSD_modifyStructMEV (EulerOp * op)
Definition at line 504 of file eulmev__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMEV (FILE * f, EulerOp * op)
Definition at line 454 of file eulmev__.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, and eulerop::solidno.
int MSD_readStructMEV (FILE * f, EulerOp * op)
Definition at line 477 of file eulmev__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.