USPDesigner: C:/USPDesig/EUL/eulmfkrh.cpp File Reference
C:/USPDesig/EUL/eulmfkrh.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highMFKRH (Id sn, Id f1, Id f2)
int MSD_highMFKRH2 (Id sn, Id f1, Id f2, Id v1, Id v2)
FPTYPE MSD_lowMFKRH (FPTYPE f, LPTYPE l, Id fn)
int MSD_execStructMFKRH (EulerOp *op)
void MSD_printStructMFKRH (FILE *f, EulerOp *op)
int MSD_readStructMFKRH (FILE *f, EulerOp *op)
int MSD_modifyStructMFKRH (EulerOp *op)
Function Documentation
int MSD_execStructMFKRH (EulerOp * op)
Definition at line 191 of file eulmfkrh.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_highMFKRH2(), and eulerop::solidno.
int MSD_highMFKRH (Id sn, Id f1, Id f2)
Definition at line 71 of file eulmfkrh.cpp.
References ERROR, FacFLoops, FacFLOut, FNIL, FPTYPE, LooNextL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowMFKRH(), NAM_MFKRH, SNIL, SPTYPE, and SUCCESS.
int MSD_highMFKRH2 (Id sn, Id f1, Id f2, Id v1, Id v2)
Definition at line 113 of file eulmfkrh.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMFKRH(), NAM_MFKRH2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMFKRH().
FPTYPE MSD_lowMFKRH (FPTYPE f, LPTYPE l, Id fn)
Definition at line 139 of file eulmfkrh.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KFMRH, LNIL, LooLEdg, LooLFace, LooNextL, LOOP, MEN_MSDAbortou, MFKRH, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowNewElement(), NAM_MFKRH, NPTYPE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by MSD_highMFKRH(), MSD_highMFKRH2(), MSD_lowEdgeRemove(), and MSD_lowSetOpFinish().
int MSD_modifyStructMFKRH (EulerOp * op)
Definition at line 242 of file eulmfkrh.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMFKRH (FILE * f, EulerOp * op)
Definition at line 203 of file eulmfkrh.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, and eulerop::solidno.
int MSD_readStructMFKRH (FILE * f, EulerOp * op)
Definition at line 217 of file eulmfkrh.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.