USPDesigner: C:/USPDesig/EUL/eulmsfkr.cpp File Reference
C:/USPDesig/EUL/eulmsfkr.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highMSFKR (Id sn, Id ff, Id fn, Id dn)
int MSD_highMSFKR2 (Id sn, Id ff, Id fn, Id dn, Id v1, Id v2)
FPTYPE MSD_lowMSFKR (LPTYPE l, Id fn, Id dn)
int MSD_execStructMSFKR (EulerOp *op)
void MSD_printStructMSFKR (FILE *f, EulerOp *op)
int MSD_readStructMSFKR (FILE *f, EulerOp *op)
int MSD_modifyStructMSFKR (EulerOp *op)
void markface (FPTYPE f, DPTYPE d)
void redo (DPTYPE shell, DPTYPE oldshell)
int sfindv (DPTYPE d, VPTYPE v)
int sfinde (DPTYPE d, EPTYPE e)
Function Documentation
void markface (FPTYPE f, DPTYPE d)
Definition at line 280 of file eulmsfkr.cpp.
References AllLoopsFace, FacFShell, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, markface(), and mate.
Referenced by markface(), and MSD_lowMSFKR().
int MSD_execStructMSFKR (EulerOp * op)
Definition at line 218 of file eulmsfkr.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highMSFKR2(), eulerop::solidno, and SUCCESS.
int MSD_highMSFKR (Id sn, Id ff, Id fn, Id dn)
Definition at line 71 of file eulmsfkr.cpp.
References ERROR, FacFLoops, FacFLOut, FNIL, FPTYPE, LooNextL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowMSFKR(), NAM_MSFKR, SNIL, SPTYPE, and SUCCESS.
int MSD_highMSFKR2 (Id sn, Id ff, Id fn, Id dn, Id v1, Id v2)
Definition at line 114 of file eulmsfkr.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getSolid(), MSD_lowMSFKR(), NAM_MSFKR2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMSFKR().
FPTYPE MSD_lowMSFKR (LPTYPE l, Id fn, Id dn)
Definition at line 140 of file eulmsfkr.cpp.
References assert1, DPTYPE, FACE, FacFaceNo, FacFLoops, FacFLOut, FacFShell, FacNextF, FNIL, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, KSFMR, LNIL, LooLEdg, LooLFace, LooNextL, LOOP, markface(), MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowListSolid(), MSD_lowNewElement(), MSFKR, NAM_MSFKR, NPTYPE, redo(), SetTrace, SHELL, SheSFaces, SheShellNo, SheSSolids, SPTYPE, trace, TraceSolid(), and VerVertexNo.
Referenced by MSD_highMSFKR(), MSD_highMSFKR2(), MSD_lowSetOpFinish(), and MSD_lowSplitFinish().
int MSD_modifyStructMSFKR (EulerOp * op)
Definition at line 271 of file eulmsfkr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMSFKR (FILE * f, EulerOp * op)
Definition at line 232 of file eulmsfkr.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
int MSD_readStructMSFKR (FILE * f, EulerOp * op)
Definition at line 247 of file eulmsfkr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.
void redo (DPTYPE shell, DPTYPE oldshell)
Definition at line 302 of file eulmsfkr.cpp.
References AllFacesShell, AllLoopsFace, EDGE, EdgHe1, ENIL, FPTYPE, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowAddList(), MSD_lowDelList(), NPTYPE, VERTEX, and VerVEdge.
Referenced by MSD_lowMSFKR().
int sfinde (DPTYPE d, EPTYPE e)
Definition at line 353 of file eulmsfkr.cpp.
References AllEdgesShell, EPTYPE, FALSE, and TRUE.
int sfindv (DPTYPE d, VPTYPE v)
Definition at line 339 of file eulmsfkr.cpp.
References AllVerticesShell, FALSE, TRUE, and VPTYPE.