USPDesigner: C:/USPDesig/EUL/eulmekr_.cpp File Reference
C:/USPDesig/EUL/eulmekr_.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highMEKR (Id sn, Id fn, Id v1, Id v2)
int MSD_highMEKR2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3)
void MSD_lowMEKR (HPTYPE he1, HPTYPE he2)
int MSD_execStructMEKR (EulerOp *op)
void MSD_printStructMEKR (FILE *f, EulerOp *op)
int MSD_readStructMEKR (FILE *f, EulerOp *op)
int MSD_modifyStructMEKR (EulerOp *op)
Function Documentation
int MSD_execStructMEKR (EulerOp * op)
Definition at line 263 of file eulmekr_.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, MSD_highMEKR2(), and eulerop::solidno.
int MSD_highMEKR (Id sn, Id fn, Id v1, Id v2)
Definition at line 71 of file eulmekr_.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MEN_VerticesEmLoopsDistintos, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEKR(), NAM_MEKR, SNIL, SPTYPE, and SUCCESS.
int MSD_highMEKR2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3)
Definition at line 128 of file eulmekr_.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEKR(), NAM_MEKR2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEKR().
void MSD_lowMEKR (HPTYPE he1, HPTYPE he2)
Definition at line 171 of file eulmekr_.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FacFaceNo, FacFLOut, FacFShell, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, KEMR, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEKR, MEN_MSDAbortou, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowDelElement(), MSD_lowNewElement(), NAM_MEKR2, NPTYPE, PLUS, RMOVE, SetTrace, SheSSolids, SPTYPE, TraceSolid(), TRUE, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by MSD_highMEKR(), MSD_highMEKR2(), MSD_lowCleanSolid(), MSD_lowFaceRemove(), MSD_lowJoin(), MSD_lowLoopGlue(), and MSD_lowSetOpJoin().
int MSD_modifyStructMEKR (EulerOp * op)
Definition at line 322 of file eulmekr_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMEKR (FILE * f, EulerOp * op)
Definition at line 278 of file eulmekr_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, and eulerop::solidno.
int MSD_readStructMEKR (FILE * f, EulerOp * op)
Definition at line 296 of file eulmekr_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.