USPDesigner: C:/USPDesig/EUL/eulmvsf_.cpp File Reference
C:/USPDesig/EUL/eulmvsf_.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
SPTYPE MSD_highMVSF (Id fn, Id vn, Id dn, real xx, real yy, real zz)
SPTYPE MSD_lowMVSF (Id sn, Id fn, Id vn, Id dn, real xx, real yy, real zz)
int MSD_execStructMVSF (EulerOp *op)
void MSD_printStructMVSF (FILE *f, EulerOp *op)
int MSD_readStructMVSF (FILE *f, EulerOp *op)
int MSD_modifyStructMVSF (EulerOp *op)
Function Documentation
int MSD_execStructMVSF (EulerOp * op)
Definition at line 138 of file eulmvsf_.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, MSD_lowMVSF(), eulerop::solidno, SolSBits, SPTYPE, and SUCCESS.
SPTYPE MSD_highMVSF (Id fn, Id vn, Id dn, real xx, real yy, real zz)
Definition at line 77 of file eulmvsf_.cpp.
References MSD_getMaxSolidId(), and MSD_lowMVSF().
SPTYPE MSD_lowMVSF (Id sn, Id fn, Id vn, Id dn, real xx, real yy, real zz)
Definition at line 82 of file eulmvsf_.cpp.
References DPTYPE, ENIL, FACE, FacFaceNo, FacFLOut, FPTYPE, Gdodirect, Gdoinversion, HalEdg, HALFEDGE, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KVSF, LooLEdg, LooLength, LOOP, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowNewElement(), MSD_setEulCoef(), MVSF, NAM_MVSF, NNIL, NPTYPE, SetTrace, SHELL, SheShellNo, SOLID, SolSolidNo, SPTYPE, TraceSolid(), VERTEX, VerVCoord, VerVertexNo, and VPTYPE.
Referenced by MSD_execStructMVSF(), MSD_highMVSF(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakePolygon(), and MSD_lowMakeSphere().
int MSD_modifyStructMVSF (EulerOp * op)
Definition at line 202 of file eulmvsf_.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMVSF (FILE * f, EulerOp * op)
Definition at line 159 of file eulmvsf_.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
int MSD_readStructMVSF (FILE * f, EulerOp * op)
Definition at line 177 of file eulmvsf_.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.