USPDesigner: C:/USPDesig/EUL/eulmodif.cpp File Reference
C:/USPDesig/EUL/eulmodif.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "curvgeom.h"
#include "eulerops.h"
#include "mancommd.h"
Classes
struct TransTable
struct eulercod
Typedefs
typedef struct TransTable TRANSTABLE
typedef struct eulercod EuCode
Functions
SPTYPE MSD_lowModifyEulerOp (EulerOp *op)
int MSD_modifyStructError (EulerOp *op)
void MSD_lowIniciaTranslatorTable (void)
int MSD_lowCheckTranslatorTable (int elemno, int code)
void MSD_lowSetTranslatorTable (int elemnoold, int elemno, int code)
Variables
static TRANSTABLE STable [100]
static TRANSTABLE GTable [100]
static TRANSTABLE ATable [100]
static int STableMax
static int GTableMax
static int ATableMax
EuCode ematrix []
Typedef Documentation
typedef struct eulercod EuCode
Definition at line 65 of file eulmodif.cpp.
typedef struct TransTable TRANSTABLE
Definition at line 54 of file eulmodif.cpp.
Function Documentation
int MSD_lowCheckTranslatorTable (int elemno, int code)
Definition at line 113 of file eulmodif.cpp.
References ATableMax, AXIS, GROUP, GTableMax, MSD_getMaxAxisId(), MSD_getMaxGroupId(), MSD_getMaxSolidId(), TransTable::NewNo, TransTable::OldNo, SOLID, and STableMax.
Referenced by MSD_modifyStructAssociate(), MSD_modifyStructColor(), MSD_modifyStructCreateGroup(), MSD_modifyStructCrtAxsRotation(), MSD_modifyStructCrtAxsTranslation(), MSD_modifyStructDetach(), MSD_modifyStructHardRemove(), MSD_modifyStructKEF(), MSD_modifyStructKEMR(), MSD_modifyStructKEV(), MSD_modifyStructKFMRH(), MSD_modifyStructKSFMR(), MSD_modifyStructKVSF(), MSD_modifyStructMEF(), MSD_modifyStructMEKR(), MSD_modifyStructMEV(), MSD_modifyStructMFKRH(), MSD_modifyStructModifyIds(), MSD_modifyStructMoveAxis(), MSD_modifyStructMSFKR(), MSD_modifyStructMVSF(), MSD_modifyStructName(), MSD_modifyStructNewVertexLocation(), MSD_modifyStructRemoveAxis(), MSD_modifyStructRemoveOneGroup(), MSD_modifyStructRevert(), MSD_modifyStructRingMove(), MSD_modifyStructRotate(), MSD_modifyStructRotateAxis(), MSD_modifyStructScale(), MSD_modifyStructSetGroupCurrent(), MSD_modifyStructTransformation(), and MSD_modifyStructTranslate().
void MSD_lowIniciaTranslatorTable (void)
Definition at line 108 of file eulmodif.cpp.
References ATableMax, GTableMax, and STableMax.
Referenced by MSD_lowCopyGroup().
SPTYPE MSD_lowModifyEulerOp (EulerOp * op)
Definition at line 81 of file eulmodif.cpp.
References eulercod::ecode, eulercod::eop, ERROR, MEN_ParametrosIncorretos, eulercod::meop, MSD_getSolid(), NAM_ModifyEulerOp, eulerop::opcode, SNIL, and eulerop::solidno.
Referenced by MSD_lowCopyGroup().
void MSD_lowSetTranslatorTable (int elemnoold, int elemno, int code)
Definition at line 163 of file eulmodif.cpp.
References ATableMax, AXIS, GROUP, GTableMax, TransTable::NewNo, TransTable::OldNo, SOLID, and STableMax.
Referenced by MSD_lowCopyGroup().
int MSD_modifyStructError (EulerOp * op)
Definition at line 100 of file eulmodif.cpp.
References ERROR, MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_ModifyEulerOp.
Variable Documentation
TRANSTABLE ATable[100] [static]
Definition at line 62 of file eulmodif.cpp.
int ATableMax [static]
Definition at line 63 of file eulmodif.cpp.
Referenced by MSD_lowCheckTranslatorTable(), MSD_lowIniciaTranslatorTable(), and MSD_lowSetTranslatorTable().
EuCode ematrix[]
Definition at line 67 of file eulerops.cpp.
TRANSTABLE GTable[100] [static]
Definition at line 62 of file eulmodif.cpp.
int GTableMax [static]
Definition at line 63 of file eulmodif.cpp.
Referenced by MSD_lowCheckTranslatorTable(), MSD_lowIniciaTranslatorTable(), and MSD_lowSetTranslatorTable().
TRANSTABLE STable[100] [static]
Definition at line 62 of file eulmodif.cpp.
int STableMax [static]
Definition at line 63 of file eulmodif.cpp.
Referenced by MSD_lowCheckTranslatorTable(), MSD_lowIniciaTranslatorTable(), and MSD_lowSetTranslatorTable().