USPDesigner: C:/USPDesig/EUL/eulmef__.cpp File Reference
C:/USPDesig/EUL/eulmef__.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highMEF (Id sn, Id v1, Id v2, Id f1, Id f2)
int MSD_highMEF2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4)
FPTYPE MSD_lowMEF (HPTYPE he1, HPTYPE he2, Id fn)
int MSD_execStructMEF (EulerOp *op)
void MSD_printStructMEF (FILE *f, EulerOp *op)
int MSD_readStructMEF (FILE *f, EulerOp *op)
int MSD_modifyStructMEF (EulerOp *op)
Function Documentation
int MSD_execStructMEF (EulerOp * op)
Definition at line 282 of file eulmef__.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highMEF2(), and eulerop::solidno.
int MSD_highMEF (Id sn, Id v1, Id v2, Id f1, Id f2)
Definition at line 72 of file eulmef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowMEF(), NAM_MEF, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), and MSD_lowMakePolygon().
int MSD_highMEF2 (Id sn, Id v1, Id v2, Id v3, Id v4, Id f1, Id f2, Id f3, Id f4)
Definition at line 123 of file eulmef__.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, MEN_NaoEncontrouArestaF, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getHalfedge(), MSD_getSolid(), MSD_lowMEF(), NAM_MEF2, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructMEF().
FPTYPE MSD_lowMEF (HPTYPE he1, HPTYPE he2, Id fn)
Definition at line 166 of file eulmef__.cpp.
References assert1, DPTYPE, EDGE, EdgEdgeNo, ENIL, EPTYPE, FACE, FacFaceNo, FacFLOut, FacFShell, findf(), findl(), FPTYPE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, KEF, LooLEdg, LooLength, LooLFace, LOOP, LPTYPE, mate, MEF, MEN_MSDAbortou, MINUS, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddHE(), MSD_lowNewElement(), NAM_MEF, NIL, NPTYPE, PLUS, SetTrace, SheSSolids, SPTYPE, TraceSolid(), and VerVertexNo.
Referenced by edv3(), edv4(), GenerationEdges_nvertices(), MakeEdgeConvexCorner(), MSD_highMEF(), MSD_highMEF2(), MSD_lowJoin(), MSD_lowLoopGlue(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), and MSD_lowSetOpJoin().
int MSD_modifyStructMEF (EulerOp * op)
Definition at line 343 of file eulmef__.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructMEF (FILE * f, EulerOp * op)
Definition at line 298 of file eulmef__.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, and eulerop::solidno.
int MSD_readStructMEF (FILE * f, EulerOp * op)
Definition at line 317 of file eulmef__.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.