USPDesigner: C:/USPDesig/EUL/eulnome_.cpp File Reference
C:/USPDesig/EUL/eulnome_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "genfunc_.h"
#include "curvgeom.h"
#include "mancommd.h"
Functions
int MSD_highName (Id sn, char *nome, int cod)
void MSD_lowSolidName (SPTYPE s, char *nome)
void MSD_lowGroupName (GPTYPE g, char *nome)
void MSD_lowAxisName (APTYPE a, char *nome)
int MSD_execStructName (EulerOp *op)
void MSD_printStructName (FILE *f, EulerOp *op)
int MSD_readStructName (FILE *f, EulerOp *op)
int MSD_modifyStructName (EulerOp *op)
Function Documentation
int MSD_execStructName (EulerOp * op)
Definition at line 196 of file eulnome_.cpp.
References EulerIp3, EulerIp4, EulerIp5, EulerIp6, EulerIp7, EulerIp8, EulerOpNext, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MSD_highName(), PEulerOp, and TRUE.
int MSD_highName (Id sn, char * nome, int cod)
Definition at line 75 of file eulnome_.cpp.
References ANIL, APTYPE, AXIS, ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getAxis(), MSD_getGroup(), MSD_getSolid(), MSD_lowAxisName(), MSD_lowGroupName(), MSD_lowSolidName(), NAM_Name, SNIL, SOLID, SPTYPE, and SUCCESS.
Referenced by MSD_execStructName(), MSD_highNameDifference(), MSD_highNameIntersection(), MSD_highNameMakeCone(), MSD_highNameMakeCube(), MSD_highNameMakeCylinder(), MSD_highNameMakePrism(), MSD_highNameMakePyramid(), MSD_highNameMakeRevolve(), MSD_highNameMakeSphere(), MSD_highNameMakeTorus(), MSD_highNameSplit(), MSD_highNameUnion(), and MSD_lowNameRenameSolid().
void MSD_lowAxisName (APTYPE a, char * nome)
Definition at line 168 of file eulnome_.cpp.
References AXIS, AxsAxisNo, AxsName, Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, and SNIL.
Referenced by MSD_highName(), and MSD_lowRemoveAxis().
void MSD_lowGroupName (GPTYPE g, char * nome)
Definition at line 140 of file eulnome_.cpp.
References Gdodirect, Gdoinversion, GROUP, GrpGroupNo, GrpName, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, and SNIL.
Referenced by MSD_highName(), and MSD_lowRemoveOneGroup().
void MSD_lowSolidName (SPTYPE s, char * nome)
Definition at line 111 of file eulnome_.cpp.
References Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAME, SOLID, SolName, and SolSolidNo.
Referenced by MSD_highName(), and MSD_lowSoftRemove().
int MSD_modifyStructName (EulerOp * op)
Definition at line 281 of file eulnome_.cpp.
References AXIS, GROUP, eulerop::ip1, eulerop::ip2, MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructName (FILE * f, EulerOp * op)
Definition at line 228 of file eulnome_.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, and eulerop::ip8.
int MSD_readStructName (FILE * f, EulerOp * op)
Definition at line 259 of file eulnome_.cpp.
References eulerop::CommandCount, ERROR, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.