USPDesigner: C:/USPDesig/EUL/eulprint.cpp File Reference
C:/USPDesig/EUL/eulprint.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Classes
struct eulercod
Typedefs
typedef struct eulercod EuCode
Functions
void MSD_highPrintAllOps (void)
void MSD_lowPrintEulerOp (FILE *f, EulerOp *op)
void MSD_printStructError (FILE *f, EulerOp *op)
void MSD_highPrintAllRedoOps (void)
Variables
EuCode ematrix []
Typedef Documentation
typedef struct eulercod EuCode
Definition at line 50 of file eulprint.cpp.
Function Documentation
void MSD_highPrintAllOps (void)
Definition at line 66 of file eulprint.cpp.
References EulerOpNext, EULEROPS, EuNIL, MSD_lowPrintEulerOp(), OpHead, and PEulerOp.
void MSD_highPrintAllRedoOps (void)
Definition at line 107 of file eulprint.cpp.
References EulerOpNextRedo, EULEROPSREDO, EuNIL, MSD_lowPrintEulerOp(), OpHeadRedo, and PEulerOp.
void MSD_lowPrintEulerOp (FILE * f, EulerOp * op)
Definition at line 84 of file eulprint.cpp.
References eulercod::ecode, eulercod::eop, eulerop::opcode, and eulercod::peop.
Referenced by MSD_highPrintAllOps(), MSD_highPrintAllRedoOps(), and MSD_lowSaveSolid().
void MSD_printStructError (FILE * f, EulerOp * op)
Definition at line 98 of file eulprint.cpp.
References MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_PrintEulerOp.
Variable Documentation
EuCode ematrix[]
Definition at line 67 of file eulerops.cpp.