USPDesigner: C:/USPDesig/EUL/eulscoef.cpp File Reference
C:/USPDesig/EUL/eulscoef.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
Functions
void MSD_setEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
void MSD_addEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
Function Documentation
void MSD_addEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
Definition at line 65 of file eulscoef.cpp.
References eulerco::edgen, solid::eucoef, eulerco::facen, eulerco::holen, eulerco::ringn, eulerco::shelln, and eulerco::vertexn.
Referenced by MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), and MSD_lowShellDetach().
void MSD_setEulCoef (SPTYPE s, int dn, int fn, int rn, int en, int vn, int hn)
Definition at line 47 of file eulscoef.cpp.
References eulerco::edgen, solid::eucoef, eulerco::facen, eulerco::holen, eulerco::ringn, eulerco::shelln, and eulerco::vertexn.
Referenced by MSD_lowMVSF().