USPDesigner: C:/USPDesig/EUL/eulxundo.cpp File Reference
C:/USPDesig/EUL/eulxundo.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "curvgeom.h"
#include "eulerops.h"
#include "mancommd.h"
Classes
struct eulercod
Typedefs
typedef struct eulercod EuCode
Functions
void MSD_execUndoOp (void)
void MSD_highUndoOp (void)
SPTYPE MSD_lowUndoOp (void)
SPTYPE MSD_lowApplyEulerOp (EulerOp *op, int *cont)
int MSD_execStructError (EulerOp *op)
void MSD_lowFreeUndoLog (PEulerOp EndOp)
void MSD_lowGetMatrix (EulerOp *op, matrix m)
Variables
EuCode ematrix []
Typedef Documentation
typedef struct eulercod EuCode
Definition at line 54 of file eulxundo.cpp.
Function Documentation
int MSD_execStructError (EulerOp * op)
Definition at line 139 of file eulxundo.cpp.
References ERROR, MEN_ParametrosIncorretos, MSD_lowNaoUtilizado, and NAM_ApplyEulerOp.
void MSD_execUndoOp (void)
Definition at line 70 of file eulxundo.cpp.
References MSD_highUndoOp().
void MSD_highUndoOp (void)
Definition at line 75 of file eulxundo.cpp.
References MSD_lowUndoOp().
Referenced by MSD_execUndoOp().
SPTYPE MSD_lowApplyEulerOp (EulerOp * op, int * cont)
Definition at line 119 of file eulxundo.cpp.
References eulercod::ecode, eulercod::eop, ERROR, MEN_ParametrosIncorretos, MSD_getSolid(), NAM_ApplyEulerOp, eulercod::num, eulerop::opcode, SNIL, eulerop::solidno, and eulercod::xeop.
Referenced by MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowSaveSolid(), and MSD_lowUndoOp().
void MSD_lowFreeUndoLog (PEulerOp EndOp)
Definition at line 147 of file eulxundo.cpp.
References NIL, OpCount, OpHead, and eulerop::opnext.
Referenced by MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), and MSD_lowSaveSolid().
void MSD_lowGetMatrix (EulerOp * op, matrix m)
Definition at line 167 of file eulxundo.cpp.
References EulerFp1, EulerFp2, EulerFp3, EulerFp4, EulerOpNext, and PEulerOp.
Referenced by MSD_execStructTransformation().
SPTYPE MSD_lowUndoOp (void)
Definition at line 80 of file eulxundo.cpp.
References eulerop::CommandCount, EulerOpNext, EULEROPS, EuNIL, Gdoinversion, MSD_lowApplyEulerOp(), OpCount, OpHead, SNIL, and SPTYPE.
Referenced by MSD_highUndoOp().
Variable Documentation
EuCode ematrix[]
Definition at line 67 of file eulerops.cpp.