USPDesigner: C:/USPDesig/GEN/genaxsds.cpp File Reference
C:/USPDesig/GEN/genaxsds.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
int MSD_highNameDesassociateAxisElement (char *name)
Function Documentation
int MSD_highNameDesassociateAxisElement (char * name)
Definition at line 70 of file genaxsds.cpp.
References ANIL, APTYPE, AxsType, ERROR, GNIL, GROUP, MEN_ElementoNaoEncontrado, MEN_NaoEncontrouAxisNome, MSD_lowAssociaGroupAxis(), MSD_lowAssociaSolidAxis(), MSD_lowFindAxisByName(), NAM_DesassociaAxisElemento, SNIL, and SOLID.
Referenced by MSD_execManipulateAxis().