USPDesigner: C:/USPDesig/GEN/genaxsas.cpp File Reference
C:/USPDesig/GEN/genaxsas.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
int MSD_highNameAssociateAxisElement (char *name1, char *name2)
Function Documentation
int MSD_highNameAssociateAxisElement (char * name1, char * name2)
Definition at line 70 of file genaxsas.cpp.
References ANIL, APTYPE, ERROR, GNIL, GPTYPE, MEN_ElementoNaoEncontrado, MEN_NaoEncontrouAxisNome, MSD_lowAssociaGroupAxis(), MSD_lowAssociaSolidAxis(), MSD_lowFindAxisByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NAM_AssociaAxisElemento, SNIL, and SPTYPE.
Referenced by MSD_execManipulateAxis().