USPDesigner: C:/USPDesig/GEN/gencopy_.cpp File Reference
C:/USPDesig/GEN/gencopy_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "hiegroup.h"
#include "shpshape.h"
#include "genfunc_.h"
#include "mancommd.h"
Functions
void MSD_execNameCopyElement (void)
int MSD_highNameCopyElement (char *name1, char *name2)
int MSD_highNameCopySolid (char *name1, char *name2)
int MSD_highCopySolid (int sn)
int MSD_lowCopySolid (SPTYPE s, Id sn)
Function Documentation
void MSD_execNameCopyElement (void)
Definition at line 54 of file gencopy_.cpp.
References lineins(), MSD_highNameCopyElement(), and restbuf.
int MSD_highCopySolid (int sn)
Definition at line 144 of file gencopy_.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCopySolid(), NAM_CopySolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCopySolid().
int MSD_highNameCopyElement (char * name1, char * name2)
Definition at line 69 of file gencopy_.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameCopyGroup(), and MSD_highNameCopySolid().
Referenced by MSD_execNameCopyElement().
int MSD_highNameCopySolid (char * name1, char * name2)
Definition at line 100 of file gencopy_.cpp.
References ERROR, MEN_NaoEncontrouSolido, MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highCopySolid(), NAM_CopySolid, SolName, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCopyElement(), MSD_lowNameNCopySolidSpiral(), and MSD_lowNameNCopySolidTranslate().
int MSD_lowCopySolid (SPTYPE s, Id sn)
Definition at line 158 of file gencopy_.cpp.
References EulerOpNext, EULEROPS, EulerSolidNo, FALSE, Gdoinversion, MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSoftRemove(), OpHead, PEulerOp, SNIL, SUCCESS, and TRUE.
Referenced by MSD_highCopySolid().