USPDesigner: C:/USPDesig/GEN/gendelet.cpp File Reference
C:/USPDesig/GEN/gendelet.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "hiegroup.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "mancommd.h"
Functions
void MSD_execNameDeleteElement (void)
int MSD_highNameDeleteElement (char *name)
Function Documentation
void MSD_execNameDeleteElement (void)
Definition at line 53 of file gendelet.cpp.
References lineins(), MSD_highNameDeleteElement(), and restbuf.
int MSD_highNameDeleteElement (char * name)
Definition at line 68 of file gendelet.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRemoveAxis(), MSD_highNameRemoveCamera(), MSD_highNameRemoveGroup(), and MSD_highNameSoftRemove().
Referenced by MSD_execNameDeleteElement().