USPDesigner: C:/USPDesig/GEN/gendir__.cpp File Reference
C:/USPDesig/GEN/gendir__.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <dir.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "shpshape.h"
#include "genfunc_.h"
#include "mancommd.h"
Defines
#define NORMAL 0x16
Functions
void MSD_execDir (void)
int MSD_lowDir (char *name)
void MSD_lowDisplayFiles (char *nam)
Define Documentation
#define NORMAL 0x16
Definition at line 55 of file gendir__.cpp.
Referenced by MSD_lowDir().
Function Documentation
void MSD_execDir (void)
Definition at line 57 of file gendir__.cpp.
References lineins(), MSD_lowDir(), and restbuf.
int MSD_lowDir (char * name)
Definition at line 72 of file gendir__.cpp.
References MSD_lowDisplayFiles(), NORMAL, and TRUE.
Referenced by MSD_execDir().
void MSD_lowDisplayFiles (char * nam)
Definition at line 87 of file gendir__.cpp.
Referenced by MSD_lowDir().