USPDesigner: C:/USPDesig/INC/genfunc_.h File Reference
C:/USPDesig/INC/genfunc_.h File Reference
#include <stdio.h>
Typedefs
typedef double real
typedef int Id
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
Functions
void MSD_execNameAssociateAxisElement (void)
int MSD_highNameAssociateAxisElement (char *name1, char *name2)
void MSD_execNameDesassociateAxisElement (void)
int MSD_highNameDesassociateAxisElement (char *name)
void MSD_execNameCopyElement (void)
int MSD_highNameCopyElement (char *name1, char *name2)
void MSD_execNameCopySolid (void)
int MSD_highNameCopySolid (char *name1, char *name2)
void MSD_execCopySolid (void)
int MSD_highCopySolid (int sn)
int MSD_lowCopySolid (SPTYPE s, Id sn)
void MSD_execNameDeleteElement (void)
int MSD_highNameDeleteElement (char *name)
void MSD_execDir (void)
int MSD_lowDir (char *name)
void MSD_lowDisplayFiles (char *nam)
void MSD_execNameListFaceAdjacency (void)
int MSD_highNameListFaceAdjacency (char *name, char *fname)
int MSD_lowListFaceAdjacency (SPTYPE optr, char *fname)
char MSD_getTypeByName (char *nam)
int MSD_getNumberOfSolid (void)
char ** MSD_putSolidNameInList (char **list)
void MSD_execNameAssociateGroupElement (void)
int MSD_highNameAssociateGroupElement (char *name1, char *name2)
void MSD_execNameDesassociateGroupElement (void)
int MSD_highNameDesassociateGroupElement (char *name)
void MSD_execListElement (void)
void MSD_lowListAllSolidName (void)
void MSD_lowListNumberOfElements (void)
void MSD_execNameLoadSolid (void)
int MSD_highNameLoadSolid (char *oname, char *fname)
void MSD_execLoadSolid (void)
int MSD_lowLoadSolid (Id sn, char *fname)
int MSD_highLoadSolid (char *fname)
void MSD_execNameNCopySolid (void)
int MSD_highNameNCopySolidTranslate (char *name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, int n)
int MSD_lowNameNCopySolidTranslate (char *name, vector omove, vector dmove, int n)
int MSD_highNameNCopySolidSpiral (char *name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, real dth, real dmv, int n)
int MSD_lowNameNCopySolidSpiral (char *name, vector cpos, vector vect, real dth, real dmv, int n)
void MSD_lowRequestNewName (char *name)
void MSD_execNameRenameElement (void)
int MSD_highNameRenameElement (char *name1, char *name2)
void MSD_execNameRenameSolid (void)
int MSD_highNameRenameSolid (char *name1, char *name2)
int MSD_lowNameRenameSolid (SPTYPE sptr, char *name2)
void MSD_execNameRotateElement (void)
int MSD_highNameRotateElement (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
void MSD_execNameSaveSolid (void)
int MSD_highNameSaveSolid (char *oname, char *fname)
void MSD_execSaveSolid (void)
int MSD_highSaveSolid (int sn, char *fname)
int MSD_lowSaveSolid (SPTYPE s, char *fname)
void MSD_execShow (void)
EPTYPE MSD_lowShowFindEdge (SPTYPE s, Id en)
VPTYPE MSD_lowShowFindVertex (SPTYPE s, Id vn)
void MSD_lowListAllSolid (void)
void MSD_lowListAllVertex (SPTYPE optr)
void MSD_lowListAllEdge (SPTYPE optr)
void MSD_lowListAllFace (SPTYPE optr)
void MSD_lowShowListSolid (SPTYPE optr)
void MSD_lowShowListVertex (VPTYPE vptr)
void MSD_lowShowListEdge (EPTYPE eptr)
void MSD_lowShowListFace (FPTYPE fptr)
void MSD_execNameTranslateElement (void)
int MSD_highNameTranslateElement (char *name, real tx, real ty, real tz)
void MSD_execWait (void)
void MSD_highWait (int waitsec)
void MSD_execTime (void)
Typedef Documentation
typedef struct edge ETYPE
Definition at line 73 of file genfunc_.h.
typedef struct face FTYPE
Definition at line 65 of file genfunc_.h.
typedef struct halfedge HTYPE
Definition at line 77 of file genfunc_.h.
typedef int Id
Definition at line 53 of file genfunc_.h.
typedef struct loop LTYPE
Definition at line 69 of file genfunc_.h.
typedef double real
Definition at line 49 of file genfunc_.h.
typedef struct solid STYPE
Definition at line 61 of file genfunc_.h.
typedef real vector[4]
Definition at line 57 of file genfunc_.h.
typedef struct vertex VTYPE
Definition at line 81 of file genfunc_.h.
Function Documentation
void MSD_execCopySolid (void)
void MSD_execDir (void)
Definition at line 57 of file gendir__.cpp.
References lineins(), MSD_lowDir(), and restbuf.
void MSD_execListElement (void)
Definition at line 51 of file genlist_.cpp.
References lineins(), MSD_lowListAllAxisName(), MSD_lowListAllCameraName(), MSD_lowListAllGroupName(), MSD_lowListAllSolidName(), MSD_lowListNumberOfElements(), and optin().
void MSD_execLoadSolid (void)
void MSD_execNameAssociateAxisElement (void)
void MSD_execNameAssociateGroupElement (void)
void MSD_execNameCopyElement (void)
Definition at line 54 of file gencopy_.cpp.
References lineins(), MSD_highNameCopyElement(), and restbuf.
void MSD_execNameCopySolid (void)
void MSD_execNameDeleteElement (void)
Definition at line 53 of file gendelet.cpp.
References lineins(), MSD_highNameDeleteElement(), and restbuf.
void MSD_execNameDesassociateAxisElement (void)
void MSD_execNameDesassociateGroupElement (void)
void MSD_execNameListFaceAdjacency (void)
void MSD_execNameLoadSolid (void)
Definition at line 68 of file genload_.cpp.
References lineins(), MSD_highNameLoadSolid(), and restbuf.
void MSD_execNameNCopySolid (void)
Definition at line 51 of file genncopy.cpp.
References lineins(), MSD_highNameNCopySolidSpiral(), MSD_highNameNCopySolidTranslate(), optin(), and restbuf.
void MSD_execNameRenameElement (void)
Definition at line 54 of file genrenam.cpp.
References lineins(), MSD_highNameRenameElement(), and restbuf.
void MSD_execNameRenameSolid (void)
void MSD_execNameRotateElement (void)
Definition at line 53 of file genrotat.cpp.
References lineins(), MSD_highNameRotateElement(), and restbuf.
void MSD_execNameSaveSolid (void)
Definition at line 54 of file gensave_.cpp.
References lineins(), MSD_highNameSaveSolid(), and restbuf.
void MSD_execNameTranslateElement (void)
Definition at line 53 of file gentrans.cpp.
References lineins(), MSD_highNameTranslateElement(), and restbuf.
void MSD_execSaveSolid (void)
void MSD_execShow (void)
Definition at line 51 of file genshow_.cpp.
References lineins(), MSD_getFace(), MSD_lowFindAxisByName(), MSD_lowFindCameraByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), MSD_lowListAllAxis(), MSD_lowListAllCamera(), MSD_lowListAllEdge(), MSD_lowListAllFace(), MSD_lowListAllGroup(), MSD_lowListAllSolid(), MSD_lowListAllVertex(), MSD_lowListAxisName(), MSD_lowListGroup(), MSD_lowNameListCameraName(), MSD_lowShowFindEdge(), MSD_lowShowFindVertex(), MSD_lowShowListEdge(), MSD_lowShowListFace(), MSD_lowShowListSolid(), MSD_lowShowListVertex(), optin(), restbuf, SNIL, and SPTYPE.
void MSD_execTime (void)
Definition at line 76 of file genwait_.cpp.
void MSD_execWait (void)
Definition at line 47 of file genwait_.cpp.
References lineins(), MSD_highWait(), and restbuf.
int MSD_getNumberOfSolid (void)
Definition at line 72 of file genfindn.cpp.
References AllSolids, and SPTYPE.
char MSD_getTypeByName (char * nam)
Definition at line 51 of file genfindn.cpp.
References ANIL, FALSE, GNIL, MSD_lowFindAxisByName(), MSD_lowFindCameraByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NIL, and SNIL.
Referenced by MSD_highNameColor(), MSD_highNameCopyElement(), MSD_highNameDeleteElement(), MSD_highNameRenameElement(), MSD_highNameRotateElement(), MSD_highNameSetDisplay(), MSD_highNameTranslateElement(), MSD_resetElement(), and MSD_selectElement().
int MSD_highCopySolid (int sn)
Definition at line 144 of file gencopy_.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCopySolid(), NAM_CopySolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCopySolid().
int MSD_highLoadSolid (char * fname)
Definition at line 120 of file genload_.cpp.
References MSD_getMaxSolidId(), and MSD_lowLoadSolid().
Referenced by MSD_highNameLoadSolid().
int MSD_highNameAssociateAxisElement (char * name1, char * name2)
Definition at line 70 of file genaxsas.cpp.
References ANIL, APTYPE, ERROR, GNIL, GPTYPE, MEN_ElementoNaoEncontrado, MEN_NaoEncontrouAxisNome, MSD_lowAssociaGroupAxis(), MSD_lowAssociaSolidAxis(), MSD_lowFindAxisByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NAM_AssociaAxisElemento, SNIL, and SPTYPE.
Referenced by MSD_execManipulateAxis().
int MSD_highNameAssociateGroupElement (char * name1, char * name2)
Definition at line 71 of file gengrpas.cpp.
References ERROR, GNIL, GPTYPE, MEN_ElementoNaoEncontrado, MEN_NaoEncontrouGroupNome, MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NAM_AssociaGrupoElemento, SNIL, and SPTYPE.
Referenced by MSD_execManipulateGroup().
int MSD_highNameCopyElement (char * name1, char * name2)
Definition at line 69 of file gencopy_.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameCopyGroup(), and MSD_highNameCopySolid().
Referenced by MSD_execNameCopyElement().
int MSD_highNameCopySolid (char * name1, char * name2)
Definition at line 100 of file gencopy_.cpp.
References ERROR, MEN_NaoEncontrouSolido, MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highCopySolid(), NAM_CopySolid, SolName, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCopyElement(), MSD_lowNameNCopySolidSpiral(), and MSD_lowNameNCopySolidTranslate().
int MSD_highNameDeleteElement (char * name)
Definition at line 68 of file gendelet.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRemoveAxis(), MSD_highNameRemoveCamera(), MSD_highNameRemoveGroup(), and MSD_highNameSoftRemove().
Referenced by MSD_execNameDeleteElement().
int MSD_highNameDesassociateAxisElement (char * name)
Definition at line 70 of file genaxsds.cpp.
References ANIL, APTYPE, AxsType, ERROR, GNIL, GROUP, MEN_ElementoNaoEncontrado, MEN_NaoEncontrouAxisNome, MSD_lowAssociaGroupAxis(), MSD_lowAssociaSolidAxis(), MSD_lowFindAxisByName(), NAM_DesassociaAxisElemento, SNIL, and SOLID.
Referenced by MSD_execManipulateAxis().
int MSD_highNameDesassociateGroupElement (char * name)
Definition at line 70 of file gengrpds.cpp.
References ERROR, GNIL, GPTYPE, MEN_ElementoNaoEncontrado, MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NAM_DesassociaGrupoElemento, SNIL, and SPTYPE.
Referenced by MSD_execManipulateGroup().
int MSD_highNameListFaceAdjacency (char * name, char * fname)
Definition at line 68 of file genfadjr.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_lowFindSolidByName(), MSD_lowListFaceAdjacency(), NAM_ListFaceAdjacency, SNIL, and SPTYPE.
int MSD_highNameLoadSolid (char * oname, char * fname)
Definition at line 83 of file genload_.cpp.
References ERROR, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highLoadSolid(), SolName, SPTYPE, and SUCCESS.
Referenced by MSD_execNameLoadSolid().
int MSD_highNameNCopySolidSpiral (char * name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, real dth, real dmv, int n)
Definition at line 120 of file genncopy.cpp.
References makevec(), MSD_lowNameNCopySolidSpiral(), and normalize().
Referenced by MSD_execNameNCopySolid().
int MSD_highNameNCopySolidTranslate (char * name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, int n)
Definition at line 91 of file genncopy.cpp.
References makevec(), and MSD_lowNameNCopySolidTranslate().
Referenced by MSD_execNameNCopySolid().
int MSD_highNameRenameElement (char * name1, char * name2)
Definition at line 69 of file genrenam.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRenameAxis(), MSD_highNameRenameCamera(), MSD_highNameRenameGroup(), and MSD_highNameRenameSolid().
Referenced by MSD_execNameRenameElement().
int MSD_highNameRenameSolid (char * name1, char * name2)
Definition at line 106 of file genrenam.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_lowFindSolidByName(), MSD_lowNameRenameSolid(), NAM_RenameSolido, SNIL, and SPTYPE.
Referenced by MSD_highNameRenameElement(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
int MSD_highNameRotateElement (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 70 of file genrotat.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRotateAxis(), MSD_highNameRotateGroup(), and MSD_highNameRotateSolidAxis().
Referenced by MSD_execNameRotateElement().
int MSD_highNameSaveSolid (char * oname, char * fname)
Definition at line 69 of file gensave_.cpp.
References FALSE, MEN_NaoEncontrouSolidNome, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highSaveSolid(), NAM_SaveSolido, SolName, and TRUE.
Referenced by MSD_execNameSaveSolid().
int MSD_highNameTranslateElement (char * name, real tx, real ty, real tz)
Definition at line 69 of file gentrans.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameMoveAxis(), MSD_highNameMoveGroup(), and MSD_highNameTranslate().
Referenced by MSD_execNameTranslateElement().
int MSD_highSaveSolid (int sn, char * fname)
Definition at line 105 of file gensave_.cpp.
References FALSE, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSaveSolid(), NAM_SaveSolido, SNIL, and SPTYPE.
Referenced by MSD_highNameSaveSolid().
void MSD_highWait (int waitsec)
Definition at line 62 of file genwait_.cpp.
Referenced by MSD_execWait().
int MSD_lowCopySolid (SPTYPE s, Id sn)
Definition at line 158 of file gencopy_.cpp.
References EulerOpNext, EULEROPS, EulerSolidNo, FALSE, Gdoinversion, MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSoftRemove(), OpHead, PEulerOp, SNIL, SUCCESS, and TRUE.
Referenced by MSD_highCopySolid().
int MSD_lowDir (char * name)
Definition at line 72 of file gendir__.cpp.
References MSD_lowDisplayFiles(), NORMAL, and TRUE.
Referenced by MSD_execDir().
void MSD_lowDisplayFiles (char * nam)
Definition at line 87 of file gendir__.cpp.
Referenced by MSD_lowDir().
void MSD_lowListAllEdge (SPTYPE optr)
Definition at line 207 of file genshow_.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EPTYPE, MSD_lowShowListEdge(), and SNIL.
Referenced by MSD_execShow().
void MSD_lowListAllFace (SPTYPE optr)
Definition at line 224 of file genshow_.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, MSD_lowShowListFace(), and SNIL.
Referenced by MSD_execShow().
void MSD_lowListAllSolid (void)
Definition at line 180 of file genshow_.cpp.
References AllSolids, MSD_lowShowListSolid(), and SPTYPE.
Referenced by MSD_execShow().
void MSD_lowListAllSolidName (void)
Definition at line 98 of file genlist_.cpp.
References AllSolids, SolName, and SPTYPE.
Referenced by MSD_execListElement().
void MSD_lowListAllVertex (SPTYPE optr)
Definition at line 190 of file genshow_.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, MSD_lowShowListVertex(), SNIL, and VPTYPE.
Referenced by MSD_execShow().
int MSD_lowListFaceAdjacency (SPTYPE optr, char * fname)
Definition at line 81 of file genfadjr.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, EdgAngle, ERROR, solid::eucoef, eulerco::facen, FacFaceNo, FacFLOut, FPTYPE, HalEdg, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, mate, MEN_NaoAbriuArquivo, NAM_ListFaceAdjacency, NIL, and TRUE.
Referenced by MSD_highNameListFaceAdjacency().
void MSD_lowListNumberOfElements (void)
Definition at line 109 of file genlist_.cpp.
References axsused, camused, edgused, facused, grpused, objused, and vtxused.
Referenced by MSD_execListElement().
int MSD_lowLoadSolid (Id sn, char * fname)
Definition at line 128 of file genload_.cpp.
References eulercod::ecode, eulercod::eop, FALSE, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MEN_NaoAbriuArquivo, MSD_lowAddEulerOp(), MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowScanEulerOperator(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), NAM_LoadSolido, NIL, eulercod::num, eulerop::opcode, OpHead, PEulerOp, SNIL, eulerop::solidno, SPTYPE, SUCCESS, and TRUE.
Referenced by MSD_highLoadSolid().
int MSD_lowNameNCopySolidSpiral (char * name, vector cpos, vector vect, real dth, real dmv, int n)
Definition at line 131 of file genncopy.cpp.
References MSD_highNameCopySolid(), MSD_lowFindSolidByName(), MSD_lowRequestNewName(), MSD_lowRotateSolidAxis(), MSD_lowTranslate(), SPTYPE, TRUE, vecpe(), and veczer().
Referenced by MSD_highNameNCopySolidSpiral().
int MSD_lowNameNCopySolidTranslate (char * name, vector omove, vector dmove, int n)
Definition at line 101 of file genncopy.cpp.
References MSD_highNameCopySolid(), MSD_lowFindSolidByName(), MSD_lowRequestNewName(), MSD_lowTranslate(), SPTYPE, TRUE, veccopy(), and vecplus().
Referenced by MSD_highNameNCopySolidTranslate().
int MSD_lowNameRenameSolid (SPTYPE sptr, char * name2)
Definition at line 123 of file genrenam.cpp.
References MSD_highName(), SOLID, SolSolidNo, and SUCCESS.
Referenced by MSD_highNameRenameSolid().
void MSD_lowRequestNewName (char * name)
Definition at line 152 of file genncopy.cpp.
References defonum.
Referenced by MSD_lowNameNCopySolidSpiral(), and MSD_lowNameNCopySolidTranslate().
int MSD_lowSaveSolid (SPTYPE s, char * fname)
Definition at line 117 of file gensave_.cpp.
References EulerOpNext, EULEROPS, FALSE, Gdodirect, Gdoinversion, MEN_NaoAbriuArquivo, MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowPrintEulerOp(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSoftRemove(), NAM_SaveSolido, NIL, OpHead, PEulerOp, SNIL, SolSolidNo, and TRUE.
Referenced by MSD_highSaveSolid().
EPTYPE MSD_lowShowFindEdge (SPTYPE s, Id en)
Definition at line 144 of file genshow_.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgEdgeNo, ENIL, and EPTYPE.
Referenced by MSD_execShow(), and MSD_highDisplayEdge().
VPTYPE MSD_lowShowFindVertex (SPTYPE s, Id vn)
Definition at line 162 of file genshow_.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_execShow().
void MSD_lowShowListEdge (EPTYPE eptr)
Definition at line 282 of file genshow_.cpp.
References EdgAngle, EdgEdgeNo, EdgHe1, EdgHe2, ENIL, FacFaceNo, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, and VerVertexNo.
Referenced by MSD_execShow(), and MSD_lowListAllEdge().
void MSD_lowShowListFace (FPTYPE fptr)
Definition at line 301 of file genshow_.cpp.
References EdgEdgeNo, FacFaceNo, FacFeq, FacFLOut, FNIL, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLength, and VerVertexNo.
Referenced by MSD_execShow(), and MSD_lowListAllFace().
void MSD_lowShowListSolid (SPTYPE optr)
Definition at line 241 of file genshow_.cpp.
References ANIL, AxsName, eulerco::edgen, solid::eucoef, eulerco::facen, GNIL, GrpGAxs, GrpName, SNIL, SolColor, SolGroup, SolName, SolOAxs, and eulerco::vertexn.
Referenced by MSD_execShow(), and MSD_lowListAllSolid().
void MSD_lowShowListVertex (VPTYPE vptr)
Definition at line 270 of file genshow_.cpp.
References VerVCoord, VerVertexNo, and VNIL.
Referenced by MSD_execShow(), and MSD_lowListAllVertex().
char** MSD_putSolidNameInList (char ** list)
Definition at line 84 of file genfindn.cpp.
References AllSolids, SolName, and SPTYPE.