USPDesigner: C:/USPDesig/GEN/genfindn.cpp File Reference
C:/USPDesig/GEN/genfindn.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
Functions
char MSD_getTypeByName (char *nam)
int MSD_getNumberOfSolid (void)
char ** MSD_putSolidNameInList (char **list)
Function Documentation
int MSD_getNumberOfSolid (void)
Definition at line 72 of file genfindn.cpp.
References AllSolids, and SPTYPE.
char MSD_getTypeByName (char * nam)
Definition at line 51 of file genfindn.cpp.
References ANIL, FALSE, GNIL, MSD_lowFindAxisByName(), MSD_lowFindCameraByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), NIL, and SNIL.
Referenced by MSD_highNameColor(), MSD_highNameCopyElement(), MSD_highNameDeleteElement(), MSD_highNameRenameElement(), MSD_highNameRotateElement(), MSD_highNameSetDisplay(), MSD_highNameTranslateElement(), MSD_resetElement(), and MSD_selectElement().
char** MSD_putSolidNameInList (char ** list)
Definition at line 84 of file genfindn.cpp.
References AllSolids, SolName, and SPTYPE.