USPDesigner: C:/USPDesig/GEN/genfadjr.cpp File Reference
C:/USPDesig/GEN/genfadjr.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "mancommd.h"
Functions
int MSD_highNameListFaceAdjacency (char *name, char *fname)
int MSD_lowListFaceAdjacency (SPTYPE optr, char *fname)
Function Documentation
int MSD_highNameListFaceAdjacency (char * name, char * fname)
Definition at line 68 of file genfadjr.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_lowFindSolidByName(), MSD_lowListFaceAdjacency(), NAM_ListFaceAdjacency, SNIL, and SPTYPE.
int MSD_lowListFaceAdjacency (SPTYPE optr, char * fname)
Definition at line 81 of file genfadjr.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, EdgAngle, ERROR, solid::eucoef, eulerco::facen, FacFaceNo, FacFLOut, FPTYPE, HalEdg, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, mate, MEN_NaoAbriuArquivo, NAM_ListFaceAdjacency, NIL, and TRUE.
Referenced by MSD_highNameListFaceAdjacency().