USPDesigner: C:/USPDesig/GEN/genload_.cpp File Reference
C:/USPDesig/GEN/genload_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "genfunc_.h"
#include "mancommd.h"
Classes
struct eulercod
Typedefs
typedef struct eulercod EuCode
Functions
void MSD_execNameLoadSolid (void)
int MSD_highNameLoadSolid (char *oname, char *fname)
int MSD_highLoadSolid (char *fname)
int MSD_lowLoadSolid (Id sn, char *fname)
Variables
EuCode ematrix []
Typedef Documentation
typedef struct eulercod EuCode
Definition at line 53 of file genload_.cpp.
Function Documentation
void MSD_execNameLoadSolid (void)
Definition at line 68 of file genload_.cpp.
References lineins(), MSD_highNameLoadSolid(), and restbuf.
int MSD_highLoadSolid (char * fname)
Definition at line 120 of file genload_.cpp.
References MSD_getMaxSolidId(), and MSD_lowLoadSolid().
Referenced by MSD_highNameLoadSolid().
int MSD_highNameLoadSolid (char * oname, char * fname)
Definition at line 83 of file genload_.cpp.
References ERROR, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highLoadSolid(), SolName, SPTYPE, and SUCCESS.
Referenced by MSD_execNameLoadSolid().
int MSD_lowLoadSolid (Id sn, char * fname)
Definition at line 128 of file genload_.cpp.
References eulercod::ecode, eulercod::eop, FALSE, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, MEN_NaoAbriuArquivo, MSD_lowAddEulerOp(), MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowScanEulerOperator(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), NAM_LoadSolido, NIL, eulercod::num, eulerop::opcode, OpHead, PEulerOp, SNIL, eulerop::solidno, SPTYPE, SUCCESS, and TRUE.
Referenced by MSD_highLoadSolid().
Variable Documentation
EuCode ematrix[]
Definition at line 67 of file eulerops.cpp.