USPDesigner: C:/USPDesig/GEN/genlist_.cpp File Reference
C:/USPDesig/GEN/genlist_.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execListElement (void)
void MSD_lowListAllSolidName (void)
void MSD_lowListNumberOfElements (void)
Function Documentation
void MSD_execListElement (void)
Definition at line 51 of file genlist_.cpp.
References lineins(), MSD_lowListAllAxisName(), MSD_lowListAllCameraName(), MSD_lowListAllGroupName(), MSD_lowListAllSolidName(), MSD_lowListNumberOfElements(), and optin().
void MSD_lowListAllSolidName (void)
Definition at line 98 of file genlist_.cpp.
References AllSolids, SolName, and SPTYPE.
Referenced by MSD_execListElement().
void MSD_lowListNumberOfElements (void)
Definition at line 109 of file genlist_.cpp.
References axsused, camused, edgused, facused, grpused, objused, and vtxused.
Referenced by MSD_execListElement().