USPDesigner: C:/USPDesig/GEN/genncopy.cpp File Reference
C:/USPDesig/GEN/genncopy.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "hiegroup.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
void MSD_execNameNCopySolid (void)
int MSD_highNameNCopySolidTranslate (char *name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, int n)
int MSD_lowNameNCopySolidTranslate (char *name, vector omove, vector dmove, int n)
int MSD_highNameNCopySolidSpiral (char *name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, real dth, real dmv, int n)
int MSD_lowNameNCopySolidSpiral (char *name, vector cpos, vector vect, real dth, real dmv, int n)
void MSD_lowRequestNewName (char *name)
Function Documentation
void MSD_execNameNCopySolid (void)
Definition at line 51 of file genncopy.cpp.
References lineins(), MSD_highNameNCopySolidSpiral(), MSD_highNameNCopySolidTranslate(), optin(), and restbuf.
int MSD_highNameNCopySolidSpiral (char * name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, real dth, real dmv, int n)
Definition at line 120 of file genncopy.cpp.
References makevec(), MSD_lowNameNCopySolidSpiral(), and normalize().
Referenced by MSD_execNameNCopySolid().
int MSD_highNameNCopySolidTranslate (char * name, real Xi, real Yi, real Zi, real Xd, real Yd, real Zd, int n)
Definition at line 91 of file genncopy.cpp.
References makevec(), and MSD_lowNameNCopySolidTranslate().
Referenced by MSD_execNameNCopySolid().
int MSD_lowNameNCopySolidSpiral (char * name, vector cpos, vector vect, real dth, real dmv, int n)
Definition at line 131 of file genncopy.cpp.
References MSD_highNameCopySolid(), MSD_lowFindSolidByName(), MSD_lowRequestNewName(), MSD_lowRotateSolidAxis(), MSD_lowTranslate(), SPTYPE, TRUE, vecpe(), and veczer().
Referenced by MSD_highNameNCopySolidSpiral().
int MSD_lowNameNCopySolidTranslate (char * name, vector omove, vector dmove, int n)
Definition at line 101 of file genncopy.cpp.
References MSD_highNameCopySolid(), MSD_lowFindSolidByName(), MSD_lowRequestNewName(), MSD_lowTranslate(), SPTYPE, TRUE, veccopy(), and vecplus().
Referenced by MSD_highNameNCopySolidTranslate().
void MSD_lowRequestNewName (char * name)
Definition at line 152 of file genncopy.cpp.
References defonum.
Referenced by MSD_lowNameNCopySolidSpiral(), and MSD_lowNameNCopySolidTranslate().