USPDesigner: C:/USPDesig/GEN/genrenam.cpp File Reference
C:/USPDesig/GEN/genrenam.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
#include "eulerops.h"
Functions
void MSD_execNameRenameElement (void)
int MSD_highNameRenameElement (char *name1, char *name2)
int MSD_highNameRenameSolid (char *name1, char *name2)
int MSD_lowNameRenameSolid (SPTYPE sptr, char *name2)
Function Documentation
void MSD_execNameRenameElement (void)
Definition at line 54 of file genrenam.cpp.
References lineins(), MSD_highNameRenameElement(), and restbuf.
int MSD_highNameRenameElement (char * name1, char * name2)
Definition at line 69 of file genrenam.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRenameAxis(), MSD_highNameRenameCamera(), MSD_highNameRenameGroup(), and MSD_highNameRenameSolid().
Referenced by MSD_execNameRenameElement().
int MSD_highNameRenameSolid (char * name1, char * name2)
Definition at line 106 of file genrenam.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_lowFindSolidByName(), MSD_lowNameRenameSolid(), NAM_RenameSolido, SNIL, and SPTYPE.
Referenced by MSD_highNameRenameElement(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
int MSD_lowNameRenameSolid (SPTYPE sptr, char * name2)
Definition at line 123 of file genrenam.cpp.
References MSD_highName(), SOLID, SolSolidNo, and SUCCESS.
Referenced by MSD_highNameRenameSolid().