USPDesigner: C:/USPDesig/GEN/genrotat.cpp File Reference
C:/USPDesig/GEN/genrotat.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execNameRotateElement (void)
int MSD_highNameRotateElement (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Function Documentation
void MSD_execNameRotateElement (void)
Definition at line 53 of file genrotat.cpp.
References lineins(), MSD_highNameRotateElement(), and restbuf.
int MSD_highNameRotateElement (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 70 of file genrotat.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameRotateAxis(), MSD_highNameRotateGroup(), and MSD_highNameRotateSolidAxis().
Referenced by MSD_execNameRotateElement().