USPDesigner: C:/USPDesig/GEN/genshow_.cpp File Reference
C:/USPDesig/GEN/genshow_.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execShow (void)
EPTYPE MSD_lowShowFindEdge (SPTYPE s, Id en)
VPTYPE MSD_lowShowFindVertex (SPTYPE s, Id vn)
void MSD_lowListAllSolid (void)
void MSD_lowListAllVertex (SPTYPE optr)
void MSD_lowListAllEdge (SPTYPE optr)
void MSD_lowListAllFace (SPTYPE optr)
void MSD_lowShowListSolid (SPTYPE optr)
void MSD_lowShowListVertex (VPTYPE vptr)
void MSD_lowShowListEdge (EPTYPE eptr)
void MSD_lowShowListFace (FPTYPE fptr)
Function Documentation
void MSD_execShow (void)
Definition at line 51 of file genshow_.cpp.
References lineins(), MSD_getFace(), MSD_lowFindAxisByName(), MSD_lowFindCameraByName(), MSD_lowFindGroupByName(), MSD_lowFindSolidByName(), MSD_lowListAllAxis(), MSD_lowListAllCamera(), MSD_lowListAllEdge(), MSD_lowListAllFace(), MSD_lowListAllGroup(), MSD_lowListAllSolid(), MSD_lowListAllVertex(), MSD_lowListAxisName(), MSD_lowListGroup(), MSD_lowNameListCameraName(), MSD_lowShowFindEdge(), MSD_lowShowFindVertex(), MSD_lowShowListEdge(), MSD_lowShowListFace(), MSD_lowShowListSolid(), MSD_lowShowListVertex(), optin(), restbuf, SNIL, and SPTYPE.
void MSD_lowListAllEdge (SPTYPE optr)
Definition at line 207 of file genshow_.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EPTYPE, MSD_lowShowListEdge(), and SNIL.
Referenced by MSD_execShow().
void MSD_lowListAllFace (SPTYPE optr)
Definition at line 224 of file genshow_.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, MSD_lowShowListFace(), and SNIL.
Referenced by MSD_execShow().
void MSD_lowListAllSolid (void)
Definition at line 180 of file genshow_.cpp.
References AllSolids, MSD_lowShowListSolid(), and SPTYPE.
Referenced by MSD_execShow().
void MSD_lowListAllVertex (SPTYPE optr)
Definition at line 190 of file genshow_.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, MSD_lowShowListVertex(), SNIL, and VPTYPE.
Referenced by MSD_execShow().
EPTYPE MSD_lowShowFindEdge (SPTYPE s, Id en)
Definition at line 144 of file genshow_.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgEdgeNo, ENIL, and EPTYPE.
Referenced by MSD_execShow(), and MSD_highDisplayEdge().
VPTYPE MSD_lowShowFindVertex (SPTYPE s, Id vn)
Definition at line 162 of file genshow_.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, VerVertexNo, VNIL, and VPTYPE.
Referenced by MSD_execShow().
void MSD_lowShowListEdge (EPTYPE eptr)
Definition at line 282 of file genshow_.cpp.
References EdgAngle, EdgEdgeNo, EdgHe1, EdgHe2, ENIL, FacFaceNo, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, and VerVertexNo.
Referenced by MSD_execShow(), and MSD_lowListAllEdge().
void MSD_lowShowListFace (FPTYPE fptr)
Definition at line 301 of file genshow_.cpp.
References EdgEdgeNo, FacFaceNo, FacFeq, FacFLOut, FNIL, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLength, and VerVertexNo.
Referenced by MSD_execShow(), and MSD_lowListAllFace().
void MSD_lowShowListSolid (SPTYPE optr)
Definition at line 241 of file genshow_.cpp.
References ANIL, AxsName, eulerco::edgen, solid::eucoef, eulerco::facen, GNIL, GrpGAxs, GrpName, SNIL, SolColor, SolGroup, SolName, SolOAxs, and eulerco::vertexn.
Referenced by MSD_execShow(), and MSD_lowListAllSolid().
void MSD_lowShowListVertex (VPTYPE vptr)
Definition at line 270 of file genshow_.cpp.
References VerVCoord, VerVertexNo, and VNIL.
Referenced by MSD_execShow(), and MSD_lowListAllVertex().