USPDesigner: C:/USPDesig/GEN/gensave_.cpp File Reference
C:/USPDesig/GEN/gensave_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "genfunc_.h"
#include "shpshape.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execNameSaveSolid (void)
int MSD_highNameSaveSolid (char *oname, char *fname)
int MSD_highSaveSolid (int sn, char *fname)
int MSD_lowSaveSolid (SPTYPE s, char *fname)
Function Documentation
void MSD_execNameSaveSolid (void)
Definition at line 54 of file gensave_.cpp.
References lineins(), MSD_highNameSaveSolid(), and restbuf.
int MSD_highNameSaveSolid (char * oname, char * fname)
Definition at line 69 of file gensave_.cpp.
References FALSE, MEN_NaoEncontrouSolidNome, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highSaveSolid(), NAM_SaveSolido, SolName, and TRUE.
Referenced by MSD_execNameSaveSolid().
int MSD_highSaveSolid (int sn, char * fname)
Definition at line 105 of file gensave_.cpp.
References FALSE, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSaveSolid(), NAM_SaveSolido, SNIL, and SPTYPE.
Referenced by MSD_highNameSaveSolid().
int MSD_lowSaveSolid (SPTYPE s, char * fname)
Definition at line 117 of file gensave_.cpp.
References EulerOpNext, EULEROPS, FALSE, Gdodirect, Gdoinversion, MEN_NaoAbriuArquivo, MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowPrintEulerOp(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSoftRemove(), NAM_SaveSolido, NIL, OpHead, PEulerOp, SNIL, SolSolidNo, and TRUE.
Referenced by MSD_highSaveSolid().