USPDesigner: C:/USPDesig/GEN/gentrans.cpp File Reference
C:/USPDesig/GEN/gentrans.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
void MSD_execNameTranslateElement (void)
int MSD_highNameTranslateElement (char *name, real tx, real ty, real tz)
Function Documentation
void MSD_execNameTranslateElement (void)
Definition at line 53 of file gentrans.cpp.
References lineins(), MSD_highNameTranslateElement(), and restbuf.
int MSD_highNameTranslateElement (char * name, real tx, real ty, real tz)
Definition at line 69 of file gentrans.cpp.
References FALSE, MSD_getTypeByName(), MSD_highNameMoveAxis(), MSD_highNameMoveGroup(), and MSD_highNameTranslate().
Referenced by MSD_execNameTranslateElement().