USPDesigner: C:/USPDesig/GEN/genwait_.cpp File Reference
C:/USPDesig/GEN/genwait_.cpp File Reference
#include <stdio.h>
#include <time.h>
#include "memvirtu.h"
#include "genfunc_.h"
#include "mancommd.h"
Functions
void MSD_execWait (void)
void MSD_highWait (int waitsec)
void MSD_execTime (void)
Function Documentation
void MSD_execTime (void)
Definition at line 76 of file genwait_.cpp.
void MSD_execWait (void)
Definition at line 47 of file genwait_.cpp.
References lineins(), MSD_highWait(), and restbuf.
void MSD_highWait (int waitsec)
Definition at line 62 of file genwait_.cpp.
Referenced by MSD_execWait().