USPDesigner: C:/USPDesig/GPH/gphclear.cpp File Reference
C:/USPDesig/GPH/gphclear.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "disdispl.h"
#include "gphgraph.h"
Functions
void MSD_execClear (void)
void MSD_lowClearWindow (void)
Function Documentation
void MSD_execClear (void)
Definition at line 49 of file gphclear.cpp.
References g_clear(), lineins(), MSD_lowClearWindow(), and optin().
void MSD_lowClearWindow (void)
Definition at line 79 of file gphclear.cpp.
References BLACK, g_filbox(), and xyratio.
Referenced by MSD_execClear().