USPDesigner: C:/USPDesig/INC/gphgraph.h File Reference
C:/USPDesig/INC/gphgraph.h File Reference
#include <stdio.h>
Defines
#define EXTERN extern
#define BLACK 0
#define RED 4
#define GREEN 2
#define BLUE 1
#define YELLOW 14
#define CYAN 3
#define MAGENTA 5
#define WHITE 15
#define MAX_COLOR 15
#define GENERIC_MAT_FILE "generic#.mat"
#define GENERIC_GIF_FILE "generic#.gif"
#define GENERIC_PS_FILE "generic#.ps"
#define NORMAL_DEFAULT_LENGTH 10
#define NORMAL_SCALER_LENGTH 100
#define DEFAULT_COLOR 1
#define VIEW_PERSPECTIVE 1
#define VIEW_ORTHOGRAPHIC 2
#define DEFAULT_PERSPECTIVE_Z -5.0
#define TRANS_SCREEN 1
#define TRANS_OBJECT 2
#define DEFAULT_NUM_OF_ISOLINES 10
#define DEFAULT_SAMPLES_PER_CURVE 6
#define LINE_LEN_LONG 256
Typedefs
typedef double real
typedef real vector [4]
Enumerations
enum GraphicEventType {
EVENT_NONE, EVENT_QUIT, EVENT_SCR_OBJ_TGL, EVENT_PERS_ORTHO_TGL,
EVENT_PERS_ORTHO_Z, EVENT_ROTATE_X, EVENT_ROTATE_Y, EVENT_ROTATE_Z,
EVENT_TRANSLATE_X, EVENT_TRANSLATE_Y, EVENT_TRANSLATE_Z, EVENT_SCALE,
EVENT_DEPTH_CUE, EVENT_DRAW_SOLID, EVENT_SAVE_MATRIX, EVENT_SAVE_GIF,
EVENT_SAVE_PS, EVENT_RESET_MATRIX
}
Functions
void MSD_execClear (void)
void MSD_lowClearWindow (void)
void MSD_execPrint (void)
void MSD_highPrint (FILE *fptr, char *mens)
void MSD_lowPrint (char *to, char *from)
void MSD_execWindow (void)
int MSD_highWindow (real, real, real)
char MSD_lowCheckWindow (real x, real y, real r)
Variables
EXTERN vector windbox
EXTERN vector dwindbox
EXTERN double releps
EXTERN int GlblDoGraphics
EXTERN int GlblTransformMode
EXTERN int GlblViewMode
EXTERN int GlblDepthCue
Define Documentation
#define BLACK 0
Definition at line 83 of file gphgraph.h.
Referenced by MSD_lowClearWindow().
#define BLUE 1
Definition at line 95 of file gphgraph.h.
#define CYAN 3
Definition at line 103 of file gphgraph.h.
#define DEFAULT_COLOR 1
Definition at line 124 of file gphgraph.h.
#define DEFAULT_NUM_OF_ISOLINES 10
Definition at line 133 of file gphgraph.h.
#define DEFAULT_PERSPECTIVE_Z -5.0
Definition at line 128 of file gphgraph.h.
#define DEFAULT_SAMPLES_PER_CURVE 6
Definition at line 134 of file gphgraph.h.
#define EXTERN extern
Definition at line 49 of file gphgraph.h.
#define GENERIC_GIF_FILE "generic#.gif"
Definition at line 117 of file gphgraph.h.
#define GENERIC_MAT_FILE "generic#.mat"
Definition at line 116 of file gphgraph.h.
#define GENERIC_PS_FILE "generic#.ps"
Definition at line 118 of file gphgraph.h.
#define GREEN 2
Definition at line 91 of file gphgraph.h.
#define LINE_LEN_LONG 256
Definition at line 135 of file gphgraph.h.
#define MAGENTA 5
Definition at line 107 of file gphgraph.h.
#define MAX_COLOR 15
Definition at line 112 of file gphgraph.h.
#define NORMAL_DEFAULT_LENGTH 10
Definition at line 121 of file gphgraph.h.
#define NORMAL_SCALER_LENGTH 100
Definition at line 122 of file gphgraph.h.
#define RED 4
Definition at line 87 of file gphgraph.h.
#define TRANS_OBJECT 2
Definition at line 131 of file gphgraph.h.
#define TRANS_SCREEN 1
Definition at line 130 of file gphgraph.h.
#define VIEW_ORTHOGRAPHIC 2
Definition at line 127 of file gphgraph.h.
#define VIEW_PERSPECTIVE 1
Definition at line 126 of file gphgraph.h.
#define WHITE 15
Definition at line 111 of file gphgraph.h.
#define YELLOW 14
Definition at line 99 of file gphgraph.h.
Typedef Documentation
typedef double real
Definition at line 64 of file gphgraph.h.
typedef real vector[4]
Definition at line 68 of file gphgraph.h.
Enumeration Type Documentation
enum GraphicEventType
Enumerator:
EVENT_NONE
EVENT_QUIT
EVENT_SCR_OBJ_TGL
EVENT_PERS_ORTHO_TGL
EVENT_PERS_ORTHO_Z
EVENT_ROTATE_X
EVENT_ROTATE_Y
EVENT_ROTATE_Z
EVENT_TRANSLATE_X
EVENT_TRANSLATE_Y
EVENT_TRANSLATE_Z
EVENT_SCALE
EVENT_DEPTH_CUE
EVENT_DRAW_SOLID
EVENT_SAVE_MATRIX
EVENT_SAVE_GIF
EVENT_SAVE_PS
EVENT_RESET_MATRIX
Definition at line 137 of file gphgraph.h.
Function Documentation
void MSD_execClear (void)
Definition at line 49 of file gphclear.cpp.
References g_clear(), lineins(), MSD_lowClearWindow(), and optin().
void MSD_execPrint (void)
Definition at line 45 of file gphprint.cpp.
References MSD_highPrint(), and restbuf.
void MSD_execWindow (void)
Definition at line 46 of file gphwindw.cpp.
References lineins(), MSD_highWindow(), and restbuf.
void MSD_highPrint (FILE * fptr, char * mens)
Definition at line 50 of file gphprint.cpp.
References MSD_lowPrint().
Referenced by MSD_execPrint().
int MSD_highWindow (real , real , real)
Definition at line 61 of file gphwindw.cpp.
References dwindbox, ERROR, MSD_lowCheckWindow(), SUCCESS, and windbox.
Referenced by MSD_execWindow().
char MSD_lowCheckWindow (real x, real y, real r)
Definition at line 74 of file gphwindw.cpp.
References FALSE, releps, and TRUE.
Referenced by MSD_highWindow().
void MSD_lowClearWindow (void)
Definition at line 79 of file gphclear.cpp.
References BLACK, g_filbox(), and xyratio.
Referenced by MSD_execClear().
void MSD_lowPrint (char * to, char * from)
Definition at line 58 of file gphprint.cpp.
Referenced by MSD_highPrint().
Variable Documentation
EXTERN vector dwindbox
Definition at line 77 of file gphgraph.h.
Referenced by g_frame(), gdcpos(), maninit(), MSD_highWindow(), and MSD_lowSetCamera3View().
EXTERN int GlblDepthCue
Definition at line 160 of file gphgraph.h.
EXTERN int GlblDoGraphics
Definition at line 160 of file gphgraph.h.
EXTERN int GlblTransformMode
Definition at line 160 of file gphgraph.h.
EXTERN int GlblViewMode
Definition at line 160 of file gphgraph.h.
EXTERN double releps
Definition at line 78 of file gphgraph.h.
Referenced by maninit(), MSD_lowCheckCamera(), MSD_lowCheckWindow(), MSD_lowEdgeEdgeCheckStep2(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowEdgeEdgeIntersection(), MSD_lowIntersectionCheckStep1(), MSD_lowIsInvertedEdge(), and MSD_lowPositionalVisibility().
EXTERN vector windbox
Definition at line 76 of file gphgraph.h.
Referenced by maninit(), MSD_highWindow(), and MSD_lowSetCamera3View().