USPDesigner: C:/USPDesig/GPH/gphlintf.cpp File Reference
C:/USPDesig/GPH/gphlintf.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <graphics.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "disdispl.h"
#include "gphgraph.h"
#include "animatio.h"
Functions
void g_frame (void)
void g_tpoint (int lt, vect2 v)
void g_iline (int lt, int *gdcsv, int *gdcev)
void g_tline (int lt, vect2 sv, vect2 ev)
void h_line (void)
void g_open (void)
void g_filbox (int color, vect2 v0, vect2 v1)
void g_clear (void)
void g_pcolor (int color)
void g_close (void)
void gdcpos (vect2 npos, int *dpos)
Variables
int GraphDriver
int GraphMode
int GraphError
int MaxColors
int MaxX
int MaxY
Function Documentation
void g_clear (void)
Definition at line 378 of file gphlintf.cpp.
Referenced by CriaFrame(), ExibeFrame(), g_open(), maninit(), MSD_createAnimation(), MSD_displayLoadedAnimation(), MSD_execClear(), and MSD_lowAreaProjetadaTotal().
void g_close (void)
Definition at line 406 of file gphlintf.cpp.
Referenced by endfunc().
void g_filbox (int color, vect2 v0, vect2 v1)
Definition at line 349 of file gphlintf.cpp.
References gdcpos().
Referenced by MSD_lowClearWindow().
void g_frame (void)
Definition at line 85 of file gphlintf.cpp.
References Draw, dspfwptr, dwindbox, framecol, framenum, MaxX, MaxY, and xyratio.
Referenced by MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), and MSD_lowDisplayLocalHidden().
void g_iline (int lt, int * gdcsv, int * gdcev)
Definition at line 164 of file gphlintf.cpp.
References Draw, and lncolor.
Referenced by DrawLine().
void g_open (void)
Definition at line 295 of file gphlintf.cpp.
References FALSE, g_clear(), GraphDriver, GraphError, GraphMode, MaxColors, MaxX, and MaxY.
Referenced by main().
void g_pcolor (int color)
Definition at line 401 of file gphlintf.cpp.
References lncolor.
Referenced by DrawLine(), MSD_lowDisplayAllEdges(), MSD_lowDisplayAxis(), MSD_lowDisplayEdge(), MSD_lowDisplayHidden(), MSD_lowDisplayIntersection(), MSD_lowDisplayLocalHidden(), and MSD_lowDisplayMesh().
void g_tline (int lt, vect2 sv, vect2 ev)
Definition at line 216 of file gphlintf.cpp.
References Draw, dspfwptr, framenum, gdcpos(), lncolor, and lntype.
Referenced by h_line(), MSD_lowDisplayDividedEdge(), MSD_lowDisplayHidden(), MSD_lowDisplayLine(), and MSD_lowDisplayLineCoordinates().
void g_tpoint (int lt, vect2 v)
Definition at line 148 of file gphlintf.cpp.
References Draw, gdcpos(), and lncolor.
Referenced by MSD_lowDisplayVertex().
void gdcpos (vect2 npos, int * dpos)
Definition at line 419 of file gphlintf.cpp.
References dwindbox, MaxX, MaxY, and xyratio.
Referenced by g_filbox(), g_tline(), g_tpoint(), and LoadFrame().
void h_line (void)
Definition at line 278 of file gphlintf.cpp.
References dspfrptr, g_tline(), and lncolor.
Referenced by MSD_lowDisplayReadFile().
Variable Documentation
int GraphDriver
Definition at line 79 of file gphlintf.cpp.
Referenced by g_open().
int GraphError
Definition at line 79 of file gphlintf.cpp.
Referenced by g_open().
int GraphMode
Definition at line 79 of file gphlintf.cpp.
Referenced by g_open().
int MaxColors
Definition at line 81 of file gphlintf.cpp.
Referenced by g_open(), MSD_highDisplayCoordinates(), MSD_highNameColor(), MSD_highNameGroupColor(), MSD_highNameSolidColor(), MSD_lowSetDefaultColor(), and MSD_lowSetFrameColor().
int MaxX
Definition at line 83 of file gphlintf.cpp.
Referenced by g_frame(), g_open(), and gdcpos().
int MaxY
Definition at line 83 of file gphlintf.cpp.
Referenced by g_frame(), g_open(), and gdcpos().