USPDesigner: C:/USPDesig/GPH/gphprint.cpp File Reference
C:/USPDesig/GPH/gphprint.cpp File Reference
#include <stdio.h>
#include "mancommd.h"
#include "gphgraph.h"
Functions
void MSD_execPrint (void)
void MSD_highPrint (FILE *fptr, char *mens)
void MSD_lowPrint (char *to, char *from)
Function Documentation
void MSD_execPrint (void)
Definition at line 45 of file gphprint.cpp.
References MSD_highPrint(), and restbuf.
void MSD_highPrint (FILE * fptr, char * mens)
Definition at line 50 of file gphprint.cpp.
References MSD_lowPrint().
Referenced by MSD_execPrint().
void MSD_lowPrint (char * to, char * from)
Definition at line 58 of file gphprint.cpp.
Referenced by MSD_highPrint().