USPDesigner: C:/USPDesig/GPH/gphwindw.cpp File Reference
C:/USPDesig/GPH/gphwindw.cpp File Reference
#include <stdio.h>
#include "lowparam.h"
#include "mancommd.h"
#include "gphgraph.h"
Functions
void MSD_execWindow (void)
int MSD_highWindow (real x, real y, real r)
char MSD_lowCheckWindow (real x, real y, real r)
Function Documentation
void MSD_execWindow (void)
Definition at line 46 of file gphwindw.cpp.
References lineins(), MSD_highWindow(), and restbuf.
int MSD_highWindow (real x, real y, real r)
Definition at line 61 of file gphwindw.cpp.
References dwindbox, ERROR, MSD_lowCheckWindow(), SUCCESS, and windbox.
Referenced by MSD_execWindow().
char MSD_lowCheckWindow (real x, real y, real r)
Definition at line 74 of file gphwindw.cpp.
References FALSE, releps, and TRUE.
Referenced by MSD_highWindow().