USPDesigner: C:/USPDesig/HIE/hieaxscr.cpp File Reference
C:/USPDesig/HIE/hieaxscr.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameCreateAxisRotation (char *name, real x1, real y1, real z1, real x2, real y2, real z2)
int MSD_highCreateAxisRotation (real x1, real y1, real z1, real x2, real y2, real z2)
int MSD_middleCreateAxisRotation (int an, real x1, real y1, real z1, real x2, real y2, real z2)
int MSD_lowCreateAxisRotation (Id an, vector pos, vector vec)
int MSD_execStructCrtAxsRotation (EulerOp *op)
void MSD_printStructCrtAxsRotation (FILE *f, EulerOp *op)
int MSD_readStructCrtAxsRotation (FILE *f, EulerOp *op)
int MSD_modifyStructCrtAxsRotation (EulerOp *op)
Function Documentation
int MSD_execStructCrtAxsRotation (EulerOp * op)
Definition at line 152 of file hieaxscr.cpp.
References EULEROPS, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, MSD_middleCreateAxisRotation(), and eulerop::opnext.
int MSD_highCreateAxisRotation (real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 111 of file hieaxscr.cpp.
References makevec(), MSD_getMaxAxisId(), and MSD_lowCreateAxisRotation().
Referenced by MSD_highNameCreateAxisRotation().
int MSD_highNameCreateAxisRotation (char * name, real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 73 of file hieaxscr.cpp.
References APTYPE, AxsName, ERROR, MEN_AxisJaExiste, MSD_getAxis(), MSD_getAxisIdFromName(), MSD_highCreateAxisRotation(), NAM_CreateAxisOfRotation, and SUCCESS.
Referenced by MSD_execManipulateAxis().
int MSD_lowCreateAxisRotation (Id an, vector pos, vector vec)
Definition at line 131 of file hieaxscr.cpp.
References ANIL, APTYPE, AXIS, AxisOfRotation, AxsAxisNo, AxsCenter, AxsMode, AxsVector, ERROR, Gdoinversion, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateAxisOfRotation, NNIL, REMAXS, SNIL, and veccopy().
Referenced by MSD_highCreateAxisRotation(), and MSD_middleCreateAxisRotation().
int MSD_middleCreateAxisRotation (int an, real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 121 of file hieaxscr.cpp.
References makevec(), and MSD_lowCreateAxisRotation().
Referenced by MSD_execStructCrtAxsRotation().
int MSD_modifyStructCrtAxsRotation (EulerOp * op)
Definition at line 215 of file hieaxscr.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructCrtAxsRotation (FILE * f, EulerOp * op)
Definition at line 175 of file hieaxscr.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
int MSD_readStructCrtAxsRotation (FILE * f, EulerOp * op)
Definition at line 189 of file hieaxscr.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.