USPDesigner: C:/USPDesig/HIE/hieassgs.cpp File Reference
C:/USPDesig/HIE/hieassgs.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameAssociaGroupSolid (char *name1, char *name2)
int MSD_highAssociaGroupSolid (int gn, int sn)
int MSD_lowAssociaGroupSolid (GPTYPE gptr, SPTYPE optr)
Function Documentation
int MSD_highAssociaGroupSolid (int gn, int sn)
Definition at line 107 of file hieassgs.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getGroup(), MSD_getSolid(), MSD_lowAssociaGroupSolid(), NAM_AssociaGroupSolid, SNIL, and SPTYPE.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupSolid(), and MSD_highNameDesassociaGroupSolid().
int MSD_highNameAssociaGroupSolid (char * name1, char * name2)
Definition at line 70 of file hieassgs.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MEN_NaoEncontrouSolidNome, MSD_getGroupIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaGroupSolid(), and NAM_AssociaGroupSolid.
int MSD_lowAssociaGroupSolid (GPTYPE gptr, SPTYPE optr)
Definition at line 127 of file hieassgs.cpp.
References ASSOCIATE, Gdoinversion, GNIL, GroupSolid, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SolGroup, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaGroupSolid(), MSD_highDesassociaGroupSolid(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), and MSD_lowRemoveOneGroup().