USPDesigner: C:/USPDesig/HIE/hieassgg.cpp File Reference
C:/USPDesig/HIE/hieassgg.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameAssociaGroupGroup (char *name1, char *name2)
int MSD_highAssociaGroupGroup (int gn1, int gn2)
int MSD_lowAssociaGroupGroup (GPTYPE gptr1, GPTYPE gptr2)
Function Documentation
int MSD_highAssociaGroupGroup (int gn1, int gn2)
Definition at line 105 of file hieassgg.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowAssociaGroupGroup(), and NAM_AssociaGroupGroup.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupGroup(), and MSD_highNameDesassociaGroupGroup().
int MSD_highNameAssociaGroupGroup (char * name1, char * name2)
Definition at line 70 of file hieassgg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highAssociaGroupGroup(), and NAM_AssociaGroupGroup.
int MSD_lowAssociaGroupGroup (GPTYPE gptr1, GPTYPE gptr2)
Definition at line 123 of file hieassgg.cpp.
References ASSOCIATE, Gdoinversion, GNIL, GroupGroup, GrpGroupNo, GrpParent, MSD_lowAddEulerOp(), SNIL, and SUCCESS.
Referenced by MSD_highAssociaGroupGroup(), MSD_highDesassociaGroupGroup(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highTransferGroup(), and MSD_lowRemoveOneGroup().