USPDesigner: C:/USPDesig/HIE/hieaxsmn.cpp File Reference
C:/USPDesig/HIE/hieaxsmn.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "hiegroup.h"
Functions
Id MSD_getAxisIdFromName (char *name)
Id MSD_getMaxAxisId (void)
int MSD_getNumberOfAxis (void)
char ** MSD_putAxisNameInList (char **list)
APTYPE MSD_lowFindAxisByName (char *nam)
APTYPE MSD_getAxis (Id an)
Function Documentation
APTYPE MSD_getAxis (Id an)
Definition at line 123 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, and AxsAxisNo.
Referenced by MSD_highAssociaGroupAxis(), MSD_highAssociaSolidAxis(), MSD_highDesassociaGroupAxis(), MSD_highDesassociaSolidAxis(), MSD_highMoveAxis(), MSD_highName(), MSD_highNameCreateAxisRotation(), MSD_highNameCreateAxisTranslation(), MSD_highRemoveAxis(), MSD_highRotateAxis(), and MSD_highTransformUsingAxis().
Id MSD_getAxisIdFromName (char * name)
Definition at line 50 of file hieaxsmn.cpp.
References AllAxis, APTYPE, AxsAxisNo, and AxsName.
Referenced by MSD_highNameAssociaGroupAxis(), MSD_highNameAssociaSolidAxis(), MSD_highNameCreateAxisRotation(), MSD_highNameCreateAxisTranslation(), MSD_highNameDesassociaGroupAxis(), MSD_highNameDesassociaSolidAxis(), MSD_highNameMoveAxis(), MSD_highNameRemoveAxis(), MSD_highNameRotateAxis(), and MSD_highNameTransformUsingAxis().
Id MSD_getMaxAxisId (void)
Definition at line 64 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, axsary, and AxsAxisNo.
Referenced by MSD_highCreateAxisRotation(), MSD_highCreateAxisTranslation(), and MSD_lowCheckTranslatorTable().
int MSD_getNumberOfAxis (void)
Definition at line 84 of file hieaxsmn.cpp.
References AllAxis, and APTYPE.
APTYPE MSD_lowFindAxisByName (char * nam)
Definition at line 109 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, and AxsName.
Referenced by MSD_addAxisToMovementStructure(), MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameDesassociateAxisElement(), MSD_highNameListAxisName(), and MSD_highNameRenameAxis().
char** MSD_putAxisNameInList (char ** list)
Definition at line 96 of file hieaxsmn.cpp.
References AllAxis, APTYPE, and AxsName.