USPDesigner: C:/USPDesig/HIE/hieaxscd.cpp File Reference
C:/USPDesig/HIE/hieaxscd.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameCreateAxisTranslation (char *name, real x, real y, real z)
int MSD_highCreateAxisTranslation (real x, real y, real z)
int MSD_middleCreateAxisTranslation (int an, real x, real y, real z)
int MSD_lowCreateAxisTranslation (int an, vector vec)
int MSD_execStructCrtAxsTranslation (EulerOp *op)
void MSD_printStructCrtAxsTranslation (FILE *f, EulerOp *op)
int MSD_readStructCrtAxsTranslation (FILE *f, EulerOp *op)
int MSD_modifyStructCrtAxsTranslation (EulerOp *op)
Function Documentation
int MSD_execStructCrtAxsTranslation (EulerOp * op)
Definition at line 149 of file hieaxscd.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and MSD_middleCreateAxisTranslation().
int MSD_highCreateAxisTranslation (real x, real y, real z)
Definition at line 110 of file hieaxscd.cpp.
References ERROR, makevec(), MSD_getMaxAxisId(), and MSD_lowCreateAxisTranslation().
Referenced by MSD_highNameCreateAxisTranslation().
int MSD_highNameCreateAxisTranslation (char * name, real x, real y, real z)
Definition at line 72 of file hieaxscd.cpp.
References APTYPE, AxsName, ERROR, MEN_AxisJaExiste, MSD_getAxis(), MSD_getAxisIdFromName(), MSD_highCreateAxisTranslation(), NAM_CreateAxisOfTranslation, and SUCCESS.
Referenced by MSD_execManipulateAxis().
int MSD_lowCreateAxisTranslation (int an, vector vec)
Definition at line 128 of file hieaxscd.cpp.
References ANIL, APTYPE, AXIS, AxisOfTranslation, AxsAxisNo, AxsMode, AxsVector, ERROR, Gdoinversion, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateAxisOfTranslation, NNIL, REMAXS, SNIL, SUCCESS, and veccopy().
Referenced by MSD_highCreateAxisTranslation(), and MSD_middleCreateAxisTranslation().
int MSD_middleCreateAxisTranslation (int an, real x, real y, real z)
Definition at line 120 of file hieaxscd.cpp.
References makevec(), and MSD_lowCreateAxisTranslation().
Referenced by MSD_execStructCrtAxsTranslation().
int MSD_modifyStructCrtAxsTranslation (EulerOp * op)
Definition at line 201 of file hieaxscd.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructCrtAxsTranslation (FILE * f, EulerOp * op)
Definition at line 161 of file hieaxscd.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
int MSD_readStructCrtAxsTranslation (FILE * f, EulerOp * op)
Definition at line 175 of file hieaxscd.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.