USPDesigner: C:/USPDesig/HIE/hieaxsli.cpp File Reference
C:/USPDesig/HIE/hieaxsli.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameListAxisName (char *name)
int MSD_lowListAxisName (APTYPE aptr)
void MSD_lowListAllAxis (void)
void MSD_lowListAllAxisName (void)
Function Documentation
int MSD_highNameListAxisName (char * name)
Definition at line 69 of file hieaxsli.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisNome, MSD_lowFindAxisByName(), MSD_lowListAxisName(), and NAM_ListAxis.
void MSD_lowListAllAxis (void)
Definition at line 125 of file hieaxsli.cpp.
References AllAxis, APTYPE, and MSD_lowListAxisName().
Referenced by MSD_execShow().
void MSD_lowListAllAxisName (void)
Definition at line 135 of file hieaxsli.cpp.
References AllAxis, APTYPE, and AxsName.
Referenced by MSD_execListElement().
int MSD_lowListAxisName (APTYPE aptr)
Definition at line 81 of file hieaxsli.cpp.
References AxisOfRotation, AxisOfTranslation, AxsAGroup, AxsASolid, AxsCenter, AxsMode, AxsName, AxsType, AxsVector, GROUP, GrpName, SOLID, SolName, and TRUE.
Referenced by MSD_execShow(), MSD_highNameListAxisName(), and MSD_lowListAllAxis().