USPDesigner: C:/USPDesig/HIE/hieaxsrm.cpp File Reference
C:/USPDesig/HIE/hieaxsrm.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameRemoveAxis (char *name)
int MSD_highRemoveAxis (int an)
int MSD_lowRemoveAxis (APTYPE aptr)
int MSD_execStructRemoveAxis (EulerOp *op)
void MSD_printStructRemoveAxis (FILE *f, EulerOp *op)
int MSD_readStructRemoveAxis (FILE *f, EulerOp *op)
int MSD_modifyStructRemoveAxis (EulerOp *op)
Function Documentation
int MSD_execStructRemoveAxis (EulerOp * op)
Definition at line 153 of file hieaxsrm.cpp.
References eulerop::ip1, and MSD_highRemoveAxis().
int MSD_highNameRemoveAxis (char * name)
Definition at line 70 of file hieaxsrm.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highRemoveAxis(), and NAM_RemoveAxis.
Referenced by MSD_execManipulateAxis(), and MSD_highNameDeleteElement().
int MSD_highRemoveAxis (int an)
Definition at line 100 of file hieaxsrm.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowRemoveAxis(), and NAM_RemoveAxis.
Referenced by MSD_execStructRemoveAxis(), and MSD_highNameRemoveAxis().
int MSD_lowRemoveAxis (APTYPE aptr)
Definition at line 112 of file hieaxsrm.cpp.
References AXIS, AxisOfRotation, AxisOfTranslation, AxsAxisNo, AxsMode, axsused, AxsVector, CRTAXSROT, CRTAXSTRS, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAxisName(), MSD_lowDelElement(), NNIL, NPTYPE, SNIL, and SUCCESS.
Referenced by MSD_highRemoveAxis(), and MSD_lowRemoveGroup().
int MSD_modifyStructRemoveAxis (EulerOp * op)
Definition at line 191 of file hieaxsrm.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructRemoveAxis (FILE * f, EulerOp * op)
Definition at line 158 of file hieaxsrm.cpp.
References eulerop::ip1, and eulerop::solidno.
int MSD_readStructRemoveAxis (FILE * f, EulerOp * op)
Definition at line 167 of file hieaxsrm.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.