USPDesigner: C:/USPDesig/HIE/hieassas.cpp File Reference
C:/USPDesig/HIE/hieassas.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameAssociaSolidAxis (char *name1, char *name2)
int MSD_highAssociaSolidAxis (int sn, int an)
int MSD_lowAssociaSolidAxis (APTYPE aptr, SPTYPE optr)
int MSD_execStructAssociate (EulerOp *op)
void MSD_printStructAssociate (FILE *f, EulerOp *op)
int MSD_readStructAssociate (FILE *f, EulerOp *op)
int MSD_modifyStructAssociate (EulerOp *op)
Function Documentation
int MSD_execStructAssociate (EulerOp * op)
Definition at line 200 of file hieassas.cpp.
References AxisGroup, AxisSolid, ERROR, GroupGroup, GroupSolid, eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highAssociaGroupAxis(), MSD_highAssociaGroupGroup(), MSD_highAssociaGroupSolid(), MSD_highAssociaSolidAxis(), and SUCCESS.
int MSD_highAssociaSolidAxis (int sn, int an)
Definition at line 105 of file hieassas.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouSolido, MEN_PonteirosNulos, MSD_getAxis(), MSD_getSolid(), MSD_lowAssociaSolidAxis(), NAM_AssociaAxisSolid, SNIL, and SPTYPE.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaSolidAxis(), and MSD_highNameDesassociaSolidAxis().
int MSD_highNameAssociaSolidAxis (char * name1, char * name2)
Definition at line 70 of file hieassas.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouSolidNome, MSD_getAxisIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaSolidAxis(), and NAM_AssociaAxisSolid.
int MSD_lowAssociaSolidAxis (APTYPE aptr, SPTYPE optr)
Definition at line 128 of file hieassas.cpp.
References ANIL, ASSOCIATE, AxisGroup, AxisSolid, AxsAGroup, AxsASolid, AxsAxisNo, AxsType, Gdoinversion, GROUP, GrpGAxs, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SOLID, SolOAxs, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaSolidAxis(), MSD_highDesassociaSolidAxis(), MSD_highNameAssociateAxisElement(), and MSD_highNameDesassociateAxisElement().
int MSD_modifyStructAssociate (EulerOp * op)
Definition at line 264 of file hieassas.cpp.
References AXIS, AxisGroup, AxisSolid, GROUP, GroupGroup, GroupSolid, eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_lowCheckTranslatorTable(), SOLID, and SUCCESS.
void MSD_printStructAssociate (FILE * f, EulerOp * op)
Definition at line 229 of file hieassas.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
int MSD_readStructAssociate (FILE * f, EulerOp * op)
Definition at line 240 of file hieassas.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.