USPDesigner: C:/USPDesig/HIE/hieaxsrt.cpp File Reference
C:/USPDesig/HIE/hieaxsrt.cpp File Reference
#include <stdio.h>
#include <malloc.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameRotateAxis (char *name, real cx, real cy, real cz, real ax, real ay, real az, real th)
int MSD_highRotateAxis (int an, real cx, real cy, real cz, real ax, real ay, real az, real th)
int MSD_lowRotateAxis (APTYPE aptr, vector center, vector axis, real th)
int MSD_execStructRotateAxis (EulerOp *op)
void MSD_printStructRotateAxis (FILE *f, EulerOp *op)
int MSD_readStructRotateAxis (FILE *f, EulerOp *op)
int MSD_modifyStructRotateAxis (EulerOp *op)
Function Documentation
int MSD_execStructRotateAxis (EulerOp * op)
Definition at line 163 of file hieaxsrt.cpp.
References EULEROPS, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, MSD_highRotateAxis(), and eulerop::opnext.
int MSD_highNameRotateAxis (char * name, real cx, real cy, real cz, real ax, real ay, real az, real th)
Definition at line 77 of file hieaxsrt.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highRotateAxis(), and NAM_RotateAxis.
Referenced by MSD_highNameRotateElement().
int MSD_highRotateAxis (int an, real cx, real cy, real cz, real ax, real ay, real az, real th)
Definition at line 111 of file hieaxsrt.cpp.
References ANIL, APTYPE, ERROR, makevec(), MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowRotateAxis(), and NAM_RotateAxis.
Referenced by MSD_execStructRotateAxis(), and MSD_highNameRotateAxis().
int MSD_lowRotateAxis (APTYPE aptr, vector center, vector axis, real th)
Definition at line 127 of file hieaxsrt.cpp.
References AxisOfRotation, AxsAxisNo, AxsCenter, AxsMode, AxsVector, Gdoinversion, MSD_lowAddEulerOp(), ROTAXIS, rotmat(), SNIL, SUCCESS, vecminus(), vecmult(), and vecplus().
Referenced by MSD_highRotateAxis(), MSD_lowRotateGroup(), and MSD_lowRotateUsingAxis().
int MSD_modifyStructRotateAxis (EulerOp * op)
Definition at line 227 of file hieaxsrt.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructRotateAxis (FILE * f, EulerOp * op)
Definition at line 187 of file hieaxsrt.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
int MSD_readStructRotateAxis (FILE * f, EulerOp * op)
Definition at line 201 of file hieaxsrt.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.