USPDesigner: C:/USPDesig/HIE/hieaxstr.cpp File Reference
C:/USPDesig/HIE/hieaxstr.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "disdispl.h"
#include "hiegroup.h"
Functions
int MSD_highNameTransformUsingAxis (char *name, real desl)
int MSD_highTransformUsingAxis (int an, real desl)
int MSD_lowTransformUsingAxis (APTYPE aptr, real desl)
void MSD_lowTranslateUsingAxis (APTYPE aptr, vector disp)
void MSD_lowRotateUsingAxis (APTYPE aptr, vector center, vector vec, real th)
Function Documentation
int MSD_highNameTransformUsingAxis (char * name, real desl)
Definition at line 72 of file hieaxstr.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highTransformUsingAxis(), and NAM_TransformUsingAxis.
Referenced by CriaFrame(), and MSD_execManipulateAxis().
int MSD_highTransformUsingAxis (int an, real desl)
Definition at line 104 of file hieaxstr.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowTransformUsingAxis(), and NAM_TransformUsingAxis.
Referenced by MSD_highNameTransformUsingAxis().
void MSD_lowRotateUsingAxis (APTYPE aptr, vector center, vector vec, real th)
Definition at line 178 of file hieaxstr.cpp.
References AllAxis, AllGroup, AllSolids, APTYPE, AxsType, GPTYPE, GROUP, GrpGAxs, matident(), MSD_lowIsAncestorAxis(), MSD_lowIsAncestorGroup(), MSD_lowRotateAxis(), MSD_lowTransformation(), MSD_lowTranslate(), PI, rotmat(), SolGroup, SOLID, SolOAxs, and SPTYPE.
Referenced by MSD_lowTransformUsingAxis().
int MSD_lowTransformUsingAxis (APTYPE aptr, real desl)
Definition at line 117 of file hieaxstr.cpp.
References AxisOfRotation, AxisOfTranslation, AxsCenter, AxsMode, AxsVector, MSD_lowRotateUsingAxis(), MSD_lowTranslateUsingAxis(), SUCCESS, and vecesc().
Referenced by MSD_highTransformUsingAxis().
void MSD_lowTranslateUsingAxis (APTYPE aptr, vector disp)
Definition at line 135 of file hieaxstr.cpp.
References AllAxis, AllGroup, AllSolids, APTYPE, AxsType, GPTYPE, GROUP, GrpGAxs, MSD_lowIsAncestorAxis(), MSD_lowIsAncestorGroup(), MSD_lowMoveAxis(), MSD_lowTranslate(), SolGroup, SOLID, SolOAxs, and SPTYPE.
Referenced by MSD_lowTransformUsingAxis().