USPDesigner: C:/USPDesig/HIE/hieaxsrn.cpp File Reference
C:/USPDesig/HIE/hieaxsrn.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameRenameAxis (char *name1, char *name2)
int MSD_lowNameRenameAxis (APTYPE aptr, char *name2)
Function Documentation
int MSD_highNameRenameAxis (char * name1, char * name2)
Definition at line 70 of file hieaxsrn.cpp.
References ANIL, APTYPE, ERROR, MEN_AxisJaExiste, MEN_NaoEncontrouAxisNome, MSD_lowFindAxisByName(), MSD_lowNameRenameAxis(), and NAM_RenameAxis.
Referenced by MSD_highNameRenameElement().
int MSD_lowNameRenameAxis (APTYPE aptr, char * name2)
Definition at line 87 of file hieaxsrn.cpp.
References AxsName, and SUCCESS.
Referenced by MSD_highNameRenameAxis().