USPDesigner: C:/USPDesig/HIE/hieassag.cpp File Reference
C:/USPDesig/HIE/hieassag.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameAssociaGroupAxis (char *name1, char *name2)
int MSD_highAssociaGroupAxis (int sn, int an)
int MSD_lowAssociaGroupAxis (APTYPE aptr, GPTYPE gptr)
Function Documentation
int MSD_highAssociaGroupAxis (int sn, int an)
Definition at line 105 of file hieassag.cpp.
References ANIL, APTYPE, ERROR, GNIL, GPTYPE, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_PonteirosNulos, MSD_getAxis(), MSD_getGroup(), MSD_lowAssociaGroupAxis(), and NAM_AssociaAxisGroup.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupAxis(), and MSD_highNameDesassociaGroupAxis().
int MSD_highNameAssociaGroupAxis (char * name1, char * name2)
Definition at line 70 of file hieassag.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouGroupNome, MSD_getAxisIdFromName(), MSD_getGroupIdFromName(), MSD_highAssociaGroupAxis(), and NAM_AssociaAxisGroup.
int MSD_lowAssociaGroupAxis (APTYPE aptr, GPTYPE gptr)
Definition at line 128 of file hieassag.cpp.
References ANIL, ASSOCIATE, AxisGroup, AxisSolid, AxsAGroup, AxsASolid, AxsAxisNo, AxsType, Gdoinversion, GNIL, GROUP, GrpGAxs, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SOLID, SolOAxs, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaGroupAxis(), MSD_highDesassociaGroupAxis(), MSD_highNameAssociateAxisElement(), and MSD_highNameDesassociateAxisElement().