USPDesigner: C:/USPDesig/HIE/hieaxsmv.cpp File Reference
C:/USPDesig/HIE/hieaxsmv.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "disdispl.h"
#include "hiegroup.h"
Functions
int MSD_highNameMoveAxis (char *name, real x, real y, real z)
int MSD_highMoveAxis (int an, real x, real y, real z)
int MSD_lowMoveAxis (APTYPE aptr, vector vec)
int MSD_execStructMoveAxis (EulerOp *op)
void MSD_printStructMoveAxis (FILE *f, EulerOp *op)
int MSD_readStructMoveAxis (FILE *f, EulerOp *op)
int MSD_modifyStructMoveAxis (EulerOp *op)
Function Documentation
int MSD_execStructMoveAxis (EulerOp * op)
Definition at line 137 of file hieaxsmv.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and MSD_highMoveAxis().
int MSD_highMoveAxis (int an, real x, real y, real z)
Definition at line 104 of file hieaxsmv.cpp.
References ANIL, APTYPE, ERROR, makevec(), MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowMoveAxis(), and NAM_MoveAxis.
Referenced by MSD_execStructMoveAxis(), and MSD_highNameMoveAxis().
int MSD_highNameMoveAxis (char * name, real x, real y, real z)
Definition at line 72 of file hieaxsmv.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highMoveAxis(), and NAM_MoveAxis.
Referenced by MSD_highNameTranslateElement().
int MSD_lowMoveAxis (APTYPE aptr, vector vec)
Definition at line 119 of file hieaxsmv.cpp.
References AxisOfTranslation, AxsAxisNo, AxsCenter, AxsMode, Gdoinversion, MOVAXIS, MSD_lowAddEulerOp(), SNIL, SUCCESS, and vecplus().
Referenced by MSD_highMoveAxis(), MSD_lowMoveGroup(), and MSD_lowTranslateUsingAxis().
int MSD_modifyStructMoveAxis (EulerOp * op)
Definition at line 189 of file hieaxsmv.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructMoveAxis (FILE * f, EulerOp * op)
Definition at line 149 of file hieaxsmv.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
int MSD_readStructMoveAxis (FILE * f, EulerOp * op)
Definition at line 163 of file hieaxsmv.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.