USPDesigner: C:/USPDesig/HIE/hiedesag.cpp File Reference
C:/USPDesig/HIE/hiedesag.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameDesassociaGroupAxis (char *name1, char *name2)
int MSD_highDesassociaGroupAxis (int gn, int an)
Function Documentation
int MSD_highDesassociaGroupAxis (int gn, int an)
Definition at line 107 of file hiedesag.cpp.
References ANIL, APTYPE, AxsAGroup, AxsType, ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_ParametrosIncorretos, MSD_getAxis(), MSD_getGroup(), MSD_lowAssociaGroupAxis(), and NAM_DesassociaAxisGroup.
int MSD_highNameDesassociaGroupAxis (char * name1, char * name2)
Definition at line 70 of file hiedesag.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouGroupNome, MSD_getAxisIdFromName(), MSD_getGroupIdFromName(), MSD_highAssociaGroupAxis(), and NAM_DesassociaAxisGroup.