USPDesigner: C:/USPDesig/HIE/hiedesgg.cpp File Reference
C:/USPDesig/HIE/hiedesgg.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameDesassociaGroupGroup (char *name1, char *name2)
int MSD_highDesassociaGroupGroup (int gn1, int gn2)
Function Documentation
int MSD_highDesassociaGroupGroup (int gn1, int gn2)
Definition at line 107 of file hiedesgg.cpp.
References ERROR, GNIL, GPTYPE, GrpParent, MEN_NaoEncontrouGroupId, MEN_ParametrosIncorretos, MSD_getGroup(), MSD_lowAssociaGroupGroup(), and NAM_DesassociaGroupGroup.
int MSD_highNameDesassociaGroupGroup (char * name1, char * name2)
Definition at line 70 of file hiedesgg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highAssociaGroupGroup(), and NAM_DesassociaGroupGroup.