USPDesigner: C:/USPDesig/HIE/hiedesgs.cpp File Reference
C:/USPDesig/HIE/hiedesgs.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameDesassociaGroupSolid (char *name1, char *name2)
int MSD_highDesassociaGroupSolid (int gn, int sn)
Function Documentation
int MSD_highDesassociaGroupSolid (int gn, int sn)
Definition at line 107 of file hiedesgs.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MEN_ParametrosIncorretos, MSD_getGroup(), MSD_getSolid(), MSD_lowAssociaGroupSolid(), NAM_DesassociaGroupSolid, SNIL, SolGroup, and SPTYPE.
Referenced by MSD_lowSoftRemove().
int MSD_highNameDesassociaGroupSolid (char * name1, char * name2)
Definition at line 70 of file hiedesgs.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MEN_NaoEncontrouSolidNome, MSD_getGroupIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaGroupSolid(), and NAM_DesassociaGroupSolid.