USPDesigner: C:/USPDesig/HIE/hiegrpcs.cpp File Reference
C:/USPDesig/HIE/hiegrpcs.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
int MSD_highNameCreateSetGroup (char *name1, char *name2)
int MSD_highCreateSetGroup (int flag)
Function Documentation
int MSD_highCreateSetGroup (int flag)
Definition at line 108 of file hiegrpcs.cpp.
References ERROR, MSD_getMaxGroupId(), MSD_highSetGroupCurrent(), and MSD_lowCreateGroup().
Referenced by MSD_highNameCreateSetGroup().
int MSD_highNameCreateSetGroup (char * name1, char * name2)
Definition at line 71 of file hiegrpcs.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCreateSetGroup(), NAM_CreateGroupSetCurrent, and SUCCESS.
Referenced by MSD_execManipulateGroup().