USPDesigner: C:/USPDesig/HIE/hiegrpsc.cpp File Reference
C:/USPDesig/HIE/hiegrpsc.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
void MSD_highNameSetGroupCurrent (char *nam)
int MSD_highSetGroupCurrent (int gn)
int MSD_lowSetGroupCurrent (GPTYPE gptr)
int MSD_execStructSetGroupCurrent (EulerOp *op)
void MSD_printStructSetGroupCurrent (FILE *f, EulerOp *op)
int MSD_readStructSetGroupCurrent (FILE *f, EulerOp *op)
int MSD_modifyStructSetGroupCurrent (EulerOp *op)
Function Documentation
int MSD_execStructSetGroupCurrent (EulerOp * op)
Definition at line 150 of file hiegrpsc.cpp.
References eulerop::ip1, and MSD_highSetGroupCurrent().
void MSD_highNameSetGroupCurrent (char * nam)
Definition at line 72 of file hiegrpsc.cpp.
References def_grpptr, GNIL, GPTYPE, GrpParent, MEN_NaoEncontrouGroupNome, MEN_NaoPossuiAncestral, MSD_lowFindGroupByName(), MSD_lowSetGroupCurrent(), and NAM_SetCurrentGroup.
Referenced by MSD_execManipulateGroup().
int MSD_highSetGroupCurrent (int gn)
Definition at line 123 of file hiegrpsc.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowSetGroupCurrent(), and NAM_SetCurrentGroup.
Referenced by MSD_execStructSetGroupCurrent(), and MSD_highCreateSetGroup().
int MSD_lowSetGroupCurrent (GPTYPE gptr)
Definition at line 135 of file hiegrpsc.cpp.
References def_grpptr, Gdoinversion, GNIL, GrpGroupNo, MSD_lowAddEulerOp(), SETGRP, SNIL, and SUCCESS.
Referenced by MSD_highNameSetGroupCurrent(), and MSD_highSetGroupCurrent().
int MSD_modifyStructSetGroupCurrent (EulerOp * op)
Definition at line 188 of file hiegrpsc.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructSetGroupCurrent (FILE * f, EulerOp * op)
Definition at line 155 of file hiegrpsc.cpp.
References eulerop::ip1, and eulerop::solidno.
int MSD_readStructSetGroupCurrent (FILE * f, EulerOp * op)
Definition at line 164 of file hiegrpsc.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.