USPDesigner: C:/USPDesig/HIE/hiegrprg.cpp File Reference
C:/USPDesig/HIE/hiegrprg.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "eulerops.h"
#include "hiegroup.h"
Functions
int MSD_highNameRemoveOneGroup (char *name)
int MSD_highRemoveOneGroup (int gn)
int MSD_lowRemoveOneGroup (GPTYPE gptr)
int MSD_execStructRemoveOneGroup (EulerOp *op)
void MSD_printStructRemoveOneGroup (FILE *f, EulerOp *op)
int MSD_readStructRemoveOneGroup (FILE *f, EulerOp *op)
int MSD_modifyStructRemoveOneGroup (EulerOp *op)
Function Documentation
int MSD_execStructRemoveOneGroup (EulerOp * op)
Definition at line 148 of file hiegrprg.cpp.
References eulerop::ip1, and MSD_highRemoveOneGroup().
int MSD_highNameRemoveOneGroup (char * name)
Definition at line 71 of file hiegrprg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRemoveOneGroup(), and NAM_RemoveOneGroup.
int MSD_highRemoveOneGroup (int gn)
Definition at line 101 of file hiegrprg.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowRemoveOneGroup(), and NAM_RemoveOneGroup.
Referenced by MSD_execStructRemoveOneGroup(), and MSD_highNameRemoveOneGroup().
int MSD_lowRemoveOneGroup (GPTYPE gptr)
Definition at line 113 of file hiegrprg.cpp.
References AllGroup, AllSolids, CRTGRP, Gdoinversion, GPTYPE, GROUP, GrpGColor, GrpGroupNo, GrpName, GrpParent, grpused, MSD_lowAddEulerOp(), MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowDelElement(), MSD_lowGroupColor(), MSD_lowGroupName(), NNIL, NPTYPE, SNIL, SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highRemoveOneGroup(), and MSD_lowRemoveGroup().
int MSD_modifyStructRemoveOneGroup (EulerOp * op)
Definition at line 186 of file hiegrprg.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructRemoveOneGroup (FILE * f, EulerOp * op)
Definition at line 153 of file hiegrprg.cpp.
References eulerop::ip1, and eulerop::solidno.
int MSD_readStructRemoveOneGroup (FILE * f, EulerOp * op)
Definition at line 162 of file hiegrprg.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.