USPDesigner: C:/USPDesig/HIE/hiegrprm.cpp File Reference
C:/USPDesig/HIE/hiegrprm.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "eulerops.h"
#include "hiegroup.h"
Functions
int MSD_highNameRemoveGroup (char *name)
int MSD_highRemoveGroup (int gn)
int MSD_lowRemoveGroup (GPTYPE gptr)
Function Documentation
int MSD_highNameRemoveGroup (char * name)
Definition at line 71 of file hiegrprm.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRemoveGroup(), and NAM_RemoveGroup.
Referenced by MSD_execManipulateGroup(), and MSD_highNameDeleteElement().
int MSD_highRemoveGroup (int gn)
Definition at line 101 of file hiegrprm.cpp.
References def_grpptr, ERROR, GNIL, GPTYPE, MEN_GrupoCorrenteEliminado, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowIsAncestorGroup(), MSD_lowRemoveGroup(), and NAM_RemoveGroup.
Referenced by MSD_highNameRemoveGroup(), and MSD_lowCopyGroup().
int MSD_lowRemoveGroup (GPTYPE gptr)
Definition at line 118 of file hiegrprm.cpp.
References ANIL, APTYPE, axsary, AxsNextA, GNIL, GPTYPE, grpary, GrpNextG, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), MSD_lowSoftRemove(), objary, SNIL, SolGroup, SolNxt, SPTYPE, and SUCCESS.
Referenced by MSD_highRemoveGroup().