USPDesigner: C:/USPDesig/HIE/hiegrpmn.cpp File Reference
C:/USPDesig/HIE/hiegrpmn.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
Id MSD_getGroupIdFromName (char *name)
Id MSD_getMaxGroupId (void)
int MSD_getNumberOfGroups (void)
char ** MSD_putGroupNameInList (char **list)
GPTYPE MSD_lowFindGroupByName (char *nam)
GPTYPE MSD_getGroup (Id gn)
char MSD_lowIsEmptyGroup (GPTYPE grpptr)
char MSD_lowIsAncestorGroup (GPTYPE ancgptr, GPTYPE desgptr)
char MSD_lowIsAncestorAxis (APTYPE ancaptr, APTYPE desaptr)
GPTYPE MSD_getGroupAxis (APTYPE axis)
Function Documentation
GPTYPE MSD_getGroup (Id gn)
Definition at line 131 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, and GrpGroupNo.
Referenced by MSD_highAssociaGroupAxis(), MSD_highAssociaGroupGroup(), MSD_highAssociaGroupSolid(), MSD_highColor(), MSD_highCopyGroup(), MSD_highDesassociaGroupAxis(), MSD_highDesassociaGroupGroup(), MSD_highDesassociaGroupSolid(), MSD_highMoveGroup(), MSD_highName(), MSD_highNameCopyGroup(), MSD_highNameCreateGroup(), MSD_highNameCreateSetGroup(), MSD_highRemoveGroup(), MSD_highRemoveOneGroup(), MSD_highRotateGroup(), MSD_highSetGroupCurrent(), MSD_highTransferGroup(), and MSD_lowCopyGroup().
GPTYPE MSD_getGroupAxis (APTYPE axis)
Definition at line 202 of file hiegrpmn.cpp.
References AxsAGroup, AxsASolid, AxsType, GNIL, GROUP, SolGroup, and SOLID.
Referenced by MSD_lowIsAncestorAxis(), MSD_lowMoveGroup(), MSD_lowRemoveGroup(), and MSD_lowRotateGroup().
Id MSD_getGroupIdFromName (char * name)
Definition at line 52 of file hiegrpmn.cpp.
References AllGroup, GPTYPE, GrpGroupNo, and GrpName.
Referenced by MSD_highNameAssociaGroupAxis(), MSD_highNameAssociaGroupGroup(), MSD_highNameAssociaGroupSolid(), MSD_highNameCopyGroup(), MSD_highNameCreateGroup(), MSD_highNameCreateSetGroup(), MSD_highNameDesassociaGroupAxis(), MSD_highNameDesassociaGroupGroup(), MSD_highNameDesassociaGroupSolid(), MSD_highNameMoveGroup(), MSD_highNameRemoveGroup(), MSD_highNameRemoveOneGroup(), MSD_highNameRotateGroup(), and MSD_highNameTransferGroup().
Id MSD_getMaxGroupId (void)
Definition at line 72 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, grpary, and GrpGroupNo.
Referenced by MSD_highCopyGroup(), MSD_highCreateGroup(), MSD_highCreateSetGroup(), and MSD_lowCheckTranslatorTable().
int MSD_getNumberOfGroups (void)
Definition at line 92 of file hiegrpmn.cpp.
References AllGroup, and GPTYPE.
GPTYPE MSD_lowFindGroupByName (char * nam)
Definition at line 117 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, and GrpName.
Referenced by MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highNameGroupColor(), MSD_highNameListGroupName(), MSD_highNameRenameGroup(), MSD_highNameSetDisplay(), MSD_highNameSetGroupCurrent(), MSD_resetGroup(), and MSD_selectGroup().
char MSD_lowIsAncestorAxis (APTYPE ancaptr, APTYPE desaptr)
Definition at line 188 of file hiegrpmn.cpp.
References FALSE, GNIL, GPTYPE, GrpGAxs, GrpParent, MSD_getGroupAxis(), and TRUE.
Referenced by MSD_lowRotateUsingAxis(), and MSD_lowTranslateUsingAxis().
char MSD_lowIsAncestorGroup (GPTYPE ancgptr, GPTYPE desgptr)
Definition at line 174 of file hiegrpmn.cpp.
References FALSE, GNIL, GPTYPE, GrpParent, and TRUE.
Referenced by MSD_highNameSetDisplay(), MSD_highRemoveGroup(), MSD_highTransferGroup(), MSD_lowCopyGroup(), MSD_lowDisplayMonitorGroup(), MSD_lowMoveGroup(), MSD_lowRemoveGroup(), MSD_lowRotateGroup(), MSD_lowRotateUsingAxis(), MSD_lowTranslateUsingAxis(), MSD_resetGroup(), and MSD_selectGroup().
char MSD_lowIsEmptyGroup (GPTYPE grpptr)
Definition at line 145 of file hiegrpmn.cpp.
References AllGroup, AllSolids, FALSE, GNIL, GPTYPE, GrpParent, SolGroup, SPTYPE, and TRUE.
char** MSD_putGroupNameInList (char ** list)
Definition at line 104 of file hiegrpmn.cpp.
References AllGroup, GPTYPE, and GrpName.