USPDesigner: C:/USPDesig/HIE/hiegrpmv.cpp File Reference
C:/USPDesig/HIE/hiegrpmv.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
int MSD_highNameMoveGroup (char *name, real x, real y, real z)
int MSD_highMoveGroup (int gn, real x, real y, real z)
int MSD_lowMoveGroup (GPTYPE gptr, vector disp)
Function Documentation
int MSD_highMoveGroup (int gn, real x, real y, real z)
Definition at line 103 of file hiegrpmv.cpp.
References ERROR, GNIL, GPTYPE, makevec(), MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowMoveGroup(), and NAM_MoveGroup.
Referenced by MSD_highNameMoveGroup().
int MSD_highNameMoveGroup (char * name, real x, real y, real z)
Definition at line 72 of file hiegrpmv.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highMoveGroup(), and NAM_MoveGroup.
Referenced by MSD_highNameTranslateElement().
int MSD_lowMoveGroup (GPTYPE gptr, vector disp)
Definition at line 117 of file hiegrpmv.cpp.
References AllAxis, AllSolids, APTYPE, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowMoveAxis(), MSD_lowTranslate(), SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highMoveGroup().