USPDesigner: C:/USPDesig/HIE/hiegrpcr.cpp File Reference
C:/USPDesig/HIE/hiegrpcr.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "eulerops.h"
#include "hiegroup.h"
Functions
int MSD_highNameCreateGroup (char *name)
int MSD_highCreateGroup (void)
int MSD_middleCreateGroup (int gn)
int MSD_lowCreateGroup (Id gn)
int MSD_execStructCreateGroup (EulerOp *op)
void MSD_printStructCreateGroup (FILE *f, EulerOp *op)
int MSD_readStructCreateGroup (FILE *f, EulerOp *op)
int MSD_modifyStructCreateGroup (EulerOp *op)
Function Documentation
int MSD_execStructCreateGroup (EulerOp * op)
Definition at line 131 of file hiegrpcr.cpp.
References eulerop::ip1, and MSD_middleCreateGroup().
int MSD_highCreateGroup (void)
Definition at line 99 of file hiegrpcr.cpp.
References ERROR, MSD_getMaxGroupId(), and MSD_lowCreateGroup().
Referenced by MSD_highNameCreateGroup().
int MSD_highNameCreateGroup (char * name)
Definition at line 72 of file hiegrpcr.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCreateGroup(), NAM_CreateGroup, and SUCCESS.
int MSD_lowCreateGroup (Id gn)
Definition at line 112 of file hiegrpcr.cpp.
References ERROR, Gdoinversion, GNIL, GPTYPE, GROUP, GrpGroupNo, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateGroup, NNIL, REMGRP, SNIL, and SUCCESS.
Referenced by MSD_highCreateGroup(), MSD_highCreateSetGroup(), and MSD_middleCreateGroup().
int MSD_middleCreateGroup (int gn)
Definition at line 107 of file hiegrpcr.cpp.
References MSD_lowCreateGroup().
Referenced by MSD_execStructCreateGroup().
int MSD_modifyStructCreateGroup (EulerOp * op)
Definition at line 169 of file hiegrpcr.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructCreateGroup (FILE * f, EulerOp * op)
Definition at line 136 of file hiegrpcr.cpp.
References eulerop::ip1, and eulerop::solidno.
int MSD_readStructCreateGroup (FILE * f, EulerOp * op)
Definition at line 145 of file hiegrpcr.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.