USPDesigner: C:/USPDesig/HIE/hiegrpcy.cpp File Reference
C:/USPDesig/HIE/hiegrpcy.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
#include "shpshape.h"
Functions
int MSD_highNameCopyGroup (char *name1, char *name2)
int MSD_highCopyGroup (int gn)
int MSD_lowCopyGroup (GPTYPE gptr, Id gn)
Function Documentation
int MSD_highCopyGroup (int gn)
Definition at line 117 of file hiegrpcy.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_getMaxGroupId(), MSD_lowCopyGroup(), and NAM_CopyGroup.
Referenced by MSD_highNameCopyGroup().
int MSD_highNameCopyGroup (char * name1, char * name2)
Definition at line 73 of file hiegrpcy.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MEN_NaoEncontrouGroupNome, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCopyGroup(), NAM_CopyGroup, and SUCCESS.
Referenced by MSD_highNameCopyElement().
int MSD_lowCopyGroup (GPTYPE gptr, Id gn)
Definition at line 132 of file hiegrpcy.cpp.
References AllSolids, EulerOpNext, EULEROPS, FALSE, Gdoinversion, GPTYPE, GROUP, GrpGroupNo, MSD_getGroup(), MSD_highRemoveGroup(), MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowIniciaTranslatorTable(), MSD_lowIsAncestorGroup(), MSD_lowModifyEulerOp(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSetTranslatorTable(), OpHead, PEulerOp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_highCopyGroup().