USPDesigner: C:/USPDesig/HIE/hiegrpli.cpp File Reference
C:/USPDesig/HIE/hiegrpli.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
int MSD_highNameListGroupName (char *name)
int MSD_lowNameListGroupName (GPTYPE gptr)
void MSD_lowListAllGroup (void)
void MSD_lowListGroup (GPTYPE gptr)
void MSD_lowListAllGroupName (void)
Function Documentation
int MSD_highNameListGroupName (char * name)
Definition at line 71 of file hiegrpli.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupNome, MSD_lowFindGroupByName(), MSD_lowNameListGroupName(), and NAM_ListGroup.
void MSD_lowListAllGroup (void)
Definition at line 108 of file hiegrpli.cpp.
References AllGroup, GPTYPE, and MSD_lowListGroup().
Referenced by MSD_execShow().
void MSD_lowListAllGroupName (void)
Definition at line 135 of file hiegrpli.cpp.
References AllGroup, GPTYPE, and GrpName.
Referenced by MSD_execListElement().
void MSD_lowListGroup (GPTYPE gptr)
Definition at line 118 of file hiegrpli.cpp.
References ANIL, AxsName, GNIL, GrpGAxs, GrpGColor, GrpName, and GrpParent.
Referenced by MSD_execShow(), and MSD_lowListAllGroup().
int MSD_lowNameListGroupName (GPTYPE gptr)
Definition at line 83 of file hiegrpli.cpp.
References AllSolids, GNIL, GrpName, GrpParent, SolGroup, SolName, SPTYPE, and SUCCESS.
Referenced by MSD_highNameListGroupName().