USPDesigner: C:/USPDesig/HIE/hiegrpdf.cpp File Reference
C:/USPDesig/HIE/hiegrpdf.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "hiegroup.h"
Functions
void MSD_execManipulateGroup (void)
Function Documentation
void MSD_execManipulateGroup (void)
Definition at line 51 of file hiegrpdf.cpp.
References lineins(), MSD_highNameAssociateGroupElement(), MSD_highNameCreateSetGroup(), MSD_highNameDesassociateGroupElement(), MSD_highNameRemoveGroup(), MSD_highNameSetGroupCurrent(), MSD_highNameTransferGroup(), optin(), and restbuf.