USPDesigner: C:/USPDesig/INC/hiegroup.h File Reference
C:/USPDesig/INC/hiegroup.h File Reference
#include <stdio.h>
Classes
struct grouptp
union hierarq
struct axistp
Defines
#define EXTERN extern
Typedefs
typedef double real
typedef real matrix [4][4]
typedef int Id
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
typedef struct axistp ATYPE
typedef struct grouptp GTYPE
typedef struct eulerop EulerOp
typedef union hierarq QTYPE
Functions
char * x_malloc (unsigned int a)
char * x_calloc (unsigned int a, unsigned int b)
char x_free (char *a)
GPTYPE MSD_getGroup (Id)
APTYPE MSD_getAxis (Id)
Id MSD_getGroupIdFromName (char *)
Id MSD_getAxisIdFromName (char *)
Id MSD_getMaxGroupId (void)
void MSD_execNameAssociaGroupAxis (void)
int MSD_highNameAssociaGroupAxis (char *name1, char *name2)
void MSD_execAssociaGroupAxis (void)
int MSD_highAssociaGroupAxis (int sn, int an)
int MSD_lowAssociaGroupAxis (APTYPE aptr, GPTYPE gptr)
void MSD_execNameAssociaSolidAxis (void)
int MSD_highNameAssociaSolidAxis (char *, char *)
void MSD_execAssociaSolidAxis (void)
int MSD_highAssociaSolidAxis (int sn, int an)
int MSD_lowAssociaSolidAxis (APTYPE aptr, SPTYPE optr)
int MSD_execStructAssociate (EulerOp *op)
void MSD_printStructAssociate (FILE *f, EulerOp *op)
int MSD_readStructAssociate (FILE *f, EulerOp *op)
int MSD_modifyStructAssociate (EulerOp *op)
void MSD_execNameAssociaGroupGroup (void)
int MSD_highNameAssociaGroupGroup (char *name1, char *name2)
void MSD_execAssociaGroupGroup (void)
int MSD_highAssociaGroupGroup (int gn1, int gn2)
int MSD_lowAssociaGroupGroup (GPTYPE gptr1, GPTYPE gptr2)
void MSD_execNameAssociaGroupSolid (void)
int MSD_highNameAssociaGroupSolid (char *name1, char *name2)
void MSD_execAssociaGroupSolid (void)
int MSD_highAssociaGroupSolid (int gn, int sn)
int MSD_lowAssociaGroupSolid (GPTYPE gptr, SPTYPE optr)
void MSD_execNameCreateAxisTranslation (void)
int MSD_highNameCreateAxisTranslation (char *name, real x, real y, real z)
void MSD_execCreateAxisTranslation (void)
int MSD_highCreateAxisTranslation (real x, real y, real z)
int MSD_middleCreateAxisTranslation (int an, real x, real y, real z)
int MSD_lowCreateAxisTranslation (int an, vector vec)
int MSD_execStructCrtAxsTranslation (EulerOp *op)
void MSD_printStructCrtAxsTranslation (FILE *f, EulerOp *op)
int MSD_readStructCrtAxsTranslation (FILE *f, EulerOp *op)
int MSD_modifyStructCrtAxsTranslation (EulerOp *op)
void MSD_execNameCreateAxisRotation (void)
int MSD_highNameCreateAxisRotation (char *name, real x1, real y1, real z1, real x2, real y2, real z2)
void MSD_execCreateAxisRotation (void)
int MSD_highCreateAxisRotation (real x1, real y1, real z1, real x2, real y2, real z2)
int MSD_middleCreateAxisRotation (int an, real x1, real y1, real z1, real x2, real y2, real z2)
int MSD_lowCreateAxisRotation (Id an, vector pos, vector vec)
int MSD_execStructCrtAxsRotation (EulerOp *op)
void MSD_printStructCrtAxsRotation (FILE *f, EulerOp *op)
int MSD_readStructCrtAxsRotation (FILE *f, EulerOp *op)
int MSD_modifyStructCrtAxsRotation (EulerOp *op)
void MSD_execManipulateAxis (void)
void MSD_execNameListAxisName (void)
int MSD_highNameListAxisName (char *name)
int MSD_lowListAxisName (APTYPE aptr)
void MSD_lowListAllAxis (void)
void MSD_lowListAllAxisName (void)
int MSD_getMaxAxisId (void)
int MSD_getNumberOfAxis (void)
char ** MSD_putAxisNameInList (char **list)
APTYPE MSD_lowFindAxisByName (char *nam)
void MSD_execNameMoveAxis (void)
int MSD_highNameMoveAxis (char *name, real x, real y, real z)
void MSD_execMoveAxis (void)
int MSD_highMoveAxis (int an, real x, real y, real z)
int MSD_lowMoveAxis (APTYPE aptr, vector vec)
int MSD_execStructMoveAxis (EulerOp *op)
void MSD_printStructMoveAxis (FILE *f, EulerOp *op)
int MSD_readStructMoveAxis (FILE *f, EulerOp *op)
int MSD_modifyStructMoveAxis (EulerOp *op)
void MSD_execNameRemoveAxis (void)
int MSD_highNameRemoveAxis (char *name)
void MSD_execRemoveAxis (void)
int MSD_highRemoveAxis (int an)
int MSD_lowRemoveAxis (APTYPE aptr)
int MSD_execStructRemoveAxis (EulerOp *op)
void MSD_printStructRemoveAxis (FILE *f, EulerOp *op)
int MSD_readStructRemoveAxis (FILE *f, EulerOp *op)
int MSD_modifyStructRemoveAxis (EulerOp *op)
void MSD_execNameRenameAxis (void)
int MSD_highNameRenameAxis (char *name1, char *name2)
int MSD_lowNameRenameAxis (APTYPE aptr, char *name2)
void MSD_execNameRotateAxis (void)
int MSD_highNameRotateAxis (char *name, real cx, real cy, real cz, real ax, real ay, real az, real th)
void MSD_execRotateAxis (void)
int MSD_highRotateAxis (int an, real cx, real cy, real cz, real ax, real ay, real az, real th)
int MSD_lowRotateAxis (APTYPE aptr, vector center, vector axis, real th)
int MSD_execStructRotateAxis (EulerOp *op)
void MSD_printStructRotateAxis (FILE *f, EulerOp *op)
int MSD_readStructRotateAxis (FILE *f, EulerOp *op)
int MSD_modifyStructRotateAxis (EulerOp *op)
void MSD_execNameTransformUsingAxis (void)
int MSD_highNameTransformUsingAxis (char *name, real desl)
void MSD_execTransformUsingAxis (void)
int MSD_highTransformUsingAxis (int an, real desl)
int MSD_lowTransformUsingAxis (APTYPE aptr, real desl)
void MSD_lowTranslateUsingAxis (APTYPE aptr, vector disp)
void MSD_lowRotateUsingAxis (APTYPE aptr, vector center, vector vec, real th)
void MSD_execNameDesassociaGroupAxis (void)
int MSD_highNameDesassociaGroupAxis (char *name1, char *name2)
void MSD_execDesassociaGroupAxis (void)
int MSD_highDesassociaGroupAxis (int gn, int an)
void MSD_execNameDesassociaSolidAxis (void)
int MSD_highNameDesassociaSolidAxis (char *name1, char *name2)
void MSD_execDesassociaSolidAxis (void)
int MSD_highDesassociaSolidAxis (int sn, int an)
void MSD_execNameDesassociaGroupGroup (void)
int MSD_highNameDesassociaGroupGroup (char *name1, char *name2)
void MSD_execDesassociaGroupGroup (void)
int MSD_highDesassociaGroupGroup (int gn1, int gn2)
int MSD_highNameDesassociaGroupSolid (char *name1, char *name2)
void MSD_execDesassociaGroupSolid (void)
int MSD_highDesassociaGroupSolid (int gn, int sn)
void MSD_execNameDesassociaGroupSolid (void)
void MSD_execNameCreateGroup (void)
int MSD_highNameCreateGroup (char *name)
void MSD_execCreateGroup (void)
int MSD_highCreateGroup (void)
int MSD_middleCreateGroup (int gn)
int MSD_lowCreateGroup (Id gn)
int MSD_execStructCreateGroup (EulerOp *op)
void MSD_printStructCreateGroup (FILE *f, EulerOp *op)
int MSD_readStructCreateGroup (FILE *f, EulerOp *op)
int MSD_modifyStructCreateGroup (EulerOp *op)
void MSD_execNameCreateSetGroup (void)
int MSD_highNameCreateSetGroup (char *name1, char *name2)
void MSD_execCreateSetGroup (void)
int MSD_highCreateSetGroup (int flag)
void MSD_execNameCopyGroup (void)
int MSD_highNameCopyGroup (char *name1, char *name2)
void MSD_execCopyGroup (void)
int MSD_highCopyGroup (int gn)
int MSD_lowCopyGroup (GPTYPE gptr, Id gn)
void MSD_execManipulateGroup (void)
void MSD_execNameListGroupName (void)
int MSD_highNameListGroupName (char *name)
int MSD_lowNameListGroupName (GPTYPE gptr)
void MSD_lowListAllGroup (void)
void MSD_lowListGroup (GPTYPE gptr)
void MSD_lowListAllGroupName (void)
int MSD_getNumberOfGroups (void)
char ** MSD_putGroupNameInList (char **list)
GPTYPE MSD_lowFindGroupByName (char *nam)
char MSD_lowIsEmptyGroup (GPTYPE grpptr)
char MSD_lowIsAncestorGroup (GPTYPE ancgptr, GPTYPE desgptr)
char MSD_lowIsAncestorAxis (APTYPE ancaptr, APTYPE desaptr)
GPTYPE MSD_getGroupAxis (APTYPE axis)
void MSD_execNameMoveGroup (void)
int MSD_highNameMoveGroup (char *name, real x, real y, real z)
void MSD_execMoveGroup (void)
int MSD_highMoveGroup (int gn, real x, real y, real z)
int MSD_lowMoveGroup (GPTYPE gptr, vector disp)
void MSD_execNameRemoveOneGroup (void)
int MSD_highNameRemoveOneGroup (char *name)
void MSD_execRemoveOneGroup (void)
int MSD_highRemoveOneGroup (int gn)
int MSD_lowRemoveOneGroup (GPTYPE gptr)
int MSD_execStructRemoveOneGroup (EulerOp *op)
void MSD_printStructRemoveOneGroup (FILE *f, EulerOp *op)
int MSD_readStructRemoveOneGroup (FILE *f, EulerOp *op)
int MSD_modifyStructRemoveOneGroup (EulerOp *op)
void MSD_execNameRemoveGroup (void)
int MSD_highNameRemoveGroup (char *name)
void MSD_execRemoveGroup (void)
int MSD_highRemoveGroup (int gn)
int MSD_lowRemoveGroup (GPTYPE gptr)
void MSD_execNameRenameGroup (void)
int MSD_highNameRenameGroup (char *name1, char *name2)
int MSD_lowNameRenameGroup (GPTYPE gptr, char *name2)
void MSD_execNameRotateGroup (void)
int MSD_highNameRotateGroup (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
void MSD_execRotateGroup (void)
int MSD_highRotateGroup (Id gn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_lowRotateGroup (GPTYPE gptr, vector center, vector vec, real th)
void MSD_execNameSetGroupCurrent (void)
void MSD_highNameSetGroupCurrent (char *nam)
void MSD_execSetGroupCurrent (void)
int MSD_highSetGroupCurrent (int gn)
int MSD_lowSetGroupCurrent (GPTYPE gptr)
int MSD_execStructSetGroupCurrent (EulerOp *op)
void MSD_printStructSetGroupCurrent (FILE *f, EulerOp *op)
int MSD_readStructSetGroupCurrent (FILE *f, EulerOp *op)
int MSD_modifyStructSetGroupCurrent (EulerOp *op)
void MSD_execNameTransferGroup (void)
int MSD_highNameTransferGroup (char *name1, char *name2)
void MSD_execTransferGroup (void)
int MSD_highTransferGroup (int gn1, int gn2)
void MSD_readExecuteMoveElement (void)
void MSD_executeMoveElement (char *name, real dx, real dy, real dz)
int _move (char *name, vector disp, int moni)
void MSD_readExecuteRotateElement (void)
void MSD_executeRotateElement (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int _rotate (char *name, vector center, vector vector, real th, int moni)
void MSD_readExecuteAffineElement (void)
char _affine (char *name, vector center, matrix mat, int moni)
void objrot (STYPE *optr, vector center, vector axis, real th)
void MSD_executeAffineElement (char *name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
Variables
EXTERN APTYPE axsary
EXTERN int axsused
EXTERN Id AxisNo
EXTERN GPTYPE grpary
EXTERN GPTYPE def_grpptr
EXTERN int grpused
EXTERN Id GroupNo
Define Documentation
#define EXTERN extern
Definition at line 51 of file hiegroup.h.
Typedef Documentation
typedef struct axistp ATYPE
Definition at line 101 of file hiegroup.h.
typedef struct edge ETYPE
Definition at line 89 of file hiegroup.h.
typedef struct eulerop EulerOp
Definition at line 109 of file hiegroup.h.
typedef struct face FTYPE
Definition at line 81 of file hiegroup.h.
typedef struct grouptp GTYPE
Definition at line 105 of file hiegroup.h.
typedef struct halfedge HTYPE
Definition at line 93 of file hiegroup.h.
typedef int Id
Definition at line 69 of file hiegroup.h.
typedef struct loop LTYPE
Definition at line 85 of file hiegroup.h.
typedef real matrix[4][4]
Definition at line 65 of file hiegroup.h.
typedef union hierarq QTYPE
Definition at line 112 of file hiegroup.h.
typedef double real
Definition at line 61 of file hiegroup.h.
typedef struct solid STYPE
Definition at line 77 of file hiegroup.h.
typedef real vector[4]
Definition at line 73 of file hiegroup.h.
typedef struct vertex VTYPE
Definition at line 97 of file hiegroup.h.
Function Documentation
char _affine (char * name, vector center, matrix mat, int moni)
int _move (char * name, vector disp, int moni)
int _rotate (char * name, vector center, vector vector, real th, int moni)
void MSD_execAssociaGroupAxis (void)
void MSD_execAssociaGroupGroup (void)
void MSD_execAssociaGroupSolid (void)
void MSD_execAssociaSolidAxis (void)
void MSD_execCopyGroup (void)
void MSD_execCreateAxisRotation (void)
void MSD_execCreateAxisTranslation (void)
void MSD_execCreateGroup (void)
void MSD_execCreateSetGroup (void)
void MSD_execDesassociaGroupAxis (void)
void MSD_execDesassociaGroupGroup (void)
void MSD_execDesassociaGroupSolid (void)
void MSD_execDesassociaSolidAxis (void)
void MSD_execManipulateAxis (void)
Definition at line 51 of file hieaxsdf.cpp.
References lineins(), MSD_highNameAssociateAxisElement(), MSD_highNameCreateAxisRotation(), MSD_highNameCreateAxisTranslation(), MSD_highNameDesassociateAxisElement(), MSD_highNameRemoveAxis(), MSD_highNameTransformUsingAxis(), optin(), and restbuf.
void MSD_execManipulateGroup (void)
Definition at line 51 of file hiegrpdf.cpp.
References lineins(), MSD_highNameAssociateGroupElement(), MSD_highNameCreateSetGroup(), MSD_highNameDesassociateGroupElement(), MSD_highNameRemoveGroup(), MSD_highNameSetGroupCurrent(), MSD_highNameTransferGroup(), optin(), and restbuf.
void MSD_execMoveAxis (void)
void MSD_execMoveGroup (void)
void MSD_execNameAssociaGroupAxis (void)
void MSD_execNameAssociaGroupGroup (void)
void MSD_execNameAssociaGroupSolid (void)
void MSD_execNameAssociaSolidAxis (void)
void MSD_execNameCopyGroup (void)
void MSD_execNameCreateAxisRotation (void)
void MSD_execNameCreateAxisTranslation (void)
void MSD_execNameCreateGroup (void)
void MSD_execNameCreateSetGroup (void)
void MSD_execNameDesassociaGroupAxis (void)
void MSD_execNameDesassociaGroupGroup (void)
void MSD_execNameDesassociaGroupSolid (void)
void MSD_execNameDesassociaSolidAxis (void)
void MSD_execNameListAxisName (void)
void MSD_execNameListGroupName (void)
void MSD_execNameMoveAxis (void)
void MSD_execNameMoveGroup (void)
void MSD_execNameRemoveAxis (void)
void MSD_execNameRemoveGroup (void)
void MSD_execNameRemoveOneGroup (void)
void MSD_execNameRenameAxis (void)
void MSD_execNameRenameGroup (void)
void MSD_execNameRotateAxis (void)
void MSD_execNameRotateGroup (void)
void MSD_execNameSetGroupCurrent (void)
void MSD_execNameTransferGroup (void)
void MSD_execNameTransformUsingAxis (void)
void MSD_execRemoveAxis (void)
void MSD_execRemoveGroup (void)
void MSD_execRemoveOneGroup (void)
void MSD_execRotateAxis (void)
void MSD_execRotateGroup (void)
void MSD_execSetGroupCurrent (void)
int MSD_execStructAssociate (EulerOp * op)
Definition at line 200 of file hieassas.cpp.
References AxisGroup, AxisSolid, ERROR, GroupGroup, GroupSolid, eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_highAssociaGroupAxis(), MSD_highAssociaGroupGroup(), MSD_highAssociaGroupSolid(), MSD_highAssociaSolidAxis(), and SUCCESS.
int MSD_execStructCreateGroup (EulerOp * op)
Definition at line 131 of file hiegrpcr.cpp.
References eulerop::ip1, and MSD_middleCreateGroup().
int MSD_execStructCrtAxsRotation (EulerOp * op)
Definition at line 152 of file hieaxscr.cpp.
References EULEROPS, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, MSD_middleCreateAxisRotation(), and eulerop::opnext.
int MSD_execStructCrtAxsTranslation (EulerOp * op)
Definition at line 149 of file hieaxscd.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and MSD_middleCreateAxisTranslation().
int MSD_execStructMoveAxis (EulerOp * op)
Definition at line 137 of file hieaxsmv.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and MSD_highMoveAxis().
int MSD_execStructRemoveAxis (EulerOp * op)
Definition at line 153 of file hieaxsrm.cpp.
References eulerop::ip1, and MSD_highRemoveAxis().
int MSD_execStructRemoveOneGroup (EulerOp * op)
Definition at line 148 of file hiegrprg.cpp.
References eulerop::ip1, and MSD_highRemoveOneGroup().
int MSD_execStructRotateAxis (EulerOp * op)
Definition at line 163 of file hieaxsrt.cpp.
References EULEROPS, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, MSD_highRotateAxis(), and eulerop::opnext.
int MSD_execStructSetGroupCurrent (EulerOp * op)
Definition at line 150 of file hiegrpsc.cpp.
References eulerop::ip1, and MSD_highSetGroupCurrent().
void MSD_execTransferGroup (void)
void MSD_execTransformUsingAxis (void)
void MSD_executeAffineElement (char * name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
void MSD_executeMoveElement (char * name, real dx, real dy, real dz)
void MSD_executeRotateElement (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
APTYPE MSD_getAxis (Id)
Definition at line 123 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, and AxsAxisNo.
Referenced by MSD_highAssociaGroupAxis(), MSD_highAssociaSolidAxis(), MSD_highDesassociaGroupAxis(), MSD_highDesassociaSolidAxis(), MSD_highMoveAxis(), MSD_highName(), MSD_highNameCreateAxisRotation(), MSD_highNameCreateAxisTranslation(), MSD_highRemoveAxis(), MSD_highRotateAxis(), and MSD_highTransformUsingAxis().
Id MSD_getAxisIdFromName (char *)
Definition at line 50 of file hieaxsmn.cpp.
References AllAxis, APTYPE, AxsAxisNo, and AxsName.
Referenced by MSD_highNameAssociaGroupAxis(), MSD_highNameAssociaSolidAxis(), MSD_highNameCreateAxisRotation(), MSD_highNameCreateAxisTranslation(), MSD_highNameDesassociaGroupAxis(), MSD_highNameDesassociaSolidAxis(), MSD_highNameMoveAxis(), MSD_highNameRemoveAxis(), MSD_highNameRotateAxis(), and MSD_highNameTransformUsingAxis().
GPTYPE MSD_getGroup (Id)
Definition at line 131 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, and GrpGroupNo.
Referenced by MSD_highAssociaGroupAxis(), MSD_highAssociaGroupGroup(), MSD_highAssociaGroupSolid(), MSD_highColor(), MSD_highCopyGroup(), MSD_highDesassociaGroupAxis(), MSD_highDesassociaGroupGroup(), MSD_highDesassociaGroupSolid(), MSD_highMoveGroup(), MSD_highName(), MSD_highNameCopyGroup(), MSD_highNameCreateGroup(), MSD_highNameCreateSetGroup(), MSD_highRemoveGroup(), MSD_highRemoveOneGroup(), MSD_highRotateGroup(), MSD_highSetGroupCurrent(), MSD_highTransferGroup(), and MSD_lowCopyGroup().
GPTYPE MSD_getGroupAxis (APTYPE axis)
Definition at line 202 of file hiegrpmn.cpp.
References AxsAGroup, AxsASolid, AxsType, GNIL, GROUP, SolGroup, and SOLID.
Referenced by MSD_lowIsAncestorAxis(), MSD_lowMoveGroup(), MSD_lowRemoveGroup(), and MSD_lowRotateGroup().
Id MSD_getGroupIdFromName (char *)
Definition at line 52 of file hiegrpmn.cpp.
References AllGroup, GPTYPE, GrpGroupNo, and GrpName.
Referenced by MSD_highNameAssociaGroupAxis(), MSD_highNameAssociaGroupGroup(), MSD_highNameAssociaGroupSolid(), MSD_highNameCopyGroup(), MSD_highNameCreateGroup(), MSD_highNameCreateSetGroup(), MSD_highNameDesassociaGroupAxis(), MSD_highNameDesassociaGroupGroup(), MSD_highNameDesassociaGroupSolid(), MSD_highNameMoveGroup(), MSD_highNameRemoveGroup(), MSD_highNameRemoveOneGroup(), MSD_highNameRotateGroup(), and MSD_highNameTransferGroup().
int MSD_getMaxAxisId (void)
Definition at line 64 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, axsary, and AxsAxisNo.
Referenced by MSD_highCreateAxisRotation(), MSD_highCreateAxisTranslation(), and MSD_lowCheckTranslatorTable().
Id MSD_getMaxGroupId (void)
Definition at line 72 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, grpary, and GrpGroupNo.
Referenced by MSD_highCopyGroup(), MSD_highCreateGroup(), MSD_highCreateSetGroup(), and MSD_lowCheckTranslatorTable().
int MSD_getNumberOfAxis (void)
Definition at line 84 of file hieaxsmn.cpp.
References AllAxis, and APTYPE.
int MSD_getNumberOfGroups (void)
Definition at line 92 of file hiegrpmn.cpp.
References AllGroup, and GPTYPE.
int MSD_highAssociaGroupAxis (int sn, int an)
Definition at line 105 of file hieassag.cpp.
References ANIL, APTYPE, ERROR, GNIL, GPTYPE, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_PonteirosNulos, MSD_getAxis(), MSD_getGroup(), MSD_lowAssociaGroupAxis(), and NAM_AssociaAxisGroup.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupAxis(), and MSD_highNameDesassociaGroupAxis().
int MSD_highAssociaGroupGroup (int gn1, int gn2)
Definition at line 105 of file hieassgg.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowAssociaGroupGroup(), and NAM_AssociaGroupGroup.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupGroup(), and MSD_highNameDesassociaGroupGroup().
int MSD_highAssociaGroupSolid (int gn, int sn)
Definition at line 107 of file hieassgs.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MSD_getGroup(), MSD_getSolid(), MSD_lowAssociaGroupSolid(), NAM_AssociaGroupSolid, SNIL, and SPTYPE.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaGroupSolid(), and MSD_highNameDesassociaGroupSolid().
int MSD_highAssociaSolidAxis (int sn, int an)
Definition at line 105 of file hieassas.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouSolido, MEN_PonteirosNulos, MSD_getAxis(), MSD_getSolid(), MSD_lowAssociaSolidAxis(), NAM_AssociaAxisSolid, SNIL, and SPTYPE.
Referenced by MSD_execStructAssociate(), MSD_highNameAssociaSolidAxis(), and MSD_highNameDesassociaSolidAxis().
int MSD_highCopyGroup (int gn)
Definition at line 117 of file hiegrpcy.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_getMaxGroupId(), MSD_lowCopyGroup(), and NAM_CopyGroup.
Referenced by MSD_highNameCopyGroup().
int MSD_highCreateAxisRotation (real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 111 of file hieaxscr.cpp.
References makevec(), MSD_getMaxAxisId(), and MSD_lowCreateAxisRotation().
Referenced by MSD_highNameCreateAxisRotation().
int MSD_highCreateAxisTranslation (real x, real y, real z)
Definition at line 110 of file hieaxscd.cpp.
References ERROR, makevec(), MSD_getMaxAxisId(), and MSD_lowCreateAxisTranslation().
Referenced by MSD_highNameCreateAxisTranslation().
int MSD_highCreateGroup (void)
Definition at line 99 of file hiegrpcr.cpp.
References ERROR, MSD_getMaxGroupId(), and MSD_lowCreateGroup().
Referenced by MSD_highNameCreateGroup().
int MSD_highCreateSetGroup (int flag)
Definition at line 108 of file hiegrpcs.cpp.
References ERROR, MSD_getMaxGroupId(), MSD_highSetGroupCurrent(), and MSD_lowCreateGroup().
Referenced by MSD_highNameCreateSetGroup().
int MSD_highDesassociaGroupAxis (int gn, int an)
Definition at line 107 of file hiedesag.cpp.
References ANIL, APTYPE, AxsAGroup, AxsType, ERROR, GNIL, GPTYPE, GROUP, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouGroupId, MEN_ParametrosIncorretos, MSD_getAxis(), MSD_getGroup(), MSD_lowAssociaGroupAxis(), and NAM_DesassociaAxisGroup.
int MSD_highDesassociaGroupGroup (int gn1, int gn2)
Definition at line 107 of file hiedesgg.cpp.
References ERROR, GNIL, GPTYPE, GrpParent, MEN_NaoEncontrouGroupId, MEN_ParametrosIncorretos, MSD_getGroup(), MSD_lowAssociaGroupGroup(), and NAM_DesassociaGroupGroup.
int MSD_highDesassociaGroupSolid (int gn, int sn)
Definition at line 107 of file hiedesgs.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MEN_NaoEncontrouSolido, MEN_ParametrosIncorretos, MSD_getGroup(), MSD_getSolid(), MSD_lowAssociaGroupSolid(), NAM_DesassociaGroupSolid, SNIL, SolGroup, and SPTYPE.
Referenced by MSD_lowSoftRemove().
int MSD_highDesassociaSolidAxis (int sn, int an)
Definition at line 107 of file hiedesas.cpp.
References ANIL, APTYPE, AxsASolid, AxsType, ERROR, MEN_NaoEncontrouAxisId, MEN_NaoEncontrouSolido, MEN_ParametrosIncorretos, MSD_getAxis(), MSD_getSolid(), MSD_lowAssociaSolidAxis(), NAM_DesassociaAxisSolid, SNIL, SOLID, and SPTYPE.
int MSD_highMoveAxis (int an, real x, real y, real z)
Definition at line 104 of file hieaxsmv.cpp.
References ANIL, APTYPE, ERROR, makevec(), MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowMoveAxis(), and NAM_MoveAxis.
Referenced by MSD_execStructMoveAxis(), and MSD_highNameMoveAxis().
int MSD_highMoveGroup (int gn, real x, real y, real z)
Definition at line 103 of file hiegrpmv.cpp.
References ERROR, GNIL, GPTYPE, makevec(), MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowMoveGroup(), and NAM_MoveGroup.
Referenced by MSD_highNameMoveGroup().
int MSD_highNameAssociaGroupAxis (char * name1, char * name2)
Definition at line 70 of file hieassag.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouGroupNome, MSD_getAxisIdFromName(), MSD_getGroupIdFromName(), MSD_highAssociaGroupAxis(), and NAM_AssociaAxisGroup.
int MSD_highNameAssociaGroupGroup (char * name1, char * name2)
Definition at line 70 of file hieassgg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highAssociaGroupGroup(), and NAM_AssociaGroupGroup.
int MSD_highNameAssociaGroupSolid (char * name1, char * name2)
Definition at line 70 of file hieassgs.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MEN_NaoEncontrouSolidNome, MSD_getGroupIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaGroupSolid(), and NAM_AssociaGroupSolid.
int MSD_highNameAssociaSolidAxis (char * , char *)
Definition at line 70 of file hieassas.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouSolidNome, MSD_getAxisIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaSolidAxis(), and NAM_AssociaAxisSolid.
int MSD_highNameCopyGroup (char * name1, char * name2)
Definition at line 73 of file hiegrpcy.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MEN_NaoEncontrouGroupNome, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCopyGroup(), NAM_CopyGroup, and SUCCESS.
Referenced by MSD_highNameCopyElement().
int MSD_highNameCreateAxisRotation (char * name, real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 73 of file hieaxscr.cpp.
References APTYPE, AxsName, ERROR, MEN_AxisJaExiste, MSD_getAxis(), MSD_getAxisIdFromName(), MSD_highCreateAxisRotation(), NAM_CreateAxisOfRotation, and SUCCESS.
Referenced by MSD_execManipulateAxis().
int MSD_highNameCreateAxisTranslation (char * name, real x, real y, real z)
Definition at line 72 of file hieaxscd.cpp.
References APTYPE, AxsName, ERROR, MEN_AxisJaExiste, MSD_getAxis(), MSD_getAxisIdFromName(), MSD_highCreateAxisTranslation(), NAM_CreateAxisOfTranslation, and SUCCESS.
Referenced by MSD_execManipulateAxis().
int MSD_highNameCreateGroup (char * name)
Definition at line 72 of file hiegrpcr.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCreateGroup(), NAM_CreateGroup, and SUCCESS.
int MSD_highNameCreateSetGroup (char * name1, char * name2)
Definition at line 71 of file hiegrpcs.cpp.
References ERROR, GPTYPE, GrpName, MEN_GroupJaExiste, MSD_getGroup(), MSD_getGroupIdFromName(), MSD_highCreateSetGroup(), NAM_CreateGroupSetCurrent, and SUCCESS.
Referenced by MSD_execManipulateGroup().
int MSD_highNameDesassociaGroupAxis (char * name1, char * name2)
Definition at line 70 of file hiedesag.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouGroupNome, MSD_getAxisIdFromName(), MSD_getGroupIdFromName(), MSD_highAssociaGroupAxis(), and NAM_DesassociaAxisGroup.
int MSD_highNameDesassociaGroupGroup (char * name1, char * name2)
Definition at line 70 of file hiedesgg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highAssociaGroupGroup(), and NAM_DesassociaGroupGroup.
int MSD_highNameDesassociaGroupSolid (char * name1, char * name2)
Definition at line 70 of file hiedesgs.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MEN_NaoEncontrouSolidNome, MSD_getGroupIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaGroupSolid(), and NAM_DesassociaGroupSolid.
int MSD_highNameDesassociaSolidAxis (char * name1, char * name2)
Definition at line 70 of file hiedesas.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MEN_NaoEncontrouSolidNome, MSD_getAxisIdFromName(), MSD_getSolidIdFromName(), MSD_highAssociaSolidAxis(), and NAM_DesassociaAxisSolid.
int MSD_highNameListAxisName (char * name)
Definition at line 69 of file hieaxsli.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisNome, MSD_lowFindAxisByName(), MSD_lowListAxisName(), and NAM_ListAxis.
int MSD_highNameListGroupName (char * name)
Definition at line 71 of file hiegrpli.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupNome, MSD_lowFindGroupByName(), MSD_lowNameListGroupName(), and NAM_ListGroup.
int MSD_highNameMoveAxis (char * name, real x, real y, real z)
Definition at line 72 of file hieaxsmv.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highMoveAxis(), and NAM_MoveAxis.
Referenced by MSD_highNameTranslateElement().
int MSD_highNameMoveGroup (char * name, real x, real y, real z)
Definition at line 72 of file hiegrpmv.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highMoveGroup(), and NAM_MoveGroup.
Referenced by MSD_highNameTranslateElement().
int MSD_highNameRemoveAxis (char * name)
Definition at line 70 of file hieaxsrm.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highRemoveAxis(), and NAM_RemoveAxis.
Referenced by MSD_execManipulateAxis(), and MSD_highNameDeleteElement().
int MSD_highNameRemoveGroup (char * name)
Definition at line 71 of file hiegrprm.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRemoveGroup(), and NAM_RemoveGroup.
Referenced by MSD_execManipulateGroup(), and MSD_highNameDeleteElement().
int MSD_highNameRemoveOneGroup (char * name)
Definition at line 71 of file hiegrprg.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRemoveOneGroup(), and NAM_RemoveOneGroup.
int MSD_highNameRenameAxis (char * name1, char * name2)
Definition at line 70 of file hieaxsrn.cpp.
References ANIL, APTYPE, ERROR, MEN_AxisJaExiste, MEN_NaoEncontrouAxisNome, MSD_lowFindAxisByName(), MSD_lowNameRenameAxis(), and NAM_RenameAxis.
Referenced by MSD_highNameRenameElement().
int MSD_highNameRenameGroup (char * name1, char * name2)
Definition at line 70 of file hiegrprn.cpp.
References ERROR, GNIL, GPTYPE, MEN_GroupJaExiste, MEN_NaoEncontrouGroupNome, MSD_lowFindGroupByName(), MSD_lowNameRenameGroup(), and NAM_RenameGroup.
Referenced by MSD_highNameRenameElement().
int MSD_highNameRotateAxis (char * name, real cx, real cy, real cz, real ax, real ay, real az, real th)
Definition at line 77 of file hieaxsrt.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highRotateAxis(), and NAM_RotateAxis.
Referenced by MSD_highNameRotateElement().
int MSD_highNameRotateGroup (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 74 of file hiegrprt.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRotateGroup(), and NAM_RotateGroup.
Referenced by MSD_highNameRotateElement().
void MSD_highNameSetGroupCurrent (char * nam)
Definition at line 72 of file hiegrpsc.cpp.
References def_grpptr, GNIL, GPTYPE, GrpParent, MEN_NaoEncontrouGroupNome, MEN_NaoPossuiAncestral, MSD_lowFindGroupByName(), MSD_lowSetGroupCurrent(), and NAM_SetCurrentGroup.
Referenced by MSD_execManipulateGroup().
int MSD_highNameTransferGroup (char * name1, char * name2)
Definition at line 70 of file hiegrptf.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highTransferGroup(), and NAM_TransferGroup.
Referenced by MSD_execManipulateGroup().
int MSD_highNameTransformUsingAxis (char * name, real desl)
Definition at line 72 of file hieaxstr.cpp.
References ERROR, MEN_NaoEncontrouAxisNome, MSD_getAxisIdFromName(), MSD_highTransformUsingAxis(), and NAM_TransformUsingAxis.
Referenced by CriaFrame(), and MSD_execManipulateAxis().
int MSD_highRemoveAxis (int an)
Definition at line 100 of file hieaxsrm.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowRemoveAxis(), and NAM_RemoveAxis.
Referenced by MSD_execStructRemoveAxis(), and MSD_highNameRemoveAxis().
int MSD_highRemoveGroup (int gn)
Definition at line 101 of file hiegrprm.cpp.
References def_grpptr, ERROR, GNIL, GPTYPE, MEN_GrupoCorrenteEliminado, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowIsAncestorGroup(), MSD_lowRemoveGroup(), and NAM_RemoveGroup.
Referenced by MSD_highNameRemoveGroup(), and MSD_lowCopyGroup().
int MSD_highRemoveOneGroup (int gn)
Definition at line 101 of file hiegrprg.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowRemoveOneGroup(), and NAM_RemoveOneGroup.
Referenced by MSD_execStructRemoveOneGroup(), and MSD_highNameRemoveOneGroup().
int MSD_highRotateAxis (int an, real cx, real cy, real cz, real ax, real ay, real az, real th)
Definition at line 111 of file hieaxsrt.cpp.
References ANIL, APTYPE, ERROR, makevec(), MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowRotateAxis(), and NAM_RotateAxis.
Referenced by MSD_execStructRotateAxis(), and MSD_highNameRotateAxis().
int MSD_highRotateGroup (Id gn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 107 of file hiegrprt.cpp.
References ERROR, GNIL, GPTYPE, makevec(), MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowRotateGroup(), NAM_RotateGroup, and normalize().
Referenced by MSD_highNameRotateGroup().
int MSD_highSetGroupCurrent (int gn)
Definition at line 123 of file hiegrpsc.cpp.
References ERROR, GNIL, GPTYPE, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowSetGroupCurrent(), and NAM_SetCurrentGroup.
Referenced by MSD_execStructSetGroupCurrent(), and MSD_highCreateSetGroup().
int MSD_highTransferGroup (int gn1, int gn2)
Definition at line 105 of file hiegrptf.cpp.
References ERROR, GNIL, GPTYPE, MEN_GroupAncestralGroup, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowAssociaGroupGroup(), MSD_lowIsAncestorGroup(), and NAM_TransferGroup.
Referenced by MSD_highNameTransferGroup().
int MSD_highTransformUsingAxis (int an, real desl)
Definition at line 104 of file hieaxstr.cpp.
References ANIL, APTYPE, ERROR, MEN_NaoEncontrouAxisId, MSD_getAxis(), MSD_lowTransformUsingAxis(), and NAM_TransformUsingAxis.
Referenced by MSD_highNameTransformUsingAxis().
int MSD_lowAssociaGroupAxis (APTYPE aptr, GPTYPE gptr)
Definition at line 128 of file hieassag.cpp.
References ANIL, ASSOCIATE, AxisGroup, AxisSolid, AxsAGroup, AxsASolid, AxsAxisNo, AxsType, Gdoinversion, GNIL, GROUP, GrpGAxs, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SOLID, SolOAxs, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaGroupAxis(), MSD_highDesassociaGroupAxis(), MSD_highNameAssociateAxisElement(), and MSD_highNameDesassociateAxisElement().
int MSD_lowAssociaGroupGroup (GPTYPE gptr1, GPTYPE gptr2)
Definition at line 123 of file hieassgg.cpp.
References ASSOCIATE, Gdoinversion, GNIL, GroupGroup, GrpGroupNo, GrpParent, MSD_lowAddEulerOp(), SNIL, and SUCCESS.
Referenced by MSD_highAssociaGroupGroup(), MSD_highDesassociaGroupGroup(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highTransferGroup(), and MSD_lowRemoveOneGroup().
int MSD_lowAssociaGroupSolid (GPTYPE gptr, SPTYPE optr)
Definition at line 127 of file hieassgs.cpp.
References ASSOCIATE, Gdoinversion, GNIL, GroupSolid, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SolGroup, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaGroupSolid(), MSD_highDesassociaGroupSolid(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), and MSD_lowRemoveOneGroup().
int MSD_lowAssociaSolidAxis (APTYPE aptr, SPTYPE optr)
Definition at line 128 of file hieassas.cpp.
References ANIL, ASSOCIATE, AxisGroup, AxisSolid, AxsAGroup, AxsASolid, AxsAxisNo, AxsType, Gdoinversion, GROUP, GrpGAxs, GrpGroupNo, MSD_lowAddEulerOp(), SNIL, SOLID, SolOAxs, SolSolidNo, and SUCCESS.
Referenced by MSD_highAssociaSolidAxis(), MSD_highDesassociaSolidAxis(), MSD_highNameAssociateAxisElement(), and MSD_highNameDesassociateAxisElement().
int MSD_lowCopyGroup (GPTYPE gptr, Id gn)
Definition at line 132 of file hiegrpcy.cpp.
References AllSolids, EulerOpNext, EULEROPS, FALSE, Gdoinversion, GPTYPE, GROUP, GrpGroupNo, MSD_getGroup(), MSD_highRemoveGroup(), MSD_lowApplyEulerOp(), MSD_lowFreeUndoLog(), MSD_lowIniciaTranslatorTable(), MSD_lowIsAncestorGroup(), MSD_lowModifyEulerOp(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSetTranslatorTable(), OpHead, PEulerOp, SolGroup, SPTYPE, and TRUE.
Referenced by MSD_highCopyGroup().
int MSD_lowCreateAxisRotation (Id an, vector pos, vector vec)
Definition at line 131 of file hieaxscr.cpp.
References ANIL, APTYPE, AXIS, AxisOfRotation, AxsAxisNo, AxsCenter, AxsMode, AxsVector, ERROR, Gdoinversion, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateAxisOfRotation, NNIL, REMAXS, SNIL, and veccopy().
Referenced by MSD_highCreateAxisRotation(), and MSD_middleCreateAxisRotation().
int MSD_lowCreateAxisTranslation (int an, vector vec)
Definition at line 128 of file hieaxscd.cpp.
References ANIL, APTYPE, AXIS, AxisOfTranslation, AxsAxisNo, AxsMode, AxsVector, ERROR, Gdoinversion, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateAxisOfTranslation, NNIL, REMAXS, SNIL, SUCCESS, and veccopy().
Referenced by MSD_highCreateAxisTranslation(), and MSD_middleCreateAxisTranslation().
int MSD_lowCreateGroup (Id gn)
Definition at line 112 of file hiegrpcr.cpp.
References ERROR, Gdoinversion, GNIL, GPTYPE, GROUP, GrpGroupNo, MEN_NaoPossuiMemoria, MSD_lowAddEulerOp(), MSD_lowNewElement(), NAM_CreateGroup, NNIL, REMGRP, SNIL, and SUCCESS.
Referenced by MSD_highCreateGroup(), MSD_highCreateSetGroup(), and MSD_middleCreateGroup().
APTYPE MSD_lowFindAxisByName (char * nam)
Definition at line 109 of file hieaxsmn.cpp.
References AllAxis, ANIL, APTYPE, and AxsName.
Referenced by MSD_addAxisToMovementStructure(), MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameDesassociateAxisElement(), MSD_highNameListAxisName(), and MSD_highNameRenameAxis().
GPTYPE MSD_lowFindGroupByName (char * nam)
Definition at line 117 of file hiegrpmn.cpp.
References AllGroup, GNIL, GPTYPE, and GrpName.
Referenced by MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highNameGroupColor(), MSD_highNameListGroupName(), MSD_highNameRenameGroup(), MSD_highNameSetDisplay(), MSD_highNameSetGroupCurrent(), MSD_resetGroup(), and MSD_selectGroup().
char MSD_lowIsAncestorAxis (APTYPE ancaptr, APTYPE desaptr)
Definition at line 188 of file hiegrpmn.cpp.
References FALSE, GNIL, GPTYPE, GrpGAxs, GrpParent, MSD_getGroupAxis(), and TRUE.
Referenced by MSD_lowRotateUsingAxis(), and MSD_lowTranslateUsingAxis().
char MSD_lowIsAncestorGroup (GPTYPE ancgptr, GPTYPE desgptr)
Definition at line 174 of file hiegrpmn.cpp.
References FALSE, GNIL, GPTYPE, GrpParent, and TRUE.
Referenced by MSD_highNameSetDisplay(), MSD_highRemoveGroup(), MSD_highTransferGroup(), MSD_lowCopyGroup(), MSD_lowDisplayMonitorGroup(), MSD_lowMoveGroup(), MSD_lowRemoveGroup(), MSD_lowRotateGroup(), MSD_lowRotateUsingAxis(), MSD_lowTranslateUsingAxis(), MSD_resetGroup(), and MSD_selectGroup().
char MSD_lowIsEmptyGroup (GPTYPE grpptr)
Definition at line 145 of file hiegrpmn.cpp.
References AllGroup, AllSolids, FALSE, GNIL, GPTYPE, GrpParent, SolGroup, SPTYPE, and TRUE.
void MSD_lowListAllAxis (void)
Definition at line 125 of file hieaxsli.cpp.
References AllAxis, APTYPE, and MSD_lowListAxisName().
Referenced by MSD_execShow().
void MSD_lowListAllAxisName (void)
Definition at line 135 of file hieaxsli.cpp.
References AllAxis, APTYPE, and AxsName.
Referenced by MSD_execListElement().
void MSD_lowListAllGroup (void)
Definition at line 108 of file hiegrpli.cpp.
References AllGroup, GPTYPE, and MSD_lowListGroup().
Referenced by MSD_execShow().
void MSD_lowListAllGroupName (void)
Definition at line 135 of file hiegrpli.cpp.
References AllGroup, GPTYPE, and GrpName.
Referenced by MSD_execListElement().
int MSD_lowListAxisName (APTYPE aptr)
Definition at line 81 of file hieaxsli.cpp.
References AxisOfRotation, AxisOfTranslation, AxsAGroup, AxsASolid, AxsCenter, AxsMode, AxsName, AxsType, AxsVector, GROUP, GrpName, SOLID, SolName, and TRUE.
Referenced by MSD_execShow(), MSD_highNameListAxisName(), and MSD_lowListAllAxis().
void MSD_lowListGroup (GPTYPE gptr)
Definition at line 118 of file hiegrpli.cpp.
References ANIL, AxsName, GNIL, GrpGAxs, GrpGColor, GrpName, and GrpParent.
Referenced by MSD_execShow(), and MSD_lowListAllGroup().
int MSD_lowMoveAxis (APTYPE aptr, vector vec)
Definition at line 119 of file hieaxsmv.cpp.
References AxisOfTranslation, AxsAxisNo, AxsCenter, AxsMode, Gdoinversion, MOVAXIS, MSD_lowAddEulerOp(), SNIL, SUCCESS, and vecplus().
Referenced by MSD_highMoveAxis(), MSD_lowMoveGroup(), and MSD_lowTranslateUsingAxis().
int MSD_lowMoveGroup (GPTYPE gptr, vector disp)
Definition at line 117 of file hiegrpmv.cpp.
References AllAxis, AllSolids, APTYPE, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowMoveAxis(), MSD_lowTranslate(), SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highMoveGroup().
int MSD_lowNameListGroupName (GPTYPE gptr)
Definition at line 83 of file hiegrpli.cpp.
References AllSolids, GNIL, GrpName, GrpParent, SolGroup, SolName, SPTYPE, and SUCCESS.
Referenced by MSD_highNameListGroupName().
int MSD_lowNameRenameAxis (APTYPE aptr, char * name2)
Definition at line 87 of file hieaxsrn.cpp.
References AxsName, and SUCCESS.
Referenced by MSD_highNameRenameAxis().
int MSD_lowNameRenameGroup (GPTYPE gptr, char * name2)
Definition at line 87 of file hiegrprn.cpp.
References GrpName, and SUCCESS.
Referenced by MSD_highNameRenameGroup().
int MSD_lowRemoveAxis (APTYPE aptr)
Definition at line 112 of file hieaxsrm.cpp.
References AXIS, AxisOfRotation, AxisOfTranslation, AxsAxisNo, AxsMode, axsused, AxsVector, CRTAXSROT, CRTAXSTRS, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAxisName(), MSD_lowDelElement(), NNIL, NPTYPE, SNIL, and SUCCESS.
Referenced by MSD_highRemoveAxis(), and MSD_lowRemoveGroup().
int MSD_lowRemoveGroup (GPTYPE gptr)
Definition at line 118 of file hiegrprm.cpp.
References ANIL, APTYPE, axsary, AxsNextA, GNIL, GPTYPE, grpary, GrpNextG, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), MSD_lowSoftRemove(), objary, SNIL, SolGroup, SolNxt, SPTYPE, and SUCCESS.
Referenced by MSD_highRemoveGroup().
int MSD_lowRemoveOneGroup (GPTYPE gptr)
Definition at line 113 of file hiegrprg.cpp.
References AllGroup, AllSolids, CRTGRP, Gdoinversion, GPTYPE, GROUP, GrpGColor, GrpGroupNo, GrpName, GrpParent, grpused, MSD_lowAddEulerOp(), MSD_lowAssociaGroupGroup(), MSD_lowAssociaGroupSolid(), MSD_lowDelElement(), MSD_lowGroupColor(), MSD_lowGroupName(), NNIL, NPTYPE, SNIL, SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highRemoveOneGroup(), and MSD_lowRemoveGroup().
int MSD_lowRotateAxis (APTYPE aptr, vector center, vector axis, real th)
Definition at line 127 of file hieaxsrt.cpp.
References AxisOfRotation, AxsAxisNo, AxsCenter, AxsMode, AxsVector, Gdoinversion, MSD_lowAddEulerOp(), ROTAXIS, rotmat(), SNIL, SUCCESS, vecminus(), vecmult(), and vecplus().
Referenced by MSD_highRotateAxis(), MSD_lowRotateGroup(), and MSD_lowRotateUsingAxis().
int MSD_lowRotateGroup (GPTYPE gptr, vector center, vector vec, real th)
Definition at line 124 of file hiegrprt.cpp.
References AllAxis, AllSolids, APTYPE, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowRotateAxis(), MSD_lowRotateSolidAxis(), SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highRotateGroup().
void MSD_lowRotateUsingAxis (APTYPE aptr, vector center, vector vec, real th)
Definition at line 178 of file hieaxstr.cpp.
References AllAxis, AllGroup, AllSolids, APTYPE, AxsType, GPTYPE, GROUP, GrpGAxs, matident(), MSD_lowIsAncestorAxis(), MSD_lowIsAncestorGroup(), MSD_lowRotateAxis(), MSD_lowTransformation(), MSD_lowTranslate(), PI, rotmat(), SolGroup, SOLID, SolOAxs, and SPTYPE.
Referenced by MSD_lowTransformUsingAxis().
int MSD_lowSetGroupCurrent (GPTYPE gptr)
Definition at line 135 of file hiegrpsc.cpp.
References def_grpptr, Gdoinversion, GNIL, GrpGroupNo, MSD_lowAddEulerOp(), SETGRP, SNIL, and SUCCESS.
Referenced by MSD_highNameSetGroupCurrent(), and MSD_highSetGroupCurrent().
int MSD_lowTransformUsingAxis (APTYPE aptr, real desl)
Definition at line 117 of file hieaxstr.cpp.
References AxisOfRotation, AxisOfTranslation, AxsCenter, AxsMode, AxsVector, MSD_lowRotateUsingAxis(), MSD_lowTranslateUsingAxis(), SUCCESS, and vecesc().
Referenced by MSD_highTransformUsingAxis().
void MSD_lowTranslateUsingAxis (APTYPE aptr, vector disp)
Definition at line 135 of file hieaxstr.cpp.
References AllAxis, AllGroup, AllSolids, APTYPE, AxsType, GPTYPE, GROUP, GrpGAxs, MSD_lowIsAncestorAxis(), MSD_lowIsAncestorGroup(), MSD_lowMoveAxis(), MSD_lowTranslate(), SolGroup, SOLID, SolOAxs, and SPTYPE.
Referenced by MSD_lowTransformUsingAxis().
int MSD_middleCreateAxisRotation (int an, real x1, real y1, real z1, real x2, real y2, real z2)
Definition at line 121 of file hieaxscr.cpp.
References makevec(), and MSD_lowCreateAxisRotation().
Referenced by MSD_execStructCrtAxsRotation().
int MSD_middleCreateAxisTranslation (int an, real x, real y, real z)
Definition at line 120 of file hieaxscd.cpp.
References makevec(), and MSD_lowCreateAxisTranslation().
Referenced by MSD_execStructCrtAxsTranslation().
int MSD_middleCreateGroup (int gn)
Definition at line 107 of file hiegrpcr.cpp.
References MSD_lowCreateGroup().
Referenced by MSD_execStructCreateGroup().
int MSD_modifyStructAssociate (EulerOp * op)
Definition at line 264 of file hieassas.cpp.
References AXIS, AxisGroup, AxisSolid, GROUP, GroupGroup, GroupSolid, eulerop::ip1, eulerop::ip2, eulerop::ip3, MSD_lowCheckTranslatorTable(), SOLID, and SUCCESS.
int MSD_modifyStructCreateGroup (EulerOp * op)
Definition at line 169 of file hiegrpcr.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructCrtAxsRotation (EulerOp * op)
Definition at line 215 of file hieaxscr.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructCrtAxsTranslation (EulerOp * op)
Definition at line 201 of file hieaxscd.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructMoveAxis (EulerOp * op)
Definition at line 189 of file hieaxsmv.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructRemoveAxis (EulerOp * op)
Definition at line 191 of file hieaxsrm.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructRemoveOneGroup (EulerOp * op)
Definition at line 186 of file hiegrprg.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructRotateAxis (EulerOp * op)
Definition at line 227 of file hieaxsrt.cpp.
References AXIS, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
int MSD_modifyStructSetGroupCurrent (EulerOp * op)
Definition at line 188 of file hiegrpsc.cpp.
References GROUP, eulerop::ip1, MSD_lowCheckTranslatorTable(), and SUCCESS.
void MSD_printStructAssociate (FILE * f, EulerOp * op)
Definition at line 229 of file hieassas.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, and eulerop::solidno.
void MSD_printStructCreateGroup (FILE * f, EulerOp * op)
Definition at line 136 of file hiegrpcr.cpp.
References eulerop::ip1, and eulerop::solidno.
void MSD_printStructCrtAxsRotation (FILE * f, EulerOp * op)
Definition at line 175 of file hieaxscr.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
void MSD_printStructCrtAxsTranslation (FILE * f, EulerOp * op)
Definition at line 161 of file hieaxscd.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
void MSD_printStructMoveAxis (FILE * f, EulerOp * op)
Definition at line 149 of file hieaxsmv.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
void MSD_printStructRemoveAxis (FILE * f, EulerOp * op)
Definition at line 158 of file hieaxsrm.cpp.
References eulerop::ip1, and eulerop::solidno.
void MSD_printStructRemoveOneGroup (FILE * f, EulerOp * op)
Definition at line 153 of file hiegrprg.cpp.
References eulerop::ip1, and eulerop::solidno.
void MSD_printStructRotateAxis (FILE * f, EulerOp * op)
Definition at line 187 of file hieaxsrt.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
void MSD_printStructSetGroupCurrent (FILE * f, EulerOp * op)
Definition at line 155 of file hiegrpsc.cpp.
References eulerop::ip1, and eulerop::solidno.
char** MSD_putAxisNameInList (char ** list)
Definition at line 96 of file hieaxsmn.cpp.
References AllAxis, APTYPE, and AxsName.
char** MSD_putGroupNameInList (char ** list)
Definition at line 104 of file hiegrpmn.cpp.
References AllGroup, GPTYPE, and GrpName.
void MSD_readExecuteAffineElement (void)
void MSD_readExecuteMoveElement (void)
void MSD_readExecuteRotateElement (void)
int MSD_readStructAssociate (FILE * f, EulerOp * op)
Definition at line 240 of file hieassas.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructCreateGroup (FILE * f, EulerOp * op)
Definition at line 145 of file hiegrpcr.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructCrtAxsRotation (FILE * f, EulerOp * op)
Definition at line 189 of file hieaxscr.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructCrtAxsTranslation (FILE * f, EulerOp * op)
Definition at line 175 of file hieaxscd.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructMoveAxis (FILE * f, EulerOp * op)
Definition at line 163 of file hieaxsmv.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructRemoveAxis (FILE * f, EulerOp * op)
Definition at line 167 of file hieaxsrm.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructRemoveOneGroup (FILE * f, EulerOp * op)
Definition at line 162 of file hiegrprg.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructRotateAxis (FILE * f, EulerOp * op)
Definition at line 201 of file hieaxsrt.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructSetGroupCurrent (FILE * f, EulerOp * op)
Definition at line 164 of file hiegrpsc.cpp.
References ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
void objrot (STYPE * optr, vector center, vector axis, real th)
char* x_calloc (unsigned int a, unsigned int b)
char x_free (char * a)
char* x_malloc (unsigned int a)
Variable Documentation
EXTERN Id AxisNo
Definition at line 150 of file hiegroup.h.
EXTERN APTYPE axsary
Definition at line 148 of file hiegroup.h.
Referenced by maninit(), MSD_getMaxAxisId(), MSD_lowAddList(), MSD_lowDelList(), and MSD_lowRemoveGroup().
EXTERN int axsused
Definition at line 149 of file hiegroup.h.
Referenced by maninit(), MSD_lowListNumberOfElements(), and MSD_lowRemoveAxis().
EXTERN GPTYPE def_grpptr
Definition at line 153 of file hiegroup.h.
Referenced by maninit(), MSD_highNameSetDisplay(), MSD_highNameSetGroupCurrent(), MSD_highRemoveGroup(), MSD_lowNewElement(), and MSD_lowSetGroupCurrent().
EXTERN Id GroupNo
Definition at line 155 of file hiegroup.h.
EXTERN GPTYPE grpary
Definition at line 152 of file hiegroup.h.
Referenced by maninit(), MSD_getMaxGroupId(), MSD_lowAddList(), MSD_lowDelList(), and MSD_lowRemoveGroup().
EXTERN int grpused
Definition at line 154 of file hiegroup.h.
Referenced by maninit(), MSD_lowListNumberOfElements(), and MSD_lowRemoveOneGroup().