USPDesigner: C:/USPDesig/HIE/hiegrptf.cpp File Reference
C:/USPDesig/HIE/hiegrptf.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "hiegroup.h"
Functions
int MSD_highNameTransferGroup (char *name1, char *name2)
int MSD_highTransferGroup (int gn1, int gn2)
Function Documentation
int MSD_highNameTransferGroup (char * name1, char * name2)
Definition at line 70 of file hiegrptf.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highTransferGroup(), and NAM_TransferGroup.
Referenced by MSD_execManipulateGroup().
int MSD_highTransferGroup (int gn1, int gn2)
Definition at line 105 of file hiegrptf.cpp.
References ERROR, GNIL, GPTYPE, MEN_GroupAncestralGroup, MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowAssociaGroupGroup(), MSD_lowIsAncestorGroup(), and NAM_TransferGroup.
Referenced by MSD_highNameTransferGroup().