USPDesigner: C:/USPDesig/HIE/hiegrprt.cpp File Reference
C:/USPDesig/HIE/hiegrprt.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "mancommd.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "shpshape.h"
#include "hiegroup.h"
Functions
int MSD_highNameRotateGroup (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_highRotateGroup (Id gn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_lowRotateGroup (GPTYPE gptr, vector center, vector vec, real th)
Function Documentation
int MSD_highNameRotateGroup (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 74 of file hiegrprt.cpp.
References ERROR, MEN_NaoEncontrouGroupNome, MSD_getGroupIdFromName(), MSD_highRotateGroup(), and NAM_RotateGroup.
Referenced by MSD_highNameRotateElement().
int MSD_highRotateGroup (Id gn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 107 of file hiegrprt.cpp.
References ERROR, GNIL, GPTYPE, makevec(), MEN_NaoEncontrouGroupId, MSD_getGroup(), MSD_lowRotateGroup(), NAM_RotateGroup, and normalize().
Referenced by MSD_highNameRotateGroup().
int MSD_lowRotateGroup (GPTYPE gptr, vector center, vector vec, real th)
Definition at line 124 of file hiegrprt.cpp.
References AllAxis, AllSolids, APTYPE, MSD_getGroupAxis(), MSD_lowIsAncestorGroup(), MSD_lowRotateAxis(), MSD_lowRotateSolidAxis(), SolGroup, SPTYPE, and SUCCESS.
Referenced by MSD_highRotateGroup().