USPDesigner: C:/USPDesig/LOW/lowaddel.cpp File Reference
C:/USPDesig/LOW/lowaddel.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
Functions
void MSD_lowAddList (int what, NPTYPE which, NPTYPE where)
void MSD_lowDelList (int what, NPTYPE which, NPTYPE where)
Function Documentation
void MSD_lowAddList (int what, NPTYPE which, NPTYPE where)
Definition at line 64 of file lowaddel.cpp.
References ANIL, APTYPE, AXIS, axsary, AxsNextA, AxsPrevA, DNIL, DPTYPE, EDGE, EdgNextE, EdgPrevE, ENIL, EPTYPE, FACE, FacFLoops, FacFShell, FacNextF, FacPrevF, FNIL, FPTYPE, GNIL, GPTYPE, GROUP, grpary, GrpNextG, GrpPrevG, LNIL, LooLFace, LooNextL, LOOP, LooPrevL, LPTYPE, objary, SHELL, SheNextD, ShePrevD, SheSEdges, SheSFaces, SheSSolids, SheSVerts, SNIL, SOLID, SolNxt, SolPrevS, SolSShells, SPTYPE, VerNextV, VerPrevV, VERTEX, VNIL, and VPTYPE.
Referenced by MSD_lowAllRingMove(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowNewElement(), MSD_lowRingMove(), MSD_lowShellDetach(), and redo().
void MSD_lowDelList (int what, NPTYPE which, NPTYPE where)
Definition at line 225 of file lowaddel.cpp.
References AllSolids, ANIL, APTYPE, AXIS, axsary, AxsNextA, AxsPrevA, DNIL, DPTYPE, EDGE, EdgNextE, EdgPrevE, ENIL, EPTYPE, error, FACE, FacFLoops, FacNextF, FacPrevF, findd(), findes(), findf(), findl(), findv(), FNIL, FPTYPE, GNIL, GPTYPE, GROUP, grpary, GrpNextG, GrpPrevG, LNIL, LooNextL, LOOP, LooPrevL, LPTYPE, objary, SetTrace, SHELL, SheNextD, ShePrevD, SheSEdges, SheSFaces, SheSVerts, SNIL, SOLID, SolNxt, SolPrevS, SolSShells, SPTYPE, TRUE, VerNextV, VerPrevV, VERTEX, VNIL, and VPTYPE.
Referenced by MSD_lowAllRingMove(), MSD_lowDelElement(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowRingMove(), MSD_lowShellDetach(), and redo().