USPDesigner: C:/USPDesig/LOW/lowaddhe.cpp File Reference
C:/USPDesig/LOW/lowaddhe.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
Functions
HPTYPE MSD_lowAddHE (EPTYPE e, VPTYPE v, HPTYPE where, int orient)
HPTYPE MSD_lowDelHE (HPTYPE he)
Function Documentation
HPTYPE MSD_lowAddHE (EPTYPE e, VPTYPE v, HPTYPE where, int orient)
Definition at line 62 of file lowaddhe.cpp.
References EdgHe1, EdgHe2, ENIL, HalEdg, HALFEDGE, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, MSD_lowNewElement(), NNIL, and PLUS.
Referenced by MSD_lowMEF(), MSD_lowMEKR(), and MSD_lowMEV().
HPTYPE MSD_lowDelHE (HPTYPE he)
Definition at line 96 of file lowaddhe.cpp.
References ENIL, HalEdg, HALFEDGE, HalNxt, HalPrv, HNIL, HPTYPE, MSD_lowDelElement(), NNIL, and NPTYPE.
Referenced by MSD_lowKEF(), MSD_lowKEMR(), and MSD_lowKEV().