USPDesigner: C:/USPDesig/LOW/lowboxop.cpp File Reference
C:/USPDesig/LOW/lowboxop.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "disdispl.h"
Functions
void MSD_lowSolidBoxFromBoxes (SPTYPE s, BTYPE *b)
int MSD_lowVertexInBox (BTYPE *b, real x, real y, real z)
int MSD_lowEdgeBoxIntersection (BTYPE *b, EPTYPE e)
static int MSD_lowEdgeBoxIntersectionAux (real x1, real x2, real bx1, real bx2)
int MSD_lowBoxBoxIntersection (BTYPE *b1, BTYPE *b2)
void MSD_lowSolidBox (SPTYPE s, BTYPE *bx)
void MSD_lowShellBox (DPTYPE d)
void MSD_lowFaceBox (FPTYPE f)
void MSD_lowEdgeBox (BTYPE *b, EPTYPE e)
void MSD_lowEvaluateSolidBoxes (SPTYPE s)
void MSD_lowWidenBox (BTYPE *b, real eps)
void MSD_lowUpdateBox (BTYPE *b1, BTYPE *b)
void MSD_lowTranslateBox (BTYPE *b, real dx, real dy, real dz)
void MSD_lowUpdateDEBox (void)
Function Documentation
int MSD_lowBoxBoxIntersection (BTYPE * b1, BTYPE * b2)
Definition at line 135 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowDisplayIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowPositionalVisibility(), MSD_lowSetOpGenerate(), and MSD_lowSetOpProcessEdge().
void MSD_lowEdgeBox (BTYPE * b, EPTYPE e)
Definition at line 246 of file lowboxop.cpp.
References CONTBVEPS, EdgHe1, EdgHe2, HalVtx, box::max, box::min, MSD_lowWidenBox(), VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpGenerate(), and MSD_lowSetOpProcessEdge().
int MSD_lowEdgeBoxIntersection (BTYPE * b, EPTYPE e)
Definition at line 88 of file lowboxop.cpp.
References EdgHe1, EdgHe2, HalVtx, box::max, box::min, MSD_lowEdgeBoxIntersectionAux(), VerVCoord, and VPTYPE.
static int MSD_lowEdgeBoxIntersectionAux (real x1, real x2, real bx1, real bx2) [static]
Definition at line 107 of file lowboxop.cpp.
void MSD_lowEvaluateSolidBoxes (SPTYPE s)
Definition at line 271 of file lowboxop.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, MSD_lowFaceBox(), and MSD_lowShellBox().
void MSD_lowFaceBox (FPTYPE f)
Definition at line 212 of file lowboxop.cpp.
References AllLoopsFace, CONTBVEPS, FacBox, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, box::max, box::min, MSD_lowWidenBox(), SetFaceBoxOK, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowEvaluateSolidBoxes(), and MSD_lowSetNormal().
void MSD_lowShellBox (DPTYPE d)
Definition at line 183 of file lowboxop.cpp.
References AllVerticesShell, CONTBVEPS, box::max, box::min, MSD_lowWidenBox(), SetShellBoxOK, SheBox, SheSVerts, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowEvaluateSolidBoxes(), and MSD_lowSetNormal().
void MSD_lowSolidBox (SPTYPE s, BTYPE * bx)
Definition at line 154 of file lowboxop.cpp.
References AllShellsSolid, AllVerticesShell, CONTBVEPS, DPTYPE, box::max, box::min, MSD_lowWidenBox(), SheSVerts, SolSShells, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowSetNormal().
void MSD_lowSolidBoxFromBoxes (SPTYPE s, BTYPE * b)
Definition at line 50 of file lowboxop.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacBox, FPTYPE, INF, box::max, box::min, and MSD_lowUpdateBox().
void MSD_lowTranslateBox (BTYPE * b, real dx, real dy, real dz)
Definition at line 317 of file lowboxop.cpp.
References box::max, and box::min.
void MSD_lowUpdateBox (BTYPE * b1, BTYPE * b)
Definition at line 299 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowSolidBoxFromBoxes().
void MSD_lowUpdateDEBox (void)
Definition at line 327 of file lowboxop.cpp.
References abseps, debox, deevtx, desvtx, box::max, and box::min.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
int MSD_lowVertexInBox (BTYPE * b, real x, real y, real z)
Definition at line 70 of file lowboxop.cpp.
References FALSE, box::max, and TRUE.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
void MSD_lowWidenBox (BTYPE * b, real eps)
Definition at line 287 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowEdgeBox(), MSD_lowFaceBox(), MSD_lowShellBox(), and MSD_lowSolidBox().