USPDesigner: C:/USPDesig/LOW/lowcheck.cpp File Reference
C:/USPDesig/LOW/lowcheck.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
Functions
void MSD_execTrace (void)
int TraceBoundaryStructure (void)
int TraceSolid (SPTYPE s)
int checkShell (FPTYPE f, DPTYPE d)
int checkf (SPTYPE s)
int findhes (DPTYPE d, HPTYPE he)
int checke (SPTYPE s)
int findhe (HPTYPE he, LPTYPE l)
int findes (DPTYPE d, EPTYPE e)
int findl (LPTYPE l, FPTYPE f)
int finde (VPTYPE v, HPTYPE he)
int findf (DPTYPE d, FPTYPE f)
int findd (SPTYPE s, DPTYPE d)
int findv (DPTYPE d, VPTYPE v)
int checkv (SPTYPE s)
Function Documentation
int checke (SPTYPE s)
Definition at line 279 of file lowcheck.cpp.
References AllEdgesShell, AllShellsSolid, assert, DNIL, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFShell, findd(), finde(), findf(), findhe(), findl(), findv(), FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLFace, LPTYPE, SheSSolids, SNIL, SolSShells, SUCCESS, VerVEdge, VNIL, and VPTYPE.
Referenced by TraceSolid().
int checkf (SPTYPE s)
Definition at line 126 of file lowcheck.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, assert, checkShell(), DNIL, DPTYPE, EdgHe1, EdgHe2, ENIL, FacFLoops, FacFLOut, FacFShell, findes(), findhes(), findv(), FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, mate, SetFaceBitNOK1, SheSFaces, SheSSolids, SNIL, SolSShells, SUCCESS, and VerVEdge.
Referenced by TraceSolid().
int checkShell (FPTYPE f, DPTYPE d)
Definition at line 93 of file lowcheck.cpp.
References AllLoopsFace, ENIL, FaceBitNOK1, FacFShell, FPTYPE, HalEdg, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, mate, and SetFaceBitOK1.
Referenced by checkf().
int checkv (SPTYPE s)
Definition at line 485 of file lowcheck.cpp.
References AllShellsSolid, AllVerticesShell, assert, DNIL, DPTYPE, ENIL, HalEdg, HalNxt, HalVtx, HNIL, HPTYPE, mate, SheSSolids, SheSVerts, SNIL, SolSShells, SUCCESS, VerVEdge, VNIL, and VPTYPE.
Referenced by TraceSolid().
int findd (SPTYPE s, DPTYPE d)
Definition at line 441 of file lowcheck.cpp.
References AllShellsSolid, assert, DNIL, DPTYPE, MSD_lowListSolid(), SheShellNo, SNIL, and SolSShells.
Referenced by checke(), and MSD_lowDelList().
int finde (VPTYPE v, HPTYPE he)
Definition at line 402 of file lowcheck.cpp.
References HalNxt, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_lowListFace(), VerVEdge, and VerVertexNo.
Referenced by checke().
int findes (DPTYPE d, EPTYPE e)
Definition at line 363 of file lowcheck.cpp.
References AllEdgesShell, assert, DNIL, EdgHe1, EdgHe2, ENIL, EPTYPE, HalVtx, MSD_lowListSolid(), SheSEdges, SheSSolids, and VerVertexNo.
Referenced by checkf(), MSD_lowDelList(), and MSD_lowKEMR().
int findf (DPTYPE d, FPTYPE f)
Definition at line 421 of file lowcheck.cpp.
References AllFacesShell, assert, DNIL, FacFaceNo, FNIL, FPTYPE, MSD_lowListFace(), MSD_lowListSolid(), SheSFaces, and SheSSolids.
Referenced by checke(), MSD_lowDelList(), and MSD_lowMEF().
int findhe (HPTYPE he, LPTYPE l)
Definition at line 342 of file lowcheck.cpp.
References assert, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LooLFace, MSD_lowListFace(), and VerVertexNo.
Referenced by checke().
int findhes (DPTYPE d, HPTYPE he)
Definition at line 232 of file lowcheck.cpp.
References AllFacesShell, AllLoopsFace, assert, FacFShell, FNIL, FPTYPE, HalNxt, HalVtx, HalWLoop, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, MSD_lowListSolid(), SheSSolids, and VerVertexNo.
Referenced by checkf().
int findl (LPTYPE l, FPTYPE f)
Definition at line 383 of file lowcheck.cpp.
References AllLoopsFace, HalNxt, HalVtx, LooLEdg, LooLFace, LPTYPE, MSD_lowListFace(), and VerVertexNo.
Referenced by checke(), MSD_lowDelList(), and MSD_lowMEF().
int findv (DPTYPE d, VPTYPE v)
Definition at line 460 of file lowcheck.cpp.
References AllVerticesShell, assert, DNIL, MSD_lowListSolid(), SheShellNo, SheSSolids, SheSVerts, VerVertexNo, VNIL, and VPTYPE.
Referenced by checke(), checkf(), and MSD_lowDelList().
void MSD_execTrace (void)
Definition at line 50 of file lowcheck.cpp.
References TraceBoundaryStructure().
int TraceBoundaryStructure (void)
Definition at line 58 of file lowcheck.cpp.
References AllSolids, error, FALSE, SPTYPE, TraceSolid(), and TRUE.
Referenced by MSD_execTrace().
int TraceSolid (SPTYPE s)
Definition at line 76 of file lowcheck.cpp.
References checke(), checkf(), checkv(), ERROR, FALSE, and TRUE.
Referenced by MSD_lowAllRingMove(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowShellDetach(), and TraceBoundaryStructure().