USPDesigner: C:/USPDesig/LOW/lowfinde.cpp File Reference
C:/USPDesig/LOW/lowfinde.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "lowmacro.h"
Functions
SPTYPE MSD_lowFindSolidByName (char *nam)
Id MSD_getSolidIdFromName (char *name)
SPTYPE MSD_getSolid (Id sn)
DPTYPE MSD_getShell (SPTYPE s, Id dn)
LPTYPE MSD_getLoop (FPTYPE f, Id vn, HPTYPE *h)
LPTYPE MSD_getEdge (FPTYPE f, Id v1, Id v2, HPTYPE *ptr)
LPTYPE MSD_getHalfedge (FPTYPE f1, FPTYPE f2, Id v1, Id v2, HPTYPE *ptr)
FPTYPE MSD_getFace (SPTYPE s, Id fn)
Id MSD_getMaxSolidId (void)
Id MSD_getMaxFaceId (SPTYPE s)
Id MSD_getMaxShellId (SPTYPE s)
Id MSD_getMaxVertexId (SPTYPE s)
Variables
SPTYPE objary
Function Documentation
LPTYPE MSD_getEdge (FPTYPE f, Id v1, Id v2, HPTYPE * ptr)
Definition at line 130 of file lowfinde.cpp.
References AllLoopsFace, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LPTYPE, and VerVertexNo.
Referenced by MSD_highJEKV(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEMR(), MSD_highKEV(), MSD_highMFKRH2(), MSD_highMSFKR2(), MSD_highRingMove(), MSD_highSEMV(), and MSD_highSVME2().
FPTYPE MSD_getFace (SPTYPE s, Id fn)
Definition at line 179 of file lowfinde.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacFaceNo, FNIL, and FPTYPE.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_execShow(), MSD_highAllRingMove(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEF2(), MSD_highKEMR(), MSD_highKEV(), MSD_highKEV2(), MSD_highKFMRH(), MSD_highKSFMR(), MSD_highKVSF(), MSD_highMEF(), MSD_highMEF2(), MSD_highMEKR(), MSD_highMEKR2(), MSD_highMEV(), MSD_highMFKRH(), MSD_highMFKRH2(), MSD_highMSFKR(), MSD_highMSFKR2(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highRingMove(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_lowImprimeListaEstudo(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCylinder(), MSD_lowMakePrism(), MSD_lowMakePyramid(), and MSD_lowMakeSWEEP().
LPTYPE MSD_getHalfedge (FPTYPE f1, FPTYPE f2, Id v1, Id v2, HPTYPE * ptr)
Definition at line 151 of file lowfinde.cpp.
References AllLoopsFace, ENIL, HalEdg, HalNxt, HalVtx, HalWLoop, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, mate, and VerVertexNo.
Referenced by MSD_highKEF2(), MSD_highKEV2(), MSD_highMEF2(), MSD_highMEKR2(), and MSD_highSVME3().
LPTYPE MSD_getLoop (FPTYPE f, Id vn, HPTYPE * h)
Definition at line 110 of file lowfinde.cpp.
References AllLoopsFace, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LPTYPE, and VerVertexNo.
Referenced by MSD_highMEF(), MSD_highMEKR(), MSD_highMEV(), MSD_highRingMove(), and MSD_highSVME().
Id MSD_getMaxFaceId (SPTYPE s)
Definition at line 204 of file lowfinde.cpp.
References maxf.
Referenced by edv3(), GenerationEdges_nvertices(), MakeEdgeConvexCorner(), MSD_lowEdgeRemove(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplit().
Id MSD_getMaxShellId (SPTYPE s)
Definition at line 211 of file lowfinde.cpp.
References maxd.
Referenced by MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplitFinish().
Id MSD_getMaxSolidId (void)
Definition at line 197 of file lowfinde.cpp.
References maxs.
Referenced by MSD_highCopySolid(), MSD_highDifference(), MSD_highIntersection(), MSD_highLoadSolid(), MSD_highMakeCone(), MSD_highMakeCube(), MSD_highMakeCylinder(), MSD_highMakePrism(), MSD_highMakePyramid(), MSD_highMakeRevolve(), MSD_highMakeSphere(), MSD_highMakeSWEEP(), MSD_highMakeTorus(), MSD_highMVSF(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_highSplit(), MSD_highUnion(), and MSD_lowCheckTranslatorTable().
Id MSD_getMaxVertexId (SPTYPE s)
Definition at line 218 of file lowfinde.cpp.
References maxv.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_lowMakeArc(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplit().
DPTYPE MSD_getShell (SPTYPE s, Id dn)
Definition at line 96 of file lowfinde.cpp.
References AllShellsSolid, DNIL, DPTYPE, and SheShellNo.
Referenced by MSD_highDetach(), and MSD_highRevert().
SPTYPE MSD_getSolid (Id sn)
Definition at line 78 of file lowfinde.cpp.
References objary, SNIL, SolNxt, SolSolidNo, and SPTYPE.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_highAffine(), MSD_highAllRingMove(), MSD_highArea(), MSD_highAreaProjetada(), MSD_highAssociaGroupSolid(), MSD_highAssociaSolidAxis(), MSD_highCentroCarena(), MSD_highCentroDeGravidade(), MSD_highCleanSolid(), MSD_highColor(), MSD_highCopySolid(), MSD_highDensidadeAbsoluta(), MSD_highDensidadeRelativa(), MSD_highDesassociaGroupSolid(), MSD_highDesassociaSolidAxis(), MSD_highDesloca(), MSD_highDetach(), MSD_highDifference(), MSD_highDimensaoPrincipal(), MSD_highDisplayEdge(), MSD_highGlue(), MSD_highHardRemove(), MSD_highIntersection(), MSD_highJEKV(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEF2(), MSD_highKEMR(), MSD_highKEV(), MSD_highKEV2(), MSD_highKFMRH(), MSD_highKSFMR(), MSD_highKVSF(), MSD_highListSolid(), MSD_highMassa(), MSD_highMatrizInercia(), MSD_highMEF(), MSD_highMEF2(), MSD_highMEKR(), MSD_highMEKR2(), MSD_highMerge(), MSD_highMEV(), MSD_highMFKRH(), MSD_highMFKRH2(), MSD_highModifyIds(), MSD_highMSFKR(), MSD_highMSFKR2(), MSD_highName(), MSD_highNameCopySolid(), MSD_highNameLoadSolid(), MSD_highNameMakeCirculo(), MSD_highNameMakeCubo(), MSD_highNameMakeEsfera(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeROVCone(), MSD_highNameMakeSWEEP(), MSD_highNameSaveSolid(), MSD_highNameSplit(), MSD_highNewVertexLocation(), MSD_highPropriedadeArea(), MSD_highRevert(), MSD_highRingMove(), MSD_highRotaciona(), MSD_highRotate(), MSD_highRotateSolidAxis(), MSD_highSaveSolid(), MSD_highScale(), MSD_highSEMV(), MSD_highSoftRemove(), MSD_highSplit(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_highTransformation(), MSD_highTranslate(), MSD_highUnion(), MSD_highVolume(), MSD_lowApplyEulerOp(), MSD_lowDetach(), MSD_lowImprimeListaEstudo(), MSD_lowMakeArc(), and MSD_lowModifyEulerOp().
Id MSD_getSolidIdFromName (char * name)
Definition at line 64 of file lowfinde.cpp.
References AllSolids, SolName, SolSolidNo, and SPTYPE.
Referenced by MSD_highNameAffine(), MSD_highNameArea(), MSD_highNameAreaProjetada(), MSD_highNameAssociaGroupSolid(), MSD_highNameAssociaSolidAxis(), MSD_highNameCentroCarena(), MSD_highNameCentroDeGravidade(), MSD_highNameCleanSolid(), MSD_highNameCopySolid(), MSD_highNameDensidadeAbsoluta(), MSD_highNameDensidadeRelativa(), MSD_highNameDesassociaGroupSolid(), MSD_highNameDesassociaSolidAxis(), MSD_highNameDesloca(), MSD_highNameDifference(), MSD_highNameDimensaoPrincipal(), MSD_highNameIntersection(), MSD_highNameLoadSolid(), MSD_highNameMakeCirculo(), MSD_highNameMakeCone(), MSD_highNameMakeCube(), MSD_highNameMakeCubo(), MSD_highNameMakeCylinder(), MSD_highNameMakeEsfera(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrism(), MSD_highNameMakePrisma(), MSD_highNameMakePyramid(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeRevolve(), MSD_highNameMakeROVCone(), MSD_highNameMakeSphere(), MSD_highNameMakeSWEEP(), MSD_highNameMakeTorus(), MSD_highNameMakeTriangulo(), MSD_highNameMassa(), MSD_highNameMatrizInercia(), MSD_highNameMerge(), MSD_highNamePropriedadeArea(), MSD_highNameRotaciona(), MSD_highNameRotate(), MSD_highNameRotateSolidAxis(), MSD_highNameSaveSolid(), MSD_highNameScale(), MSD_highNameSplit(), MSD_highNameTransformation(), MSD_highNameTranslate(), MSD_highNameUnion(), MSD_highNameVolume(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
SPTYPE MSD_lowFindSolidByName (char * nam)
Definition at line 50 of file lowfinde.cpp.
References AllSolids, SNIL, SolName, and SPTYPE.
Referenced by MSD_CriaListaDePoligonosCoplanares(), MSD_execRndAllEdges(), MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highNameListFaceAdjacency(), MSD_highNameRenameSolid(), MSD_highNameSetDisplay(), MSD_highNameSoftRemove(), MSD_highNameSolidColor(), MSD_highRound(), MSD_lowAreaProjetadaTotal(), MSD_lowNameNCopySolidSpiral(), MSD_lowNameNCopySolidTranslate(), MSD_resetObject(), and MSD_selectObject().
Variable Documentation
SPTYPE objary
Definition at line 322 of file lowsolid.h.
Referenced by main(), maninit(), MSD_getSolid(), MSD_lowAddList(), MSD_lowDelList(), and MSD_lowRemoveGroup().