USPDesigner: C:/USPDesig/LOW/lowfaceq.cpp File Reference
C:/USPDesig/LOW/lowfaceq.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "vectorop.h"
Functions
int MSD_lowFaceEq (LPTYPE l, vector eq)
Function Documentation
int MSD_lowFaceEq (LPTYPE l, vector eq)
Definition at line 49 of file lowfaceq.cpp.
References comp(), EPS, ERROR, FacFeq, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLFace, SetFaceEqOK, SUCCESS, veczer(), and VerVCoord.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowAllRingMove(), MSD_lowFaceCG(), MSD_lowFacVtxContainment(), MSD_lowListFace(), MSD_lowMakeCube(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSWEEP(), MSD_lowSetNormal(), MSD_lowSetOpConnect(), MSD_lowSetOpFinish(), MSD_lowSetOpInside(), MSD_lowSolVtxContainment(), and MSD_lowSplit().