USPDesigner: C:/USPDesig/INC/lowgeome.h File Reference
C:/USPDesig/INC/lowgeome.h File Reference
Typedefs
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
Functions
int MSD_lowEdgVtxContainment (VPTYPE, VPTYPE, VPTYPE)
int MSD_lowFacVtxContainment (FPTYPE, VPTYPE)
int MSD_lowFacVtxCoordContainment (FPTYPE, VPTYPE, int)
int MSD_lowLooVtxBoundary (LPTYPE, VPTYPE)
int MSD_lowLooVtxContainment (LPTYPE, VPTYPE, int)
int MSD_lowLooBoxContainment (LPTYPE, VPTYPE, int)
int MSD_lowSolVtxContainment (SPTYPE, VPTYPE)
int MSD_lowVtxVtxContainment (VPTYPE, VPTYPE)
int MSD_lowFacFacIdentical (FPTYPE, FPTYPE)
int MSD_lowFacFacContainment (FPTYPE, FPTYPE)
int MSD_lowFacFacEqualEqs (FPTYPE, FPTYPE)
int MSD_lowFacFacOppositeEqs (FPTYPE, FPTYPE)
int MSD_lowEdgEdgColinear (EPTYPE, EPTYPE)
int MSD_lowNullEdge (HPTYPE)
int MSD_lowEdgEdgIntersection (VPTYPE, VPTYPE, VPTYPE, VPTYPE, int, real *, real *)
int MSD_lowVtxEdgIntersection (VPTYPE, VPTYPE, VPTYPE, real *)
Typedef Documentation
typedef struct edge ETYPE
Definition at line 60 of file lowgeome.h.
typedef struct face FTYPE
Definition at line 52 of file lowgeome.h.
typedef struct halfedge HTYPE
Definition at line 64 of file lowgeome.h.
typedef struct loop LTYPE
Definition at line 56 of file lowgeome.h.
typedef struct solid STYPE
Definition at line 48 of file lowgeome.h.
typedef real vector[4]
Definition at line 44 of file lowgeome.h.
typedef struct vertex VTYPE
Definition at line 68 of file lowgeome.h.
Function Documentation
int MSD_lowEdgEdgColinear (EPTYPE , EPTYPE)
Definition at line 626 of file lowgeome.cpp.
References cross(), EdgHe1, EdgHe2, EPS, HalVtx, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowCleanSolid().
int MSD_lowEdgEdgIntersection (VPTYPE , VPTYPE , VPTYPE , VPTYPE , int , real * , real *)
Definition at line 180 of file lowgeome.cpp.
References comp(), EPS, VerVCoord, X, Y, and Z.
Referenced by MSD_lowLooVtxContainment().
int MSD_lowEdgVtxContainment (VPTYPE , VPTYPE , VPTYPE)
Definition at line 100 of file lowgeome.cpp.
References EPS, FALSE, MSD_lowEdgVtxIntersection(), and TRUE.
Referenced by MSD_lowLooVtxBoundary().
int MSD_lowFacFacContainment (FPTYPE , FPTYPE)
Definition at line 577 of file lowgeome.cpp.
References AllLoopsFace, FacFeq, FacFLOut, FALSE, getdrop(), HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowLooVtxContainment(), and TRUE.
Referenced by MSD_lowGlue().
int MSD_lowFacFacEqualEqs (FPTYPE , FPTYPE)
Definition at line 597 of file lowgeome.cpp.
References comp(), EPS, FacFeq, FALSE, veccopy(), and vecequal().
Referenced by MSD_lowCleanSolid().
int MSD_lowFacFacIdentical (FPTYPE , FPTYPE)
Definition at line 535 of file lowgeome.cpp.
References FacFLOut, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LooLength, LPTYPE, and MSD_lowVtxVtxContainment().
Referenced by MSD_lowGlue().
int MSD_lowFacFacOppositeEqs (FPTYPE , FPTYPE)
Definition at line 611 of file lowgeome.cpp.
References comp(), EPS, FacFeq, veccopy(), vecnull(), and vecplus().
Referenced by MSD_lowGlue().
int MSD_lowFacVtxContainment (FPTYPE , VPTYPE)
Definition at line 117 of file lowgeome.cpp.
References FaceEqNOK, FacFeq, FacFLOut, getdrop(), MSD_lowFaceEq(), and MSD_lowFacVtxCoordContainment().
Referenced by MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpFacPntContainment(), and MSD_lowSolVtxContainment().
int MSD_lowFacVtxCoordContainment (FPTYPE , VPTYPE , int)
Definition at line 126 of file lowgeome.cpp.
References AllLoopsFace, FacFLOut, LPTYPE, and MSD_lowLooVtxContainment().
Referenced by MSD_lowAllRingMove(), and MSD_lowFacVtxContainment().
int MSD_lowLooBoxContainment (LPTYPE , VPTYPE , int)
Definition at line 315 of file lowgeome.cpp.
References CONTBVEPS, HalNxt, HalVtx, HPTYPE, LooLEdg, VerVCoord, VPTYPE, X, Y, and Z.
int MSD_lowLooVtxBoundary (LPTYPE , VPTYPE)
Definition at line 153 of file lowgeome.cpp.
References HalNxt, HalVtx, hithe, hitvertex, HNIL, HPTYPE, LooLEdg, MSD_lowEdgVtxContainment(), MSD_lowVtxVtxContainment(), and VNIL.
Referenced by MSD_lowLooVtxContainment().
int MSD_lowLooVtxContainment (LPTYPE , VPTYPE , int)
Definition at line 225 of file lowgeome.cpp.
References comp(), EPS, ERROR, HalNxt, HalVtx, HPTYPE, LooLEdg, MSD_getMemVirtual(), MSD_lowEdgEdgIntersection(), MSD_lowLooVtxBoundary(), MSD_putMemVirtual(), veccopy(), vecesc(), vecplus(), VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowCleanSolid(), MSD_lowFacFacContainment(), MSD_lowFacVtxCoordContainment(), and MSD_lowMakeFaceToPoint().
int MSD_lowNullEdge (HPTYPE)
Definition at line 645 of file lowgeome.cpp.
References HalNxt, HalVtx, and MSD_lowVtxVtxContainment().
int MSD_lowSolVtxContainment (SPTYPE , VPTYPE)
Definition at line 432 of file lowgeome.cpp.
References AllFacesShell, AllShellsSolid, comp(), DPTYPE, EPS, FaceEqNOK, FacFeq, FacFLOut, FPTYPE, MSD_getMemVirtual(), MSD_lowDistancePlanePoint(), MSD_lowFaceEq(), MSD_lowFacVtxContainment(), MSD_putMemVirtual(), VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOp().
int MSD_lowVtxEdgIntersection (VPTYPE , VPTYPE , VPTYPE , real *)
int MSD_lowVtxVtxContainment (VPTYPE , VPTYPE)
Definition at line 52 of file lowgeome.cpp.
References veccopy(), vecequal(), and VerVCoord.
Referenced by MSD_lowCleanSolid(), MSD_lowEdgVtxIntersection(), MSD_lowFacFacIdentical(), MSD_lowLoopGlue(), MSD_lowLooVtxBoundary(), MSD_lowNullEdge(), and MSD_lowSetOpNullEdge().