USPDesigner: C:/USPDesig/LOW/lowgeome.cpp File Reference
C:/USPDesig/LOW/lowgeome.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "splsplit.h"
#include "lowgeome.h"
Functions
int MSD_lowVtxVtxContainment (VPTYPE v1, VPTYPE v2)
int MSD_lowEdgVtxIntersection (VPTYPE v1, VPTYPE v2, VPTYPE v3, real *t)
int MSD_lowEdgVtxContainment (VPTYPE v1, VPTYPE v2, VPTYPE v3)
int MSD_lowFacVtxContainment (FPTYPE f, VPTYPE v)
int MSD_lowFacVtxCoordContainment (FPTYPE f, VPTYPE v, int drop)
int MSD_lowLooVtxBoundary (LPTYPE l, VPTYPE v)
int MSD_lowEdgEdgIntersection (VPTYPE v1, VPTYPE v2, VPTYPE v3, VPTYPE v4, int drop, real *t1, real *t2)
int MSD_lowLooVtxContainment (LPTYPE l, VPTYPE v, int drop)
int MSD_lowLooBoxContainment (LPTYPE l, VPTYPE v, int drop)
int MSD_lowSolVtxContainment (SPTYPE s, VPTYPE v)
int MSD_lowFacFacIdentical (FPTYPE f1, FPTYPE f2)
int MSD_lowFacFacContainment (FPTYPE f1, FPTYPE f2)
int MSD_lowFacFacEqualEqs (FPTYPE f1, FPTYPE f2)
int MSD_lowFacFacOppositeEqs (FPTYPE f1, FPTYPE f2)
int MSD_lowEdgEdgColinear (EPTYPE e1, EPTYPE e2)
int MSD_lowNullEdge (HPTYPE h)
Function Documentation
int MSD_lowEdgEdgColinear (EPTYPE e1, EPTYPE e2)
Definition at line 626 of file lowgeome.cpp.
References cross(), EdgHe1, EdgHe2, EPS, HalVtx, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowCleanSolid().
int MSD_lowEdgEdgIntersection (VPTYPE v1, VPTYPE v2, VPTYPE v3, VPTYPE v4, int drop, real * t1, real * t2)
Definition at line 180 of file lowgeome.cpp.
References comp(), EPS, VerVCoord, X, Y, and Z.
Referenced by MSD_lowLooVtxContainment().
int MSD_lowEdgVtxContainment (VPTYPE v1, VPTYPE v2, VPTYPE v3)
Definition at line 100 of file lowgeome.cpp.
References EPS, FALSE, MSD_lowEdgVtxIntersection(), and TRUE.
Referenced by MSD_lowLooVtxBoundary().
int MSD_lowEdgVtxIntersection (VPTYPE v1, VPTYPE v2, VPTYPE v3, real * t)
Definition at line 62 of file lowgeome.cpp.
References dot(), EPS, MSD_getMemVirtual(), MSD_lowVtxVtxContainment(), MSD_putMemVirtual(), veccopy(), vecminus(), vecpe(), VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowEdgVtxContainment().
int MSD_lowFacFacContainment (FPTYPE f1, FPTYPE f2)
Definition at line 577 of file lowgeome.cpp.
References AllLoopsFace, FacFeq, FacFLOut, FALSE, getdrop(), HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowLooVtxContainment(), and TRUE.
Referenced by MSD_lowGlue().
int MSD_lowFacFacEqualEqs (FPTYPE f1, FPTYPE f2)
Definition at line 597 of file lowgeome.cpp.
References comp(), EPS, FacFeq, FALSE, veccopy(), and vecequal().
Referenced by MSD_lowCleanSolid().
int MSD_lowFacFacIdentical (FPTYPE f1, FPTYPE f2)
Definition at line 535 of file lowgeome.cpp.
References FacFLOut, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LooLength, LPTYPE, and MSD_lowVtxVtxContainment().
Referenced by MSD_lowGlue().
int MSD_lowFacFacOppositeEqs (FPTYPE f1, FPTYPE f2)
Definition at line 611 of file lowgeome.cpp.
References comp(), EPS, FacFeq, veccopy(), vecnull(), and vecplus().
Referenced by MSD_lowGlue().
int MSD_lowFacVtxContainment (FPTYPE f, VPTYPE v)
Definition at line 117 of file lowgeome.cpp.
References FaceEqNOK, FacFeq, FacFLOut, getdrop(), MSD_lowFaceEq(), and MSD_lowFacVtxCoordContainment().
Referenced by MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpFacPntContainment(), and MSD_lowSolVtxContainment().
int MSD_lowFacVtxCoordContainment (FPTYPE f, VPTYPE v, int drop)
Definition at line 126 of file lowgeome.cpp.
References AllLoopsFace, FacFLOut, LPTYPE, and MSD_lowLooVtxContainment().
Referenced by MSD_lowAllRingMove(), and MSD_lowFacVtxContainment().
int MSD_lowLooBoxContainment (LPTYPE l, VPTYPE v, int drop)
Definition at line 315 of file lowgeome.cpp.
References CONTBVEPS, HalNxt, HalVtx, HPTYPE, LooLEdg, VerVCoord, VPTYPE, X, Y, and Z.
int MSD_lowLooVtxBoundary (LPTYPE l, VPTYPE v)
Definition at line 153 of file lowgeome.cpp.
References HalNxt, HalVtx, hithe, hitvertex, HNIL, HPTYPE, LooLEdg, MSD_lowEdgVtxContainment(), MSD_lowVtxVtxContainment(), and VNIL.
Referenced by MSD_lowLooVtxContainment().
int MSD_lowLooVtxContainment (LPTYPE l, VPTYPE v, int drop)
Definition at line 225 of file lowgeome.cpp.
References comp(), EPS, ERROR, HalNxt, HalVtx, HPTYPE, LooLEdg, MSD_getMemVirtual(), MSD_lowEdgEdgIntersection(), MSD_lowLooVtxBoundary(), MSD_putMemVirtual(), veccopy(), vecesc(), vecplus(), VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowCleanSolid(), MSD_lowFacFacContainment(), MSD_lowFacVtxCoordContainment(), and MSD_lowMakeFaceToPoint().
int MSD_lowNullEdge (HPTYPE h)
Definition at line 645 of file lowgeome.cpp.
References HalNxt, HalVtx, and MSD_lowVtxVtxContainment().
int MSD_lowSolVtxContainment (SPTYPE s, VPTYPE v)
Definition at line 432 of file lowgeome.cpp.
References AllFacesShell, AllShellsSolid, comp(), DPTYPE, EPS, FaceEqNOK, FacFeq, FacFLOut, FPTYPE, MSD_getMemVirtual(), MSD_lowDistancePlanePoint(), MSD_lowFaceEq(), MSD_lowFacVtxContainment(), MSD_putMemVirtual(), VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOp().
int MSD_lowVtxVtxContainment (VPTYPE v1, VPTYPE v2)
Definition at line 52 of file lowgeome.cpp.
References veccopy(), vecequal(), and VerVCoord.
Referenced by MSD_lowCleanSolid(), MSD_lowEdgVtxIntersection(), MSD_lowFacFacIdentical(), MSD_lowLoopGlue(), MSD_lowLooVtxBoundary(), MSD_lowNullEdge(), and MSD_lowSetOpNullEdge().