USPDesigner: C:/USPDesig/LOW/lowinfos.cpp File Reference
C:/USPDesig/LOW/lowinfos.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
Functions
void MSD_lowSetInfo (SPTYPE optr)
void MSD_lowSetLoopEdge (SPTYPE optr)
void MSD_lowCountFaceEdges (SPTYPE optr)
Function Documentation
void MSD_lowCountFaceEdges (SPTYPE optr)
Definition at line 87 of file lowinfos.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, DPTYPE, FacFLOut, FPTYPE, HalNxt, HPTYPE, LooLEdg, LooLength, and LPTYPE.
Referenced by MSD_lowSetInfo().
void MSD_lowSetInfo (SPTYPE optr)
Definition at line 48 of file lowinfos.cpp.
References MSD_lowCountFaceEdges(), and MSD_lowSetLoopEdge().
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowSetOp(), and MSD_lowSplit().
void MSD_lowSetLoopEdge (SPTYPE optr)
Definition at line 54 of file lowinfos.cpp.
References AllEdgesShell, AllFacesShell, AllLoopsFace, AllShellsSolid, DPTYPE, EdgEdgeNo, EPTYPE, FacFLOut, FPTYPE, LooLoopNo, and LPTYPE.
Referenced by MSD_lowSetInfo().