USPDesigner: C:/USPDesig/LOW/lowlists.cpp File Reference
C:/USPDesig/LOW/lowlists.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
Functions
int MSD_highListSolid (Id sn, int sw)
void MSD_lowListSolid (FILE *file, SPTYPE s, int sw)
void MSD_lowListFace (FILE *file, FPTYPE f, int sw)
Function Documentation
int MSD_highListSolid (Id sn, int sw)
Definition at line 67 of file lowlists.cpp.
References ERROR, MSD_getSolid(), MSD_lowListSolid(), SNIL, SPTYPE, and SUCCESS.
void MSD_lowListFace (FILE * file, FPTYPE f, int sw)
Definition at line 152 of file lowlists.cpp.
References AllLoopsFace, EdgHe1, EdgHe2, ENIL, EPTYPE, FacFaceNo, FacFLOut, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowFaceEq(), VerVertexNo, and VPTYPE.
Referenced by finde(), findf(), findhe(), findl(), MSD_lowListSolid(), and MSD_lowSetOpConnect().
void MSD_lowListSolid (FILE * file, SPTYPE s, int sw)
Definition at line 80 of file lowlists.cpp.
References AllEdgesShell, AllFacesShell, AllShellsSolid, AllVerticesShell, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFaceNo, FPTYPE, HalEdg, HalNxt, HalVtx, HalWLoop, HNIL, HPTYPE, LooLFace, mate, MSD_lowListFace(), SheShellNo, SNIL, SolSolidNo, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by findd(), findes(), findf(), findhes(), findv(), MSD_highListSolid(), MSD_lowMSFKR(), MSD_lowSetOp(), and MSD_lowSplit().