USPDesigner: C:/USPDesig/LOW/lownewel.cpp File Reference
C:/USPDesig/LOW/lownewel.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "hiegroup.h"
#include "curvgeom.h"
Functions
NPTYPE MSD_lowNewElement (int what, NPTYPE where)
void MSD_lowDelElement (int what, NPTYPE node, NPTYPE where)
int bytesused (STYPE *s)
Variables
unsigned nodesize []
Function Documentation
int bytesused (STYPE * s)
Definition at line 314 of file lownewel.cpp.
References AllEdgesShell, AllFacesShell, AllLoopsFace, AllShellsSolid, AllVerticesShell, EDGE, FACE, HALFEDGE, loop::length, LOOP, nodesize, SHELL, SOLID, and VERTEX.
void MSD_lowDelElement (int what, NPTYPE node, NPTYPE where)
Definition at line 261 of file lownewel.cpp.
References AXIS, EDGE, FACE, GROUP, HALFEDGE, LOOP, MSD_lowDelList(), MSD_putMemVirtual(), SHELL, SOLID, and VERTEX.
Referenced by MSD_lowDelHE(), MSD_lowHardRemove(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEKR(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), and MSD_lowShellDetach().
NPTYPE MSD_lowNewElement (int what, NPTYPE where)
Definition at line 89 of file lownewel.cpp.
References ANIL, AXIS, AxsAGroup, AxsType, CNIL, def_grpptr, DNIL, EdgColor, EdgD, EDGE, EdgFgMake, EdgFgRound, EdgT1, EdgT2, EdgT3, EdgT4, ENIL, FacColor, FACE, FacFBits, FacFlag, FacFLoops, FacFLOut, FNIL, GNIL, GROUP, GrpGAxs, GrpGColor, GrpParent, HalCurv, HALFEDGE, HalR, HNIL, LNIL, LOOP, MSD_getMemVirtual(), MSD_lowAddList(), NIL, NNIL, nodesize, NONE, NPTYPE, SheColor, SheDBits, SHELL, SheSEdges, SheSFaces, SheSVerts, SolColor, SolCurv, SolDsp, SolGroup, SOLID, SolName, SolOAxs, SolPerfil, SolSBits, SolSShells, TRUE, VerFgMake, VerFgRound, VERTEX, VerVEdge, and VNIL.
Referenced by MSD_lowAddHE(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCreateGroup(), MSD_lowDetach(), MSD_lowKEMR(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), and MSD_lowMVSF().
Variable Documentation
unsigned nodesize[]
Initial value:
{
   sizeof(STYPE), sizeof(DTYPE), sizeof(FTYPE), sizeof(LTYPE),
   sizeof(ETYPE), sizeof(HTYPE), sizeof(VTYPE), sizeof(ATYPE),
   sizeof(GTYPE),             0,
}
Definition at line 53 of file lownewel.cpp.
Referenced by bytesused(), and MSD_lowNewElement().