USPDesigner: C:/USPDesig/INC/lowsolid.h File Reference
C:/USPDesig/INC/lowsolid.h File Reference
#include "hiegroup.h"
Classes
struct box
struct eulerco
struct solid
struct shell
struct face
struct loop
struct edge
struct halfedge
struct vertex
union nodes
Defines
#define GRAVIDADE 9.8
Typedefs
typedef real vect2 [3]
typedef struct cameratp CTYPE
typedef struct shell DTYPE
typedef struct box BTYPE
typedef struct eulerco EulerCo
typedef union nodes NTYPE
Functions
void MSD_lowAddList (int what, NPTYPE which, NPTYPE where)
void MSD_lowDelList (int what, NPTYPE which, NPTYPE where)
HPTYPE MSD_lowAddHE (EPTYPE e, VPTYPE v, HPTYPE where, int orient)
HPTYPE MSD_lowDelHE (HPTYPE he)
void MSD_lowSolidBoxFromBoxes (SPTYPE s, BTYPE *b)
int MSD_lowEdgeBoxIntersection (BTYPE *b, EPTYPE e)
int MSD_lowEdgeBoxIntersectionAux (real x1, real x2, real bx1, real bx2)
int MSD_lowBoxBoxIntersection (BTYPE *b1, BTYPE *b2)
int MSD_lowVertexInBox (BTYPE *b, real x, real y, real z)
void MSD_lowSolidBox (SPTYPE s, BTYPE *bx)
void MSD_lowShellBox (DPTYPE d)
void MSD_lowFaceBox (FPTYPE f)
void MSD_lowEdgeBox (BTYPE *b, EPTYPE e)
void MSD_lowEvaluateSolidBoxes (SPTYPE s)
void MSD_lowWidenBox (BTYPE *b, real eps)
void MSD_lowUpdateBox (BTYPE *b1, BTYPE *b)
void MSD_lowTranslatedBox (BTYPE *b, real dx, real dy, real dz)
void MSD_lowUpdateDEBox (void)
void MSD_execTrace (void)
int TraceBoundaryStructure (void)
int TraceSolid (SPTYPE s)
int checkf (SPTYPE s)
int findhes (DPTYPE d, HPTYPE he)
int checke (SPTYPE s)
int findhe (HPTYPE he, LPTYPE l)
int findes (DPTYPE d, EPTYPE e)
int findl (LPTYPE l, FPTYPE f)
int finde (VPTYPE v, HPTYPE he)
int findf (DPTYPE d, FPTYPE f)
int findd (SPTYPE s, DPTYPE d)
int findv (DPTYPE d, VPTYPE v)
int checkv (SPTYPE s)
int MSD_lowFaceEq (LPTYPE l, vector eq)
SPTYPE MSD_lowFindSolidByName (char *name)
Id MSD_getSolidIdFromName (char *name)
SPTYPE MSD_getSolid (Id sn)
DPTYPE MSD_getShell (SPTYPE s, Id dn)
LPTYPE MSD_getLoop (FPTYPE f, Id vn, HPTYPE *h)
LPTYPE MSD_getEdge (FPTYPE f, Id v1, Id v2, HPTYPE *ptr)
LPTYPE MSD_getHalfedge (FPTYPE f1, FPTYPE f2, Id v1, Id v2, HPTYPE *ptr)
FPTYPE MSD_getFace (SPTYPE s, Id fn)
Id MSD_getMaxSolidId (void)
Id MSD_getMaxShellId (SPTYPE s)
Id MSD_getMaxFaceId (SPTYPE s)
Id MSD_getMaxVertexId (SPTYPE s)
void MSD_lowSetInfo (SPTYPE optr)
void MSD_lowSetLoopEdge (SPTYPE optr)
void MSD_lowCountFaceEdges (SPTYPE optr)
void MSD_execListSolid (void)
int MSD_highListSolid (Id sn, int sw)
void MSD_lowListSolid (FILE *file, SPTYPE s, int sw)
void MSD_lowListFace (FILE *file, FPTYPE f, int sw)
NPTYPE MSD_lowNewElement (int what, NPTYPE where)
void MSD_lowDelElement (int what, NPTYPE node, NPTYPE where)
int bytesused (SPTYPE s)
void MSD_execNameAffine (void)
int MSD_highNameAffine (char *name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
void MSD_execAffine (void)
int MSD_highAffine (Id sn, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
int MSD_lowAffine (SPTYPE sptr, vector center, matrix mat)
void MSD_execNameTransformation (void)
int MSD_highNameTransformation (char *name, matrix)
void MSD_execTransformation (void)
int MSD_highTransformation (Id sn, matrix)
void MSD_lowTransformation (SPTYPE s, matrix)
int MSD_execStructTransformation (EulerOp *op)
void MSD_printStructTransformation (FILE *f, EulerOp *op)
int MSD_readStructTransformation (FILE *f, EulerOp *op)
int MSD_modifyStructTransformation (EulerOp *op)
void MSD_execNameRotate (void)
int MSD_highNameRotate (char *name, real tx, real ty, real tz)
void MSD_execRotate (void)
int MSD_highRotate (Id sn, real tx, real ty, real tz)
void MSD_lowRotate (SPTYPE s, real tx, real ty, real tz)
int MSD_execStructRotate (EulerOp *op)
void MSD_printStructRotate (FILE *f, EulerOp *op)
int MSD_readStructRotate (FILE *f, EulerOp *op)
int MSD_modifyStructRotate (EulerOp *op)
void MSD_execNameRotateSolidAxis (void)
int MSD_highNameRotateSolidAxis (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
void MSD_execRotateSolidAxis (void)
int MSD_highRotateSolidAxis (Id sn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_lowRotateSolidAxis (SPTYPE sptr, vector center, vector axis, real th)
void MSD_execNameScale (void)
int MSD_highNameScale (char *name, real tx, real ty, real tz)
void MSD_execScale (void)
int MSD_highScale (Id sn, real tx, real ty, real tz)
void MSD_lowScale (SPTYPE s, real tx, real ty, real tz)
int MSD_execStructScale (EulerOp *op)
void MSD_printStructScale (FILE *f, EulerOp *op)
int MSD_readStructScale (FILE *f, EulerOp *op)
int MSD_modifyStructScale (EulerOp *op)
void MSD_execNameTranslate (void)
int MSD_highNameTranslate (char *name, real tx, real ty, real tz)
void MSD_execTranslate (void)
int MSD_highTranslate (Id sn, real tx, real ty, real tz)
void MSD_lowTranslate (SPTYPE s, real tx, real ty, real tz)
int MSD_execStructTranslate (EulerOp *op)
void MSD_printStructTranslate (FILE *f, EulerOp *op)
int MSD_readStructTranslate (FILE *f, EulerOp *op)
int MSD_modifyStructTranslate (EulerOp *op)
Variables
EXTERN int maxs
EXTERN Id maxf
EXTERN Id maxv
EXTERN Id maxd
EXTERN int error
EXTERN VPTYPE hitvertex
EXTERN HPTYPE hithe
EXTERN SPTYPE objary
EXTERN int SetTrace
EXTERN int objused
EXTERN int facused
EXTERN int looused
EXTERN int edgused
EXTERN int vtxused
EXTERN long defonum
Define Documentation
#define GRAVIDADE 9.8
Definition at line 59 of file lowsolid.h.
Referenced by MSD_lowEmpuxoTotal(), and MSD_lowPesoTotal().
Typedef Documentation
typedef struct box BTYPE
Definition at line 142 of file lowsolid.h.
typedef struct cameratp CTYPE
Definition at line 107 of file lowsolid.h.
typedef struct shell DTYPE
Definition at line 118 of file lowsolid.h.
typedef struct eulerco EulerCo
Definition at line 144 of file lowsolid.h.
typedef union nodes NTYPE
Definition at line 145 of file lowsolid.h.
typedef real vect2[3]
Definition at line 73 of file lowsolid.h.
Function Documentation
int bytesused (SPTYPE s)
int checke (SPTYPE s)
Definition at line 279 of file lowcheck.cpp.
References AllEdgesShell, AllShellsSolid, assert, DNIL, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFShell, findd(), finde(), findf(), findhe(), findl(), findv(), FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLFace, LPTYPE, SheSSolids, SNIL, SolSShells, SUCCESS, VerVEdge, VNIL, and VPTYPE.
Referenced by TraceSolid().
int checkf (SPTYPE s)
Definition at line 126 of file lowcheck.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, assert, checkShell(), DNIL, DPTYPE, EdgHe1, EdgHe2, ENIL, FacFLoops, FacFLOut, FacFShell, findes(), findhes(), findv(), FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, mate, SetFaceBitNOK1, SheSFaces, SheSSolids, SNIL, SolSShells, SUCCESS, and VerVEdge.
Referenced by TraceSolid().
int checkv (SPTYPE s)
Definition at line 485 of file lowcheck.cpp.
References AllShellsSolid, AllVerticesShell, assert, DNIL, DPTYPE, ENIL, HalEdg, HalNxt, HalVtx, HNIL, HPTYPE, mate, SheSSolids, SheSVerts, SNIL, SolSShells, SUCCESS, VerVEdge, VNIL, and VPTYPE.
Referenced by TraceSolid().
int findd (SPTYPE s, DPTYPE d)
Definition at line 441 of file lowcheck.cpp.
References AllShellsSolid, assert, DNIL, DPTYPE, MSD_lowListSolid(), SheShellNo, SNIL, and SolSShells.
Referenced by checke(), and MSD_lowDelList().
int finde (VPTYPE v, HPTYPE he)
Definition at line 402 of file lowcheck.cpp.
References HalNxt, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_lowListFace(), VerVEdge, and VerVertexNo.
Referenced by checke().
int findes (DPTYPE d, EPTYPE e)
Definition at line 363 of file lowcheck.cpp.
References AllEdgesShell, assert, DNIL, EdgHe1, EdgHe2, ENIL, EPTYPE, HalVtx, MSD_lowListSolid(), SheSEdges, SheSSolids, and VerVertexNo.
Referenced by checkf(), MSD_lowDelList(), and MSD_lowKEMR().
int findf (DPTYPE d, FPTYPE f)
Definition at line 421 of file lowcheck.cpp.
References AllFacesShell, assert, DNIL, FacFaceNo, FNIL, FPTYPE, MSD_lowListFace(), MSD_lowListSolid(), SheSFaces, and SheSSolids.
Referenced by checke(), MSD_lowDelList(), and MSD_lowMEF().
int findhe (HPTYPE he, LPTYPE l)
Definition at line 342 of file lowcheck.cpp.
References assert, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LooLFace, MSD_lowListFace(), and VerVertexNo.
Referenced by checke().
int findhes (DPTYPE d, HPTYPE he)
Definition at line 232 of file lowcheck.cpp.
References AllFacesShell, AllLoopsFace, assert, FacFShell, FNIL, FPTYPE, HalNxt, HalVtx, HalWLoop, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, MSD_lowListSolid(), SheSSolids, and VerVertexNo.
Referenced by checkf().
int findl (LPTYPE l, FPTYPE f)
Definition at line 383 of file lowcheck.cpp.
References AllLoopsFace, HalNxt, HalVtx, LooLEdg, LooLFace, LPTYPE, MSD_lowListFace(), and VerVertexNo.
Referenced by checke(), MSD_lowDelList(), and MSD_lowMEF().
int findv (DPTYPE d, VPTYPE v)
Definition at line 460 of file lowcheck.cpp.
References AllVerticesShell, assert, DNIL, MSD_lowListSolid(), SheShellNo, SheSSolids, SheSVerts, VerVertexNo, VNIL, and VPTYPE.
Referenced by checke(), checkf(), and MSD_lowDelList().
void MSD_execAffine (void)
void MSD_execListSolid (void)
void MSD_execNameAffine (void)
Definition at line 52 of file lowtrafn.cpp.
References lineins(), MSD_highNameAffine(), and restbuf.
void MSD_execNameRotate (void)
void MSD_execNameRotateSolidAxis (void)
void MSD_execNameScale (void)
Definition at line 53 of file lowtrsca.cpp.
References lineins(), MSD_highNameScale(), and restbuf.
void MSD_execNameTransformation (void)
void MSD_execNameTranslate (void)
void MSD_execRotate (void)
void MSD_execRotateSolidAxis (void)
void MSD_execScale (void)
int MSD_execStructRotate (EulerOp * op)
Definition at line 160 of file lowtrrot.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highRotate(), eulerop::solidno, and SUCCESS.
int MSD_execStructScale (EulerOp * op)
Definition at line 163 of file lowtrsca.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highScale(), eulerop::solidno, and SUCCESS.
int MSD_execStructTransformation (EulerOp * op)
Definition at line 221 of file lowtrans.cpp.
References matident(), MSD_highTransformation(), MSD_lowGetMatrix(), eulerop::solidno, and SUCCESS.
int MSD_execStructTranslate (EulerOp * op)
Definition at line 175 of file lowtrtra.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highTranslate(), eulerop::solidno, and SUCCESS.
void MSD_execTrace (void)
Definition at line 50 of file lowcheck.cpp.
References TraceBoundaryStructure().
void MSD_execTransformation (void)
void MSD_execTranslate (void)
LPTYPE MSD_getEdge (FPTYPE f, Id v1, Id v2, HPTYPE * ptr)
Definition at line 130 of file lowfinde.cpp.
References AllLoopsFace, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LPTYPE, and VerVertexNo.
Referenced by MSD_highJEKV(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEMR(), MSD_highKEV(), MSD_highMFKRH2(), MSD_highMSFKR2(), MSD_highRingMove(), MSD_highSEMV(), and MSD_highSVME2().
FPTYPE MSD_getFace (SPTYPE s, Id fn)
Definition at line 179 of file lowfinde.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacFaceNo, FNIL, and FPTYPE.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_execShow(), MSD_highAllRingMove(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEF2(), MSD_highKEMR(), MSD_highKEV(), MSD_highKEV2(), MSD_highKFMRH(), MSD_highKSFMR(), MSD_highKVSF(), MSD_highMEF(), MSD_highMEF2(), MSD_highMEKR(), MSD_highMEKR2(), MSD_highMEV(), MSD_highMFKRH(), MSD_highMFKRH2(), MSD_highMSFKR(), MSD_highMSFKR2(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highRingMove(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_lowImprimeListaEstudo(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCylinder(), MSD_lowMakePrism(), MSD_lowMakePyramid(), and MSD_lowMakeSWEEP().
LPTYPE MSD_getHalfedge (FPTYPE f1, FPTYPE f2, Id v1, Id v2, HPTYPE * ptr)
Definition at line 151 of file lowfinde.cpp.
References AllLoopsFace, ENIL, HalEdg, HalNxt, HalVtx, HalWLoop, HPTYPE, LNIL, LooLEdg, LooLFace, LPTYPE, mate, and VerVertexNo.
Referenced by MSD_highKEF2(), MSD_highKEV2(), MSD_highMEF2(), MSD_highMEKR2(), and MSD_highSVME3().
LPTYPE MSD_getLoop (FPTYPE f, Id vn, HPTYPE * h)
Definition at line 110 of file lowfinde.cpp.
References AllLoopsFace, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LPTYPE, and VerVertexNo.
Referenced by MSD_highMEF(), MSD_highMEKR(), MSD_highMEV(), MSD_highRingMove(), and MSD_highSVME().
Id MSD_getMaxFaceId (SPTYPE s)
Definition at line 204 of file lowfinde.cpp.
References maxf.
Referenced by edv3(), GenerationEdges_nvertices(), MakeEdgeConvexCorner(), MSD_lowEdgeRemove(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplit().
Id MSD_getMaxShellId (SPTYPE s)
Definition at line 211 of file lowfinde.cpp.
References maxd.
Referenced by MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplitFinish().
Id MSD_getMaxSolidId (void)
Definition at line 197 of file lowfinde.cpp.
References maxs.
Referenced by MSD_highCopySolid(), MSD_highDifference(), MSD_highIntersection(), MSD_highLoadSolid(), MSD_highMakeCone(), MSD_highMakeCube(), MSD_highMakeCylinder(), MSD_highMakePrism(), MSD_highMakePyramid(), MSD_highMakeRevolve(), MSD_highMakeSphere(), MSD_highMakeSWEEP(), MSD_highMakeTorus(), MSD_highMVSF(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_highSplit(), MSD_highUnion(), and MSD_lowCheckTranslatorTable().
Id MSD_getMaxVertexId (SPTYPE s)
Definition at line 218 of file lowfinde.cpp.
References maxv.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_lowMakeArc(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSweep(), MSD_lowMakeSweepNew(), MSD_lowMerge(), MSD_lowSetOp(), and MSD_lowSplit().
DPTYPE MSD_getShell (SPTYPE s, Id dn)
Definition at line 96 of file lowfinde.cpp.
References AllShellsSolid, DNIL, DPTYPE, and SheShellNo.
Referenced by MSD_highDetach(), and MSD_highRevert().
SPTYPE MSD_getSolid (Id sn)
Definition at line 78 of file lowfinde.cpp.
References objary, SNIL, SolNxt, SolSolidNo, and SPTYPE.
Referenced by MSD_determinaDimensaoPrincipal(), MSD_highAffine(), MSD_highAllRingMove(), MSD_highArea(), MSD_highAreaProjetada(), MSD_highAssociaGroupSolid(), MSD_highAssociaSolidAxis(), MSD_highCentroCarena(), MSD_highCentroDeGravidade(), MSD_highCleanSolid(), MSD_highColor(), MSD_highCopySolid(), MSD_highDensidadeAbsoluta(), MSD_highDensidadeRelativa(), MSD_highDesassociaGroupSolid(), MSD_highDesassociaSolidAxis(), MSD_highDesloca(), MSD_highDetach(), MSD_highDifference(), MSD_highDimensaoPrincipal(), MSD_highDisplayEdge(), MSD_highGlue(), MSD_highHardRemove(), MSD_highIntersection(), MSD_highJEKV(), MSD_highJVKE(), MSD_highKEF(), MSD_highKEF2(), MSD_highKEMR(), MSD_highKEV(), MSD_highKEV2(), MSD_highKFMRH(), MSD_highKSFMR(), MSD_highKVSF(), MSD_highListSolid(), MSD_highMassa(), MSD_highMatrizInercia(), MSD_highMEF(), MSD_highMEF2(), MSD_highMEKR(), MSD_highMEKR2(), MSD_highMerge(), MSD_highMEV(), MSD_highMFKRH(), MSD_highMFKRH2(), MSD_highModifyIds(), MSD_highMSFKR(), MSD_highMSFKR2(), MSD_highName(), MSD_highNameCopySolid(), MSD_highNameLoadSolid(), MSD_highNameMakeCirculo(), MSD_highNameMakeCubo(), MSD_highNameMakeEsfera(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeROVCone(), MSD_highNameMakeSWEEP(), MSD_highNameSaveSolid(), MSD_highNameSplit(), MSD_highNewVertexLocation(), MSD_highPropriedadeArea(), MSD_highRevert(), MSD_highRingMove(), MSD_highRotaciona(), MSD_highRotate(), MSD_highRotateSolidAxis(), MSD_highSaveSolid(), MSD_highScale(), MSD_highSEMV(), MSD_highSoftRemove(), MSD_highSplit(), MSD_highSVME(), MSD_highSVME2(), MSD_highSVME3(), MSD_highTransformation(), MSD_highTranslate(), MSD_highUnion(), MSD_highVolume(), MSD_lowApplyEulerOp(), MSD_lowDetach(), MSD_lowImprimeListaEstudo(), MSD_lowMakeArc(), and MSD_lowModifyEulerOp().
Id MSD_getSolidIdFromName (char * name)
Definition at line 64 of file lowfinde.cpp.
References AllSolids, SolName, SolSolidNo, and SPTYPE.
Referenced by MSD_highNameAffine(), MSD_highNameArea(), MSD_highNameAreaProjetada(), MSD_highNameAssociaGroupSolid(), MSD_highNameAssociaSolidAxis(), MSD_highNameCentroCarena(), MSD_highNameCentroDeGravidade(), MSD_highNameCleanSolid(), MSD_highNameCopySolid(), MSD_highNameDensidadeAbsoluta(), MSD_highNameDensidadeRelativa(), MSD_highNameDesassociaGroupSolid(), MSD_highNameDesassociaSolidAxis(), MSD_highNameDesloca(), MSD_highNameDifference(), MSD_highNameDimensaoPrincipal(), MSD_highNameIntersection(), MSD_highNameLoadSolid(), MSD_highNameMakeCirculo(), MSD_highNameMakeCone(), MSD_highNameMakeCube(), MSD_highNameMakeCubo(), MSD_highNameMakeCylinder(), MSD_highNameMakeEsfera(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrism(), MSD_highNameMakePrisma(), MSD_highNameMakePyramid(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeRevolve(), MSD_highNameMakeROVCone(), MSD_highNameMakeSphere(), MSD_highNameMakeSWEEP(), MSD_highNameMakeTorus(), MSD_highNameMakeTriangulo(), MSD_highNameMassa(), MSD_highNameMatrizInercia(), MSD_highNameMerge(), MSD_highNamePropriedadeArea(), MSD_highNameRotaciona(), MSD_highNameRotate(), MSD_highNameRotateSolidAxis(), MSD_highNameSaveSolid(), MSD_highNameScale(), MSD_highNameSplit(), MSD_highNameTransformation(), MSD_highNameTranslate(), MSD_highNameUnion(), MSD_highNameVolume(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
int MSD_highAffine (Id sn, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
Definition at line 172 of file lowtrafn.cpp.
References CommandCount, ERROR, makevec(), matident(), MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowAffine(), NAM_AffineSolid, SNIL, and SPTYPE.
Referenced by MSD_highNameAffine().
int MSD_highListSolid (Id sn, int sw)
Definition at line 67 of file lowlists.cpp.
References ERROR, MSD_getSolid(), MSD_lowListSolid(), SNIL, SPTYPE, and SUCCESS.
int MSD_highNameAffine (char * name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
Definition at line 103 of file lowtrafn.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highAffine(), and NAM_AffineSolid.
Referenced by MSD_execNameAffine().
int MSD_highNameRotate (char * name, real tx, real ty, real tz)
Definition at line 72 of file lowtrrot.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highRotate(), and NAM_RotateSolid.
int MSD_highNameRotateSolidAxis (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 73 of file lowtrrtg.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highRotateSolidAxis(), and NAM_RotateSolidAxis.
Referenced by MSD_highNameRotateElement().
int MSD_highNameScale (char * name, real tx, real ty, real tz)
Definition at line 69 of file lowtrsca.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highScale(), and NAM_ScaleSolid.
Referenced by MSD_execNameScale().
int MSD_highNameTransformation (char * name, matrix)
Definition at line 102 of file lowtrans.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highTransformation(), and NAM_TransformSolid.
int MSD_highNameTranslate (char * name, real tx, real ty, real tz)
Definition at line 71 of file lowtrtra.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highTranslate(), and NAM_TranslateSolid.
Referenced by MSD_highNameTranslateElement().
int MSD_highRotate (Id sn, real tx, real ty, real tz)
Definition at line 103 of file lowtrrot.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowRotate(), NAM_RotateSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructRotate(), and MSD_highNameRotate().
int MSD_highRotateSolidAxis (Id sn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 107 of file lowtrrtg.cpp.
References CommandCount, ERROR, makevec(), MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowRotateSolidAxis(), NAM_RotateSolidAxis, normalize(), SNIL, and SPTYPE.
Referenced by MSD_highNameRotateSolidAxis().
int MSD_highScale (Id sn, real tx, real ty, real tz)
Definition at line 100 of file lowtrsca.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowScale(), NAM_ScaleSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructScale(), and MSD_highNameScale().
int MSD_highTransformation (Id sn, matrix)
Definition at line 161 of file lowtrans.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowTransformation(), NAM_TransformSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructTransformation(), and MSD_highNameTransformation().
int MSD_highTranslate (Id sn, real tx, real ty, real tz)
Definition at line 102 of file lowtrtra.cpp.
References CommandCount, ERROR, MSD_getSolid(), MSD_lowTranslate(), SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructTranslate(), and MSD_highNameTranslate().
HPTYPE MSD_lowAddHE (EPTYPE e, VPTYPE v, HPTYPE where, int orient)
Definition at line 62 of file lowaddhe.cpp.
References EdgHe1, EdgHe2, ENIL, HalEdg, HALFEDGE, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, MSD_lowNewElement(), NNIL, and PLUS.
Referenced by MSD_lowMEF(), MSD_lowMEKR(), and MSD_lowMEV().
void MSD_lowAddList (int what, NPTYPE which, NPTYPE where)
Definition at line 64 of file lowaddel.cpp.
References ANIL, APTYPE, AXIS, axsary, AxsNextA, AxsPrevA, DNIL, DPTYPE, EDGE, EdgNextE, EdgPrevE, ENIL, EPTYPE, FACE, FacFLoops, FacFShell, FacNextF, FacPrevF, FNIL, FPTYPE, GNIL, GPTYPE, GROUP, grpary, GrpNextG, GrpPrevG, LNIL, LooLFace, LooNextL, LOOP, LooPrevL, LPTYPE, objary, SHELL, SheNextD, ShePrevD, SheSEdges, SheSFaces, SheSSolids, SheSVerts, SNIL, SOLID, SolNxt, SolPrevS, SolSShells, SPTYPE, VerNextV, VerPrevV, VERTEX, VNIL, and VPTYPE.
Referenced by MSD_lowAllRingMove(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowNewElement(), MSD_lowRingMove(), MSD_lowShellDetach(), and redo().
int MSD_lowAffine (SPTYPE sptr, vector center, matrix mat)
Definition at line 201 of file lowtrafn.cpp.
References matident(), matmult(), mattrans(), MSD_lowTransformation(), and SUCCESS.
Referenced by MSD_highAffine().
int MSD_lowBoxBoxIntersection (BTYPE * b1, BTYPE * b2)
Definition at line 135 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowDisplayIntersection(), MSD_lowEdgeFaceIntersection(), MSD_lowPositionalVisibility(), MSD_lowSetOpGenerate(), and MSD_lowSetOpProcessEdge().
void MSD_lowCountFaceEdges (SPTYPE optr)
Definition at line 87 of file lowinfos.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, DPTYPE, FacFLOut, FPTYPE, HalNxt, HPTYPE, LooLEdg, LooLength, and LPTYPE.
Referenced by MSD_lowSetInfo().
void MSD_lowDelElement (int what, NPTYPE node, NPTYPE where)
Definition at line 261 of file lownewel.cpp.
References AXIS, EDGE, FACE, GROUP, HALFEDGE, LOOP, MSD_lowDelList(), MSD_putMemVirtual(), SHELL, SOLID, and VERTEX.
Referenced by MSD_lowDelHE(), MSD_lowHardRemove(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEKR(), MSD_lowRemoveAxis(), MSD_lowRemoveOneGroup(), and MSD_lowShellDetach().
HPTYPE MSD_lowDelHE (HPTYPE he)
Definition at line 96 of file lowaddhe.cpp.
References ENIL, HalEdg, HALFEDGE, HalNxt, HalPrv, HNIL, HPTYPE, MSD_lowDelElement(), NNIL, and NPTYPE.
Referenced by MSD_lowKEF(), MSD_lowKEMR(), and MSD_lowKEV().
void MSD_lowDelList (int what, NPTYPE which, NPTYPE where)
Definition at line 225 of file lowaddel.cpp.
References AllSolids, ANIL, APTYPE, AXIS, axsary, AxsNextA, AxsPrevA, DNIL, DPTYPE, EDGE, EdgNextE, EdgPrevE, ENIL, EPTYPE, error, FACE, FacFLoops, FacNextF, FacPrevF, findd(), findes(), findf(), findl(), findv(), FNIL, FPTYPE, GNIL, GPTYPE, GROUP, grpary, GrpNextG, GrpPrevG, LNIL, LooNextL, LOOP, LooPrevL, LPTYPE, objary, SetTrace, SHELL, SheNextD, ShePrevD, SheSEdges, SheSFaces, SheSVerts, SNIL, SOLID, SolNxt, SolPrevS, SolSShells, SPTYPE, TRUE, VerNextV, VerPrevV, VERTEX, VNIL, and VPTYPE.
Referenced by MSD_lowAllRingMove(), MSD_lowDelElement(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowRingMove(), MSD_lowShellDetach(), and redo().
void MSD_lowEdgeBox (BTYPE * b, EPTYPE e)
Definition at line 246 of file lowboxop.cpp.
References CONTBVEPS, EdgHe1, EdgHe2, HalVtx, box::max, box::min, MSD_lowWidenBox(), VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpGenerate(), and MSD_lowSetOpProcessEdge().
int MSD_lowEdgeBoxIntersection (BTYPE * b, EPTYPE e)
Definition at line 88 of file lowboxop.cpp.
References EdgHe1, EdgHe2, HalVtx, box::max, box::min, MSD_lowEdgeBoxIntersectionAux(), VerVCoord, and VPTYPE.
int MSD_lowEdgeBoxIntersectionAux (real x1, real x2, real bx1, real bx2)
Referenced by MSD_lowEdgeBoxIntersection().
void MSD_lowEvaluateSolidBoxes (SPTYPE s)
Definition at line 271 of file lowboxop.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FPTYPE, MSD_lowFaceBox(), and MSD_lowShellBox().
void MSD_lowFaceBox (FPTYPE f)
Definition at line 212 of file lowboxop.cpp.
References AllLoopsFace, CONTBVEPS, FacBox, FacFLOut, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, box::max, box::min, MSD_lowWidenBox(), SetFaceBoxOK, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowEvaluateSolidBoxes(), and MSD_lowSetNormal().
int MSD_lowFaceEq (LPTYPE l, vector eq)
Definition at line 49 of file lowfaceq.cpp.
References comp(), EPS, ERROR, FacFeq, HalNxt, HalVtx, HPTYPE, LooLEdg, LooLFace, SetFaceEqOK, SUCCESS, veczer(), and VerVCoord.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowAllRingMove(), MSD_lowFaceCG(), MSD_lowFacVtxContainment(), MSD_lowListFace(), MSD_lowMakeCube(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSWEEP(), MSD_lowSetNormal(), MSD_lowSetOpConnect(), MSD_lowSetOpFinish(), MSD_lowSetOpInside(), MSD_lowSolVtxContainment(), and MSD_lowSplit().
SPTYPE MSD_lowFindSolidByName (char * name)
Definition at line 50 of file lowfinde.cpp.
References AllSolids, SNIL, SolName, and SPTYPE.
Referenced by MSD_CriaListaDePoligonosCoplanares(), MSD_execRndAllEdges(), MSD_execShow(), MSD_getTypeByName(), MSD_highNameAssociateAxisElement(), MSD_highNameAssociateGroupElement(), MSD_highNameDesassociateGroupElement(), MSD_highNameListFaceAdjacency(), MSD_highNameRenameSolid(), MSD_highNameSetDisplay(), MSD_highNameSoftRemove(), MSD_highNameSolidColor(), MSD_highRound(), MSD_lowAreaProjetadaTotal(), MSD_lowNameNCopySolidSpiral(), MSD_lowNameNCopySolidTranslate(), MSD_resetObject(), and MSD_selectObject().
void MSD_lowListFace (FILE * file, FPTYPE f, int sw)
Definition at line 152 of file lowlists.cpp.
References AllLoopsFace, EdgHe1, EdgHe2, ENIL, EPTYPE, FacFaceNo, FacFLOut, HalEdg, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MSD_lowFaceEq(), VerVertexNo, and VPTYPE.
Referenced by finde(), findf(), findhe(), findl(), MSD_lowListSolid(), and MSD_lowSetOpConnect().
void MSD_lowListSolid (FILE * file, SPTYPE s, int sw)
Definition at line 80 of file lowlists.cpp.
References AllEdgesShell, AllFacesShell, AllShellsSolid, AllVerticesShell, DPTYPE, EdgHe1, EdgHe2, EPTYPE, FacFaceNo, FPTYPE, HalEdg, HalNxt, HalVtx, HalWLoop, HNIL, HPTYPE, LooLFace, mate, MSD_lowListFace(), SheShellNo, SNIL, SolSolidNo, VerVCoord, VerVEdge, VerVertexNo, and VPTYPE.
Referenced by findd(), findes(), findf(), findhes(), findv(), MSD_highListSolid(), MSD_lowMSFKR(), MSD_lowSetOp(), and MSD_lowSplit().
NPTYPE MSD_lowNewElement (int what, NPTYPE where)
Definition at line 89 of file lownewel.cpp.
References ANIL, AXIS, AxsAGroup, AxsType, CNIL, def_grpptr, DNIL, EdgColor, EdgD, EDGE, EdgFgMake, EdgFgRound, EdgT1, EdgT2, EdgT3, EdgT4, ENIL, FacColor, FACE, FacFBits, FacFlag, FacFLoops, FacFLOut, FNIL, GNIL, GROUP, GrpGAxs, GrpGColor, GrpParent, HalCurv, HALFEDGE, HalR, HNIL, LNIL, LOOP, MSD_getMemVirtual(), MSD_lowAddList(), NIL, NNIL, nodesize, NONE, NPTYPE, SheColor, SheDBits, SHELL, SheSEdges, SheSFaces, SheSVerts, SolColor, SolCurv, SolDsp, SolGroup, SOLID, SolName, SolOAxs, SolPerfil, SolSBits, SolSShells, TRUE, VerFgMake, VerFgRound, VERTEX, VerVEdge, and VNIL.
Referenced by MSD_lowAddHE(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCreateGroup(), MSD_lowDetach(), MSD_lowKEMR(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), and MSD_lowMVSF().
void MSD_lowRotate (SPTYPE s, real tx, real ty, real tz)
Definition at line 117 of file lowtrrot.cpp.
References AllShellsSolid, AllVerticesShell, determ(), DPTYPE, Gdodirect, Gdoinversion, matident(), matrotat(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowRevert(), MSD_lowSetNormal(), ROTAT, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highRotaciona(), and MSD_highRotate().
int MSD_lowRotateSolidAxis (SPTYPE sptr, vector center, vector axis, real th)
Definition at line 125 of file lowtrrtg.cpp.
References matident(), MSD_lowTransformation(), MSD_lowTranslate(), rotmat(), and SUCCESS.
Referenced by MSD_highRotateSolidAxis(), MSD_lowNameNCopySolidSpiral(), and MSD_lowRotateGroup().
void MSD_lowScale (SPTYPE s, real tx, real ty, real tz)
Definition at line 114 of file lowtrsca.cpp.
References AllShellsSolid, AllVerticesShell, comp(), determ(), DPTYPE, EPS, Gdodirect, Gdoinversion, matident(), matscale(), MEN_FatorEscalaNulo, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowRevert(), MSD_lowSetNormal(), NAM_ScaleSolid, SCALE, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highScale().
void MSD_lowSetInfo (SPTYPE optr)
Definition at line 48 of file lowinfos.cpp.
References MSD_lowCountFaceEdges(), and MSD_lowSetLoopEdge().
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowSetOp(), and MSD_lowSplit().
void MSD_lowSetLoopEdge (SPTYPE optr)
Definition at line 54 of file lowinfos.cpp.
References AllEdgesShell, AllFacesShell, AllLoopsFace, AllShellsSolid, DPTYPE, EdgEdgeNo, EPTYPE, FacFLOut, FPTYPE, LooLoopNo, and LPTYPE.
Referenced by MSD_lowSetInfo().
void MSD_lowShellBox (DPTYPE d)
Definition at line 183 of file lowboxop.cpp.
References AllVerticesShell, CONTBVEPS, box::max, box::min, MSD_lowWidenBox(), SetShellBoxOK, SheBox, SheSVerts, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowEvaluateSolidBoxes(), and MSD_lowSetNormal().
void MSD_lowSolidBox (SPTYPE s, BTYPE * bx)
Definition at line 154 of file lowboxop.cpp.
References AllShellsSolid, AllVerticesShell, CONTBVEPS, DPTYPE, box::max, box::min, MSD_lowWidenBox(), SheSVerts, SolSShells, veccopy(), VerVCoord, and VPTYPE.
Referenced by MSD_lowSetNormal().
void MSD_lowSolidBoxFromBoxes (SPTYPE s, BTYPE * b)
Definition at line 50 of file lowboxop.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FacBox, FPTYPE, INF, box::max, box::min, and MSD_lowUpdateBox().
void MSD_lowTransformation (SPTYPE s, matrix)
Definition at line 175 of file lowtrans.cpp.
References AllShellsSolid, AllVerticesShell, determ(), DPTYPE, Gdodirect, Gdoinversion, invmat(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddMatrix(), MSD_lowAddMatrixRedo(), MSD_lowRevert(), MSD_lowSetEdgeAngle(), MSD_lowSetNormal(), TRANSFORM, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highTransformation(), MSD_lowAffine(), MSD_lowRotateSolidAxis(), and MSD_lowRotateUsingAxis().
void MSD_lowTranslate (SPTYPE s, real tx, real ty, real tz)
Definition at line 116 of file lowtrtra.cpp.
References AllFacesShell, AllShellsSolid, AllVerticesShell, dot(), DPTYPE, FacFeq, FacFLOut, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, HPTYPE, LooLEdg, matident(), mattrans(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowSetNormal(), TRANS, TRUE, vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_highDesloca(), MSD_highTranslate(), MSD_lowMoveGroup(), MSD_lowNameNCopySolidSpiral(), MSD_lowNameNCopySolidTranslate(), MSD_lowRotateSolidAxis(), MSD_lowRotateUsingAxis(), and MSD_lowTranslateUsingAxis().
void MSD_lowTranslatedBox (BTYPE * b, real dx, real dy, real dz)
void MSD_lowUpdateBox (BTYPE * b1, BTYPE * b)
Definition at line 299 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowSolidBoxFromBoxes().
void MSD_lowUpdateDEBox (void)
Definition at line 327 of file lowboxop.cpp.
References abseps, debox, deevtx, desvtx, box::max, and box::min.
Referenced by MSD_lowDisplayHidden(), and MSD_lowIntersectionFaceFace().
int MSD_lowVertexInBox (BTYPE * b, real x, real y, real z)
Definition at line 70 of file lowboxop.cpp.
References FALSE, box::max, and TRUE.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
void MSD_lowWidenBox (BTYPE * b, real eps)
Definition at line 287 of file lowboxop.cpp.
References box::max, and box::min.
Referenced by MSD_lowEdgeBox(), MSD_lowFaceBox(), MSD_lowShellBox(), and MSD_lowSolidBox().
int MSD_modifyStructRotate (EulerOp * op)
Definition at line 213 of file lowtrrot.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructScale (EulerOp * op)
Definition at line 216 of file lowtrsca.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructTransformation (EulerOp * op)
Definition at line 284 of file lowtrans.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
int MSD_modifyStructTranslate (EulerOp * op)
Definition at line 228 of file lowtrtra.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructRotate (FILE * f, EulerOp * op)
Definition at line 173 of file lowtrrot.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
void MSD_printStructScale (FILE * f, EulerOp * op)
Definition at line 176 of file lowtrsca.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
void MSD_printStructTransformation (FILE * f, EulerOp * op)
Definition at line 233 of file lowtrans.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
void MSD_printStructTranslate (FILE * f, EulerOp * op)
Definition at line 188 of file lowtrtra.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
int MSD_readStructRotate (FILE * f, EulerOp * op)
Definition at line 187 of file lowtrrot.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructScale (FILE * f, EulerOp * op)
Definition at line 190 of file lowtrsca.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructTransformation (FILE * f, EulerOp * op)
Definition at line 257 of file lowtrans.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int MSD_readStructTranslate (FILE * f, EulerOp * op)
Definition at line 202 of file lowtrtra.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.
int TraceBoundaryStructure (void)
Definition at line 58 of file lowcheck.cpp.
References AllSolids, error, FALSE, SPTYPE, TraceSolid(), and TRUE.
Referenced by MSD_execTrace().
int TraceSolid (SPTYPE s)
Definition at line 76 of file lowcheck.cpp.
References checke(), checkf(), checkv(), ERROR, FALSE, and TRUE.
Referenced by MSD_lowAllRingMove(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowRevert(), MSD_lowRingMove(), MSD_lowShellDetach(), and TraceBoundaryStructure().
Variable Documentation
EXTERN long defonum
Definition at line 329 of file lowsolid.h.
Referenced by maninit(), and MSD_lowRequestNewName().
EXTERN int edgused
Definition at line 327 of file lowsolid.h.
Referenced by maninit(), and MSD_lowListNumberOfElements().
EXTERN int error
Definition at line 319 of file lowsolid.h.
Referenced by main(), maninit(), MSD_lowDelList(), and TraceBoundaryStructure().
EXTERN int facused
Definition at line 325 of file lowsolid.h.
Referenced by maninit(), and MSD_lowListNumberOfElements().
EXTERN HPTYPE hithe
Definition at line 321 of file lowsolid.h.
Referenced by MSD_lowLooVtxBoundary(), MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
EXTERN VPTYPE hitvertex
Definition at line 320 of file lowsolid.h.
Referenced by MSD_lowLooVtxBoundary(), MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
EXTERN int looused
Definition at line 326 of file lowsolid.h.
EXTERN Id maxd
Definition at line 318 of file lowsolid.h.
Referenced by maninit(), MSD_getMaxShellId(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakePolygon(), MSD_lowMakeSphere(), MSD_lowMerge(), MSD_lowSetOp(), MSD_lowSetOpFinish(), and MSD_lowSplitFinish().
EXTERN Id maxf
Definition at line 316 of file lowsolid.h.
Referenced by edv3(), edv4(), GenerationEdges_nvertices(), MakeEdgeConvexCorner(), maninit(), MSD_getMaxFaceId(), MSD_lowEdgeRemove(), MSD_lowJoin(), MSD_lowLoopGlue(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakePolygon(), MSD_lowMakePrism(), MSD_lowMakePyramid(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSphere(), MSD_lowMakeSweep(), MSD_lowMerge(), MSD_lowSetOp(), MSD_lowSetOpFinish(), MSD_lowSetOpJoin(), MSD_lowSplit(), and MSD_lowSplitFinish().
EXTERN int maxs
Definition at line 315 of file lowsolid.h.
Referenced by maninit(), and MSD_getMaxSolidId().
EXTERN Id maxv
Definition at line 317 of file lowsolid.h.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), maninit(), MSD_getMaxVertexId(), MSD_lowInsertNullEdges(), MSD_lowMakeArc(), MSD_lowMakeCircle(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeOpenRSweep(), MSD_lowMakePolygon(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSphere(), MSD_lowMakeSweep(), MSD_lowMerge(), MSD_lowSetOp(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSplit(), and MSD_lowSplitGenerate().
EXTERN SPTYPE objary
Definition at line 322 of file lowsolid.h.
Referenced by main(), maninit(), MSD_getSolid(), MSD_lowAddList(), MSD_lowDelList(), and MSD_lowRemoveGroup().
EXTERN int objused
Definition at line 324 of file lowsolid.h.
Referenced by maninit(), and MSD_lowListNumberOfElements().
EXTERN int SetTrace
Definition at line 323 of file lowsolid.h.
Referenced by main(), maninit(), MSD_execResetTrace(), MSD_execSetTrace(), MSD_lowAllRingMove(), MSD_lowDelList(), MSD_lowHardRemove(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowKVSF(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowMEV(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowMVSF(), MSD_lowRevert(), MSD_lowRingMove(), and MSD_lowShellDetach().
EXTERN int vtxused
Definition at line 328 of file lowsolid.h.
Referenced by maninit(), and MSD_lowListNumberOfElements().