USPDesigner: C:/USPDesig/LOW/lowtrsca.cpp File Reference
C:/USPDesig/LOW/lowtrsca.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
void MSD_execNameScale (void)
int MSD_highNameScale (char *name, real tx, real ty, real tz)
int MSD_highScale (Id sn, real sx, real sy, real sz)
void MSD_lowScale (SPTYPE s, real sx, real sy, real sz)
int MSD_execStructScale (EulerOp *op)
void MSD_printStructScale (FILE *f, EulerOp *op)
int MSD_readStructScale (FILE *f, EulerOp *op)
int MSD_modifyStructScale (EulerOp *op)
Function Documentation
void MSD_execNameScale (void)
Definition at line 53 of file lowtrsca.cpp.
References lineins(), MSD_highNameScale(), and restbuf.
int MSD_execStructScale (EulerOp * op)
Definition at line 163 of file lowtrsca.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highScale(), eulerop::solidno, and SUCCESS.
int MSD_highNameScale (char * name, real tx, real ty, real tz)
Definition at line 69 of file lowtrsca.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highScale(), and NAM_ScaleSolid.
Referenced by MSD_execNameScale().
int MSD_highScale (Id sn, real sx, real sy, real sz)
Definition at line 100 of file lowtrsca.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowScale(), NAM_ScaleSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructScale(), and MSD_highNameScale().
void MSD_lowScale (SPTYPE s, real sx, real sy, real sz)
Definition at line 114 of file lowtrsca.cpp.
References AllShellsSolid, AllVerticesShell, comp(), determ(), DPTYPE, EPS, Gdodirect, Gdoinversion, matident(), matscale(), MEN_FatorEscalaNulo, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowRevert(), MSD_lowSetNormal(), NAM_ScaleSolid, SCALE, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highScale().
int MSD_modifyStructScale (EulerOp * op)
Definition at line 216 of file lowtrsca.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructScale (FILE * f, EulerOp * op)
Definition at line 176 of file lowtrsca.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
int MSD_readStructScale (FILE * f, EulerOp * op)
Definition at line 190 of file lowtrsca.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.