USPDesigner: C:/USPDesig/LOW/lowtrafn.cpp File Reference
C:/USPDesig/LOW/lowtrafn.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
void MSD_execNameAffine (void)
int MSD_highNameAffine (char *name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
int MSD_highAffine (Id sn, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
int MSD_lowAffine (SPTYPE sptr, vector center, matrix mat)
Function Documentation
void MSD_execNameAffine (void)
Definition at line 52 of file lowtrafn.cpp.
References lineins(), MSD_highNameAffine(), and restbuf.
int MSD_highAffine (Id sn, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
Definition at line 172 of file lowtrafn.cpp.
References CommandCount, ERROR, makevec(), matident(), MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowAffine(), NAM_AffineSolid, SNIL, and SPTYPE.
Referenced by MSD_highNameAffine().
int MSD_highNameAffine (char * name, real a11, real a12, real a13, real a21, real a22, real a23, real a31, real a32, real a33, real xc, real yc, real zc)
Definition at line 103 of file lowtrafn.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highAffine(), and NAM_AffineSolid.
Referenced by MSD_execNameAffine().
int MSD_lowAffine (SPTYPE sptr, vector center, matrix mat)
Definition at line 201 of file lowtrafn.cpp.
References matident(), matmult(), mattrans(), MSD_lowTransformation(), and SUCCESS.
Referenced by MSD_highAffine().