USPDesigner: C:/USPDesig/LOW/lowtrans.cpp File Reference
C:/USPDesig/LOW/lowtrans.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
int MSD_highNameTransformation (char *name, matrix m)
int MSD_highTransformation (int sn, matrix m)
void MSD_lowTransformation (SPTYPE s, matrix m)
int MSD_execStructTransformation (EulerOp *op)
void MSD_printStructTransformation (FILE *f, EulerOp *op)
int MSD_readStructTransformation (FILE *f, EulerOp *op)
int MSD_modifyStructTransformation (EulerOp *op)
Function Documentation
int MSD_execStructTransformation (EulerOp * op)
Definition at line 221 of file lowtrans.cpp.
References matident(), MSD_highTransformation(), MSD_lowGetMatrix(), eulerop::solidno, and SUCCESS.
int MSD_highNameTransformation (char * name, matrix m)
Definition at line 102 of file lowtrans.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highTransformation(), and NAM_TransformSolid.
int MSD_highTransformation (int sn, matrix m)
Definition at line 161 of file lowtrans.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowTransformation(), NAM_TransformSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructTransformation(), and MSD_highNameTransformation().
void MSD_lowTransformation (SPTYPE s, matrix m)
Definition at line 175 of file lowtrans.cpp.
References AllShellsSolid, AllVerticesShell, determ(), DPTYPE, Gdodirect, Gdoinversion, invmat(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddMatrix(), MSD_lowAddMatrixRedo(), MSD_lowRevert(), MSD_lowSetEdgeAngle(), MSD_lowSetNormal(), TRANSFORM, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highTransformation(), MSD_lowAffine(), MSD_lowRotateSolidAxis(), and MSD_lowRotateUsingAxis().
int MSD_modifyStructTransformation (EulerOp * op)
Definition at line 284 of file lowtrans.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructTransformation (FILE * f, EulerOp * op)
Definition at line 233 of file lowtrans.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, and eulerop::solidno.
int MSD_readStructTransformation (FILE * f, EulerOp * op)
Definition at line 257 of file lowtrans.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.