USPDesigner: C:/USPDesig/LOW/lowtrtra.cpp File Reference
C:/USPDesig/LOW/lowtrtra.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
int MSD_highNameTranslate (char *name, real tx, real ty, real tz)
int MSD_highTranslate (Id sn, real tx, real ty, real tz)
void MSD_lowTranslate (SPTYPE s, real tx, real ty, real tz)
int MSD_execStructTranslate (EulerOp *op)
void MSD_printStructTranslate (FILE *f, EulerOp *op)
int MSD_readStructTranslate (FILE *f, EulerOp *op)
int MSD_modifyStructTranslate (EulerOp *op)
Function Documentation
int MSD_execStructTranslate (EulerOp * op)
Definition at line 175 of file lowtrtra.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highTranslate(), eulerop::solidno, and SUCCESS.
int MSD_highNameTranslate (char * name, real tx, real ty, real tz)
Definition at line 71 of file lowtrtra.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highTranslate(), and NAM_TranslateSolid.
Referenced by MSD_highNameTranslateElement().
int MSD_highTranslate (Id sn, real tx, real ty, real tz)
Definition at line 102 of file lowtrtra.cpp.
References CommandCount, ERROR, MSD_getSolid(), MSD_lowTranslate(), SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructTranslate(), and MSD_highNameTranslate().
void MSD_lowTranslate (SPTYPE s, real tx, real ty, real tz)
Definition at line 116 of file lowtrtra.cpp.
References AllFacesShell, AllShellsSolid, AllVerticesShell, dot(), DPTYPE, FacFeq, FacFLOut, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalVtx, HPTYPE, LooLEdg, matident(), mattrans(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowSetNormal(), TRANS, TRUE, vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_highDesloca(), MSD_highTranslate(), MSD_lowMoveGroup(), MSD_lowNameNCopySolidSpiral(), MSD_lowNameNCopySolidTranslate(), MSD_lowRotateSolidAxis(), MSD_lowRotateUsingAxis(), and MSD_lowTranslateUsingAxis().
int MSD_modifyStructTranslate (EulerOp * op)
Definition at line 228 of file lowtrtra.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructTranslate (FILE * f, EulerOp * op)
Definition at line 188 of file lowtrtra.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
int MSD_readStructTranslate (FILE * f, EulerOp * op)
Definition at line 202 of file lowtrtra.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.