USPDesigner: C:/USPDesig/LOW/lowtrrot.cpp File Reference
C:/USPDesig/LOW/lowtrrot.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
int MSD_highNameRotate (char *name, real tx, real ty, real tz)
int MSD_highRotate (Id sn, real rx, real ry, real rz)
void MSD_lowRotate (SPTYPE s, real rx, real ry, real rz)
int MSD_execStructRotate (EulerOp *op)
void MSD_printStructRotate (FILE *f, EulerOp *op)
int MSD_readStructRotate (FILE *f, EulerOp *op)
int MSD_modifyStructRotate (EulerOp *op)
Function Documentation
int MSD_execStructRotate (EulerOp * op)
Definition at line 160 of file lowtrrot.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, MSD_highRotate(), eulerop::solidno, and SUCCESS.
int MSD_highNameRotate (char * name, real tx, real ty, real tz)
Definition at line 72 of file lowtrrot.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highRotate(), and NAM_RotateSolid.
int MSD_highRotate (Id sn, real rx, real ry, real rz)
Definition at line 103 of file lowtrrot.cpp.
References CommandCount, ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowRotate(), NAM_RotateSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructRotate(), and MSD_highNameRotate().
void MSD_lowRotate (SPTYPE s, real rx, real ry, real rz)
Definition at line 117 of file lowtrrot.cpp.
References AllShellsSolid, AllVerticesShell, determ(), DPTYPE, Gdodirect, Gdoinversion, matident(), matrotat(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowRevert(), MSD_lowSetNormal(), ROTAT, TRUE, vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_highRotaciona(), and MSD_highRotate().
int MSD_modifyStructRotate (EulerOp * op)
Definition at line 213 of file lowtrrot.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructRotate (FILE * f, EulerOp * op)
Definition at line 173 of file lowtrrot.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, and eulerop::solidno.
int MSD_readStructRotate (FILE * f, EulerOp * op)
Definition at line 187 of file lowtrrot.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.