USPDesigner: C:/USPDesig/LOW/lowtrrtg.cpp File Reference
C:/USPDesig/LOW/lowtrrtg.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "genfunc_.h"
#include "eulerops.h"
#include "shpshape.h"
#include "vectorop.h"
#include "mancommd.h"
Functions
int MSD_highNameRotateSolidAxis (char *name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_highRotateSolidAxis (Id sn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
int MSD_lowRotateSolidAxis (SPTYPE sptr, vector center, vector axis, real th)
Function Documentation
int MSD_highNameRotateSolidAxis (char * name, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 73 of file lowtrrtg.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highRotateSolidAxis(), and NAM_RotateSolidAxis.
Referenced by MSD_highNameRotateElement().
int MSD_highRotateSolidAxis (Id sn, real x1, real y1, real z1, real x2, real y2, real z2, real th)
Definition at line 107 of file lowtrrtg.cpp.
References CommandCount, ERROR, makevec(), MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowRotateSolidAxis(), NAM_RotateSolidAxis, normalize(), SNIL, and SPTYPE.
Referenced by MSD_highNameRotateSolidAxis().
int MSD_lowRotateSolidAxis (SPTYPE sptr, vector center, vector axis, real th)
Definition at line 125 of file lowtrrtg.cpp.
References matident(), MSD_lowTransformation(), MSD_lowTranslate(), rotmat(), and SUCCESS.
Referenced by MSD_highRotateSolidAxis(), MSD_lowNameNCopySolidSpiral(), and MSD_lowRotateGroup().