USPDesigner: C:/USPDesig/INC/mancommd.h File Reference
C:/USPDesig/INC/mancommd.h File Reference
#include <stdio.h>
Classes
struct command
Defines
#define BUFLENG 256
Typedefs
typedef struct command COMTYPE
Functions
void help (void)
void helpman (COMTYPE *p)
char optin (void)
char lineins (char *s)
void control (void)
int main (int argc, char **argv)
void maninit (void)
void MSD_readFileExecute (void)
void MSD_executeFileCommand (char *name)
void endfunc (void)
void comerror (void)
void strupper (unsigned char *s)
void strlower (unsigned char *s)
void skipsp (char **p)
void skipnext (char **p)
void MSD_execSetTrace (void)
void MSD_execResetTrace (void)
Variables
COMTYPE comtable []
FILE * instream
char linebuf [BUFLENG]
char * restbuf
Define Documentation
#define BUFLENG 256
Definition at line 47 of file mancommd.h.
Referenced by lineins().
Typedef Documentation
typedef struct command COMTYPE
Definition at line 48 of file mancommd.h.
Function Documentation
void comerror (void)
Definition at line 239 of file manmainp.cpp.
void control (void)
Definition at line 95 of file manlinin.cpp.
References linebuf.
Referenced by lineins().
void endfunc (void)
Definition at line 221 of file manmainp.cpp.
References g_close(), instream, and MSD_highTerminateMemVirtual().
void help (void)
Definition at line 48 of file manhelp_.cpp.
References command::comname, comtable, helpman(), NIL, restbuf, and strupper().
void helpman (COMTYPE * p)
Definition at line 102 of file manhelp_.cpp.
References command::comname, and NIL.
Referenced by help().
char lineins (char * s)
Definition at line 68 of file manlinin.cpp.
References BUFLENG, control(), FALSE, instream, linebuf, restbuf, and skipsp().
Referenced by animatio(), cinema(), main(), MSD_execAnaliseShow(), MSD_execCamera(), MSD_execClear(), MSD_execColor(), MSD_execDensidadeFluido(), MSD_execDir(), MSD_execDisplay(), MSD_execDisplayCoordinates(), MSD_execDisplayFile(), MSD_execListElement(), MSD_execManipulateAxis(), MSD_execManipulateGroup(), MSD_execManipulatePropriedade(), MSD_execMonitor(), MSD_execNameAffine(), MSD_execNameArea(), MSD_execNameAreaProjetada(), MSD_execNameCentroCarena(), MSD_execNameCentroDeGravidade(), MSD_execNameCopyElement(), MSD_execNameDeleteElement(), MSD_execNameDensidadeAbsoluta(), MSD_execNameDensidadeRelativa(), MSD_execNameDesloca(), MSD_execNameDifference(), MSD_execNameDimensaoPrincipal(), MSD_execNameIntersection(), MSD_execNameLoadSolid(), MSD_execNameMakeCirculo(), MSD_execNameMakeCone(), MSD_execNameMakeCube(), MSD_execNameMakeCubo(), MSD_execNameMakeCylinder(), MSD_execNameMakeEsfera(), MSD_execNameMakePerfilI(), MSD_execNameMakePerfilL(), MSD_execNameMakePerfilT(), MSD_execNameMakePiramide(), MSD_execNameMakePlaca(), MSD_execNameMakePrism(), MSD_execNameMakePrisma(), MSD_execNameMakePyramid(), MSD_execNameMakeQuadrado(), MSD_execNameMakeRetangulo(), MSD_execNameMakeRevolve(), MSD_execNameMakeROVCone(), MSD_execNameMakeSphere(), MSD_execNameMakeSweep(), MSD_execNameMakeTorus(), MSD_execNameMakeTriangulo(), MSD_execNameMassa(), MSD_execNameMatrizInercia(), MSD_execNameNCopySolid(), MSD_execNameRenameElement(), MSD_execNameRotaciona(), MSD_execNameRotateElement(), MSD_execNameSaveSolid(), MSD_execNameScale(), MSD_execNameSplit(), MSD_execNameTranslateElement(), MSD_execNameUnion(), MSD_execNameVolume(), MSD_execOrdena(), MSD_execProjetadaTotal(), MSD_execRndAllEdges(), MSD_execRound(), MSD_execShow(), MSD_execVoronoi(), MSD_execWait(), MSD_execWindow(), MSD_highRound(), MSD_highSetLine(), MSD_readFileExecute(), and setvtpi().
int main (int argc, char ** argv)
Definition at line 74 of file manmainp.cpp.
References command::comfunc, command::comname, comtable, error, EuNIL, FALSE, g_open(), Gdoinversion, instream, lineins(), maninit(), MSD_lowSetBreakInterruption(), NIL, objary, OpHead, restbuf, SetTrace, skipnext(), SNIL, strupper(), and TRUE.
void maninit (void)
Definition at line 125 of file manmainp.cpp.
References abseps, angsmooth, ANIL, axsary, axsused, breakflg, camary, camptr, camused, def_grpptr, defltcol, defonum, Draw, dspfrptr, dspfwptr, dwindbox, edgused, error, EuNIL, facused, FALSE, framecol, g_clear(), Gdodirect, Gdoinversion, GNIL, grpary, grpused, instream, ListaEscoamento, lncolor, lntype, maxd, maxf, maxs, maxv, monicptr, monisw, MSD_highIniciateMemVirtual(), MSD_highTerminateMemVirtual(), NIL, NumListaEscoamento, objary, objused, OpHead, OpHeadRedo, OutputPlanoCorte, releps, SetTrace, SNIL, TRUE, vtxused, windbox, and xyratio.
Referenced by main().
void MSD_execResetTrace (void)
Definition at line 67 of file mantrace.cpp.
References FALSE, and SetTrace.
void MSD_execSetTrace (void)
Definition at line 52 of file mantrace.cpp.
References AllSolids, MSD_lowSetEdgeAngle(), MSD_lowSetNormal(), SetTrace, SPTYPE, and TRUE.
void MSD_executeFileCommand (char * name)
Definition at line 197 of file manmainp.cpp.
References instream, and NIL.
Referenced by MSD_readFileExecute().
void MSD_readFileExecute (void)
Definition at line 181 of file manmainp.cpp.
References instream, lineins(), MSD_executeFileCommand(), and restbuf.
char optin (void)
Definition at line 47 of file manlinin.cpp.
References restbuf, and skipsp().
Referenced by animatio(), cinema(), MSD_execCamera(), MSD_execClear(), MSD_execColor(), MSD_execDisplayCoordinates(), MSD_execDisplayFile(), MSD_execListElement(), MSD_execManipulateAxis(), MSD_execManipulateGroup(), MSD_execManipulatePropriedade(), MSD_execNameNCopySolid(), and MSD_execShow().
void skipnext (char ** p)
Definition at line 69 of file manstrmp.cpp.
References skipsp().
Referenced by main(), MSD_execDisplay(), and MSD_highRound().
void skipsp (char ** p)
Definition at line 61 of file manstrmp.cpp.
Referenced by lineins(), MSD_execDisplayCoordinates(), optin(), and skipnext().
void strlower (unsigned char * s)
Definition at line 53 of file manstrmp.cpp.
Referenced by MSD_highMonitor().
void strupper (unsigned char * s)
Definition at line 45 of file manstrmp.cpp.
Referenced by help(), main(), and MSD_lowScanEulerOperator().
Variable Documentation
COMTYPE comtable[]
Referenced by help(), and main().
FILE* instream
Referenced by endfunc(), lineins(), main(), maninit(), MSD_executeFileCommand(), MSD_lowSetBreakResident(), and MSD_readFileExecute().
char linebuf[BUFLENG]
Referenced by control(), and lineins().
char* restbuf
Referenced by animatio(), cinema(), help(), lineins(), main(), MSD_execAnaliseShow(), MSD_execCamera(), MSD_execColor(), MSD_execDensidadeFluido(), MSD_execDir(), MSD_execDisplay(), MSD_execDisplayCoordinates(), MSD_execDisplayFile(), MSD_execManipulateAxis(), MSD_execManipulateGroup(), MSD_execManipulatePropriedade(), MSD_execMonitor(), MSD_execNameAffine(), MSD_execNameArea(), MSD_execNameAreaProjetada(), MSD_execNameCentroCarena(), MSD_execNameCentroDeGravidade(), MSD_execNameCopyElement(), MSD_execNameDeleteElement(), MSD_execNameDensidadeAbsoluta(), MSD_execNameDensidadeRelativa(), MSD_execNameDesloca(), MSD_execNameDifference(), MSD_execNameDimensaoPrincipal(), MSD_execNameIntersection(), MSD_execNameLoadSolid(), MSD_execNameMakeCirculo(), MSD_execNameMakeCone(), MSD_execNameMakeCube(), MSD_execNameMakeCubo(), MSD_execNameMakeCylinder(), MSD_execNameMakeEsfera(), MSD_execNameMakePerfilI(), MSD_execNameMakePerfilL(), MSD_execNameMakePerfilT(), MSD_execNameMakePiramide(), MSD_execNameMakePlaca(), MSD_execNameMakePrism(), MSD_execNameMakePrisma(), MSD_execNameMakePyramid(), MSD_execNameMakeQuadrado(), MSD_execNameMakeRetangulo(), MSD_execNameMakeRevolve(), MSD_execNameMakeROVCone(), MSD_execNameMakeSphere(), MSD_execNameMakeSweep(), MSD_execNameMakeTorus(), MSD_execNameMakeTriangulo(), MSD_execNameMassa(), MSD_execNameMatrizInercia(), MSD_execNameNCopySolid(), MSD_execNameRenameElement(), MSD_execNameRotaciona(), MSD_execNameRotateElement(), MSD_execNameSaveSolid(), MSD_execNameScale(), MSD_execNameSplit(), MSD_execNameTranslateElement(), MSD_execNameUnion(), MSD_execNameVolume(), MSD_execOrdena(), MSD_execPrint(), MSD_execProjetadaTotal(), MSD_execRndAllEdges(), MSD_execRound(), MSD_execShow(), MSD_execVoronoi(), MSD_execWait(), MSD_execWindow(), MSD_highRound(), MSD_highSetLine(), MSD_readFileExecute(), optin(), and setvtpi().