USPDesigner: C:/USPDesig/MAN/manhelp_.cpp File Reference
C:/USPDesig/MAN/manhelp_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "mancommd.h"
Functions
void help (void)
void helpman (COMTYPE *p)
Function Documentation
void help (void)
Definition at line 48 of file manhelp_.cpp.
References command::comname, comtable, helpman(), NIL, restbuf, and strupper().
void helpman (COMTYPE * p)
Definition at line 102 of file manhelp_.cpp.
References command::comname, and NIL.
Referenced by help().