USPDesigner: C:/USPDesig/MAN/manlinin.cpp File Reference
C:/USPDesig/MAN/manlinin.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "lowparam.h"
#include "mancommd.h"
Functions
char optin (void)
char lineins (char *s)
void control (void)
Function Documentation
void control (void)
Definition at line 95 of file manlinin.cpp.
References linebuf.
Referenced by lineins().
char lineins (char * s)
Definition at line 68 of file manlinin.cpp.
References BUFLENG, control(), FALSE, instream, linebuf, restbuf, and skipsp().
Referenced by animatio(), cinema(), main(), MSD_execAnaliseShow(), MSD_execCamera(), MSD_execClear(), MSD_execColor(), MSD_execDensidadeFluido(), MSD_execDir(), MSD_execDisplay(), MSD_execDisplayCoordinates(), MSD_execDisplayFile(), MSD_execListElement(), MSD_execManipulateAxis(), MSD_execManipulateGroup(), MSD_execManipulatePropriedade(), MSD_execMonitor(), MSD_execNameAffine(), MSD_execNameArea(), MSD_execNameAreaProjetada(), MSD_execNameCentroCarena(), MSD_execNameCentroDeGravidade(), MSD_execNameCopyElement(), MSD_execNameDeleteElement(), MSD_execNameDensidadeAbsoluta(), MSD_execNameDensidadeRelativa(), MSD_execNameDesloca(), MSD_execNameDifference(), MSD_execNameDimensaoPrincipal(), MSD_execNameIntersection(), MSD_execNameLoadSolid(), MSD_execNameMakeCirculo(), MSD_execNameMakeCone(), MSD_execNameMakeCube(), MSD_execNameMakeCubo(), MSD_execNameMakeCylinder(), MSD_execNameMakeEsfera(), MSD_execNameMakePerfilI(), MSD_execNameMakePerfilL(), MSD_execNameMakePerfilT(), MSD_execNameMakePiramide(), MSD_execNameMakePlaca(), MSD_execNameMakePrism(), MSD_execNameMakePrisma(), MSD_execNameMakePyramid(), MSD_execNameMakeQuadrado(), MSD_execNameMakeRetangulo(), MSD_execNameMakeRevolve(), MSD_execNameMakeROVCone(), MSD_execNameMakeSphere(), MSD_execNameMakeSweep(), MSD_execNameMakeTorus(), MSD_execNameMakeTriangulo(), MSD_execNameMassa(), MSD_execNameMatrizInercia(), MSD_execNameNCopySolid(), MSD_execNameRenameElement(), MSD_execNameRotaciona(), MSD_execNameRotateElement(), MSD_execNameSaveSolid(), MSD_execNameScale(), MSD_execNameSplit(), MSD_execNameTranslateElement(), MSD_execNameUnion(), MSD_execNameVolume(), MSD_execOrdena(), MSD_execProjetadaTotal(), MSD_execRndAllEdges(), MSD_execRound(), MSD_execShow(), MSD_execVoronoi(), MSD_execWait(), MSD_execWindow(), MSD_highRound(), MSD_highSetLine(), MSD_readFileExecute(), and setvtpi().
char optin (void)
Definition at line 47 of file manlinin.cpp.
References restbuf, and skipsp().
Referenced by animatio(), cinema(), MSD_execCamera(), MSD_execClear(), MSD_execColor(), MSD_execDisplayCoordinates(), MSD_execDisplayFile(), MSD_execListElement(), MSD_execManipulateAxis(), MSD_execManipulateGroup(), MSD_execManipulatePropriedade(), MSD_execNameNCopySolid(), and MSD_execShow().