USPDesigner: C:/USPDesig/MAN/manmainp.cpp File Reference
C:/USPDesig/MAN/manmainp.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <malloc.h>
#include <stdlib.h>
#include <graphics.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "curvgeom.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "shpshape.h"
#include "sethmain.h"
#include "splsplit.h"
#include "hiegroup.h"
#include "animatio.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "gphgraph.h"
#include "analise_.h"
#include "basrov__.h"
#include "rndround.h"
#include "prop.h"
#include "mancommd.h"
Defines
#define _DVS_
Functions
int main (int argc, char **argv)
void maninit (void)
void MSD_readFileExecute (void)
void MSD_executeFileCommand (char *name)
void endfunc (void)
void comerror (void)
Define Documentation
#define _DVS_
Definition at line 41 of file manmainp.cpp.
Function Documentation
void comerror (void)
Definition at line 239 of file manmainp.cpp.
void endfunc (void)
Definition at line 221 of file manmainp.cpp.
References g_close(), instream, and MSD_highTerminateMemVirtual().
int main (int argc, char ** argv)
Definition at line 74 of file manmainp.cpp.
References command::comfunc, command::comname, comtable, error, EuNIL, FALSE, g_open(), Gdoinversion, instream, lineins(), maninit(), MSD_lowSetBreakInterruption(), NIL, objary, OpHead, restbuf, SetTrace, skipnext(), SNIL, strupper(), and TRUE.
void maninit (void)
Definition at line 125 of file manmainp.cpp.
References abseps, angsmooth, ANIL, axsary, axsused, breakflg, camary, camptr, camused, def_grpptr, defltcol, defonum, Draw, dspfrptr, dspfwptr, dwindbox, edgused, error, EuNIL, facused, FALSE, framecol, g_clear(), Gdodirect, Gdoinversion, GNIL, grpary, grpused, instream, ListaEscoamento, lncolor, lntype, maxd, maxf, maxs, maxv, monicptr, monisw, MSD_highIniciateMemVirtual(), MSD_highTerminateMemVirtual(), NIL, NumListaEscoamento, objary, objused, OpHead, OpHeadRedo, OutputPlanoCorte, releps, SetTrace, SNIL, TRUE, vtxused, windbox, and xyratio.
Referenced by main().
void MSD_executeFileCommand (char * name)
Definition at line 197 of file manmainp.cpp.
References instream, and NIL.
Referenced by MSD_readFileExecute().
void MSD_readFileExecute (void)
Definition at line 181 of file manmainp.cpp.
References instream, lineins(), MSD_executeFileCommand(), and restbuf.