USPDesigner: C:/USPDesig/MAN/manstrmp.cpp File Reference
C:/USPDesig/MAN/manstrmp.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
Functions
void strupper (unsigned char *s)
void strlower (unsigned char *s)
void skipsp (char **p)
void skipnext (char **p)
Function Documentation
void skipnext (char ** p)
Definition at line 69 of file manstrmp.cpp.
References skipsp().
Referenced by main(), MSD_execDisplay(), and MSD_highRound().
void skipsp (char ** p)
Definition at line 61 of file manstrmp.cpp.
Referenced by lineins(), MSD_execDisplayCoordinates(), optin(), and skipnext().
void strlower (unsigned char * s)
Definition at line 53 of file manstrmp.cpp.
Referenced by MSD_highMonitor().
void strupper (unsigned char * s)
Definition at line 45 of file manstrmp.cpp.
Referenced by help(), main(), and MSD_lowScanEulerOperator().