USPDesigner: C:/USPDesig/INC/prop.h File Reference
C:/USPDesig/INC/prop.h File Reference
Functions
void MSD_execManipulatePropriedade (void)
Function Documentation
void MSD_execManipulatePropriedade (void)
Definition at line 20 of file PROP.CPP.
References lineins(), MSD_highNamePropriedadeArea(), optin(), and restbuf.