USPDesigner: C:/USPDesig/RN1/rndaux__.cpp File Reference
C:/USPDesig/RN1/rndaux__.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "rndround.h"
#include "curvgeom.h"
Functions
void calc_point (vector v1, vector v2, real t, vector p)
real angle_edge (HPTYPE he)
int GetEdges (VPTYPE v, int flag)
void CLC (SPTYPE s, HPTYPE he, vector p1, vector p2, vector c)
void lgeo_arc (vector c, vector p1, vector p2, vector t1, vector t2, real d1, real d2)
void _line (vector r1, real d1, vector r2, real d2, vector p1, vector p2, vector n)
void line_parallel (vector r1, vector r2, vector p1, vector p2, vector n, real d)
real calc_t (vector v1, vector v2, vector p)
void line_inter (vector v1, vector v2, vector v3, vector v4, vector p)
void point_perp (vector v1, vector v2, vector p, vector n, real d)
Function Documentation
void _line (vector r1, real d1, vector r2, real d2, vector p1, vector p2, vector n)
Definition at line 139 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by MakingEdges_tables().
real angle_edge (HPTYPE he)
Definition at line 61 of file rndaux__.cpp.
References comp(), cross(), dot(), EPS, FacFeq, HalPrv, HalVtx, HalWLoop, LooLFace, mate, normalize(), PI, veccopy(), vecminus(), and VerVCoord.
Referenced by GenerationEdges_corners(), GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakingEdges_tables(), and MakingVertices_edges().
void calc_point (vector v1, vector v2, real t, vector p)
Definition at line 54 of file rndaux__.cpp.
References vecesc(), vecminus(), and vecplus().
real calc_t (vector v1, vector v2, vector p)
Definition at line 171 of file rndaux__.cpp.
References vecminus(), and veczer().
Referenced by MakingEdges_tables().
void CLC (SPTYPE s, HPTYPE he, vector p1, vector p2, vector c)
Definition at line 109 of file rndaux__.cpp.
References getmaxct(), lgeo_arc(), SolSolidNo, and vecd().
Referenced by EdgeAttached_vertexfase1(), edv2(), edv3(), and edv4().
int GetEdges (VPTYPE v, int flag)
Definition at line 88 of file rndaux__.cpp.
References EdgFgRound, HalEdg, HalNxt, HPTYPE, mate, and VerVEdge.
Referenced by EdgeAttached_vertexfase1(), and EdgesAttachedOriginal_vertex().
void lgeo_arc (vector c, vector p1, vector p2, vector t1, vector t2, real d1, real d2)
Definition at line 123 of file rndaux__.cpp.
References normalize(), and vecminus().
Referenced by CLC().
void line_inter (vector v1, vector v2, vector v3, vector v4, vector p)
Definition at line 186 of file rndaux__.cpp.
References comp(), cross(), EPS, getdrop(), normalize(), vecminus(), X, Y, and Z.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), and MakingEdges_tables().
void line_parallel (vector r1, vector r2, vector p1, vector p2, vector n, real d)
Definition at line 156 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
void point_perp (vector v1, vector v2, vector p, vector n, real d)
Definition at line 244 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), and MakeEdgeFlatCorner().