USPDesigner: C:/USPDesig/RN1/rndfase2.cpp File Reference
C:/USPDesig/RN1/rndfase2.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "rndround.h"
Functions
int EdgeGeneration_faces (SPTYPE s)
int GenerationEdges_corners (SPTYPE s)
int GenerationEdges_nvertices (SPTYPE s)
void MakeEdgeFlatCorner (SPTYPE s, HPTYPE he)
void MakeEdgeConcaveCorner (SPTYPE s, HPTYPE he)
HPTYPE MakeEdgeConvexCorner (SPTYPE s, HPTYPE he)
void GetNxtVertex (HPTYPE he, vector p)
void GetPrvVertex (HPTYPE he, vector p)
int cont_point (VPTYPE v1, VPTYPE v2, vector p)
Function Documentation
int cont_point (VPTYPE v1, VPTYPE v2, vector p)
Definition at line 748 of file rndfase2.cpp.
References veccopy(), vecd(), and VerVCoord.
Referenced by GenerationEdges_nvertices().
int EdgeGeneration_faces (SPTYPE s)
Definition at line 53 of file rndfase2.cpp.
References GenerationEdges_corners(), GenerationEdges_nvertices(), and SUCCESS.
Referenced by MSD_lowRound().
int GenerationEdges_corners (SPTYPE s)
Definition at line 62 of file rndfase2.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, angle_edge(), comp(), DPTYPE, EPS, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MSD_ROUND_V_ORIGINAL, PI, TRUE, and VerFgMake.
Referenced by EdgeGeneration_faces().
int GenerationEdges_nvertices (SPTYPE s)
Definition at line 138 of file rndfase2.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, angle_edge(), comp(), cont_point(), cross(), DPTYPE, EdgFgMake, EdgFgRound, EPS, EPTYPE, FacFaceNo, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, line_inter(), LooLEdg, LPTYPE, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_E_ORIGINAL, MSD_ROUND_FLAG_E1, MSD_ROUND_V_FASE2, normalize(), PI, point_perp(), TRUE, veccopy(), vecequal(), vecminus(), VerFgMake, VerVCoord, and VPTYPE.
Referenced by EdgeGeneration_faces().
void GetNxtVertex (HPTYPE he, vector p)
Definition at line 620 of file rndfase2.cpp.
References angle_edge(), comp(), EdgFgRound, EPS, FacFeq, HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_ROUND_V_FASE2, MSD_ROUND_V_ORIGINAL, PI, point_perp(), veccopy(), vecesc(), VerFgMake, and VerVCoord.
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
void GetPrvVertex (HPTYPE he, vector p)
Definition at line 685 of file rndfase2.cpp.
References angle_edge(), comp(), EdgFgRound, EPS, FacFeq, HalEdg, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_ROUND_V_FASE2, MSD_ROUND_V_ORIGINAL, PI, point_perp(), veccopy(), VerFgMake, and VerVCoord.
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
void MakeEdgeConcaveCorner (SPTYPE s, HPTYPE he)
Definition at line 404 of file rndfase2.cpp.
References EdgFgMake, EdgFgRound, FacFeq, GetNxtVertex(), GetPrvVertex(), HalEdg, HalPrv, HalR, HalVtx, HalWLoop, line_inter(), line_parallel(), LooLFace, mate, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecesc(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GenerationEdges_corners().
HPTYPE MakeEdgeConvexCorner (SPTYPE s, HPTYPE he)
Definition at line 494 of file rndfase2.cpp.
References comp(), EdgFgMake, EdgFgRound, EPS, FacFeq, GetNxtVertex(), GetPrvVertex(), HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, line_inter(), line_parallel(), LooLFace, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecequal(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GenerationEdges_corners().
void MakeEdgeFlatCorner (SPTYPE s, HPTYPE he)
Definition at line 351 of file rndfase2.cpp.
References EdgFgMake, EdgFgRound, EPTYPE, FacFeq, HalEdg, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecesc(), vecplus(), VerFgMake, and VerVCoord.
Referenced by GenerationEdges_corners().