USPDesigner: C:/USPDesig/RN1/rndfase3.cpp File Reference
C:/USPDesig/RN1/rndfase3.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "rndround.h"
Functions
int GenerationCurved_edges (SPTYPE s)
int EdgesAttachedOriginal_vertex (SPTYPE s)
VPTYPE edv1 (VPTYPE v)
VPTYPE edv2 (SPTYPE s, VPTYPE v)
VPTYPE edv3 (SPTYPE s, VPTYPE v)
VPTYPE edv4 (SPTYPE s, VPTYPE v)
int EdgeAttached_vertexfase1 (SPTYPE s)
Function Documentation
int EdgeAttached_vertexfase1 (SPTYPE s)
Definition at line 299 of file rndfase3.cpp.
References AllShellsSolid, CLC(), DPTYPE, EdgFgMake, EdgFgRound, EdgHe1, EdgHe2, EdgNextE, ENIL, EPTYPE, GetEdges(), HalNxt, HalPrv, HalVtx, mate, MSD_lowKEF(), MSD_lowKEV(), MSD_lowNewVertexLocation(), SheSEdges, SheSVerts, SUCCESS, veccopy(), VerFgMake, VerNextV, VerVCoord, VerVEdge, VNIL, and VPTYPE.
Referenced by GenerationCurved_edges().
int EdgesAttachedOriginal_vertex (SPTYPE s)
Definition at line 59 of file rndfase3.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgFgMake, EdgFgRound, edv1(), edv2(), edv3(), edv4(), EPTYPE, GetEdges(), SheSVerts, SUCCESS, VerFgMake, VerNextV, VerVCoord, VNIL, and VPTYPE.
Referenced by GenerationCurved_edges().
VPTYPE edv1 (VPTYPE v)
Definition at line 144 of file rndfase3.cpp.
References HalNxt, HPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv2 (SPTYPE s, VPTYPE v)
Definition at line 173 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), MSD_lowNewVertexLocation(), veccopy(), VerFgMake, VerVCoord, VerVEdge, and VPTYPE.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv3 (SPTYPE s, VPTYPE v)
Definition at line 226 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, maxf, MSD_getMaxFaceId(), MSD_lowKEF(), MSD_lowMEF(), veccopy(), VerVCoord, and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv4 (SPTYPE s, VPTYPE v)
Definition at line 264 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, maxf, MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEF(), veccopy(), VerVCoord, and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
int GenerationCurved_edges (SPTYPE s)
Definition at line 52 of file rndfase3.cpp.
References EdgeAttached_vertexfase1(), EdgesAttachedOriginal_vertex(), and SUCCESS.
Referenced by MSD_lowRound().