USPDesigner: C:/USPDesig/RN1/rndfase1.cpp File Reference
C:/USPDesig/RN1/rndfase1.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "rndround.h"
#include "curvgeom.h"
Functions
int GeneratingVertices_edges (SPTYPE s)
int MakingEdges_tables (SPTYPE s)
int MakingVertices_edges (SPTYPE s)
Function Documentation
int GeneratingVertices_edges (SPTYPE s)
Definition at line 54 of file rndfase1.cpp.
References ERROR, MakingEdges_tables(), MakingVertices_edges(), and SUCCESS.
Referenced by MSD_lowRound().
int MakingEdges_tables (SPTYPE s)
Definition at line 67 of file rndfase1.cpp.
References _line(), AllEdgesShell, AllShellsSolid, angle_edge(), calc_t(), comp(), dot(), DPTYPE, EdgD, EdgEdgeNo, EdgFgRound, EdgHe1, EdgHe2, EdgT1, EdgT2, EdgT3, EdgT4, EPS, EPTYPE, ERROR, FacFeq, HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, line_inter(), LooLFace, mate, PI, SUCCESS, veccopy(), vecminus(), VerVCoord, and VPTYPE.
Referenced by GeneratingVertices_edges().
int MakingVertices_edges (SPTYPE s)
Definition at line 252 of file rndfase1.cpp.
References AllEdgesShell, AllShellsSolid, angle_edge(), comp(), DPTYPE, EdgD, EdgFgMake, EdgFgRound, EdgHe1, EdgHe2, EdgT1, EdgT2, EdgT3, EdgT4, EPS, EPTYPE, ERROR, HalEdg, HalNxt, HalPrv, HalR, HalVtx, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_E_FASE1, MSD_ROUND_FLAG_E0, MSD_ROUND_FLAG_V0, MSD_ROUND_V_FASE1, normalize(), PI, SUCCESS, veccopy(), vecequal(), vecesc(), vecminus(), vecplus(), veczer(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GeneratingVertices_edges().