USPDesigner: C:/USPDesig/INC/rndround.h File Reference
C:/USPDesig/INC/rndround.h File Reference
Classes
struct RND
Defines
#define EXTERN extern
#define MSD_ROUND_E_ORIGINAL 0
#define MSD_ROUND_E_FASE1 1
#define MSD_ROUND_E_FASE2 2
#define MSD_ROUND_E_FASE3 3
#define MSD_ROUND_V_ORIGINAL 0
#define MSD_ROUND_V_FASE1 1
#define MSD_ROUND_V_FASE2 2
#define MSD_ROUND_V_FASE3 3
#define MSD_ROUND_FLAG_E0 0
#define MSD_ROUND_FLAG_E1 1
#define MSD_ROUND_FLAG_E2 2
#define MSD_ROUND_FLAG_E3 3
#define MSD_ROUND_FLAG_E4 4
#define MSD_ROUND_FLAG_V0 0
#define MSD_ROUND_FLAG_V1 1
Functions
EPTYPE sedge (SPTYPE, Id)
void MSD_execRound (void)
int MSD_highRound (char *, int, int)
int MSD_lowRound (SPTYPE)
Id getmaxct (SPTYPE)
int leval_edge (SPTYPE, int)
void MSD_execEvalEdge (void)
int lrnd_alledges (SPTYPE, real)
void MSD_execRndAllEdges (void)
int GeneratingVertices_edges (SPTYPE)
int MakingEdges_tables (SPTYPE)
int MakingVertices_edges (SPTYPE)
int EdgeGeneration_faces (SPTYPE)
int GenerationEdges_corners (SPTYPE)
int GenerationEdges_nvertices (SPTYPE)
void MakeEdgeFlatCorner (SPTYPE, HPTYPE)
HPTYPE MakeEdgeConvexCorner (SPTYPE, HPTYPE)
void MakeEdgeConcaveCorner (SPTYPE, HPTYPE)
void GetNxtVertex (HPTYPE, vector)
void GetPrvVertex (HPTYPE, vector)
int cont_point (VPTYPE, VPTYPE, vector)
int GenerationCurved_edges (SPTYPE)
int EdgesAttachedOriginal_vertex (SPTYPE)
VPTYPE edv1 (VPTYPE)
VPTYPE edv2 (SPTYPE, VPTYPE)
VPTYPE edv3 (SPTYPE, VPTYPE)
VPTYPE edv4 (SPTYPE, VPTYPE)
int EdgeAttached_vertexfase1 (SPTYPE)
void calc_point (vector, vector, real, vector)
real angle_edge (HPTYPE)
int GetEdges (VPTYPE, int)
void CLC (SPTYPE, HPTYPE, vector, vector, vector)
void lgeo_arc (vector, vector, vector, vector, vector, real, real)
void _line (vector, real, vector, real, vector, vector, vector)
void line_parallel (vector, vector, vector, vector, vector, real)
real calc_t (vector, vector, vector)
void line_inter (vector, vector, vector, vector, vector)
void point_perp (vector, vector, vector, vector, real)
Define Documentation
#define EXTERN extern
Definition at line 46 of file rndround.h.
#define MSD_ROUND_E_FASE1 1
Definition at line 62 of file rndround.h.
Referenced by MakingVertices_edges().
#define MSD_ROUND_E_FASE2 2
Definition at line 63 of file rndround.h.
Referenced by GenerationEdges_nvertices(), MakeEdgeConvexCorner(), and MakeEdgeFlatCorner().
#define MSD_ROUND_E_FASE3 3
Definition at line 64 of file rndround.h.
#define MSD_ROUND_E_ORIGINAL 0
Definition at line 61 of file rndround.h.
Referenced by GenerationEdges_nvertices().
#define MSD_ROUND_FLAG_E0 0
Definition at line 70 of file rndround.h.
Referenced by MakingVertices_edges().
#define MSD_ROUND_FLAG_E1 1
Definition at line 71 of file rndround.h.
Referenced by GenerationEdges_nvertices().
#define MSD_ROUND_FLAG_E2 2
Definition at line 72 of file rndround.h.
#define MSD_ROUND_FLAG_E3 3
Definition at line 73 of file rndround.h.
#define MSD_ROUND_FLAG_E4 4
Definition at line 74 of file rndround.h.
#define MSD_ROUND_FLAG_V0 0
Definition at line 75 of file rndround.h.
Referenced by MakingVertices_edges().
#define MSD_ROUND_FLAG_V1 1
Definition at line 76 of file rndround.h.
#define MSD_ROUND_V_FASE1 1
Definition at line 66 of file rndround.h.
Referenced by MakingVertices_edges().
#define MSD_ROUND_V_FASE2 2
Definition at line 67 of file rndround.h.
Referenced by GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), and MakeEdgeFlatCorner().
#define MSD_ROUND_V_FASE3 3
Definition at line 68 of file rndround.h.
#define MSD_ROUND_V_ORIGINAL 0
Definition at line 65 of file rndround.h.
Referenced by GenerationEdges_corners(), GetNxtVertex(), and GetPrvVertex().
Function Documentation
void _line (vector , real , vector , real , vector , vector , vector)
Definition at line 139 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by MakingEdges_tables().
real angle_edge (HPTYPE)
Definition at line 61 of file rndaux__.cpp.
References comp(), cross(), dot(), EPS, FacFeq, HalPrv, HalVtx, HalWLoop, LooLFace, mate, normalize(), PI, veccopy(), vecminus(), and VerVCoord.
Referenced by GenerationEdges_corners(), GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakingEdges_tables(), and MakingVertices_edges().
void calc_point (vector , vector , real , vector)
Definition at line 54 of file rndaux__.cpp.
References vecesc(), vecminus(), and vecplus().
real calc_t (vector , vector , vector)
Definition at line 171 of file rndaux__.cpp.
References vecminus(), and veczer().
Referenced by MakingEdges_tables().
void CLC (SPTYPE , HPTYPE , vector , vector , vector)
Definition at line 109 of file rndaux__.cpp.
References getmaxct(), lgeo_arc(), SolSolidNo, and vecd().
Referenced by EdgeAttached_vertexfase1(), edv2(), edv3(), and edv4().
int cont_point (VPTYPE , VPTYPE , vector)
Definition at line 748 of file rndfase2.cpp.
References veccopy(), vecd(), and VerVCoord.
Referenced by GenerationEdges_nvertices().
int EdgeAttached_vertexfase1 (SPTYPE)
Definition at line 299 of file rndfase3.cpp.
References AllShellsSolid, CLC(), DPTYPE, EdgFgMake, EdgFgRound, EdgHe1, EdgHe2, EdgNextE, ENIL, EPTYPE, GetEdges(), HalNxt, HalPrv, HalVtx, mate, MSD_lowKEF(), MSD_lowKEV(), MSD_lowNewVertexLocation(), SheSEdges, SheSVerts, SUCCESS, veccopy(), VerFgMake, VerNextV, VerVCoord, VerVEdge, VNIL, and VPTYPE.
Referenced by GenerationCurved_edges().
int EdgeGeneration_faces (SPTYPE)
Definition at line 53 of file rndfase2.cpp.
References GenerationEdges_corners(), GenerationEdges_nvertices(), and SUCCESS.
Referenced by MSD_lowRound().
int EdgesAttachedOriginal_vertex (SPTYPE)
Definition at line 59 of file rndfase3.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgFgMake, EdgFgRound, edv1(), edv2(), edv3(), edv4(), EPTYPE, GetEdges(), SheSVerts, SUCCESS, VerFgMake, VerNextV, VerVCoord, VNIL, and VPTYPE.
Referenced by GenerationCurved_edges().
VPTYPE edv1 (VPTYPE)
Definition at line 144 of file rndfase3.cpp.
References HalNxt, HPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv2 (SPTYPE , VPTYPE)
Definition at line 173 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), MSD_lowNewVertexLocation(), veccopy(), VerFgMake, VerVCoord, VerVEdge, and VPTYPE.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv3 (SPTYPE , VPTYPE)
Definition at line 226 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, maxf, MSD_getMaxFaceId(), MSD_lowKEF(), MSD_lowMEF(), veccopy(), VerVCoord, and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
VPTYPE edv4 (SPTYPE , VPTYPE)
Definition at line 264 of file rndfase3.cpp.
References CLC(), EdgFgRound, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, mate, maxf, MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEF(), veccopy(), VerVCoord, and VerVEdge.
Referenced by EdgesAttachedOriginal_vertex().
int GeneratingVertices_edges (SPTYPE)
Definition at line 54 of file rndfase1.cpp.
References ERROR, MakingEdges_tables(), MakingVertices_edges(), and SUCCESS.
Referenced by MSD_lowRound().
int GenerationCurved_edges (SPTYPE)
Definition at line 52 of file rndfase3.cpp.
References EdgeAttached_vertexfase1(), EdgesAttachedOriginal_vertex(), and SUCCESS.
Referenced by MSD_lowRound().
int GenerationEdges_corners (SPTYPE)
Definition at line 62 of file rndfase2.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, angle_edge(), comp(), DPTYPE, EPS, FPTYPE, HalNxt, HalVtx, HPTYPE, LooLEdg, LPTYPE, MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MSD_ROUND_V_ORIGINAL, PI, TRUE, and VerFgMake.
Referenced by EdgeGeneration_faces().
int GenerationEdges_nvertices (SPTYPE)
Definition at line 138 of file rndfase2.cpp.
References AllFacesShell, AllLoopsFace, AllShellsSolid, angle_edge(), comp(), cont_point(), cross(), DPTYPE, EdgFgMake, EdgFgRound, EPS, EPTYPE, FacFaceNo, FPTYPE, HalEdg, HalNxt, HalPrv, HalVtx, HPTYPE, line_inter(), LooLEdg, LPTYPE, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_E_ORIGINAL, MSD_ROUND_FLAG_E1, MSD_ROUND_V_FASE2, normalize(), PI, point_perp(), TRUE, veccopy(), vecequal(), vecminus(), VerFgMake, VerVCoord, and VPTYPE.
Referenced by EdgeGeneration_faces().
int GetEdges (VPTYPE , int)
Definition at line 88 of file rndaux__.cpp.
References EdgFgRound, HalEdg, HalNxt, HPTYPE, mate, and VerVEdge.
Referenced by EdgeAttached_vertexfase1(), and EdgesAttachedOriginal_vertex().
Id getmaxct (SPTYPE)
Definition at line 246 of file rndround.cpp.
References NIL, and SolCurv.
Referenced by CLC().
void GetNxtVertex (HPTYPE , vector)
Definition at line 620 of file rndfase2.cpp.
References angle_edge(), comp(), EdgFgRound, EPS, FacFeq, HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_ROUND_V_FASE2, MSD_ROUND_V_ORIGINAL, PI, point_perp(), veccopy(), vecesc(), VerFgMake, and VerVCoord.
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
void GetPrvVertex (HPTYPE , vector)
Definition at line 685 of file rndfase2.cpp.
References angle_edge(), comp(), EdgFgRound, EPS, FacFeq, HalEdg, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_ROUND_V_FASE2, MSD_ROUND_V_ORIGINAL, PI, point_perp(), veccopy(), VerFgMake, and VerVCoord.
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
int leval_edge (SPTYPE , int)
Definition at line 266 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgHe1, EPTYPE, HalCurv, and NIL.
Referenced by MSD_lowRound().
void lgeo_arc (vector , vector , vector , vector , vector , real , real)
Definition at line 123 of file rndaux__.cpp.
References normalize(), and vecminus().
Referenced by CLC().
void line_inter (vector , vector , vector , vector , vector)
Definition at line 186 of file rndaux__.cpp.
References comp(), cross(), EPS, getdrop(), normalize(), vecminus(), X, Y, and Z.
Referenced by GenerationEdges_nvertices(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), and MakingEdges_tables().
void line_parallel (vector , vector , vector , vector , vector , real)
Definition at line 156 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by MakeEdgeConcaveCorner(), and MakeEdgeConvexCorner().
int lrnd_alledges (SPTYPE , real)
Definition at line 309 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, AllVerticesShell, DPTYPE, EdgFgRound, EdgHe1, EdgHe2, EPTYPE, ERROR, HalR, MSD_lowRound(), SUCCESS, VerFgRound, and VPTYPE.
Referenced by MSD_execRndAllEdges().
void MakeEdgeConcaveCorner (SPTYPE , HPTYPE)
Definition at line 404 of file rndfase2.cpp.
References EdgFgMake, EdgFgRound, FacFeq, GetNxtVertex(), GetPrvVertex(), HalEdg, HalPrv, HalR, HalVtx, HalWLoop, line_inter(), line_parallel(), LooLFace, mate, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecesc(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GenerationEdges_corners().
HPTYPE MakeEdgeConvexCorner (SPTYPE , HPTYPE)
Definition at line 494 of file rndfase2.cpp.
References comp(), EdgFgMake, EdgFgRound, EPS, FacFeq, GetNxtVertex(), GetPrvVertex(), HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, line_inter(), line_parallel(), LooLFace, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecequal(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GenerationEdges_corners().
void MakeEdgeFlatCorner (SPTYPE , HPTYPE)
Definition at line 351 of file rndfase2.cpp.
References EdgFgMake, EdgFgRound, EPTYPE, FacFeq, HalEdg, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_E_FASE2, MSD_ROUND_V_FASE2, point_perp(), veccopy(), vecesc(), vecplus(), VerFgMake, and VerVCoord.
Referenced by GenerationEdges_corners().
int MakingEdges_tables (SPTYPE)
Definition at line 67 of file rndfase1.cpp.
References _line(), AllEdgesShell, AllShellsSolid, angle_edge(), calc_t(), comp(), dot(), DPTYPE, EdgD, EdgEdgeNo, EdgFgRound, EdgHe1, EdgHe2, EdgT1, EdgT2, EdgT3, EdgT4, EPS, EPTYPE, ERROR, FacFeq, HalEdg, HalNxt, HalPrv, HalR, HalVtx, HalWLoop, HPTYPE, line_inter(), LooLFace, mate, PI, SUCCESS, veccopy(), vecminus(), VerVCoord, and VPTYPE.
Referenced by GeneratingVertices_edges().
int MakingVertices_edges (SPTYPE)
Definition at line 252 of file rndfase1.cpp.
References AllEdgesShell, AllShellsSolid, angle_edge(), comp(), DPTYPE, EdgD, EdgFgMake, EdgFgRound, EdgHe1, EdgHe2, EdgT1, EdgT2, EdgT3, EdgT4, EPS, EPTYPE, ERROR, HalEdg, HalNxt, HalPrv, HalR, HalVtx, maxv, MSD_getMaxVertexId(), MSD_lowMEV(), MSD_ROUND_E_FASE1, MSD_ROUND_FLAG_E0, MSD_ROUND_FLAG_V0, MSD_ROUND_V_FASE1, normalize(), PI, SUCCESS, veccopy(), vecequal(), vecesc(), vecminus(), vecplus(), veczer(), VerFgMake, VerFgRound, and VerVCoord.
Referenced by GeneratingVertices_edges().
void MSD_execEvalEdge (void)
void MSD_execRndAllEdges (void)
Definition at line 340 of file rndround.cpp.
References ERROR, lineins(), lrnd_alledges(), MEN_NaoEncontrouSolidNome, MEN_OperacaoNaoRealizada, MSD_lowFindSolidByName(), NAM_RoundAll, restbuf, SNIL, and SPTYPE.
void MSD_execRound (void)
Definition at line 75 of file rndround.cpp.
References ERROR, lineins(), MEN_OperacaoNaoRealizada, MSD_highRound(), NAM_Round, and restbuf.
int MSD_highRound (char * , int , int)
Definition at line 94 of file rndround.cpp.
References EdgFgRound, EdgHe1, EdgHe2, ENIL, EPTYPE, ERROR, FALSE, HalR, HalVtx, lineins(), MEN_NaoEncontrouEdgeNo, MEN_NaoEncontrouSolidNome, MSD_lowFindSolidByName(), MSD_lowRound(), NAM_Round, restbuf, sedge(), skipnext(), SNIL, SolSolidNo, SPTYPE, SUCCESS, VerFgRound, and workbuf.
Referenced by MSD_execRound().
int MSD_lowRound (SPTYPE)
Definition at line 231 of file rndround.cpp.
References EdgeGeneration_faces(), ERROR, GeneratingVertices_edges(), GenerationCurved_edges(), leval_edge(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SUCCESS, and TRUE.
Referenced by lrnd_alledges(), and MSD_highRound().
void point_perp (vector , vector , vector , vector , real)
Definition at line 244 of file rndaux__.cpp.
References cross(), normalize(), vecesc(), vecminus(), vecplus(), and veczer().
Referenced by GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), and MakeEdgeFlatCorner().
EPTYPE sedge (SPTYPE , Id)
Definition at line 57 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgEdgeNo, ENIL, and EPTYPE.
Referenced by MSD_highRound().