USPDesigner: C:/USPDesig/RN1/rndround.cpp File Reference
C:/USPDesig/RN1/rndround.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "rndround.h"
#include "curvgeom.h"
#include "disdispl.h"
#include "shpshape.h"
#include "genfunc_.h"
Functions
EPTYPE sedge (SPTYPE s, Id en)
void MSD_execRound (void)
int MSD_highRound (char *sn, int ne, int flag_vertex)
int MSD_lowRound (SPTYPE s)
Id getmaxct (SPTYPE s)
int leval_edge (SPTYPE s, int nsegm)
int lrnd_alledges (SPTYPE s, real r)
void MSD_execRndAllEdges (void)
Function Documentation
Id getmaxct (SPTYPE s)
Definition at line 246 of file rndround.cpp.
References NIL, and SolCurv.
Referenced by CLC().
int leval_edge (SPTYPE s, int nsegm)
Definition at line 266 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgHe1, EPTYPE, HalCurv, and NIL.
Referenced by MSD_lowRound().
int lrnd_alledges (SPTYPE s, real r)
Definition at line 309 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, AllVerticesShell, DPTYPE, EdgFgRound, EdgHe1, EdgHe2, EPTYPE, ERROR, HalR, MSD_lowRound(), SUCCESS, VerFgRound, and VPTYPE.
Referenced by MSD_execRndAllEdges().
void MSD_execRndAllEdges (void)
Definition at line 340 of file rndround.cpp.
References ERROR, lineins(), lrnd_alledges(), MEN_NaoEncontrouSolidNome, MEN_OperacaoNaoRealizada, MSD_lowFindSolidByName(), NAM_RoundAll, restbuf, SNIL, and SPTYPE.
void MSD_execRound (void)
Definition at line 75 of file rndround.cpp.
References ERROR, lineins(), MEN_OperacaoNaoRealizada, MSD_highRound(), NAM_Round, and restbuf.
int MSD_highRound (char * sn, int ne, int flag_vertex)
Definition at line 94 of file rndround.cpp.
References EdgFgRound, EdgHe1, EdgHe2, ENIL, EPTYPE, ERROR, FALSE, HalR, HalVtx, lineins(), MEN_NaoEncontrouEdgeNo, MEN_NaoEncontrouSolidNome, MSD_lowFindSolidByName(), MSD_lowRound(), NAM_Round, restbuf, sedge(), skipnext(), SNIL, SolSolidNo, SPTYPE, SUCCESS, VerFgRound, and workbuf.
Referenced by MSD_execRound().
int MSD_lowRound (SPTYPE s)
Definition at line 231 of file rndround.cpp.
References EdgeGeneration_faces(), ERROR, GeneratingVertices_edges(), GenerationCurved_edges(), leval_edge(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SUCCESS, and TRUE.
Referenced by lrnd_alledges(), and MSD_highRound().
EPTYPE sedge (SPTYPE s, Id en)
Definition at line 57 of file rndround.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EdgEdgeNo, ENIL, and EPTYPE.
Referenced by MSD_highRound().