USPDesigner: C:/USPDesig/ROV/rovcubo_.cpp File Reference
C:/USPDesig/ROV/rovcubo_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakeCubo (char *name, real a)
void MSD_execNameMakeCubo (void)
Function Documentation
void MSD_execNameMakeCubo (void)
Definition at line 55 of file rovcubo_.cpp.
References lineins(), MSD_highNameMakeCubo(), and restbuf.
void MSD_highNameMakeCubo (char * name, real a)
Definition at line 71 of file rovcubo_.cpp.
References FRONTEIRA_CV, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeCube(), NAM_RovCubo, SolFronteira, SolGeometria, SOLIDO_GEOM_CUBO, SOLIDO_TIPO_SOLID, SolName, SolParam1, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakeCubo().