USPDesigner: C:/USPDesig/ROV/rovcone_.cpp File Reference
C:/USPDesig/ROV/rovcone_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakeROVCone (char *name, real r, real h, int n)
void MSD_execNameMakeROVCone (void)
Function Documentation
void MSD_execNameMakeROVCone (void)
Definition at line 55 of file rovcone_.cpp.
References lineins(), MSD_highNameMakeROVCone(), and restbuf.
void MSD_highNameMakeROVCone (char * name, real r, real h, int n)
Definition at line 72 of file rovcone_.cpp.
References FRONTEIRA_A, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeCone(), NAM_RovCone, SolFronteira, SolGeometria, SOLIDO_GEOM_CONE, SOLIDO_TIPO_SOLID, SolName, SolParam1, SolParam2, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakeROVCone().