USPDesigner: C:/USPDesig/ROV/rovcirc_.cpp File Reference
C:/USPDesig/ROV/rovcirc_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakeCirculo (char *name, real r, real h, int n)
void MSD_execNameMakeCirculo (void)
Function Documentation
void MSD_execNameMakeCirculo (void)
Definition at line 55 of file rovcirc_.cpp.
References lineins(), MSD_highNameMakeCirculo(), and restbuf.
void MSD_highNameMakeCirculo (char * name, real r, real h, int n)
Definition at line 72 of file rovcirc_.cpp.
References BARRA_GEOM_CIRCULO, FRONTEIRA_A, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeCylinder(), NAM_RovCirculo, SolFronteira, SolGeometria, SOLIDO_TIPO_BARRA, SolName, SolParam1, SolParam2, SolPerfil, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakeCirculo().