USPDesigner: C:/USPDesig/ROV/rovdist_.cpp File Reference
C:/USPDesig/ROV/rovdist_.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowmacro.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "analise_.h"
#include "basrov__.h"
Functions
real MSD_determinaDistanciaParametrica (vector cc, vector dir, vector pp)
real MSD_determinaDimensaoPrincipalBarra (SPTYPE s, vector dir)
real MSD_determinaMaiorDimensao (SPTYPE s)
real MSD_determinaDimensaoPrincipal (SPTYPE s, vector dir, real dim)
Function Documentation
real MSD_determinaDimensaoPrincipal (SPTYPE s, vector dir, real dim)
Definition at line 138 of file rovdist_.cpp.
References BARRA_GEOM_CIRCULO, BARRA_GEOM_ELIPSE, BARRA_GEOM_PERFIL_I, BARRA_GEOM_PERFIL_L, BARRA_GEOM_PERFIL_T, BARRA_GEOM_QUADRADO, BARRA_GEOM_RETANGULO, BARRA_GEOM_TRIANGULO, comp(), cross(), dot(), FacFeq, MSD_determinaDimensaoPrincipalBarra(), MSD_getFace(), MSD_getSolid(), MSD_lowSolidDimensaoPrincipal(), SNIL, SolGeometria, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolParam1, SolParam2, SolPerfil, SolPrincDir, SolType, SPTYPE, veccopy(), and vecnull().
Referenced by MSD_CalculaParametrosInterferencia(), and MSD_highDimensaoPrincipal().
real MSD_determinaDimensaoPrincipalBarra (SPTYPE s, vector dir)
Definition at line 68 of file rovdist_.cpp.
References AllVerticesShell, dot(), DPTYPE, makevec(), MSD_determinaDistanciaParametrica(), SolSShells, veccopy(), vecesc(), VerVCoord, and VPTYPE.
Referenced by MSD_determinaDimensaoPrincipal().
real MSD_determinaDistanciaParametrica (vector cc, vector dir, vector pp)
Definition at line 60 of file rovdist_.cpp.
References dot().
Referenced by MSD_determinaDimensaoPrincipalBarra(), MSD_lowCalculaDimensoesRelativas(), and MSD_lowCriaListaEstudo().
real MSD_determinaMaiorDimensao (SPTYPE s)
Definition at line 102 of file rovdist_.cpp.
References BARRA_GEOM_CIRCULO, BARRA_GEOM_ELIPSE, BARRA_GEOM_PERFIL_I, BARRA_GEOM_PERFIL_L, BARRA_GEOM_PERFIL_T, BARRA_GEOM_QUADRADO, BARRA_GEOM_RETANGULO, BARRA_GEOM_TRIANGULO, SolGeometria, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolParam2, SolParam3, SolParam4, and SolType.
Referenced by MSD_CalculaParametrosInterferencia().