USPDesigner: C:/USPDesig/ROV/rovdmprc.cpp File Reference
C:/USPDesig/ROV/rovdmprc.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "analise_.h"
#include "basrov__.h"
Functions
real MSD_highNameDimensaoPrincipal (char *name, real dx, real dy, real dz)
real MSD_highDimensaoPrincipal (Id sn, real dx, real dy, real dz)
void MSD_execNameDimensaoPrincipal (void)
Function Documentation
void MSD_execNameDimensaoPrincipal (void)
Definition at line 57 of file rovdmprc.cpp.
References lineins(), MSD_highNameDimensaoPrincipal(), and restbuf.
real MSD_highDimensaoPrincipal (Id sn, real dx, real dy, real dz)
Definition at line 86 of file rovdmprc.cpp.
References makevec(), MEN_NaoEncontrouSolido, MSD_determinaDimensaoPrincipal(), MSD_getSolid(), NAM_DimPrinc, SNIL, and SPTYPE.
Referenced by MSD_highNameDimensaoPrincipal().
real MSD_highNameDimensaoPrincipal (char * name, real dx, real dy, real dz)
Definition at line 74 of file rovdmprc.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDimensaoPrincipal(), and NAM_DimPrinc.
Referenced by MSD_execNameDimensaoPrincipal().