USPDesigner: C:/USPDesig/ROV/rovesfer.cpp File Reference
C:/USPDesig/ROV/rovesfer.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakeEsfera (char *name, real r, int n)
void MSD_execNameMakeEsfera (void)
Function Documentation
void MSD_execNameMakeEsfera (void)
Definition at line 55 of file rovesfer.cpp.
References lineins(), MSD_highNameMakeEsfera(), and restbuf.
void MSD_highNameMakeEsfera (char * name, real r, int n)
Definition at line 72 of file rovesfer.cpp.
References FRONTEIRA_A, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeSphere(), NAM_RovEsfera, SolFronteira, SolGeometria, SOLIDO_GEOM_ESFERA, SOLIDO_TIPO_SOLID, SolName, SolParam1, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakeEsfera().