USPDesigner: C:/USPDesig/ROV/rovorden.cpp File Reference
C:/USPDesig/ROV/rovorden.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <math.h>
#include <stdlib.h>
#include "lowmacro.h"
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "genfunc_.h"
#include "sethmain.h"
#include "mancommd.h"
#include "analise_.h"
#include "basrov__.h"
#include "gphgraph.h"
#include "disdispl.h"
Functions
int MSD_lowOrdena (char *nome, real raio, real dx, real dy, real dz)
int MSD_lowAreaProjetadaTotal (real dx, real dy, real dz, real *area, real *dim)
double MSD_lowSolidAreaProjetada (SPTYPE s)
void MSD_execProjetadaTotal (void)
void MSD_execOrdena (void)
int MSD_lowOrdenaListaEstudo (void)
int MSD_lowCriaListaEstudo (real dx, real dy, real dz)
int MSD_lowSetVariaveisImpressao (int i, int j, char *TSolido, char *TFronteira, char *TGeometria, char *TAtitude, real dx, real dy, real dz, int flag)
int MSD_lowCalculaDimensoesRelativas (int i, int j, real *LD, real *TD, real dx, real dy, real dz)
int MSD_lowImprimeListaEstudo (char *nome, real raio, real dx, real dy, real dz)
int MSD_CalculaParametrosInterferencia (real dx, real dy, real dz)
Variables
char MSD_formatImpressao []
Function Documentation
int MSD_CalculaParametrosInterferencia (real dx, real dy, real dz)
Definition at line 528 of file rovorden.cpp.
References ListaOrdenada::area, ListaOrdenada::D, ListaOrdenada::H_D, ListaEscoamento, makevec(), MSD_determinaDimensaoPrincipal(), MSD_determinaMaiorDimensao(), MSD_lowAreaProjetada(), NumListaEscoamento, and TRUE.
Referenced by MSD_lowOrdena().
void MSD_execOrdena (void)
Definition at line 87 of file rovorden.cpp.
References lineins(), ListaEscoamento, MSD_lowOrdena(), NumListaEscoamento, restbuf, SolName, and SolSolidNo.
void MSD_execProjetadaTotal (void)
Definition at line 70 of file rovorden.cpp.
References lineins(), MSD_lowAreaProjetadaTotal(), and restbuf.
int MSD_lowAreaProjetadaTotal (real dx, real dy, real dz, real * area, real * dim)
Definition at line 550 of file rovorden.cpp.
References AllSolids, g_clear(), makevec(), MSD_getSolidIdFromName(), MSD_highNameDisplay(), MSD_highNameRenameSolid(), MSD_highNameSoftRemove(), MSD_highNameUnion(), MSD_lowAreaProjetada(), MSD_lowFindSolidByName(), MSD_lowSolidAreaProjetada(), MSD_lowSolidDimensaoPrincipal(), SOLIDO_TIPO_SOLID, SolName, SolPerfil, SolType, SPTYPE, and TRUE.
Referenced by MSD_execProjetadaTotal().
int MSD_lowCalculaDimensoesRelativas (int i, int j, real * LD, real * TD, real dx, real dy, real dz)
Definition at line 362 of file rovorden.cpp.
References ListaOrdenada::D, dot(), ListaEscoamento, makevec(), MSD_determinaDistanciaParametrica(), TRUE, vecesc(), vecminus(), and vecplus().
Referenced by MSD_lowImprimeListaEstudo().
int MSD_lowCriaListaEstudo (real dx, real dy, real dz)
Definition at line 141 of file rovorden.cpp.
References AllSolids, ERROR, ListaEscoamento, makevec(), MEN_NaoPossuiMemoria, MSD_determinaDistanciaParametrica(), MSD_lowCentroDeGravidade(), NAM_RovOrdena, NIL, NumListaEscoamento, ListaOrdenada::optr, ListaOrdenada::param, SOLIDO_TIPO_SOLID, SolPerfil, SolType, SPTYPE, TRUE, and veccopy().
Referenced by MSD_lowOrdena().
int MSD_lowImprimeListaEstudo (char * nome, real raio, real dx, real dy, real dz)
Definition at line 384 of file rovorden.cpp.
References comp(), cross(), dot(), EPS, ERROR, FacFeq, ListaEscoamento, makevec(), MSD_formatImpressao, MSD_getFace(), MSD_getSolid(), MSD_lowCalculaDimensoesRelativas(), MSD_lowSetVariaveisImpressao(), NIL, normalize(), NumListaEscoamento, SNIL, SOLIDO_TIPO_BARRA, SolName, SolPerfil, SolType, SPTYPE, TRUE, vecd(), and vecnull().
Referenced by MSD_lowOrdena().
int MSD_lowOrdena (char * nome, real raio, real dx, real dy, real dz)
Definition at line 589 of file rovorden.cpp.
References ERROR, MSD_CalculaParametrosInterferencia(), MSD_lowCriaListaEstudo(), MSD_lowImprimeListaEstudo(), MSD_lowOrdenaListaEstudo(), and TRUE.
Referenced by MSD_execOrdena().
int MSD_lowOrdenaListaEstudo (void)
Definition at line 111 of file rovorden.cpp.
References FALSE, ListaEscoamento, NumListaEscoamento, ListaOrdenada::optr, ListaOrdenada::param, SPTYPE, TRUE, and veccopy().
Referenced by MSD_lowOrdena().
int MSD_lowSetVariaveisImpressao (int i, int j, char * TSolido, char * TFronteira, char * TGeometria, char * TAtitude, real dx, real dy, real dz, int flag)
Definition at line 186 of file rovorden.cpp.
References BARRA_GEOM_CIRCULO, BARRA_GEOM_ELIPSE, BARRA_GEOM_PERFIL_I, BARRA_GEOM_PERFIL_L, BARRA_GEOM_PERFIL_T, BARRA_GEOM_QUADRADO, BARRA_GEOM_RETANGULO, BARRA_GEOM_TRIANGULO, comp(), cross(), dot(), EPS, ERROR, ListaEscoamento, makevec(), MSD_lowRebatePontoNoPlano(), SolGeometria, SOLIDO_GEOM_CONE, SOLIDO_GEOM_CUBO, SOLIDO_GEOM_ESFERA, SOLIDO_GEOM_PIRAMIDE, SOLIDO_GEOM_PRISMA, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolPrincDir, SolType, TRUE, veccopy(), and vecnull().
Referenced by MSD_lowImprimeListaEstudo().
double MSD_lowSolidAreaProjetada (SPTYPE s)
Variable Documentation
char MSD_formatImpressao[]
Initial value:
   "(%s %s %.2f %.2f MSD %s %s %s %s %s %s %s %s %.2f %.2f)\n"
Definition at line 63 of file rovorden.cpp.
Referenced by MSD_lowImprimeListaEstudo().