USPDesigner: C:/USPDesig/ROV/rovpert_.cpp File Reference
C:/USPDesig/ROV/rovpert_.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakePerfilT (char *name, real a, real b, real t, real h)
void MSD_execNameMakePerfilT (void)
Function Documentation
void MSD_execNameMakePerfilT (void)
Definition at line 56 of file rovpert_.cpp.
References lineins(), MSD_highNameMakePerfilT(), and restbuf.
void MSD_highNameMakePerfilT (char * name, real a, real b, real t, real h)
Definition at line 72 of file rovpert_.cpp.
References BARRA_GEOM_PERFIL_T, dot(), ERROR, FacFLOut, FALSE, FRONTEIRA_CV, Gdoinversion, HARDREM, makevec(), MEN_SolidoJaExiste, MSD_getFace(), MSD_getMaxSolidId(), MSD_getSolidIdFromName(), MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowFaceEq(), MSD_lowHardRemove(), MSD_lowMakeSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), NAM_RovPerfilT, SNIL, SolFronteira, SolGeometria, SOLIDO_TIPO_BARRA, SolName, SolParam1, SolParam2, SolParam3, SolParam4, SolPerfil, SolPrincDir, SolType, SPTYPE, and TRUE.
Referenced by MSD_execNameMakePerfilT().