USPDesigner: C:/USPDesig/ROV/rovprism.cpp File Reference
C:/USPDesig/ROV/rovprism.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakePrisma (char *name, real a, real b, real c)
void MSD_execNameMakePrisma (void)
Function Documentation
void MSD_execNameMakePrisma (void)
Definition at line 55 of file rovprism.cpp.
References lineins(), MSD_highNameMakePrisma(), and restbuf.
void MSD_highNameMakePrisma (char * name, real a, real b, real c)
Definition at line 71 of file rovprism.cpp.
References FRONTEIRA_CV, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeCube(), NAM_RovPrisma, SolFronteira, SolGeometria, SOLIDO_GEOM_PRISMA, SOLIDO_TIPO_SOLID, SolName, SolParam1, SolParam2, SolParam3, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakePrisma().