USPDesigner: C:/USPDesig/ROV/rovpyram.cpp File Reference
C:/USPDesig/ROV/rovpyram.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakePiramide (char *name, int n, real h, XY *listvtx)
void MSD_execNameMakePiramide (void)
Function Documentation
void MSD_execNameMakePiramide (void)
Definition at line 55 of file rovpyram.cpp.
References lineins(), MSD_highNameMakePiramide(), restbuf, and setvtpi().
void MSD_highNameMakePiramide (char * name, int n, real h, XY * listvtx)
Definition at line 76 of file rovpyram.cpp.
References FRONTEIRA_CV, makevec(), MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakePyramid(), NAM_RovPiramide, SolFronteira, SolGeometria, SOLIDO_GEOM_PIRAMIDE, SOLIDO_TIPO_SOLID, SolName, SolParam1, SolPrincDir, SolType, and SPTYPE.
Referenced by MSD_execNameMakePiramide().