USPDesigner: C:/USPDesig/ROV/rovtrnds.cpp File Reference
C:/USPDesig/ROV/rovtrnds.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
Functions
int MSD_highNameDesloca (char *name, real dx, real dy, real dz)
int MSD_highDesloca (Id sn, real dx, real dy, real dz)
void MSD_execNameDesloca (void)
Function Documentation
void MSD_execNameDesloca (void)
Definition at line 55 of file rovtrnds.cpp.
References lineins(), MSD_highNameDesloca(), and restbuf.
int MSD_highDesloca (Id sn, real dx, real dy, real dz)
Definition at line 83 of file rovtrnds.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowTranslate(), NAM_RovTranslate, SNIL, SolPerfil, SPTYPE, and SUCCESS.
Referenced by MSD_highNameDesloca().
int MSD_highNameDesloca (char * name, real dx, real dy, real dz)
Definition at line 71 of file rovtrnds.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highDesloca(), and NAM_RovTranslate.
Referenced by MSD_execNameDesloca().