USPDesigner: C:/USPDesig/ROV/rovtrntr.cpp File Reference
C:/USPDesig/ROV/rovtrntr.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
int MSD_highNameRotaciona (char *name, real ax, real ay, real az)
int MSD_highRotaciona (Id sn, real ax, real ay, real az)
void MSD_execNameRotaciona (void)
Function Documentation
void MSD_execNameRotaciona (void)
Definition at line 56 of file rovtrntr.cpp.
References lineins(), MSD_highNameRotaciona(), and restbuf.
int MSD_highNameRotaciona (char * name, real ax, real ay, real az)
Definition at line 72 of file rovtrntr.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highRotaciona(), and NAM_RovRotate.
Referenced by MSD_execNameRotaciona().
int MSD_highRotaciona (Id sn, real ax, real ay, real az)
Definition at line 84 of file rovtrntr.cpp.
References ERROR, matident(), matrotat(), MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowRotate(), NAM_RovRotate, SNIL, SolGeometria, SOLIDO_GEOM_CONE, SOLIDO_TIPO_BARRA, SOLIDO_TIPO_PLACA, SOLIDO_TIPO_SOLID, SolPerfil, SolPrincDir, SolType, SPTYPE, SUCCESS, veccopy(), and vecmult().
Referenced by MSD_highNameRotaciona().