USPDesigner: C:/USPDesig/ROV/rovtrian.cpp File Reference
C:/USPDesig/ROV/rovtrian.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "basrov__.h"
Functions
void MSD_highNameMakeTriangulo (char *name, real a, real b, real c, real h)
void MSD_execNameMakeTriangulo (void)
Function Documentation
void MSD_execNameMakeTriangulo (void)
Definition at line 56 of file rovtrian.cpp.
References lineins(), MSD_highNameMakeTriangulo(), and restbuf.
void MSD_highNameMakeTriangulo (char * name, real a, real b, real c, real h)
Definition at line 72 of file rovtrian.cpp.
References BARRA_GEOM_TRIANGULO, dot(), ERROR, FacFLOut, FALSE, FRONTEIRA_CV, Gdoinversion, HARDREM, makevec(), MEN_SolidoJaExiste, MSD_getFace(), MSD_getMaxSolidId(), MSD_getSolidIdFromName(), MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowFaceEq(), MSD_lowHardRemove(), MSD_lowMakeSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), NAM_MakeCube, NAM_RovTriangulo, SNIL, SolFronteira, SolGeometria, SOLIDO_TIPO_BARRA, SolName, SolParam1, SolParam2, SolParam3, SolParam4, SolPerfil, SolPrincDir, SolType, SPTYPE, and TRUE.
Referenced by MSD_execNameMakeTriangulo().