USPDesigner: C:/USPDesig/SET/setdiffe.cpp File Reference
C:/USPDesig/SET/setdiffe.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "genfunc_.h"
#include "shpshape.h"
#include "disdispl.h"
#include "sethmain.h"
Functions
void MSD_execNameDifference (void)
void MSD_highNameDifference (char *name1, char *name2, char *name)
Id MSD_highDifference (Id sn1, Id sn2)
Function Documentation
void MSD_execNameDifference (void)
Definition at line 55 of file setdiffe.cpp.
References lineins(), MSD_highNameDifference(), and restbuf.
Id MSD_highDifference (Id sn1, Id sn2)
Definition at line 114 of file setdiffe.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetDifference, SNIL, SPTYPE, SUCCESS, and USP_DIFFERENCE.
Referenced by MSD_highNameDifference().
void MSD_highNameDifference (char * name1, char * name2, char * name)
Definition at line 70 of file setdiffe.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highDifference(), MSD_highName(), NAM_SetDifference, and SOLID.
Referenced by MSD_execNameDifference(), and MSD_lowMakeUnion().