USPDesigner: C:/USPDesig/INC/sethmain.h File Reference
C:/USPDesig/INC/sethmain.h File Reference
#include <stdio.h>
Classes
struct _nbr
struct _nb
struct _sectors
struct _sonvv
struct _sonvf
struct sff
Defines
#define EXT extern
#define MAXONVERTICES 200
#define MAXSECTORS 50
#define MAXEDGESFORVERTEX 50
#define MAXNULLEDGES 100
#define MAXNULLFACES 50
#define MAXENDEDGES 50
#define MAXENDS 30
#define USP_IN 1
#define USP_ON 0
#define USP_OUT -1
#define USP_UNION 1
#define USP_INTERSECT 2
#define USP_DIFFERENCE 3
#define MAXSHELLS 50
Typedefs
typedef int Id
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
typedef struct _nbr NBR
typedef struct _nb NB
typedef struct _sectors SECTORS
typedef struct _sonvv SONVV
typedef struct _sonvf SONVF
typedef struct sff SFF
Functions
void MSD_execNameDifference (void)
void MSD_highNameDifference (char *name1, char *name2, char *name)
void MSD_execDifference (void)
Id MSD_highDifference (Id sn1, Id sn2)
void MSD_execNameIntersection (void)
void MSD_highNameIntersection (char *name1, char *name2, char *name)
void MSD_execIntersection (void)
Id MSD_highIntersection (Id sn1, Id sn2)
int MSD_lowSetOp (SPTYPE a, SPTYPE b, Id sn, SPTYPE *res, int op)
int MSD_lowSetOpInitiate0 (void)
void MSD_lowSetOpTerminate0 (void)
int MSD_lowSetOpInitiate1 (void)
void MSD_lowSetOpTerminate1 (void)
int MSD_lowSetOpInitiate2 (void)
void MSD_lowSetOpTerminate2 (void)
int MSD_lowSetOpInitiate3 (void)
void MSD_lowSetOpTerminate3 (void)
int MSD_lowSetOpInitiate4 (void)
void MSD_lowSetOpTerminate4 (void)
int MSD_lowSetOpInitiate5 (void)
void MSD_lowSetOpTerminate5 (void)
void MSD_lowSetOpClassify (int op)
void MSD_lowVtxVtxClassify (VPTYPE va, VPTYPE vb, int op)
void MSD_lowVtxFacClassify (VPTYPE v, FPTYPE f, int op, int flag)
void MSD_lowSetOpVFGetNeighborhood (VPTYPE v, vector SP)
void MSD_lowSetOpVFReclassifyOnSectors (vector SP, int op, int flag)
void MSD_lowSetOpVFReclassifyOnEdges (void)
void MSD_lowSetOpVFInsertNullEdges (FPTYPE f, int flag)
void MSD_lowSetOpMakeRing (FPTYPE f, double x, double y, double z, int flag)
void MSD_lowSetOpConnect (void)
void MSD_lowSetOpJoin (HPTYPE, HPTYPE)
int MSD_lowSetOpCanJoin (HPTYPE, HPTYPE, HPTYPE *, HPTYPE *)
void MSD_lowSetOpSortNullEdges (void)
int MSD_lowSetOpGreater (int i, int j)
void MSD_lowSetOpSwap (int i, int j)
int MSD_lowSetOpIsLooseA (HPTYPE he)
int MSD_lowSetOpIsLooseB (HPTYPE he)
void MSD_lowSetOpCutA (HPTYPE he)
void MSD_lowSetOpCutB (HPTYPE he)
int MSD_lowSetOpGetNextNullEdge (EPTYPE *, EPTYPE *)
int MSD_lowSetOpNeighbor (HPTYPE, HPTYPE)
SPTYPE MSD_lowSetOpFinish (SPTYPE a, SPTYPE b, Id sn, int op)
void MSD_lowSetOpGenerate (SPTYPE a, SPTYPE b)
void MSD_lowSetOpProcessEdge (EPTYPE, FPTYPE, DPTYPE, int BvxA)
void MSD_lowSetOpDoGenerate (EPTYPE, FPTYPE, int BvxA)
void MSD_lowSetOpDoVertexOnFace (VPTYPE, FPTYPE, int BvxA)
void MSD_lowSetOpAddSOVF (VPTYPE, FPTYPE, int flag)
void MSD_lowSetOpAddSOVV (VPTYPE, VPTYPE, int flag)
int MSD_lowSetOpFacPntContainment (FPTYPE, real x, real y, real z)
void MSD_lowSetOpVVGetNeighborhood (VPTYPE, VPTYPE)
int MSD_lowSetOpNbaPreProcess (VPTYPE)
int MSD_lowSetOpNbbPreProcess (VPTYPE)
int MSD_lowSetOpSectorTest (int i, int j)
int MSD_lowSetOpSectorWithin (vector dir, vector ref1, vector ref2, vector ref12)
int MSD_lowSetOpOverlap (HPTYPE, HPTYPE)
int MSD_lowSetOpSectorOverlap (HPTYPE, HPTYPE)
void MSD_lowSetOpInside (HPTYPE he, vector in)
void MSD_lowSetOpVVInsertNullEdges (int)
int MSD_lowSetOpGetOrient (HPTYPE, HPTYPE, HPTYPE)
int MSD_lowSetOpSectorWide (HPTYPE, int)
int MSD_lowSetOpConvexEdge (HPTYPE)
void MSD_lowSetOpSepar1 (HPTYPE, HPTYPE, int)
void MSD_lowSetOpSepar2 (HPTYPE, int, int, int)
int MSD_lowSetOpStrutNullEdge (HPTYPE)
int MSD_lowSetOpNullEdge (HPTYPE)
void MSD_lowSetOpVVReclassifyEdges (int op)
void MSD_lowSetOpVVReclassifySectors (int op)
void MSD_execNameUnion (void)
void MSD_highNameUnion (char *name1, char *name2, char *name)
void MSD_execUnion (void)
Id MSD_highUnion (Id sn1, Id sn2)
void trace_he (HPTYPE he)
void trace_e (EPTYPE e)
void trace_nbr (int x)
void trace_nba (int x)
void trace_nbb (int x)
Variables
EXT NB nbb [MAXSECTORS]
EXT NB nba [MAXSECTORS]
EXT SECTORS sectors [MAXSECTORS]
EXT int nnba
EXT int nnbb
EXT int nsectors
EXT NBR nbr [MAXEDGESFORVERTEX]
EXT int nnbr
EXT SFF shellposa [MAXSHELLS]
EXT SFF shellposb [MAXSHELLS]
EXT int contshella
EXT int contshellb
EXT SONVV sonvv [MAXONVERTICES]
EXT SONVF sonva [MAXONVERTICES]
EXT SONVF sonvb [MAXONVERTICES]
EXT int nvvtx
EXT int nvtxa
EXT int nvtxb
EXT EPTYPE sonea [MAXNULLEDGES]
EXT EPTYPE soneb [MAXNULLEDGES]
EXT FPTYPE sonfa [MAXNULLFACES *2]
EXT FPTYPE sonfb [MAXNULLFACES *2]
EXT int nedga
EXT int nedgb
EXT int nfaca
EXT int nfacb
EXT HPTYPE endsa [MAXENDS]
EXT HPTYPE endsb [MAXENDS]
EXT int nenda
EXT int nendb
EXT int null_pnta
EXT int null_pntb
Define Documentation
#define EXT extern
Definition at line 49 of file sethmain.h.
#define MAXEDGESFORVERTEX 50
Definition at line 110 of file sethmain.h.
Referenced by MSD_lowGetNeighborhood(), and MSD_lowSetOpVFGetNeighborhood().
#define MAXENDEDGES 50
Definition at line 113 of file sethmain.h.
#define MAXENDS 30
Definition at line 114 of file sethmain.h.
Referenced by MSD_lowSetOpCanJoin().
#define MAXNULLEDGES 100
Definition at line 111 of file sethmain.h.
Referenced by MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), and MSD_lowSetOpVFInsertNullEdges().
#define MAXNULLFACES 50
Definition at line 112 of file sethmain.h.
Referenced by MSD_lowSetOpCutA(), and MSD_lowSetOpCutB().
#define MAXONVERTICES 200
Definition at line 108 of file sethmain.h.
Referenced by MSD_lowSetOpAddSOVF(), and MSD_lowSetOpAddSOVV().
#define MAXSECTORS 50
Definition at line 109 of file sethmain.h.
Referenced by MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), and MSD_lowSetOpVVGetNeighborhood().
#define MAXSHELLS 50
Definition at line 183 of file sethmain.h.
#define USP_DIFFERENCE 3
Definition at line 127 of file sethmain.h.
Referenced by MSD_highDifference(), MSD_lowSetOpFinish(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowVtxFacClassify(), and MSD_lowVtxVtxClassify().
#define USP_IN 1
Definition at line 121 of file sethmain.h.
Referenced by MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVInsertNullEdges(), MSD_lowSetOpVVReclassifyEdges(), and MSD_lowSetOpVVReclassifySectors().
#define USP_INTERSECT 2
Definition at line 126 of file sethmain.h.
Referenced by MSD_highIntersection(), MSD_lowSetOpFinish(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowVtxFacClassify(), and MSD_lowVtxVtxClassify().
#define USP_ON 0
Definition at line 122 of file sethmain.h.
Referenced by MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVReclassifyEdges(), and MSD_lowSetOpVVReclassifySectors().
#define USP_OUT -1
Definition at line 123 of file sethmain.h.
Referenced by MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVInsertNullEdges(), MSD_lowSetOpVVReclassifyEdges(), and MSD_lowSetOpVVReclassifySectors().
#define USP_UNION 1
Definition at line 125 of file sethmain.h.
Referenced by MSD_highUnion(), MSD_lowSetOpFinish(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowSetOpVVReclassifySectors(), MSD_lowVtxFacClassify(), and MSD_lowVtxVtxClassify().
Typedef Documentation
typedef struct edge ETYPE
Definition at line 78 of file sethmain.h.
typedef struct face FTYPE
Definition at line 70 of file sethmain.h.
typedef struct halfedge HTYPE
Definition at line 82 of file sethmain.h.
typedef int Id
Definition at line 58 of file sethmain.h.
typedef struct loop LTYPE
Definition at line 74 of file sethmain.h.
typedef struct _nb NB
Definition at line 134 of file sethmain.h.
typedef struct _nbr NBR
Definition at line 133 of file sethmain.h.
typedef struct _sectors SECTORS
Definition at line 135 of file sethmain.h.
typedef struct sff SFF
Definition at line 185 of file sethmain.h.
typedef struct _sonvf SONVF
Definition at line 137 of file sethmain.h.
typedef struct _sonvv SONVV
Definition at line 136 of file sethmain.h.
typedef struct solid STYPE
Definition at line 66 of file sethmain.h.
typedef real vector[4]
Definition at line 62 of file sethmain.h.
typedef struct vertex VTYPE
Definition at line 86 of file sethmain.h.
Function Documentation
void MSD_execDifference (void)
void MSD_execIntersection (void)
void MSD_execNameDifference (void)
Definition at line 55 of file setdiffe.cpp.
References lineins(), MSD_highNameDifference(), and restbuf.
void MSD_execNameIntersection (void)
Definition at line 55 of file setinter.cpp.
References lineins(), MSD_highNameIntersection(), and restbuf.
void MSD_execNameUnion (void)
Definition at line 55 of file setunion.cpp.
References lineins(), MSD_highNameUnion(), and restbuf.
void MSD_execUnion (void)
Id MSD_highDifference (Id sn1, Id sn2)
Definition at line 114 of file setdiffe.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetDifference, SNIL, SPTYPE, SUCCESS, and USP_DIFFERENCE.
Referenced by MSD_highNameDifference().
Id MSD_highIntersection (Id sn1, Id sn2)
Definition at line 114 of file setinter.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetIntersection, SNIL, SPTYPE, SUCCESS, and USP_INTERSECT.
Referenced by MSD_highNameIntersection().
void MSD_highNameDifference (char * name1, char * name2, char * name)
Definition at line 70 of file setdiffe.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highDifference(), MSD_highName(), NAM_SetDifference, and SOLID.
Referenced by MSD_execNameDifference(), and MSD_lowMakeUnion().
void MSD_highNameIntersection (char * name1, char * name2, char * name)
Definition at line 70 of file setinter.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highIntersection(), MSD_highName(), NAM_SetIntersection, and SOLID.
Referenced by MSD_execNameIntersection().
void MSD_highNameUnion (char * name1, char * name2, char * name)
Definition at line 70 of file setunion.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highName(), MSD_highUnion(), NAM_SetUnion, and SOLID.
Referenced by MSD_execNameUnion(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
Id MSD_highUnion (Id sn1, Id sn2)
Definition at line 114 of file setunion.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetUnion, SNIL, SPTYPE, SUCCESS, and USP_UNION.
Referenced by MSD_highNameUnion().
int MSD_lowSetOp (SPTYPE a, SPTYPE b, Id sn, SPTYPE * res, int op)
Definition at line 59 of file setomain.cpp.
References AllShellsSolid, ArqVirtualMemory, AXIS, close_v_array(), CommandCount, contshella, contshellb, DPTYPE, ERROR, FALSE, GROUP, maxd, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxShellId(), MSD_getMaxVertexId(), MSD_lowListSolid(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSetOpClassify(), MSD_lowSetOpConnect(), MSD_lowSetOpFinish(), MSD_lowSetOpGenerate(), MSD_lowSetOpInitiate0(), MSD_lowSetOpInitiate1(), MSD_lowSetOpInitiate2(), MSD_lowSetOpTerminate0(), MSD_lowSetOpTerminate5(), MSD_lowSoftRemove(), MSD_lowSolVtxContainment(), nedga, nfaca, nfacb, NIL, NumRecordsVM, open_v_array(), SET01VirtualArray, SetASheShell, SetASheSign, SetBSheShell, SetBSheSign, SheShellNo, SheSVerts, SNIL, sola, solb, SUCCESS, trace, TRUE, VerNextV, VirtualMemoryBlock, VNIL, and VPTYPE.
Referenced by MSD_highDifference(), MSD_highIntersection(), and MSD_highUnion().
void MSD_lowSetOpAddSOVF (VPTYPE , FPTYPE , int flag)
Definition at line 351 of file setopgen.cpp.
References MAXONVERTICES, nvtxa, nvtxb, SetAVFf, SetAVFv, SetBVFf, SetBVFv, trace, trace_f, and trace_v.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
void MSD_lowSetOpAddSOVV (VPTYPE , VPTYPE , int flag)
Definition at line 438 of file setopgen.cpp.
References MAXONVERTICES, nvvtx, SetVVva, SetVVvb, trace, and trace_v.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
int MSD_lowSetOpCanJoin (HPTYPE , HPTYPE , HPTYPE * , HPTYPE *)
Definition at line 272 of file setopcon.cpp.
References HNIL, MAXENDS, MSD_lowSetOpNeighbor(), nenda, nendb, SetEndsa, SetEndsb, trace, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpClassify (int op)
Definition at line 56 of file setopcls.cpp.
References ERROR, VACB::file, MSD_lowSetOpInitiate3(), MSD_lowSetOpInitiate4(), MSD_lowSetOpInitiate5(), MSD_lowSetOpTerminate1(), MSD_lowSetOpTerminate2(), MSD_lowSetOpTerminate3(), MSD_lowSetOpTerminate4(), MSD_lowVtxFacClassify(), MSD_lowVtxVtxClassify(), nedga, nedgb, NIL, nvtxa, nvtxb, nvvtx, SET03VirtualArray, SetAVFf, SetAVFv, SetBVFf, SetBVFv, SetSonea, SetSoneb, SetVVva, SetVVvb, trace, and trace_e().
Referenced by MSD_lowSetOp().
void MSD_lowSetOpConnect (void)
Definition at line 62 of file setopcon.cpp.
References EdgHe1, EdgHe2, EPTYPE, FacFeq, FacFLOut, HNIL, HPTYPE, mate, MSD_lowFaceEq(), MSD_lowListFace(), MSD_lowSetOpCanJoin(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpIsLooseA(), MSD_lowSetOpIsLooseB(), MSD_lowSetOpJoin(), MSD_lowSetOpSortNullEdges(), nenda, nendb, nfaca, nfacb, SetSonfa, SetSonfb, trace, trace_f, and veccopy().
Referenced by MSD_lowSetOp().
int MSD_lowSetOpConvexEdge (HPTYPE)
Definition at line 273 of file setsinsn.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_lowSetOpNullEdge(), veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowSetOpGetOrient().
void MSD_lowSetOpCutA (HPTYPE he)
Definition at line 427 of file setopcon.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MAXNULLFACES, MSD_lowKEF(), MSD_lowKEMR(), nfaca, SetSonfa, trace, trace_f, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpCutB (HPTYPE he)
Definition at line 467 of file setopcon.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MAXNULLFACES, MSD_lowKEF(), MSD_lowKEMR(), nfacb, SetSonfb, trace, trace_f, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpDoGenerate (EPTYPE , FPTYPE , int BvxA)
Definition at line 188 of file setopgen.cpp.
References comp(), EdgHe1, EdgHe2, EPS, FacBox, FacFeq, FacFShell, HalEdg, HalNxt, HalPrv, HalVtx, hithe, hitvertex, mate, maxv, MSD_lowDistancePlanePoint(), MSD_lowMEV(), MSD_lowSetOpAddSOVF(), MSD_lowSetOpAddSOVV(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpFacPntContainment(), MSD_lowSetOpProcessEdge(), MSD_lowVertexInBox(), trace, trace_e(), trace_f, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpProcessEdge().
void MSD_lowSetOpDoVertexOnFace (VPTYPE , FPTYPE , int BvxA)
Definition at line 290 of file setopgen.cpp.
References FacBox, HalNxt, HalVtx, hithe, hitvertex, mate, maxv, MSD_lowFacVtxContainment(), MSD_lowMEV(), MSD_lowSetOpAddSOVF(), MSD_lowSetOpAddSOVV(), MSD_lowVertexInBox(), trace, and VerVCoord.
Referenced by MSD_lowSetOpDoGenerate().
int MSD_lowSetOpFacPntContainment (FPTYPE , real x, real y, real z)
Definition at line 528 of file setopgen.cpp.
References MSD_getMemVirtual(), MSD_lowFacVtxContainment(), MSD_putMemVirtual(), vertex::vcoord, VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpDoGenerate().
SPTYPE MSD_lowSetOpFinish (SPTYPE a, SPTYPE b, Id sn, int op)
Definition at line 148 of file setopfin.cpp.
References AllShellsSolid, contshella, contshellb, DPTYPE, FacFeq, FacFLOut, FacFShell, InnerLoop, LPTYPE, maxd, maxf, MSD_lowCheckSetOpFinish(), MSD_lowDetach(), MSD_lowFaceEq(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowLoopGlue(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowRevert(), nfaca, nfacb, SetASheShell, SetASheSign, SetBSheShell, SetBSheSign, SetSonfa, SetSonfb, SheShellNo, SNIL, SPTYPE, trace, trace_f, USP_DIFFERENCE, USP_INTERSECT, and USP_UNION.
Referenced by MSD_lowSetOp().
void MSD_lowSetOpGenerate (SPTYPE a, SPTYPE b)
Definition at line 57 of file setopgen.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EPTYPE, MSD_lowBoxBoxIntersection(), MSD_lowEdgeBox(), MSD_lowSetOpProcessEdge(), nvtxa, nvtxb, nvvtx, SetAVFf, SetAVFv, SetBVFf, SetBVFv, SetVVva, SetVVvb, SheBox, SheSFaces, SolBox, SolSShells, trace, trace_f, and trace_v.
Referenced by MSD_lowSetOp().
int MSD_lowSetOpGetNextNullEdge (EPTYPE * , EPTYPE *)
Definition at line 507 of file setopcon.cpp.
References EdgHe1, ENIL, FALSE, nedga, nedgb, null_pnta, null_pntb, SetSonea, SetSoneb, trace, trace_he(), and TRUE.
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpGetOrient (HPTYPE , HPTYPE , HPTYPE)
Definition at line 192 of file setsinsn.cpp.
References HalNxt, HPTYPE, mate, MSD_lowSetOpConvexEdge(), and MSD_lowSetOpSectorWide().
Referenced by MSD_lowSetOpVVInsertNullEdges().
int MSD_lowSetOpGreater (int i, int j)
Definition at line 358 of file setopcon.cpp.
References comp(), EdgHe1, EPS, HalVtx, SetSonea, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpSortNullEdges().
int MSD_lowSetOpInitiate0 (void)
Referenced by MSD_lowSetOp().
int MSD_lowSetOpInitiate1 (void)
Referenced by MSD_lowSetOp().
int MSD_lowSetOpInitiate2 (void)
Referenced by MSD_lowSetOp().
int MSD_lowSetOpInitiate3 (void)
Referenced by MSD_lowSetOpClassify().
int MSD_lowSetOpInitiate4 (void)
Referenced by MSD_lowSetOpClassify().
int MSD_lowSetOpInitiate5 (void)
Referenced by MSD_lowSetOpClassify().
void MSD_lowSetOpInside (HPTYPE he, vector in)
Definition at line 466 of file setopget.cpp.
References cross(), FacFLOut, HalNxt, HalVtx, HalWLoop, LooLFace, MSD_lowFaceEq(), veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_lowSetOpNbaPreProcess(), and MSD_lowSetOpNbbPreProcess().
int MSD_lowSetOpIsLooseA (HPTYPE he)
Definition at line 399 of file setopcon.cpp.
References nenda, and SetEndsa.
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpIsLooseB (HPTYPE he)
Definition at line 413 of file setopcon.cpp.
References nendb, and SetEndsb.
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpJoin (HPTYPE , HPTYPE)
Definition at line 177 of file setopcon.cpp.
References EdgHe1, FacFLoops, FacFLOut, FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalWLoop, LNIL, LooLFace, LooNextL, maxf, MSD_lowAllRingMove(), MSD_lowMEF(), MSD_lowMEKR(), trace, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpMakeRing (FPTYPE f, double x, double y, double z, int flag)
Definition at line 540 of file setopcls.cpp.
References FacFLOut, HalEdg, HalPrv, HPTYPE, LooLEdg, MAXNULLEDGES, maxv, MSD_lowKEMR(), MSD_lowMEV(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), and trace_he().
Referenced by MSD_lowSetOpVFInsertNullEdges().
int MSD_lowSetOpNbaPreProcess (VPTYPE)
Definition at line 186 of file setopget.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MAXSECTORS, MSD_lowSetOpInside(), SetANB1, SetANB12, SetANB2, SetANBHe, veccopy(), vecminus(), vecnull(), vecplus(), VerVCoord, and VerVEdge.
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpNbbPreProcess (VPTYPE)
Definition at line 249 of file setopget.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MAXSECTORS, MSD_lowSetOpInside(), SetBNB1, SetBNB12, SetBNB2, SetBNBHe, veccopy(), vecminus(), vecnull(), vecplus(), VerVCoord, and VerVEdge.
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpNeighbor (HPTYPE , HPTYPE)
Definition at line 530 of file setopcon.cpp.
References EdgHe1, EdgHe2, FALSE, HalEdg, HalVtx, HalWLoop, LooLFace, and mate.
Referenced by MSD_lowSetOpCanJoin().
int MSD_lowSetOpNullEdge (HPTYPE)
Definition at line 500 of file setsinsn.cpp.
References HalNxt, HalVtx, and MSD_lowVtxVtxContainment().
Referenced by MSD_lowSetOpConvexEdge(), MSD_lowSetOpSepar1(), and MSD_lowSetOpSepar2().
int MSD_lowSetOpOverlap (HPTYPE , HPTYPE)
Definition at line 458 of file setopget.cpp.
References MSD_lowNaoUtilizado, and TRUE.
Referenced by MSD_lowSetOpSectorTest().
void MSD_lowSetOpProcessEdge (EPTYPE , FPTYPE , DPTYPE , int BvxA)
Definition at line 164 of file setopgen.cpp.
References DNIL, DPTYPE, FacBox, FacNextF, FNIL, FPTYPE, MSD_lowBoxBoxIntersection(), MSD_lowEdgeBox(), MSD_lowSetOpDoGenerate(), SheBox, SheNextD, and SheSFaces.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpGenerate().
int MSD_lowSetOpSectorOverlap (HPTYPE , HPTYPE)
int MSD_lowSetOpSectorTest (int i, int j)
Definition at line 312 of file setopget.cpp.
References cross(), EPS, FacFeq, FALSE, HalWLoop, HPTYPE, LooLFace, MSD_lowSetOpOverlap(), MSD_lowSetOpSectorWithin(), SetANB1, SetANB12, SetANB2, SetANBHe, SetBNB1, SetBNB12, SetBNB2, SetBNBHe, trace, TRUE, veccopy(), and vecnull().
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpSectorWide (HPTYPE , int)
Definition at line 255 of file setsinsn.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowSetOpGetOrient().
int MSD_lowSetOpSectorWithin (vector dir, vector ref1, vector ref2, vector ref12)
Definition at line 387 of file setopget.cpp.
References comp(), cross(), dot(), EPS, FALSE, trace, TRUE, and vecnull().
Referenced by MSD_lowSetOpSectorTest(), and MSD_lowSetOpVVGetNeighborhood().
void MSD_lowSetOpSepar1 (HPTYPE , HPTYPE , int)
Definition at line 297 of file setsinsn.cpp.
References EdgHe1, EdgHe2, HalEdg, HalPrv, HalVtx, HPTYPE, mate, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpNullEdge(), MSD_lowSetOpStrutNullEdge(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSetOpVVInsertNullEdges().
void MSD_lowSetOpSepar2 (HPTYPE , int , int , int)
Definition at line 411 of file setsinsn.cpp.
References EdgHe1, EdgHe2, HalEdg, HalPrv, HalVtx, HPTYPE, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpNullEdge(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSetOpVVInsertNullEdges().
void MSD_lowSetOpSortNullEdges (void)
Definition at line 332 of file setopcon.cpp.
References MSD_lowSetOpGreater(), MSD_lowSetOpSwap(), nedga, null_pnta, and null_pntb.
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpStrutNullEdge (HPTYPE)
Definition at line 491 of file setsinsn.cpp.
References HalNxt, HalPrv, and mate.
Referenced by MSD_lowSetOpSepar1().
void MSD_lowSetOpSwap (int i, int j)
Definition at line 387 of file setopcon.cpp.
References EPTYPE, SetSonea, and SetSoneb.
Referenced by MSD_lowSetOpSortNullEdges().
void MSD_lowSetOpTerminate0 (void)
Referenced by MSD_lowSetOp().
void MSD_lowSetOpTerminate1 (void)
Referenced by MSD_lowSetOpClassify().
void MSD_lowSetOpTerminate2 (void)
Referenced by MSD_lowSetOpClassify().
void MSD_lowSetOpTerminate3 (void)
Referenced by MSD_lowSetOpClassify().
void MSD_lowSetOpTerminate4 (void)
Referenced by MSD_lowSetOpClassify().
void MSD_lowSetOpTerminate5 (void)
Referenced by MSD_lowSetOp().
void MSD_lowSetOpVFGetNeighborhood (VPTYPE v, vector SP)
Definition at line 293 of file setopcls.cpp.
References comp(), EPS, HalNxt, HalVtx, HPTYPE, mate, MAXEDGESFORVERTEX, MSD_getMemVirtual(), MSD_lowBisector(), MSD_lowCheckWideness(), MSD_lowDistancePlanePoint(), MSD_putMemVirtual(), nnbr, SetNBRC1, SetNBRSector, veccopy(), VERTEX, VerVCoord, VerVEdge, and VPTYPE.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFInsertNullEdges (FPTYPE f, int flag)
Definition at line 450 of file setopcls.cpp.
References HalEdg, HalPrv, HalVtx, HPTYPE, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpMakeRing(), nedga, nedgb, nnbr, SetNBRC1, SetNBRSector, SetSonea, SetSoneb, trace, trace_e(), trace_he(), USP_IN, USP_OUT, and VerVCoord.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFReclassifyOnEdges (void)
Definition at line 416 of file setopcls.cpp.
References nnbr, SetNBRC1, USP_IN, USP_ON, and USP_OUT.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFReclassifyOnSectors (vector SP, int op, int flag)
Definition at line 357 of file setopcls.cpp.
References comp(), cross(), dot(), EPS, FacFeq, FPTYPE, HalWLoop, LooLFace, mate, nnbr, SetNBRC1, SetNBRSector, USP_IN, USP_OUT, and USP_UNION.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVVGetNeighborhood (VPTYPE , VPTYPE)
Definition at line 59 of file setopget.cpp.
References comp(), dot(), EPS, FacFeq, HalWLoop, HPTYPE, LooLFace, MAXSECTORS, MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWithin(), nnba, nnbb, nsectors, SetANB1, SetANB12, SetANB2, SetANBHe, SetBNB1, SetBNB12, SetBNB2, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecOnOn, SetSecs1a, SetSecs1b, SetSecs2a, SetSecs2b, trace, trace_nba(), trace_nbb(), USP_ON, USP_OUT, and veccopy().
Referenced by MSD_lowVtxVtxClassify().
void MSD_lowSetOpVVInsertNullEdges (int)
Definition at line 56 of file setsinsn.cpp.
References HNIL, HPTYPE, MSD_lowSetOpGetOrient(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), nsectors, SetANBHe, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecs1a, SetSecs1b, USP_IN, and USP_OUT.
Referenced by MSD_lowVtxVtxClassify().
void MSD_lowSetOpVVReclassifyEdges (int op)
Definition at line 51 of file setsrece.cpp.
References nnba, nnbb, nsectors, SetANBHe, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecs1a, SetSecs1b, SetSecs2a, SetSecs2b, trace, USP_DIFFERENCE, USP_IN, USP_INTERSECT, USP_ON, USP_OUT, and USP_UNION.
Referenced by MSD_lowVtxVtxClassify().
void MSD_lowSetOpVVReclassifySectors (int op)
Definition at line 51 of file setsrecs.cpp.
References FacFeq, HalWLoop, HPTYPE, LooLFace, nnba, nnbb, nsectors, SetANBHe, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecs1a, SetSecs1b, SetSecs2a, SetSecs2b, trace, USP_IN, USP_ON, USP_OUT, USP_UNION, veccopy(), and vecequal().
Referenced by MSD_lowVtxVtxClassify().
void MSD_lowVtxFacClassify (VPTYPE v, FPTYPE f, int op, int flag)
Definition at line 225 of file setopcls.cpp.
References FacFeq, MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVFReclassifyOnSectors(), nnbr, SetNBRSector, trace, trace_f, trace_he(), trace_nbr(), trace_v, USP_DIFFERENCE, USP_INTERSECT, USP_UNION, and veccopy().
Referenced by MSD_lowSetOpClassify().
void MSD_lowVtxVtxClassify (VPTYPE va, VPTYPE vb, int op)
Definition at line 172 of file setopcls.cpp.
References MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVInsertNullEdges(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowSetOpVVReclassifySectors(), nsectors, trace, trace_sec, USP_DIFFERENCE, USP_INTERSECT, and USP_UNION.
Referenced by MSD_lowSetOpClassify().
void trace_e (EPTYPE e)
Referenced by MSD_lowInsertNullEdges(), MSD_lowSetOpClassify(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSplitClassify(), and MSD_lowSplitGenerate().
void trace_he (HPTYPE he)
Referenced by MSD_lowCanJoin(), MSD_lowCut(), MSD_lowInsertNullEdges(), MSD_lowJoin(), MSD_lowSetOpCanJoin(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpJoin(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), and MSD_lowVtxFacClassify().
void trace_nba (int x)
Referenced by MSD_lowSetOpVVGetNeighborhood().
void trace_nbb (int x)
Referenced by MSD_lowSetOpVVGetNeighborhood().
void trace_nbr (int x)
Referenced by MSD_lowSplitClassify(), and MSD_lowVtxFacClassify().
Variable Documentation
EXT int contshella
Definition at line 194 of file sethmain.h.
Referenced by MSD_lowSetOp(), and MSD_lowSetOpFinish().
EXT int contshellb
Definition at line 194 of file sethmain.h.
Referenced by MSD_lowSetOp(), and MSD_lowSetOpFinish().
EXT HPTYPE endsa[MAXENDS]
Definition at line 212 of file sethmain.h.
EXT HPTYPE endsb[MAXENDS]
Definition at line 213 of file sethmain.h.
EXT NB nba[MAXSECTORS]
Definition at line 159 of file sethmain.h.
EXT NB nbb[MAXSECTORS]
Definition at line 158 of file sethmain.h.
EXT NBR nbr[MAXEDGESFORVERTEX]
Definition at line 165 of file sethmain.h.
EXT int nedga
Definition at line 208 of file sethmain.h.
Referenced by MSD_lowSetOp(), MSD_lowSetOpClassify(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpSortNullEdges(), and MSD_lowSetOpVFInsertNullEdges().
EXT int nedgb
Definition at line 208 of file sethmain.h.
Referenced by MSD_lowSetOpClassify(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), and MSD_lowSetOpVFInsertNullEdges().
EXT int nenda
Definition at line 215 of file sethmain.h.
Referenced by MSD_lowSetOpCanJoin(), MSD_lowSetOpConnect(), and MSD_lowSetOpIsLooseA().
EXT int nendb
Definition at line 215 of file sethmain.h.
Referenced by MSD_lowSetOpCanJoin(), MSD_lowSetOpConnect(), and MSD_lowSetOpIsLooseB().
EXT int nfaca
Definition at line 208 of file sethmain.h.
Referenced by MSD_lowCheckSOFBorderFace(), MSD_lowSetOp(), MSD_lowSetOpConnect(), MSD_lowSetOpCutA(), and MSD_lowSetOpFinish().
EXT int nfacb
Definition at line 208 of file sethmain.h.
Referenced by MSD_lowCheckSOFBorderFace(), MSD_lowSetOp(), MSD_lowSetOpConnect(), MSD_lowSetOpCutB(), and MSD_lowSetOpFinish().
EXT int nnba
Definition at line 162 of file sethmain.h.
Referenced by MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVReclassifyEdges(), and MSD_lowSetOpVVReclassifySectors().
EXT int nnbb
Definition at line 162 of file sethmain.h.
Referenced by MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVReclassifyEdges(), and MSD_lowSetOpVVReclassifySectors().
EXT int nnbr
Definition at line 167 of file sethmain.h.
Referenced by MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVFReclassifyOnSectors(), and MSD_lowVtxFacClassify().
EXT int nsectors
Definition at line 162 of file sethmain.h.
Referenced by MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVInsertNullEdges(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowSetOpVVReclassifySectors(), and MSD_lowVtxVtxClassify().
EXT int null_pnta
Definition at line 215 of file sethmain.h.
Referenced by MSD_lowSetOpGetNextNullEdge(), and MSD_lowSetOpSortNullEdges().
EXT int null_pntb
Definition at line 215 of file sethmain.h.
Referenced by MSD_lowSetOpGetNextNullEdge(), and MSD_lowSetOpSortNullEdges().
EXT int nvtxa
Definition at line 200 of file sethmain.h.
Referenced by MSD_lowSetOpAddSOVF(), MSD_lowSetOpClassify(), and MSD_lowSetOpGenerate().
EXT int nvtxb
Definition at line 200 of file sethmain.h.
Referenced by MSD_lowSetOpAddSOVF(), MSD_lowSetOpClassify(), and MSD_lowSetOpGenerate().
EXT int nvvtx
Definition at line 200 of file sethmain.h.
Referenced by MSD_lowSetOpAddSOVV(), MSD_lowSetOpClassify(), and MSD_lowSetOpGenerate().
EXT SECTORS sectors[MAXSECTORS]
Definition at line 160 of file sethmain.h.
EXT SFF shellposa[MAXSHELLS]
Definition at line 192 of file sethmain.h.
EXT SFF shellposb[MAXSHELLS]
Definition at line 192 of file sethmain.h.
EXT EPTYPE sonea[MAXNULLEDGES]
Definition at line 203 of file sethmain.h.
EXT EPTYPE soneb[MAXNULLEDGES]
Definition at line 204 of file sethmain.h.
EXT FPTYPE sonfa[MAXNULLFACES *2]
Definition at line 205 of file sethmain.h.
EXT FPTYPE sonfb[MAXNULLFACES *2]
Definition at line 206 of file sethmain.h.
EXT SONVF sonva[MAXONVERTICES]
Definition at line 198 of file sethmain.h.
EXT SONVF sonvb[MAXONVERTICES]
Definition at line 198 of file sethmain.h.
EXT SONVV sonvv[MAXONVERTICES]
Definition at line 197 of file sethmain.h.