USPDesigner: C:/USPDesig/SET/setinter.cpp File Reference
C:/USPDesig/SET/setinter.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "sethmain.h"
Functions
void MSD_execNameIntersection (void)
void MSD_highNameIntersection (char *name1, char *name2, char *name)
Id MSD_highIntersection (Id sn1, Id sn2)
Function Documentation
void MSD_execNameIntersection (void)
Definition at line 55 of file setinter.cpp.
References lineins(), MSD_highNameIntersection(), and restbuf.
Id MSD_highIntersection (Id sn1, Id sn2)
Definition at line 114 of file setinter.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetIntersection, SNIL, SPTYPE, SUCCESS, and USP_INTERSECT.
Referenced by MSD_highNameIntersection().
void MSD_highNameIntersection (char * name1, char * name2, char * name)
Definition at line 70 of file setinter.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highIntersection(), MSD_highName(), NAM_SetIntersection, and SOLID.
Referenced by MSD_execNameIntersection().