USPDesigner: C:/USPDesig/SET/setopcon.cpp File Reference
C:/USPDesig/SET/setopcon.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "sethmain.h"
#include "disdispl.h"
#include "gphgraph.h"
Functions
int MSD_checkBoolean (void)
void MSD_lowSetOpConnect (void)
void MSD_lowSetOpJoin (HPTYPE h1, HPTYPE h2)
int MSD_lowSetOpCanJoin (HPTYPE hea, HPTYPE heb, HPTYPE *reta, HPTYPE *retb)
void MSD_lowSetOpSortNullEdges (void)
int MSD_lowSetOpGreater (int i, int j)
void MSD_lowSetOpSwap (int i, int j)
int MSD_lowSetOpIsLooseA (HPTYPE he)
int MSD_lowSetOpIsLooseB (HPTYPE he)
void MSD_lowSetOpCutA (HPTYPE he)
void MSD_lowSetOpCutB (HPTYPE he)
int MSD_lowSetOpGetNextNullEdge (EPTYPE *nexta, EPTYPE *nextb)
int MSD_lowSetOpNeighbor (HPTYPE h1, HPTYPE h2)
Variables
SPTYPE sola
SPTYPE solb
Function Documentation
int MSD_checkBoolean (void)
int MSD_lowSetOpCanJoin (HPTYPE hea, HPTYPE heb, HPTYPE * reta, HPTYPE * retb)
Definition at line 272 of file setopcon.cpp.
References HNIL, MAXENDS, MSD_lowSetOpNeighbor(), nenda, nendb, SetEndsa, SetEndsb, trace, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpConnect (void)
Definition at line 62 of file setopcon.cpp.
References EdgHe1, EdgHe2, EPTYPE, FacFeq, FacFLOut, HNIL, HPTYPE, mate, MSD_lowFaceEq(), MSD_lowListFace(), MSD_lowSetOpCanJoin(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpIsLooseA(), MSD_lowSetOpIsLooseB(), MSD_lowSetOpJoin(), MSD_lowSetOpSortNullEdges(), nenda, nendb, nfaca, nfacb, SetSonfa, SetSonfb, trace, trace_f, and veccopy().
Referenced by MSD_lowSetOp().
void MSD_lowSetOpCutA (HPTYPE he)
Definition at line 427 of file setopcon.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MAXNULLFACES, MSD_lowKEF(), MSD_lowKEMR(), nfaca, SetSonfa, trace, trace_f, and trace_he().
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpCutB (HPTYPE he)
Definition at line 467 of file setopcon.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MAXNULLFACES, MSD_lowKEF(), MSD_lowKEMR(), nfacb, SetSonfb, trace, trace_f, and trace_he().
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpGetNextNullEdge (EPTYPE * nexta, EPTYPE * nextb)
Definition at line 507 of file setopcon.cpp.
References EdgHe1, ENIL, FALSE, nedga, nedgb, null_pnta, null_pntb, SetSonea, SetSoneb, trace, trace_he(), and TRUE.
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpGreater (int i, int j)
Definition at line 358 of file setopcon.cpp.
References comp(), EdgHe1, EPS, HalVtx, SetSonea, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpSortNullEdges().
int MSD_lowSetOpIsLooseA (HPTYPE he)
Definition at line 399 of file setopcon.cpp.
References nenda, and SetEndsa.
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpIsLooseB (HPTYPE he)
Definition at line 413 of file setopcon.cpp.
References nendb, and SetEndsb.
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpJoin (HPTYPE h1, HPTYPE h2)
Definition at line 177 of file setopcon.cpp.
References EdgHe1, FacFLoops, FacFLOut, FNIL, FPTYPE, HalEdg, HalNxt, HalPrv, HalWLoop, LNIL, LooLFace, LooNextL, maxf, MSD_lowAllRingMove(), MSD_lowMEF(), MSD_lowMEKR(), trace, and trace_he().
Referenced by MSD_lowSetOpConnect().
int MSD_lowSetOpNeighbor (HPTYPE h1, HPTYPE h2)
Definition at line 530 of file setopcon.cpp.
References EdgHe1, EdgHe2, FALSE, HalEdg, HalVtx, HalWLoop, LooLFace, and mate.
Referenced by MSD_lowSetOpCanJoin().
void MSD_lowSetOpSortNullEdges (void)
Definition at line 332 of file setopcon.cpp.
References MSD_lowSetOpGreater(), MSD_lowSetOpSwap(), nedga, null_pnta, and null_pntb.
Referenced by MSD_lowSetOpConnect().
void MSD_lowSetOpSwap (int i, int j)
Definition at line 387 of file setopcon.cpp.
References EPTYPE, SetSonea, and SetSoneb.
Referenced by MSD_lowSetOpSortNullEdges().
Variable Documentation
SPTYPE sola
Definition at line 55 of file setomain.cpp.
SPTYPE solb
Definition at line 56 of file setomain.cpp.