USPDesigner: C:/USPDesig/SET/setomain.cpp File Reference
C:/USPDesig/SET/setomain.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "lowgeome.h"
#include "eulerops.h"
#include "shpshape.h"
#include "sethmain.h"
Defines
#define _BOOLEAN_
Functions
int MSD_lowSetOp (SPTYPE a, SPTYPE b, Id sn, SPTYPE *res, int op)
Variables
int NumRecordsVM [10]
char * ArqVirtualMemory []
SPTYPE sola
SPTYPE solb
Define Documentation
#define _BOOLEAN_
Definition at line 41 of file setomain.cpp.
Function Documentation
int MSD_lowSetOp (SPTYPE a, SPTYPE b, Id sn, SPTYPE * res, int op)
Definition at line 59 of file setomain.cpp.
References AllShellsSolid, ArqVirtualMemory, AXIS, close_v_array(), CommandCount, contshella, contshellb, DPTYPE, ERROR, FALSE, GROUP, maxd, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxShellId(), MSD_getMaxVertexId(), MSD_lowListSolid(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSetOpClassify(), MSD_lowSetOpConnect(), MSD_lowSetOpFinish(), MSD_lowSetOpGenerate(), MSD_lowSetOpInitiate0(), MSD_lowSetOpInitiate1(), MSD_lowSetOpInitiate2(), MSD_lowSetOpTerminate0(), MSD_lowSetOpTerminate5(), MSD_lowSoftRemove(), MSD_lowSolVtxContainment(), nedga, nfaca, nfacb, NIL, NumRecordsVM, open_v_array(), SET01VirtualArray, SetASheShell, SetASheSign, SetBSheShell, SetBSheSign, SheShellNo, SheSVerts, SNIL, sola, solb, SUCCESS, trace, TRUE, VerNextV, VirtualMemoryBlock, VNIL, and VPTYPE.
Referenced by MSD_highDifference(), MSD_highIntersection(), and MSD_highUnion().
Variable Documentation
char* ArqVirtualMemory[]
Referenced by MSD_lowSetOp().
int NumRecordsVM[10]
Referenced by MSD_lowSetOp().
SPTYPE sola
Definition at line 55 of file setomain.cpp.
Referenced by MSD_lowSetOp().
SPTYPE solb
Definition at line 56 of file setomain.cpp.
Referenced by MSD_lowSetOp().