USPDesigner: C:/USPDesig/SET/setopcls.cpp File Reference
C:/USPDesig/SET/setopcls.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "sethmain.h"
#include "splsplit.h"
Functions
void MSD_lowSetOpClassify (int op)
void MSD_lowVtxVtxClassify (VPTYPE va, VPTYPE vb, int op)
void MSD_lowVtxFacClassify (VPTYPE v, FPTYPE f, int op, int flag)
void MSD_lowSetOpVFGetNeighborhood (VPTYPE v, vector SP)
void MSD_lowSetOpVFReclassifyOnSectors (vector SP, int op, int flag)
void MSD_lowSetOpVFReclassifyOnEdges (void)
void MSD_lowSetOpVFInsertNullEdges (FPTYPE f, int flag)
void MSD_lowSetOpMakeRing (FPTYPE f, double x, double y, double z, int flag)
Function Documentation
void MSD_lowSetOpClassify (int op)
Definition at line 56 of file setopcls.cpp.
References ERROR, VACB::file, MSD_lowSetOpInitiate3(), MSD_lowSetOpInitiate4(), MSD_lowSetOpInitiate5(), MSD_lowSetOpTerminate1(), MSD_lowSetOpTerminate2(), MSD_lowSetOpTerminate3(), MSD_lowSetOpTerminate4(), MSD_lowVtxFacClassify(), MSD_lowVtxVtxClassify(), nedga, nedgb, NIL, nvtxa, nvtxb, nvvtx, SET03VirtualArray, SetAVFf, SetAVFv, SetBVFf, SetBVFv, SetSonea, SetSoneb, SetVVva, SetVVvb, trace, and trace_e().
Referenced by MSD_lowSetOp().
void MSD_lowSetOpMakeRing (FPTYPE f, double x, double y, double z, int flag)
Definition at line 540 of file setopcls.cpp.
References FacFLOut, HalEdg, HalPrv, HPTYPE, LooLEdg, MAXNULLEDGES, maxv, MSD_lowKEMR(), MSD_lowMEV(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), and trace_he().
Referenced by MSD_lowSetOpVFInsertNullEdges().
void MSD_lowSetOpVFGetNeighborhood (VPTYPE v, vector SP)
Definition at line 293 of file setopcls.cpp.
References comp(), EPS, HalNxt, HalVtx, HPTYPE, mate, MAXEDGESFORVERTEX, MSD_getMemVirtual(), MSD_lowBisector(), MSD_lowCheckWideness(), MSD_lowDistancePlanePoint(), MSD_putMemVirtual(), nnbr, SetNBRC1, SetNBRSector, veccopy(), VERTEX, VerVCoord, VerVEdge, and VPTYPE.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFInsertNullEdges (FPTYPE f, int flag)
Definition at line 450 of file setopcls.cpp.
References HalEdg, HalPrv, HalVtx, HPTYPE, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpMakeRing(), nedga, nedgb, nnbr, SetNBRC1, SetNBRSector, SetSonea, SetSoneb, trace, trace_e(), trace_he(), USP_IN, USP_OUT, and VerVCoord.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFReclassifyOnEdges (void)
Definition at line 416 of file setopcls.cpp.
References nnbr, SetNBRC1, USP_IN, USP_ON, and USP_OUT.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowSetOpVFReclassifyOnSectors (vector SP, int op, int flag)
Definition at line 357 of file setopcls.cpp.
References comp(), cross(), dot(), EPS, FacFeq, FPTYPE, HalWLoop, LooLFace, mate, nnbr, SetNBRC1, SetNBRSector, USP_IN, USP_OUT, and USP_UNION.
Referenced by MSD_lowVtxFacClassify().
void MSD_lowVtxFacClassify (VPTYPE v, FPTYPE f, int op, int flag)
Definition at line 225 of file setopcls.cpp.
References FacFeq, MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVFReclassifyOnEdges(), MSD_lowSetOpVFReclassifyOnSectors(), nnbr, SetNBRSector, trace, trace_f, trace_he(), trace_nbr(), trace_v, USP_DIFFERENCE, USP_INTERSECT, USP_UNION, and veccopy().
Referenced by MSD_lowSetOpClassify().
void MSD_lowVtxVtxClassify (VPTYPE va, VPTYPE vb, int op)
Definition at line 172 of file setopcls.cpp.
References MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVInsertNullEdges(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowSetOpVVReclassifySectors(), nsectors, trace, trace_sec, USP_DIFFERENCE, USP_INTERSECT, and USP_UNION.
Referenced by MSD_lowSetOpClassify().