USPDesigner: C:/USPDesig/SET/setopget.cpp File Reference
C:/USPDesig/SET/setopget.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "sethmain.h"
Functions
void MSD_lowSetOpVVGetNeighborhood (VPTYPE va, VPTYPE vb)
int MSD_lowSetOpNbaPreProcess (VPTYPE v)
int MSD_lowSetOpNbbPreProcess (VPTYPE v)
int MSD_lowSetOpSectorTest (int i, int j)
int MSD_lowSetOpSectorWithin (vector dir, vector ref1, vector ref2, vector ref12)
int MSD_lowSetOpOverlap (HPTYPE he1, HPTYPE he2)
void MSD_lowSetOpInside (HPTYPE he, vector in)
Function Documentation
void MSD_lowSetOpInside (HPTYPE he, vector in)
Definition at line 466 of file setopget.cpp.
References cross(), FacFLOut, HalNxt, HalVtx, HalWLoop, LooLFace, MSD_lowFaceEq(), veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_lowSetOpNbaPreProcess(), and MSD_lowSetOpNbbPreProcess().
int MSD_lowSetOpNbaPreProcess (VPTYPE v)
Definition at line 186 of file setopget.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MAXSECTORS, MSD_lowSetOpInside(), SetANB1, SetANB12, SetANB2, SetANBHe, veccopy(), vecminus(), vecnull(), vecplus(), VerVCoord, and VerVEdge.
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpNbbPreProcess (VPTYPE v)
Definition at line 249 of file setopget.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MAXSECTORS, MSD_lowSetOpInside(), SetBNB1, SetBNB12, SetBNB2, SetBNBHe, veccopy(), vecminus(), vecnull(), vecplus(), VerVCoord, and VerVEdge.
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpOverlap (HPTYPE he1, HPTYPE he2)
Definition at line 458 of file setopget.cpp.
References MSD_lowNaoUtilizado, and TRUE.
Referenced by MSD_lowSetOpSectorTest().
int MSD_lowSetOpSectorTest (int i, int j)
Definition at line 312 of file setopget.cpp.
References cross(), EPS, FacFeq, FALSE, HalWLoop, HPTYPE, LooLFace, MSD_lowSetOpOverlap(), MSD_lowSetOpSectorWithin(), SetANB1, SetANB12, SetANB2, SetANBHe, SetBNB1, SetBNB12, SetBNB2, SetBNBHe, trace, TRUE, veccopy(), and vecnull().
Referenced by MSD_lowSetOpVVGetNeighborhood().
int MSD_lowSetOpSectorWithin (vector dir, vector ref1, vector ref2, vector ref12)
Definition at line 387 of file setopget.cpp.
References comp(), cross(), dot(), EPS, FALSE, trace, TRUE, and vecnull().
Referenced by MSD_lowSetOpSectorTest(), and MSD_lowSetOpVVGetNeighborhood().
void MSD_lowSetOpVVGetNeighborhood (VPTYPE va, VPTYPE vb)
Definition at line 59 of file setopget.cpp.
References comp(), dot(), EPS, FacFeq, HalWLoop, HPTYPE, LooLFace, MAXSECTORS, MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWithin(), nnba, nnbb, nsectors, SetANB1, SetANB12, SetANB2, SetANBHe, SetBNB1, SetBNB12, SetBNB2, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecOnOn, SetSecs1a, SetSecs1b, SetSecs2a, SetSecs2b, trace, trace_nba(), trace_nbb(), USP_ON, USP_OUT, and veccopy().
Referenced by MSD_lowVtxVtxClassify().