USPDesigner: C:/USPDesig/SET/setopfin.cpp File Reference
C:/USPDesig/SET/setopfin.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "sethmain.h"
#include "splsplit.h"
Functions
int MSD_lowCheckSOFBorderFace (FPTYPE f, int flag)
int MSD_lowCheckSOFShell (FPTYPE f, FPTYPE ff, int flag)
int MSD_lowCheckSetOpFinish (LPTYPE l, int flag)
SPTYPE MSD_lowSetOpFinish (SPTYPE a, SPTYPE b, Id sn, int op)
Function Documentation
int MSD_lowCheckSetOpFinish (LPTYPE l, int flag)
Definition at line 112 of file setopfin.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FaceBitNOK1, FacFShell, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, mate, MSD_lowCheckSOFShell(), SetFaceBitNOK1, SheSSolids, and SPTYPE.
Referenced by MSD_lowSetOpFinish().
int MSD_lowCheckSOFBorderFace (FPTYPE f, int flag)
Definition at line 52 of file setopfin.cpp.
References FALSE, nfaca, nfacb, SetSonfa, SetSonfb, and TRUE.
Referenced by MSD_lowCheckSOFShell().
int MSD_lowCheckSOFShell (FPTYPE f, FPTYPE ff, int flag)
Definition at line 74 of file setopfin.cpp.
References AllLoopsFace, FaceBitNOK1, FPTYPE, HalNxt, HalWLoop, HPTYPE, LooLEdg, LooLFace, LPTYPE, mate, MSD_lowCheckSOFBorderFace(), and SetFaceBitOK1.
Referenced by MSD_lowCheckSetOpFinish().
SPTYPE MSD_lowSetOpFinish (SPTYPE a, SPTYPE b, Id sn, int op)
Definition at line 148 of file setopfin.cpp.
References AllShellsSolid, contshella, contshellb, DPTYPE, FacFeq, FacFLOut, FacFShell, InnerLoop, LPTYPE, maxd, maxf, MSD_lowCheckSetOpFinish(), MSD_lowDetach(), MSD_lowFaceEq(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowLoopGlue(), MSD_lowMFKRH(), MSD_lowMSFKR(), MSD_lowRevert(), nfaca, nfacb, SetASheShell, SetASheSign, SetBSheShell, SetBSheSign, SetSonfa, SetSonfb, SheShellNo, SNIL, SPTYPE, trace, trace_f, USP_DIFFERENCE, USP_INTERSECT, and USP_UNION.
Referenced by MSD_lowSetOp().