USPDesigner: C:/USPDesig/SET/setopgen.cpp File Reference
C:/USPDesig/SET/setopgen.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "vectorop.h"
#include "sethmain.h"
#include "splsplit.h"
Functions
void MSD_lowSetOpGenerate (SPTYPE a, SPTYPE b)
void MSD_lowSetOpProcessEdge (EPTYPE e, FPTYPE fini, DPTYPE dini, int BvxA)
void MSD_lowSetOpDoGenerate (EPTYPE e, FPTYPE f, int BvxA)
void MSD_lowSetOpDoVertexOnFace (VPTYPE v, FPTYPE f, int BvxA)
void MSD_lowSetOpAddSOVF (VPTYPE v, FPTYPE f, int flag)
void MSD_lowSetOpAddSOVV (VPTYPE v1, VPTYPE v2, int flag)
int MSD_lowSetOpFacPntContainment (FPTYPE f, real x, real y, real z)
Function Documentation
void MSD_lowSetOpAddSOVF (VPTYPE v, FPTYPE f, int flag)
Definition at line 351 of file setopgen.cpp.
References MAXONVERTICES, nvtxa, nvtxb, SetAVFf, SetAVFv, SetBVFf, SetBVFv, trace, trace_f, and trace_v.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
void MSD_lowSetOpAddSOVV (VPTYPE v1, VPTYPE v2, int flag)
Definition at line 438 of file setopgen.cpp.
References MAXONVERTICES, nvvtx, SetVVva, SetVVvb, trace, and trace_v.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpDoVertexOnFace().
void MSD_lowSetOpDoGenerate (EPTYPE e, FPTYPE f, int BvxA)
Definition at line 188 of file setopgen.cpp.
References comp(), EdgHe1, EdgHe2, EPS, FacBox, FacFeq, FacFShell, HalEdg, HalNxt, HalPrv, HalVtx, hithe, hitvertex, mate, maxv, MSD_lowDistancePlanePoint(), MSD_lowMEV(), MSD_lowSetOpAddSOVF(), MSD_lowSetOpAddSOVV(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpFacPntContainment(), MSD_lowSetOpProcessEdge(), MSD_lowVertexInBox(), trace, trace_e(), trace_f, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpProcessEdge().
void MSD_lowSetOpDoVertexOnFace (VPTYPE v, FPTYPE f, int BvxA)
Definition at line 290 of file setopgen.cpp.
References FacBox, HalNxt, HalVtx, hithe, hitvertex, mate, maxv, MSD_lowFacVtxContainment(), MSD_lowMEV(), MSD_lowSetOpAddSOVF(), MSD_lowSetOpAddSOVV(), MSD_lowVertexInBox(), trace, and VerVCoord.
Referenced by MSD_lowSetOpDoGenerate().
int MSD_lowSetOpFacPntContainment (FPTYPE f, real x, real y, real z)
Definition at line 528 of file setopgen.cpp.
References MSD_getMemVirtual(), MSD_lowFacVtxContainment(), MSD_putMemVirtual(), vertex::vcoord, VERTEX, VerVCoord, and VPTYPE.
Referenced by MSD_lowSetOpDoGenerate().
void MSD_lowSetOpGenerate (SPTYPE a, SPTYPE b)
Definition at line 57 of file setopgen.cpp.
References AllEdgesShell, AllShellsSolid, DPTYPE, EPTYPE, MSD_lowBoxBoxIntersection(), MSD_lowEdgeBox(), MSD_lowSetOpProcessEdge(), nvtxa, nvtxb, nvvtx, SetAVFf, SetAVFv, SetBVFf, SetBVFv, SetVVva, SetVVvb, SheBox, SheSFaces, SolBox, SolSShells, trace, trace_f, and trace_v.
Referenced by MSD_lowSetOp().
void MSD_lowSetOpProcessEdge (EPTYPE e, FPTYPE fini, DPTYPE dini, int BvxA)
Definition at line 164 of file setopgen.cpp.
References DNIL, DPTYPE, FacBox, FacNextF, FNIL, FPTYPE, MSD_lowBoxBoxIntersection(), MSD_lowEdgeBox(), MSD_lowSetOpDoGenerate(), SheBox, SheNextD, and SheSFaces.
Referenced by MSD_lowSetOpDoGenerate(), and MSD_lowSetOpGenerate().