USPDesigner: C:/USPDesig/SET/setsinsn.cpp File Reference
C:/USPDesig/SET/setsinsn.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "lowgeome.h"
#include "eulerops.h"
#include "vectorop.h"
#include "sethmain.h"
Functions
void MSD_lowSetOpVVInsertNullEdges (int op)
int MSD_lowSetOpGetOrient (HPTYPE ref, HPTYPE he1, HPTYPE he2)
int MSD_lowSetOpSectorWide (HPTYPE he, int ind)
int MSD_lowSetOpConvexEdge (HPTYPE he)
void MSD_lowSetOpSepar1 (HPTYPE from, HPTYPE to, int type)
void MSD_lowSetOpSepar2 (HPTYPE he, int type, int orient, int)
int MSD_lowSetOpStrutNullEdge (HPTYPE he)
int MSD_lowSetOpNullEdge (HPTYPE he)
Function Documentation
int MSD_lowSetOpConvexEdge (HPTYPE he)
Definition at line 273 of file setsinsn.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalVtx, HalWLoop, HPTYPE, LooLFace, mate, MSD_lowSetOpNullEdge(), veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowSetOpGetOrient().
int MSD_lowSetOpGetOrient (HPTYPE ref, HPTYPE he1, HPTYPE he2)
Definition at line 192 of file setsinsn.cpp.
References HalNxt, HPTYPE, mate, MSD_lowSetOpConvexEdge(), and MSD_lowSetOpSectorWide().
Referenced by MSD_lowSetOpVVInsertNullEdges().
int MSD_lowSetOpNullEdge (HPTYPE he)
Definition at line 500 of file setsinsn.cpp.
References HalNxt, HalVtx, and MSD_lowVtxVtxContainment().
Referenced by MSD_lowSetOpConvexEdge(), MSD_lowSetOpSepar1(), and MSD_lowSetOpSepar2().
int MSD_lowSetOpSectorWide (HPTYPE he, int ind)
Definition at line 255 of file setsinsn.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowSetOpGetOrient().
void MSD_lowSetOpSepar1 (HPTYPE from, HPTYPE to, int type)
Definition at line 297 of file setsinsn.cpp.
References EdgHe1, EdgHe2, HalEdg, HalPrv, HalVtx, HPTYPE, mate, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpNullEdge(), MSD_lowSetOpStrutNullEdge(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSetOpVVInsertNullEdges().
void MSD_lowSetOpSepar2 (HPTYPE he, int type, int orient, int)
Definition at line 411 of file setsinsn.cpp.
References EdgHe1, EdgHe2, HalEdg, HalPrv, HalVtx, HPTYPE, MAXNULLEDGES, maxv, MSD_lowMEV(), MSD_lowSetOpNullEdge(), nedga, nedgb, SetSonea, SetSoneb, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSetOpVVInsertNullEdges().
int MSD_lowSetOpStrutNullEdge (HPTYPE he)
Definition at line 491 of file setsinsn.cpp.
References HalNxt, HalPrv, and mate.
Referenced by MSD_lowSetOpSepar1().
void MSD_lowSetOpVVInsertNullEdges (int op)
Definition at line 56 of file setsinsn.cpp.
References HNIL, HPTYPE, MSD_lowSetOpGetOrient(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), nsectors, SetANBHe, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecs1a, SetSecs1b, USP_IN, and USP_OUT.
Referenced by MSD_lowVtxVtxClassify().