USPDesigner: C:/USPDesig/SET/setsrecs.cpp File Reference
C:/USPDesig/SET/setsrecs.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "sethmain.h"
Functions
void MSD_lowSetOpVVReclassifySectors (int op)
Function Documentation
void MSD_lowSetOpVVReclassifySectors (int op)
Definition at line 51 of file setsrecs.cpp.
References FacFeq, HalWLoop, HPTYPE, LooLFace, nnba, nnbb, nsectors, SetANBHe, SetBNBHe, SetSecA, SetSecB, SetSecInter, SetSecs1a, SetSecs1b, SetSecs2a, SetSecs2b, trace, USP_IN, USP_ON, USP_OUT, USP_UNION, veccopy(), and vecequal().
Referenced by MSD_lowVtxVtxClassify().