USPDesigner: C:/USPDesig/SET/setunion.cpp File Reference
C:/USPDesig/SET/setunion.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "sethmain.h"
Functions
void MSD_execNameUnion (void)
void MSD_highNameUnion (char *name1, char *name2, char *name)
Id MSD_highUnion (Id sn1, Id sn2)
Function Documentation
void MSD_execNameUnion (void)
Definition at line 55 of file setunion.cpp.
References lineins(), MSD_highNameUnion(), and restbuf.
void MSD_highNameUnion (char * name1, char * name2, char * name)
Definition at line 70 of file setunion.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highName(), MSD_highUnion(), NAM_SetUnion, and SOLID.
Referenced by MSD_execNameUnion(), MSD_lowAreaProjetadaTotal(), and MSD_lowMakeUnion().
Id MSD_highUnion (Id sn1, Id sn2)
Definition at line 114 of file setunion.cpp.
References GNIL, MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowCleanSolid(), MSD_lowDisplayMonitor(), MSD_lowModifyIds(), MSD_lowSetOp(), NAM_SetUnion, SNIL, SPTYPE, SUCCESS, and USP_UNION.
Referenced by MSD_highNameUnion().