USPDesigner: C:/USPDesig/SHP/shpcylin.cpp File Reference
C:/USPDesig/SHP/shpcylin.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
Functions
void MSD_execNameMakeCylinder (void)
void MSD_highNameMakeCylinder (char *name, int n, real r, real h)
Id MSD_highMakeCylinder (int n, real r, real h)
void MSD_execNameMakeCone (void)
void MSD_highNameMakeCone (char *name, int n, real r, real h)
Id MSD_highMakeCone (int n, real r, real h)
SPTYPE MSD_lowMakeCylinder (Id sn, real rad, real h, int n)
SPTYPE MSD_lowMakeCylinder0 (Id sn, real rad, int n)
SPTYPE MSD_lowMakeCone (Id sn, real rad, real h, int n)
void MSD_lowRot90Dg (SPTYPE s)
Function Documentation
void MSD_execNameMakeCone (void)
Definition at line 133 of file shpcylin.cpp.
References lineins(), MSD_highNameMakeCone(), and restbuf.
void MSD_execNameMakeCylinder (void)
Definition at line 55 of file shpcylin.cpp.
References lineins(), MSD_highNameMakeCylinder(), and restbuf.
Id MSD_highMakeCone (int n, real r, real h)
Definition at line 185 of file shpcylin.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCone(), MSD_lowMakeCylinder0(), NAM_MakeCone, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCone(), and MSD_highNameMakeROVCone().
Id MSD_highMakeCylinder (int n, real r, real h)
Definition at line 107 of file shpcylin.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), NAM_MakeCylinder, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCirculo(), and MSD_highNameMakeCylinder().
void MSD_highNameMakeCone (char * name, int n, real r, real h)
Definition at line 150 of file shpcylin.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCone(), MSD_highName(), NAM_MakeCone, and SOLID.
Referenced by MSD_execNameMakeCone().
void MSD_highNameMakeCylinder (char * name, int n, real r, real h)
Definition at line 72 of file shpcylin.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCylinder(), MSD_highName(), NAM_MakeCylinder, and SOLID.
Referenced by MSD_execNameMakeCylinder().
SPTYPE MSD_lowMakeCone (Id sn, real rad, real h, int n)
Definition at line 272 of file shpcylin.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeFaceToPoint(), MSD_lowMakeSweep(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetFaceToPoint(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCone().
SPTYPE MSD_lowMakeCylinder (Id sn, real rad, real h, int n)
Definition at line 211 of file shpcylin.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeSweep(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCylinder().
SPTYPE MSD_lowMakeCylinder0 (Id sn, real rad, int n)
Definition at line 252 of file shpcylin.cpp.
References CommandCount, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowMakeCircle(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCone(), and MSD_highMakeCylinder().
void MSD_lowRot90Dg (SPTYPE s)
Definition at line 312 of file shpcylin.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, matident(), matrotat(), vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_lowMakeCone(), MSD_lowMakeCylinder(), and MSD_lowMakeCylinder0().