USPDesigner: C:/USPDesig/SHP/shpgeoms.cpp File Reference
C:/USPDesig/SHP/shpgeoms.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "shpshape.h"
Functions
void MSD_lowSetNormal (SPTYPE optr, int op)
void MSD_lowSetEdgeAngle (SPTYPE optr)
Function Documentation
void MSD_lowSetEdgeAngle (SPTYPE optr)
Definition at line 87 of file shpgeoms.cpp.
References AllEdgesShell, AllShellsSolid, cross(), dot(), DPTYPE, EdgAngle, EdgHe1, EdgHe2, EPTYPE, FacFeq, HalVtx, HalWLoop, LooLFace, normalize(), veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_execSetTrace(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowCleanSolid(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowSetOp(), MSD_lowSplit(), and MSD_lowTransformation().
void MSD_lowSetNormal (SPTYPE optr, int op)
Definition at line 50 of file shpgeoms.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FaceBoxNOK, FaceEqNOK, FacFeq, FacFLOut, FALSE, FPTYPE, MSD_lowFaceBox(), MSD_lowFaceEq(), MSD_lowShellBox(), MSD_lowSolidBox(), ShellBoxNOK, SolBox, SolidBoxNOK, and TRUE.
Referenced by MSD_execSetTrace(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowCleanSolid(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePolygon(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRotate(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowScale(), MSD_lowSetOp(), MSD_lowSplit(), MSD_lowTransformation(), and MSD_lowTranslate().