USPDesigner: C:/USPDesig/SHP/shpmpris.cpp File Reference
C:/USPDesig/SHP/shpmpris.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
#include "eulerops.h"
Functions
void MSD_execNameMakePrism (void)
void MSD_highNameMakePrism (char *name, int n, real h, XY *listvtx)
Id MSD_highMakePrism (int n, real h, XY *listvtx)
void MSD_execNameMakePyramid (void)
void MSD_highNameMakePyramid (char *name, int n, real h, XY *listvtx)
Id MSD_highMakePyramid (int n, real h, XY *listvtx)
char setvtpi (XY **listxy, int n)
Function Documentation
void MSD_execNameMakePrism (void)
Definition at line 52 of file shpmpris.cpp.
References lineins(), MSD_highNameMakePrism(), restbuf, and setvtpi().
void MSD_execNameMakePyramid (void)
Definition at line 137 of file shpmpris.cpp.
References lineins(), MSD_highNameMakePyramid(), restbuf, and setvtpi().
Id MSD_highMakePrism (int n, real h, XY * listvtx)
Definition at line 111 of file shpmpris.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakePrism(), MSD_lowMakePrism0(), NAM_MakePrism, SNIL, and SPTYPE.
Referenced by MSD_highNameMakePrism().
Id MSD_highMakePyramid (int n, real h, XY * listvtx)
Definition at line 196 of file shpmpris.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), NAM_MakePyramid, SNIL, and SPTYPE.
Referenced by MSD_highNameMakePiramide(), and MSD_highNameMakePyramid().
void MSD_highNameMakePrism (char * name, int n, real h, XY * listvtx)
Definition at line 73 of file shpmpris.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakePrism(), MSD_highName(), NAM_MakePrism, and SOLID.
Referenced by MSD_execNameMakePrism(), and MSD_lowMakeUnion().
void MSD_highNameMakePyramid (char * name, int n, real h, XY * listvtx)
Definition at line 158 of file shpmpris.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakePyramid(), MSD_highName(), NAM_MakePyramid, and SOLID.
Referenced by MSD_execNameMakePyramid().
char setvtpi (XY ** listxy, int n)
Definition at line 222 of file shpmpris.cpp.
References FALSE, lineins(), restbuf, TRUE, and workbuf.
Referenced by MSD_execNameMakePiramide(), MSD_execNameMakePrism(), MSD_execNameMakePyramid(), MSD_execNameMakeRevolve(), and MSD_execNameMakeSweep().