USPDesigner: C:/USPDesig/SHP/shpmrevo.cpp File Reference
C:/USPDesig/SHP/shpmrevo.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
#include "eulerops.h"
Functions
void MSD_execNameMakeRevolve (void)
void MSD_highNameMakeRevolve (char *name, int m, int n, XY *listvtx)
Id MSD_highMakeRevolve (int m, int n, XY *listvtx)
Function Documentation
void MSD_execNameMakeRevolve (void)
Definition at line 52 of file shpmrevo.cpp.
References lineins(), MSD_highNameMakeRevolve(), restbuf, and setvtpi().
Id MSD_highMakeRevolve (int m, int n, XY * listvtx)
Definition at line 109 of file shpmrevo.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeRevolve(), NAM_MakeRevolve, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeRevolve().
void MSD_highNameMakeRevolve (char * name, int m, int n, XY * listvtx)
Definition at line 72 of file shpmrevo.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeRevolve(), MSD_highName(), NAM_MakeRevolve, and SOLID.
Referenced by MSD_execNameMakeRevolve().