USPDesigner: C:/USPDesig/SHP/shppyram.cpp File Reference
C:/USPDesig/SHP/shppyram.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
Functions
SPTYPE MSD_lowMakePyramid (Id sn, XY *listvtx, real h, int n)
void MSD_lowSetFaceToPoint (FPTYPE fptr, real x, real y, real z)
Function Documentation
SPTYPE MSD_lowMakePyramid (Id sn, XY * listvtx, real h, int n)
Definition at line 50 of file shppyram.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeFaceToPoint(), MSD_lowMakePolygon(), MSD_lowMakeSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetFaceToPoint(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePyramid().
void MSD_lowSetFaceToPoint (FPTYPE fptr, real x, real y, real z)
Definition at line 92 of file shppyram.cpp.
References FacFLoops, HalNxt, HalVtx, HPTYPE, LooLEdg, and VerVCoord.
Referenced by MSD_lowMakeCone(), and MSD_lowMakePyramid().