USPDesigner: C:/USPDesig/SHP/shpprism.cpp File Reference
C:/USPDesig/SHP/shpprism.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
Functions
SPTYPE MSD_lowMakePrism (Id sn, XY *listvtx, real h, int n)
int MSD_lowMakeSweep (FPTYPE fac, real dx, real dy, real dz)
Function Documentation
SPTYPE MSD_lowMakePrism (Id sn, XY * listvtx, real h, int n)
Definition at line 51 of file shpprism.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakePolygon(), MSD_lowMakeSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePrism().
int MSD_lowMakeSweep (FPTYPE fac, real dx, real dy, real dz)
Definition at line 94 of file shpprism.cpp.
References AllLoopsFace, FacFShell, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LPTYPE, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), SheSSolids, SUCCESS, VerVCoord, and VPTYPE.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCylinder(), MSD_lowMakePrism(), and MSD_lowMakePyramid().