USPDesigner: C:/USPDesig/SHP/shppris0.cpp File Reference
C:/USPDesig/SHP/shppris0.cpp File Reference
#include <stdio.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "shpshape.h"
Functions
SPTYPE MSD_lowMakePrism0 (Id sn, XY *listvtx, int n, int pln)
SPTYPE MSD_lowMakePolygon (Id sn, XY *listvtx, int n, int pln)
Function Documentation
SPTYPE MSD_lowMakePolygon (Id sn, XY * listvtx, int n, int pln)
Definition at line 69 of file shppris0.cpp.
References ERROR, maxd, maxf, maxv, MSD_highMEF(), MSD_highMEV(), MSD_lowHardRemove(), MSD_lowMVSF(), MSD_lowSetNormal(), SNIL, SPTYPE, TRUE, XY::x, and XY::y.
Referenced by MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), and MSD_lowMakeSWEEP().
SPTYPE MSD_lowMakePrism0 (Id sn, XY * listvtx, int n, int pln)
Definition at line 49 of file shppris0.cpp.
References CommandCount, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowMakePolygon(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePrism(), and MSD_highMakePyramid().