USPDesigner: C:/USPDesig/SHP/shprevol.cpp File Reference
C:/USPDesig/SHP/shprevol.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
Functions
SPTYPE MSD_lowMakeRevolve (Id sn, XY *listvtx, int m, int n)
char MSD_lowMakeRotationalSweep (SPTYPE s, int nfaces, int axs, int pln, vector vect)
void MSD_lowMakeFaceToPoint (FPTYPE f)
int MSD_lowMakeOpenRSweep (SPTYPE s, int pln)
HPTYPE MSD_lowTouchAxis (HPTYPE eptr, int pln)
HPTYPE MSD_lowTouchWire (HPTYPE eptr, int *cut, int pln)
Variables
FILE * trace
Function Documentation
void MSD_lowMakeFaceToPoint (FPTYPE f)
Definition at line 213 of file shprevol.cpp.
References AllLoopsFace, ENIL, FacFeq, FacFLoops, FacFLOut, getdrop(), HalEdg, HalNxt, HalVtx, HPTYPE, InnerLoop, LooLEdg, LPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), and MSD_lowLooVtxContainment().
Referenced by MSD_lowCleanSolid(), MSD_lowMakeCone(), MSD_lowMakePyramid(), and MSD_lowMakeRotationalSweep().
int MSD_lowMakeOpenRSweep (SPTYPE s, int pln)
Definition at line 266 of file shprevol.cpp.
References comp(), EPS, FacFLoops, FacNextF, FNIL, HalNxt, HalPrv, HalVtx, HNIL, HPTYPE, LooLEdg, mate, maxv, MSD_getMaxVertexId(), MSD_lowKEF(), MSD_lowMEV(), MSD_lowTouchAxis(), SheSFaces, SolSShells, and VerVCoord.
Referenced by MSD_lowMakeRotationalSweep().
SPTYPE MSD_lowMakeRevolve (Id sn, XY * listvtx, int m, int n)
Definition at line 58 of file shprevol.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakePolygon(), MSD_lowMakeRotationalSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeRevolve().
char MSD_lowMakeRotationalSweep (SPTYPE s, int nfaces, int axs, int pln, vector vect)
Definition at line 112 of file shprevol.cpp.
References comp(), dot(), EPS, ERROR, FacFeq, FacFLoops, FPTYPE, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LooLEdg, LooLFace, mate, matident(), matrotat(), maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowFaceEq(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), MSD_lowMakeOpenRSweep(), MSD_lowMEF(), MSD_lowMEV(), MSD_lowTouchWire(), SheSFaces, SolSShells, SUCCESS, vecmult(), and VerVCoord.
Referenced by MSD_lowMakeRevolve(), MSD_lowMakeSphere(), and MSD_lowMakeTorus().
HPTYPE MSD_lowTouchAxis (HPTYPE eptr, int pln)
Definition at line 302 of file shprevol.cpp.
References comp(), EPS, HalNxt, HalVtx, HNIL, HPTYPE, and VerVCoord.
Referenced by MSD_lowMakeOpenRSweep().
HPTYPE MSD_lowTouchWire (HPTYPE eptr, int * cut, int pln)
Definition at line 317 of file shprevol.cpp.
References comp(), EPS, HalNxt, HalPrv, HalVtx, mate, MSD_lowKEV(), and VerVCoord.
Referenced by MSD_lowMakeRotationalSweep().
Variable Documentation
FILE* trace
Referenced by MSD_lowAddSplitOnVertex(), MSD_lowCanJoin(), MSD_lowCut(), MSD_lowInsertNullEdges(), MSD_lowJoin(), MSD_lowMSFKR(), MSD_lowSetOp(), MSD_lowSetOpAddSOVF(), MSD_lowSetOpAddSOVV(), MSD_lowSetOpCanJoin(), MSD_lowSetOpClassify(), MSD_lowSetOpConnect(), MSD_lowSetOpCutA(), MSD_lowSetOpCutB(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpDoVertexOnFace(), MSD_lowSetOpFinish(), MSD_lowSetOpGenerate(), MSD_lowSetOpGetNextNullEdge(), MSD_lowSetOpJoin(), MSD_lowSetOpMakeRing(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWithin(), MSD_lowSetOpSepar1(), MSD_lowSetOpSepar2(), MSD_lowSetOpVFInsertNullEdges(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVReclassifyEdges(), MSD_lowSetOpVVReclassifySectors(), MSD_lowSplit(), MSD_lowSplitClassify(), MSD_lowSplitConnect(), MSD_lowSplitFinish(), MSD_lowSplitGenerate(), MSD_lowVtxFacClassify(), and MSD_lowVtxVtxClassify().