USPDesigner: C:/USPDesig/SHP/shpspher.cpp File Reference
C:/USPDesig/SHP/shpspher.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
Functions
void MSD_execNameMakeSphere (void)
void MSD_highNameMakeSphere (char *name, int n, real r)
Id MSD_highMakeSphere (int n, real r)
SPTYPE MSD_lowMakeSphere (Id sn, real r, int nver, int nhor)
char MSD_lowMakeArc (Id s, Id f, Id v, real cx, real cz, real rad, real h, real phi1, real phi2, int n)
SPTYPE MSD_lowMakeCircle (Id sn, real cx, real cz, real rad, real h, int n)
Function Documentation
void MSD_execNameMakeSphere (void)
Definition at line 53 of file shpspher.cpp.
References lineins(), MSD_highNameMakeSphere(), and restbuf.
Id MSD_highMakeSphere (int n, real r)
Definition at line 104 of file shpspher.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeSphere(), NAM_MakeSphere, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeEsfera(), and MSD_highNameMakeSphere().
void MSD_highNameMakeSphere (char * name, int n, real r)
Definition at line 70 of file shpspher.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeSphere(), MSD_highName(), NAM_MakeSphere, and SOLID.
Referenced by MSD_execNameMakeSphere().
char MSD_lowMakeArc (Id s, Id f, Id v, real cx, real cz, real rad, real h, real phi1, real phi2, int n)
Definition at line 170 of file shpspher.cpp.
References ERROR, maxv, MSD_getMaxVertexId(), MSD_getSolid(), MSD_highMEV(), PI, and SUCCESS.
Referenced by MSD_lowMakeCircle(), and MSD_lowMakeSphere().
SPTYPE MSD_lowMakeCircle (Id sn, real cx, real cz, real rad, real h, int n)
Definition at line 194 of file shpspher.cpp.
References ERROR, maxd, maxf, maxv, MSD_highMEF(), MSD_lowHardRemove(), MSD_lowMakeArc(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_lowMakeCone(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), and MSD_lowMakeTorus().
SPTYPE MSD_lowMakeSphere (Id sn, real r, int nver, int nhor)
Definition at line 122 of file shpspher.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeArc(), MSD_lowMakeRotationalSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeSphere().