USPDesigner: C:/USPDesig/INC/shpshape.h File Reference
C:/USPDesig/INC/shpshape.h File Reference
Classes
struct XY
Defines
#define EXTERN extern
Typedefs
typedef int Id
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
Functions
void MSD_execNameMakeCylinder (void)
void MSD_highNameMakeCylinder (char *name, int n, real r, real h)
void MSD_execMakeCylinder (void)
Id MSD_highMakeCylinder (int n, real r, real h)
void MSD_execNameMakeCone (void)
void MSD_highNameMakeCone (char *name, int n, real r, real h)
void MSD_execMakeCone (void)
Id MSD_highMakeCone (int n, real r, real h)
SPTYPE MSD_lowMakeCylinder (Id sn, real rad, real h, int n)
SPTYPE MSD_lowMakeCylinder0 (Id sn, real rad, int n)
SPTYPE MSD_lowMakeCone (Id sn, real rad, real h, int n)
void MSD_lowRot90Dg (SPTYPE s)
void MSD_lowSetNormal (SPTYPE optr, int op)
void MSD_lowSetEdgeAngle (SPTYPE optr)
void MSD_execNameMakePrism (void)
void MSD_highNameMakePrism (char *, int, real, XY *)
void MSD_execMakePrism (void)
Id MSD_highMakePrism (int, real, XY *)
void MSD_execNameMakePyramid (void)
void MSD_highNameMakePyramid (char *, int, real, XY *)
void MSD_execMakePyramid (void)
Id MSD_highMakePyramid (int, real, XY *)
char setvtpi (XY **, int)
void MSD_execNameMakeRevolve (void)
void MSD_highNameMakeRevolve (char *, int, int, XY *)
void MSD_execMakeRevolve (void)
Id MSD_highMakeRevolve (int, int, XY *)
SPTYPE MSD_lowMakePrism0 (Id sn, XY *listvtx, int n, int pln)
SPTYPE MSD_lowMakePolygon (Id sn, XY *listvtx, int n, int pln)
SPTYPE MSD_lowMakePrism (Id sn, XY *listvtx, real h, int n)
int MSD_lowMakeSweep (FPTYPE fac, real dx, real dy, real dz)
SPTYPE MSD_lowMakePyramid (Id sn, XY *listvtx, real h, int n)
void MSD_lowSetFaceToPoint (FPTYPE fptr, real x, real y, real z)
SPTYPE MSD_lowMakeRevolve (Id sn, XY *listvtx, int m, int n)
char MSD_lowMakeRotationalSweep (SPTYPE s, int nfaces, int axs, int pln, vector vect)
void MSD_lowMakeFaceToPoint (FPTYPE f)
int MSD_lowMakeOpenRSweep (SPTYPE s, int pln)
HPTYPE MSD_lowTouchAxis (HPTYPE eptr, int pln)
HPTYPE MSD_lowTouchWire (HPTYPE eptr, int *cut, int pln)
void MSD_execNameMakeSphere (void)
void MSD_highNameMakeSphere (char *name, int n, real r)
void MSD_execMakeSphere (void)
Id MSD_highMakeSphere (int n, real r)
SPTYPE MSD_lowMakeSphere (Id sn, real r, int nver, int nhor)
char MSD_lowMakeArc (Id s, Id f, Id v, real cx, real cz, real rad, real h, real phi1, real phi2, int n)
SPTYPE MSD_lowMakeCircle (Id sn, real cx, real cz, real rad, real h, int n)
void MSD_execNameMakeSweep (void)
void MSD_execNameMakeTorus (void)
void MSD_highNameMakeTorus (char *name, int n, real r0, real r1)
void MSD_execMakeTorus (void)
Id MSD_highMakeTorus (int n, real r0, real r1)
SPTYPE MSD_lowMakeTorus (Id sn, real r1, real r2, int nf1, int nf2)
void MSD_execNameMakeCube (void)
void MSD_highNameMakeCube (char *name, real a, real b, real c)
void MSD_execMakeCube (void)
Id MSD_highMakeCube (real a, real b, real c)
SPTYPE MSD_lowMakeCube (Id sn, real dx, real dy, real dz)
SPTYPE MSD_lowMakeCube0 (Id sn, real dx, real dy)
Variables
EXTERN unsigned char workbuf [2000]
Define Documentation
#define EXTERN extern
Definition at line 49 of file shpshape.h.
Typedef Documentation
typedef struct edge ETYPE
Definition at line 75 of file shpshape.h.
typedef struct face FTYPE
Definition at line 67 of file shpshape.h.
typedef struct halfedge HTYPE
Definition at line 79 of file shpshape.h.
typedef int Id
Definition at line 55 of file shpshape.h.
typedef struct loop LTYPE
Definition at line 71 of file shpshape.h.
typedef struct solid STYPE
Definition at line 63 of file shpshape.h.
typedef real vector[4]
Definition at line 59 of file shpshape.h.
typedef struct vertex VTYPE
Definition at line 83 of file shpshape.h.
Function Documentation
void MSD_execMakeCone (void)
void MSD_execMakeCube (void)
void MSD_execMakeCylinder (void)
void MSD_execMakePrism (void)
void MSD_execMakePyramid (void)
void MSD_execMakeRevolve (void)
void MSD_execMakeSphere (void)
void MSD_execMakeTorus (void)
void MSD_execNameMakeCone (void)
Definition at line 133 of file shpcylin.cpp.
References lineins(), MSD_highNameMakeCone(), and restbuf.
void MSD_execNameMakeCube (void)
Definition at line 53 of file shpxcube.cpp.
References lineins(), MSD_highNameMakeCube(), and restbuf.
void MSD_execNameMakeCylinder (void)
Definition at line 55 of file shpcylin.cpp.
References lineins(), MSD_highNameMakeCylinder(), and restbuf.
void MSD_execNameMakePrism (void)
Definition at line 52 of file shpmpris.cpp.
References lineins(), MSD_highNameMakePrism(), restbuf, and setvtpi().
void MSD_execNameMakePyramid (void)
Definition at line 137 of file shpmpris.cpp.
References lineins(), MSD_highNameMakePyramid(), restbuf, and setvtpi().
void MSD_execNameMakeRevolve (void)
Definition at line 52 of file shpmrevo.cpp.
References lineins(), MSD_highNameMakeRevolve(), restbuf, and setvtpi().
void MSD_execNameMakeSphere (void)
Definition at line 53 of file shpspher.cpp.
References lineins(), MSD_highNameMakeSphere(), and restbuf.
void MSD_execNameMakeSweep (void)
Definition at line 76 of file shpsweep.cpp.
References lineins(), LinePTYPE, MSD_highNameMakeSWEEP(), MSD_highSetLine(), restbuf, and setvtpi().
void MSD_execNameMakeTorus (void)
Definition at line 52 of file shptorus.cpp.
References lineins(), MSD_highNameMakeTorus(), and restbuf.
Id MSD_highMakeCone (int n, real r, real h)
Definition at line 185 of file shpcylin.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCone(), MSD_lowMakeCylinder0(), NAM_MakeCone, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCone(), and MSD_highNameMakeROVCone().
Id MSD_highMakeCube (real a, real b, real c)
Definition at line 104 of file shpxcube.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCube(), MSD_lowMakeCube0(), NAM_MakeCube, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCube(), MSD_highNameMakeCubo(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), and MSD_highNameMakeRetangulo().
Id MSD_highMakeCylinder (int n, real r, real h)
Definition at line 107 of file shpcylin.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), NAM_MakeCylinder, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCirculo(), and MSD_highNameMakeCylinder().
Id MSD_highMakePrism (int , real , XY *)
Definition at line 111 of file shpmpris.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakePrism(), MSD_lowMakePrism0(), NAM_MakePrism, SNIL, and SPTYPE.
Referenced by MSD_highNameMakePrism().
Id MSD_highMakePyramid (int , real , XY *)
Definition at line 196 of file shpmpris.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), NAM_MakePyramid, SNIL, and SPTYPE.
Referenced by MSD_highNameMakePiramide(), and MSD_highNameMakePyramid().
Id MSD_highMakeRevolve (int , int , XY *)
Definition at line 109 of file shpmrevo.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeRevolve(), NAM_MakeRevolve, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeRevolve().
Id MSD_highMakeSphere (int n, real r)
Definition at line 104 of file shpspher.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeSphere(), NAM_MakeSphere, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeEsfera(), and MSD_highNameMakeSphere().
Id MSD_highMakeTorus (int n, real r0, real r1)
Definition at line 103 of file shptorus.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeTorus(), NAM_MakeTorus, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeTorus().
void MSD_highNameMakeCone (char * name, int n, real r, real h)
Definition at line 150 of file shpcylin.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCone(), MSD_highName(), NAM_MakeCone, and SOLID.
Referenced by MSD_execNameMakeCone().
void MSD_highNameMakeCube (char * name, real a, real b, real c)
Definition at line 69 of file shpxcube.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCube(), MSD_highName(), NAM_MakeCube, and SOLID.
Referenced by MSD_execNameMakeCube().
void MSD_highNameMakeCylinder (char * name, int n, real r, real h)
Definition at line 72 of file shpcylin.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCylinder(), MSD_highName(), NAM_MakeCylinder, and SOLID.
Referenced by MSD_execNameMakeCylinder().
void MSD_highNameMakePrism (char * , int , real , XY *)
Definition at line 73 of file shpmpris.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakePrism(), MSD_highName(), NAM_MakePrism, and SOLID.
Referenced by MSD_execNameMakePrism(), and MSD_lowMakeUnion().
void MSD_highNameMakePyramid (char * , int , real , XY *)
Definition at line 158 of file shpmpris.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakePyramid(), MSD_highName(), NAM_MakePyramid, and SOLID.
Referenced by MSD_execNameMakePyramid().
void MSD_highNameMakeRevolve (char * , int , int , XY *)
Definition at line 72 of file shpmrevo.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeRevolve(), MSD_highName(), NAM_MakeRevolve, and SOLID.
Referenced by MSD_execNameMakeRevolve().
void MSD_highNameMakeSphere (char * name, int n, real r)
Definition at line 70 of file shpspher.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeSphere(), MSD_highName(), NAM_MakeSphere, and SOLID.
Referenced by MSD_execNameMakeSphere().
void MSD_highNameMakeTorus (char * name, int n, real r0, real r1)
Definition at line 69 of file shptorus.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeTorus(), MSD_highName(), NAM_MakeTorus, and SOLID.
Referenced by MSD_execNameMakeTorus().
char MSD_lowMakeArc (Id s, Id f, Id v, real cx, real cz, real rad, real h, real phi1, real phi2, int n)
Definition at line 170 of file shpspher.cpp.
References ERROR, maxv, MSD_getMaxVertexId(), MSD_getSolid(), MSD_highMEV(), PI, and SUCCESS.
Referenced by MSD_lowMakeCircle(), and MSD_lowMakeSphere().
SPTYPE MSD_lowMakeCircle (Id sn, real cx, real cz, real rad, real h, int n)
Definition at line 194 of file shpspher.cpp.
References ERROR, maxd, maxf, maxv, MSD_highMEF(), MSD_lowHardRemove(), MSD_lowMakeArc(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_lowMakeCone(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), and MSD_lowMakeTorus().
SPTYPE MSD_lowMakeCone (Id sn, real rad, real h, int n)
Definition at line 272 of file shpcylin.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeFaceToPoint(), MSD_lowMakeSweep(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetFaceToPoint(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCone().
SPTYPE MSD_lowMakeCube (Id sn, real dx, real dy, real dz)
Definition at line 147 of file shpxcube.cpp.
References CommandCount, dot(), ERROR, FacFLOut, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_getFace(), MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowFaceEq(), MSD_lowHardRemove(), MSD_lowMakeSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCube().
SPTYPE MSD_lowMakeCube0 (Id sn, real dx, real dy)
Definition at line 209 of file shpxcube.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCube().
SPTYPE MSD_lowMakeCylinder (Id sn, real rad, real h, int n)
Definition at line 211 of file shpcylin.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeSweep(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCylinder().
SPTYPE MSD_lowMakeCylinder0 (Id sn, real rad, int n)
Definition at line 252 of file shpcylin.cpp.
References CommandCount, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowMakeCircle(), MSD_lowRot90Dg(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCone(), and MSD_highMakeCylinder().
void MSD_lowMakeFaceToPoint (FPTYPE f)
Definition at line 213 of file shprevol.cpp.
References AllLoopsFace, ENIL, FacFeq, FacFLoops, FacFLOut, getdrop(), HalEdg, HalNxt, HalVtx, HPTYPE, InnerLoop, LooLEdg, LPTYPE, mate, MSD_lowKEF(), MSD_lowKEV(), and MSD_lowLooVtxContainment().
Referenced by MSD_lowCleanSolid(), MSD_lowMakeCone(), MSD_lowMakePyramid(), and MSD_lowMakeRotationalSweep().
int MSD_lowMakeOpenRSweep (SPTYPE s, int pln)
Definition at line 266 of file shprevol.cpp.
References comp(), EPS, FacFLoops, FacNextF, FNIL, HalNxt, HalPrv, HalVtx, HNIL, HPTYPE, LooLEdg, mate, maxv, MSD_getMaxVertexId(), MSD_lowKEF(), MSD_lowMEV(), MSD_lowTouchAxis(), SheSFaces, SolSShells, and VerVCoord.
Referenced by MSD_lowMakeRotationalSweep().
SPTYPE MSD_lowMakePolygon (Id sn, XY * listvtx, int n, int pln)
Definition at line 69 of file shppris0.cpp.
References ERROR, maxd, maxf, maxv, MSD_highMEF(), MSD_highMEV(), MSD_lowHardRemove(), MSD_lowMVSF(), MSD_lowSetNormal(), SNIL, SPTYPE, TRUE, XY::x, and XY::y.
Referenced by MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), and MSD_lowMakeSWEEP().
SPTYPE MSD_lowMakePrism (Id sn, XY * listvtx, real h, int n)
Definition at line 51 of file shpprism.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakePolygon(), MSD_lowMakeSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePrism().
SPTYPE MSD_lowMakePrism0 (Id sn, XY * listvtx, int n, int pln)
Definition at line 49 of file shppris0.cpp.
References CommandCount, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowMakePolygon(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePrism(), and MSD_highMakePyramid().
SPTYPE MSD_lowMakePyramid (Id sn, XY * listvtx, real h, int n)
Definition at line 50 of file shppyram.cpp.
References CommandCount, dot(), ERROR, FacFeq, FALSE, Gdoinversion, HARDREM, maxf, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeFaceToPoint(), MSD_lowMakePolygon(), MSD_lowMakeSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetFaceToPoint(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakePyramid().
SPTYPE MSD_lowMakeRevolve (Id sn, XY * listvtx, int m, int n)
Definition at line 58 of file shprevol.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakePolygon(), MSD_lowMakeRotationalSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeRevolve().
char MSD_lowMakeRotationalSweep (SPTYPE s, int nfaces, int axs, int pln, vector vect)
Definition at line 112 of file shprevol.cpp.
References comp(), dot(), EPS, ERROR, FacFeq, FacFLoops, FPTYPE, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LooLEdg, LooLFace, mate, matident(), matrotat(), maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowFaceEq(), MSD_lowKEF(), MSD_lowKFMRH(), MSD_lowLoopGlue(), MSD_lowMakeFaceToPoint(), MSD_lowMakeOpenRSweep(), MSD_lowMEF(), MSD_lowMEV(), MSD_lowTouchWire(), SheSFaces, SolSShells, SUCCESS, vecmult(), and VerVCoord.
Referenced by MSD_lowMakeRevolve(), MSD_lowMakeSphere(), and MSD_lowMakeTorus().
SPTYPE MSD_lowMakeSphere (Id sn, real r, int nver, int nhor)
Definition at line 122 of file shpspher.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeArc(), MSD_lowMakeRotationalSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeSphere().
int MSD_lowMakeSweep (FPTYPE fac, real dx, real dy, real dz)
Definition at line 94 of file shpprism.cpp.
References AllLoopsFace, FacFShell, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LPTYPE, mate, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowMEF(), MSD_lowMEV(), SheSSolids, SUCCESS, VerVCoord, and VPTYPE.
Referenced by MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCylinder(), MSD_lowMakePrism(), and MSD_lowMakePyramid().
SPTYPE MSD_lowMakeTorus (Id sn, real r1, real r2, int nf1, int nf2)
Definition at line 121 of file shptorus.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeRotationalSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeTorus().
void MSD_lowRot90Dg (SPTYPE s)
Definition at line 312 of file shpcylin.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, matident(), matrotat(), vecmult(), VerVCoord, and VPTYPE.
Referenced by MSD_lowMakeCone(), MSD_lowMakeCylinder(), and MSD_lowMakeCylinder0().
void MSD_lowSetEdgeAngle (SPTYPE optr)
Definition at line 87 of file shpgeoms.cpp.
References AllEdgesShell, AllShellsSolid, cross(), dot(), DPTYPE, EdgAngle, EdgHe1, EdgHe2, EPTYPE, FacFeq, HalVtx, HalWLoop, LooLFace, normalize(), veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_execSetTrace(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowCleanSolid(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowSetOp(), MSD_lowSplit(), and MSD_lowTransformation().
void MSD_lowSetFaceToPoint (FPTYPE fptr, real x, real y, real z)
Definition at line 92 of file shppyram.cpp.
References FacFLoops, HalNxt, HalVtx, HPTYPE, LooLEdg, and VerVCoord.
Referenced by MSD_lowMakeCone(), and MSD_lowMakePyramid().
void MSD_lowSetNormal (SPTYPE optr, int op)
Definition at line 50 of file shpgeoms.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, FaceBoxNOK, FaceEqNOK, FacFeq, FacFLOut, FALSE, FPTYPE, MSD_lowFaceBox(), MSD_lowFaceEq(), MSD_lowShellBox(), MSD_lowSolidBox(), ShellBoxNOK, SolBox, SolidBoxNOK, and TRUE.
Referenced by MSD_execSetTrace(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowCleanSolid(), MSD_lowCopyGroup(), MSD_lowCopySolid(), MSD_lowLoadSolid(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakeCylinder0(), MSD_lowMakePolygon(), MSD_lowMakePrism(), MSD_lowMakePrism0(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), MSD_lowMakeTorus(), MSD_lowRotate(), MSD_lowRound(), MSD_lowSaveSolid(), MSD_lowScale(), MSD_lowSetOp(), MSD_lowSplit(), MSD_lowTransformation(), and MSD_lowTranslate().
HPTYPE MSD_lowTouchAxis (HPTYPE eptr, int pln)
Definition at line 302 of file shprevol.cpp.
References comp(), EPS, HalNxt, HalVtx, HNIL, HPTYPE, and VerVCoord.
Referenced by MSD_lowMakeOpenRSweep().
HPTYPE MSD_lowTouchWire (HPTYPE eptr, int * cut, int pln)
Definition at line 317 of file shprevol.cpp.
References comp(), EPS, HalNxt, HalPrv, HalVtx, mate, MSD_lowKEV(), and VerVCoord.
Referenced by MSD_lowMakeRotationalSweep().
char setvtpi (XY ** , int)
Definition at line 222 of file shpmpris.cpp.
References FALSE, lineins(), restbuf, TRUE, and workbuf.
Referenced by MSD_execNameMakePiramide(), MSD_execNameMakePrism(), MSD_execNameMakePyramid(), MSD_execNameMakeRevolve(), and MSD_execNameMakeSweep().
Variable Documentation
EXTERN unsigned char workbuf[2000]
Definition at line 92 of file shpshape.h.
Referenced by MSD_execDisplay(), MSD_highRound(), MSD_lowDisplayHidden(), MSD_lowIntersectionFaceFace(), and setvtpi().