USPDesigner: C:/USPDesig/SHP/shpsweep.cpp File Reference
C:/USPDesig/SHP/shpsweep.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
#include "genfunc_.h"
#include "mensagem.h"
Classes
struct LineTYPE
Defines
#define LinePTYPE LineTYPE *
Functions
LinePTYPE MSD_highSetLine (char *name2, int n)
void MSD_highNameMakeSWEEP (char *name1, int pn, XY *listvtx, LinePTYPE line)
void MSD_execMakeSWEEP (void)
Id MSD_highMakeSWEEP (int pn, XY *listvtx, LinePTYPE line)
SPTYPE MSD_lowMakeSWEEP (Id sn, int pn, XY *listvtx, LinePTYPE line)
int MSD_lowMakeSweepNew (FPTYPE fac, LinePTYPE line)
int MSD_lowMakeNewPoint (vector nc, vector oc, vector li, vector U, vector UpV, real den, real ampl, real rot)
void MSD_lowFaceCG (FPTYPE fac, vector cg)
real MSD_lowLoopCG (LPTYPE l, vector cg, vector norm)
void MSD_execNameMakeSweep (void)
Define Documentation
#define LinePTYPE LineTYPE *
Definition at line 57 of file shpsweep.cpp.
Referenced by MSD_execNameMakeSweep(), and MSD_highSetLine().
Function Documentation
void MSD_execMakeSWEEP (void)
void MSD_execNameMakeSweep (void)
Definition at line 76 of file shpsweep.cpp.
References lineins(), LinePTYPE, MSD_highNameMakeSWEEP(), MSD_highSetLine(), restbuf, and setvtpi().
Id MSD_highMakeSWEEP (int pn, XY * listvtx, LinePTYPE line)
Definition at line 206 of file shpsweep.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeSWEEP(), NAM_MakeSweep, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeSWEEP().
void MSD_highNameMakeSWEEP (char * name1, int pn, XY * listvtx, LinePTYPE line)
Definition at line 189 of file shpsweep.cpp.
References MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highMakeSWEEP(), NAM_MakeSweep, SolName, and SPTYPE.
Referenced by MSD_execNameMakeSweep().
LinePTYPE MSD_highSetLine (char * name2, int n)
Definition at line 97 of file shpsweep.cpp.
References ERROR, lineins(), LinePTYPE, MSD_getMaxSolidId(), MSD_highMEV(), MSD_lowHardRemove(), MSD_lowMVSF(), MSD_lowSetNormal(), PI, restbuf, SNIL, SolName, and TRUE.
Referenced by MSD_execNameMakeSweep().
void MSD_lowFaceCG (FPTYPE fac, vector cg)
Definition at line 373 of file shpsweep.cpp.
References FaceEqNOK, FacFeq, FacFLoops, FacFLOut, LNIL, LooNextL, LPTYPE, MSD_lowFaceEq(), MSD_lowLoopCG(), vecesc(), vecplus(), and veczer().
Referenced by MSD_lowMakeSweepNew().
real MSD_lowLoopCG (LPTYPE l, vector cg, vector norm)
Definition at line 397 of file shpsweep.cpp.
References cross(), dot(), HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, veccopy(), vecesc(), vecminus(), vecplus(), veczer(), VerVCoord, and VPTYPE.
Referenced by MSD_lowFaceCG().
int MSD_lowMakeNewPoint (vector nc, vector oc, vector li, vector U, vector UpV, real den, real ampl, real rot)
Definition at line 343 of file shpsweep.cpp.
References cross(), dot(), ERROR, normalize(), SUCCESS, veccopy(), vecesc(), vecminus(), and vecplus().
Referenced by MSD_lowMakeSweepNew().
SPTYPE MSD_lowMakeSWEEP (Id sn, int pn, XY * listvtx, LinePTYPE line)
Definition at line 221 of file shpsweep.cpp.
References dot(), ERROR, FaceEqNOK, FacFeq, FacFLoops, FacFLOut, FALSE, FPTYPE, Gdoinversion, HalNxt, HalVtx, HARDREM, HPTYPE, LooLEdg, MSD_getFace(), MSD_lowAddEulerOp(), MSD_lowFaceEq(), MSD_lowHardRemove(), MSD_lowMakePolygon(), MSD_lowMakeSweepNew(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SheSFaces, SNIL, SolSShells, SPTYPE, TRUE, veccopy(), vecminus(), and VerVCoord.
Referenced by MSD_highMakeSWEEP().
int MSD_lowMakeSweepNew (FPTYPE fac, LinePTYPE line)
Definition at line 273 of file shpsweep.cpp.
References AllLoopsFace, dot(), ERROR, FacFLoops, FacFShell, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LPTYPE, mate, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowFaceCG(), MSD_lowMakeNewPoint(), MSD_lowMEF(), MSD_lowMEV(), normalize(), SheSFaces, SheSSolids, SolSShells, SUCCESS, veccopy(), vecminus(), vecplus(), VerVCoord, and VPTYPE.
Referenced by MSD_lowMakeSWEEP().