USPDesigner: C:/USPDesig/SHP/shptorus.cpp File Reference
C:/USPDesig/SHP/shptorus.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
Functions
void MSD_execNameMakeTorus (void)
void MSD_highNameMakeTorus (char *name, int n, real r0, real r1)
Id MSD_highMakeTorus (int n, real r0, real r1)
SPTYPE MSD_lowMakeTorus (Id sn, real r1, real r2, int nf1, int nf2)
Function Documentation
void MSD_execNameMakeTorus (void)
Definition at line 52 of file shptorus.cpp.
References lineins(), MSD_highNameMakeTorus(), and restbuf.
Id MSD_highMakeTorus (int n, real r0, real r1)
Definition at line 103 of file shptorus.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeTorus(), NAM_MakeTorus, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeTorus().
void MSD_highNameMakeTorus (char * name, int n, real r0, real r1)
Definition at line 69 of file shptorus.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeTorus(), MSD_highName(), NAM_MakeTorus, and SOLID.
Referenced by MSD_execNameMakeTorus().
SPTYPE MSD_lowMakeTorus (Id sn, real r1, real r2, int nf1, int nf2)
Definition at line 121 of file shptorus.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMakeCircle(), MSD_lowMakeRotationalSweep(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeTorus().