USPDesigner: C:/USPDesig/SHP/shpxcube.cpp File Reference
C:/USPDesig/SHP/shpxcube.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "mancommd.h"
#include "shpshape.h"
#include "disdispl.h"
Functions
void MSD_execNameMakeCube (void)
void MSD_highNameMakeCube (char *name, real a, real b, real c)
Id MSD_highMakeCube (real a, real b, real c)
SPTYPE MSD_lowMakeCube (Id sn, real dx, real dy, real dz)
SPTYPE MSD_lowMakeCube0 (Id sn, real dx, real dy)
Function Documentation
void MSD_execNameMakeCube (void)
Definition at line 53 of file shpxcube.cpp.
References lineins(), MSD_highNameMakeCube(), and restbuf.
Id MSD_highMakeCube (real a, real b, real c)
Definition at line 104 of file shpxcube.cpp.
References GNIL, MEN_ParametrosIncorretos, MSD_getMaxSolidId(), MSD_lowDisplayMonitor(), MSD_lowMakeCube(), MSD_lowMakeCube0(), NAM_MakeCube, SNIL, and SPTYPE.
Referenced by MSD_highNameMakeCube(), MSD_highNameMakeCubo(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), and MSD_highNameMakeRetangulo().
void MSD_highNameMakeCube (char * name, real a, real b, real c)
Definition at line 69 of file shpxcube.cpp.
References MEN_SolidoJaExiste, MSD_getSolidIdFromName(), MSD_highMakeCube(), MSD_highName(), NAM_MakeCube, and SOLID.
Referenced by MSD_execNameMakeCube().
SPTYPE MSD_lowMakeCube (Id sn, real dx, real dy, real dz)
Definition at line 147 of file shpxcube.cpp.
References CommandCount, dot(), ERROR, FacFLOut, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_getFace(), MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowFaceEq(), MSD_lowHardRemove(), MSD_lowMakeSweep(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCube().
SPTYPE MSD_lowMakeCube0 (Id sn, real dx, real dy)
Definition at line 209 of file shpxcube.cpp.
References CommandCount, ERROR, FALSE, Gdoinversion, HARDREM, maxd, maxf, maxv, MSD_highMEF(), MSD_highMEV(), MSD_lowAddEulerOp(), MSD_lowHardRemove(), MSD_lowMVSF(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), SNIL, SPTYPE, and TRUE.
Referenced by MSD_highMakeCube().