USPDesigner: C:/USPDesig/SPL/splmain_.cpp File Reference
C:/USPDesig/SPL/splmain_.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "shpshape.h"
#include "vectorop.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "splsplit.h"
#include "eulerops.h"
Functions
void MSD_execNameSplit (void)
void MSD_highNameSplit (char *nameo, char *name1, char *name2, real a, real b, real c, real d)
Id MSD_highSplit (Id sn, real a, real b, real c, real d)
int MSD_lowSplit (SPTYPE s, vector SP, Id sn1, Id sn2, SPTYPE *Above, SPTYPE *Below)
Variables
int NumRecordsVM [10]
char * ArqVirtualMemory []
Function Documentation
void MSD_execNameSplit (void)
Definition at line 60 of file splmain_.cpp.
References lineins(), MSD_highNameSplit(), and restbuf.
void MSD_highNameSplit (char * nameo, char * name1, char * name2, real a, real b, real c, real d)
Definition at line 76 of file splmain_.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highName(), MSD_highSplit(), NAM_SplitSolid, SNIL, and SOLID.
Referenced by MSD_execNameSplit().
Id MSD_highSplit (Id sn, real a, real b, real c, real d)
Definition at line 128 of file splmain_.cpp.
References GNIL, makevec(), MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowDisplayMonitor(), MSD_lowSplit(), NAM_SplitSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameSplit().
int MSD_lowSplit (SPTYPE s, vector SP, Id sn1, Id sn2, SPTYPE * Above, SPTYPE * Below)
Definition at line 160 of file splmain_.cpp.
References AllFacesShell, AllShellsSolid, CommandCount, comp(), dot(), DPTYPE, EPS, FacFeq, FacFLOut, FPTYPE, maxf, maxv, MEN_NaoAbriuArquivo, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowDistancePlanePoint(), MSD_lowFaceEq(), MSD_lowListSolid(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSplitClassify(), MSD_lowSplitConnect(), MSD_lowSplitFinish(), MSD_lowSplitGenerate(), MSD_lowSplitInitiate(), MSD_lowSplitTerminate(), NAM_SplitSolid, NIL, normalize(), SheSVerts, SNIL, spl_contshell, spl_nedge, SplShellShell, SplShellSign, SUCCESS, trace, and TRUE.
Referenced by MSD_highSplit().
Variable Documentation
char* ArqVirtualMemory[]
int NumRecordsVM[10]