USPDesigner: C:/USPDesig/SPL/splstep1.cpp File Reference
C:/USPDesig/SPL/splstep1.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "vectorop.h"
#include "shpshape.h"
#include "splsplit.h"
Functions
void MSD_lowSplitGenerate (SPTYPE s, vector SP)
void MSD_lowAddSplitOnVertex (VPTYPE v)
Function Documentation
void MSD_lowAddSplitOnVertex (VPTYPE v)
Definition at line 142 of file splstep1.cpp.
References spl_nvtx, SplSoov, and trace.
Referenced by MSD_lowSplitGenerate().
void MSD_lowSplitGenerate (SPTYPE s, vector SP)
Definition at line 53 of file splstep1.cpp.
References AllEdgesShell, AllShellsSolid, comp(), DPTYPE, EdgHe1, EdgHe2, EPS, EPTYPE, HalNxt, HalPrv, HalVtx, HPTYPE, maxv, MSD_lowAddSplitOnVertex(), MSD_lowDistancePlanePoint(), MSD_lowMEV(), spl_nvtx, SplSoov, trace, trace_e(), trace_v, VerVCoord, and VPTYPE.
Referenced by MSD_lowSplit().