USPDesigner: C:/USPDesig/SPL/splstep3.cpp File Reference
C:/USPDesig/SPL/splstep3.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "vectorop.h"
#include "shpshape.h"
#include "splsplit.h"
Functions
void MSD_lowSplitConnect (void)
HPTYPE MSD_lowCanJoin (HPTYPE he)
void MSD_lowJoin (HPTYPE h1, HPTYPE h2)
void MSD_lowCut (HPTYPE he)
int MSD_lowNeighbor (HPTYPE he1, HPTYPE he2)
int MSD_lowIsLoose (HPTYPE he)
void MSD_lowSortNullEdge (void)
int MSD_lowGreater (int i, int j)
void MSD_lowSwap (int i, int j)
EPTYPE MSD_lowGetNextNullEdge (void)
Function Documentation
HPTYPE MSD_lowCanJoin (HPTYPE he)
Definition at line 114 of file splstep3.cpp.
References HNIL, HPTYPE, MSD_lowNeighbor(), spl_nend, SplEnds, trace, and trace_he().
Referenced by MSD_lowSplitConnect().
void MSD_lowCut (HPTYPE he)
Definition at line 224 of file splstep3.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MSD_lowKEF(), MSD_lowKEMR(), spl_nfac, SplSonf, trace, trace_f, and trace_he().
Referenced by MSD_lowSplitConnect().
EPTYPE MSD_lowGetNextNullEdge (void)
Definition at line 333 of file splstep3.cpp.
References ENIL, EPTYPE, spl_nedge, spl_null_edge_pointer, and SplSone.
Referenced by MSD_lowSplitConnect().
int MSD_lowGreater (int i, int j)
Definition at line 296 of file splstep3.cpp.
References comp(), EdgHe1, EdgHe2, EPS, HalVtx, SplSone, veccopy(), and VerVCoord.
Referenced by MSD_lowSortNullEdge().
int MSD_lowIsLoose (HPTYPE he)
Definition at line 262 of file splstep3.cpp.
References FALSE, spl_nend, SplEnds, and TRUE.
Referenced by MSD_lowSplitConnect().
void MSD_lowJoin (HPTYPE h1, HPTYPE h2)
Definition at line 150 of file splstep3.cpp.
References FacFLoops, FNIL, FPTYPE, HalNxt, HalPrv, HalWLoop, LNIL, LooLFace, LooNextL, maxf, MSD_lowAllRingMove(), MSD_lowMEF(), MSD_lowMEKR(), trace, and trace_he().
Referenced by MSD_lowSplitConnect().
int MSD_lowNeighbor (HPTYPE he1, HPTYPE he2)
Definition at line 255 of file splstep3.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, and LooLFace.
Referenced by MSD_lowCanJoin().
void MSD_lowSortNullEdge (void)
Definition at line 276 of file splstep3.cpp.
References MSD_lowGreater(), MSD_lowSwap(), and spl_nedge.
Referenced by MSD_lowSplitConnect().
void MSD_lowSplitConnect (void)
Definition at line 53 of file splstep3.cpp.
References EdgHe1, EdgHe2, ENIL, EPTYPE, HNIL, HPTYPE, mate, MSD_lowCanJoin(), MSD_lowCut(), MSD_lowGetNextNullEdge(), MSD_lowIsLoose(), MSD_lowJoin(), MSD_lowSortNullEdge(), spl_nend, spl_nfac, spl_null_edge_pointer, SplSonf, trace, and trace_f.
Referenced by MSD_lowSplit().
void MSD_lowSwap (int i, int j)
Definition at line 324 of file splstep3.cpp.
References EPTYPE, and SplSone.
Referenced by MSD_lowSortNullEdge().