USPDesigner: C:/USPDesig/INC/splsplit.h File Reference
C:/USPDesig/INC/splsplit.h File Reference
#include <stdio.h>
Classes
struct sf
struct _spl_nbr
Defines
#define EXTERN extern
#define ON 0
#define BELOW -1
#define ABOVE 1
#define MAXSHELLS 50
#define MAXONVERTICES 100
#define MAXNULLEDGES 100
#define MAXEDGESFORVERTEX 100
#define MAXNULLFACES 100
Typedefs
typedef int Id
typedef real vector [4]
typedef struct solid STYPE
typedef struct face FTYPE
typedef struct loop LTYPE
typedef struct edge ETYPE
typedef struct halfedge HTYPE
typedef struct vertex VTYPE
typedef struct sf SF
typedef struct _spl_nbr spl_NBR
Functions
void MSD_execNameSplit (void)
void MSD_highNameSplit (char *, char *, char *, real, real, real, real)
void MSD_execSplit (void)
Id MSD_highSplit (Id, real, real, real, real)
int MSD_lowSplit (SPTYPE, vector, Id, Id, SPTYPE *, SPTYPE *)
void MSD_lowSplitInitiate (void)
void MSD_lowSplitTerminate (void)
void MSD_lowSplitGenerate (SPTYPE, vector)
void MSD_lowAddSplitOnVertex (VPTYPE)
void MSD_lowSplitClassify (vector)
void MSD_lowGetNeighborhood (VPTYPE, vector)
void MSD_lowReclassifyOnSectors (vector)
void MSD_lowReclassifyOnEdges (void)
void MSD_lowInsertNullEdges (void)
int MSD_lowCheckWideness (HPTYPE)
void MSD_lowBisector (HPTYPE, vector)
real MSD_lowDistancePlanePoint (vector, VPTYPE)
void MSD_lowSplitConnect (void)
HPTYPE MSD_lowCanJoin (HPTYPE)
void MSD_lowJoin (HPTYPE, HPTYPE)
void MSD_lowCut (HPTYPE)
int MSD_lowNeighbor (HPTYPE, HPTYPE)
int MSD_lowIsLoose (HPTYPE)
void MSD_lowSortNullEdge (void)
int MSD_lowGreater (int i, int j)
void MSD_lowSwap (int i, int j)
EPTYPE MSD_lowGetNextNullEdge (void)
void MSD_lowSplitFinish (SPTYPE, Id, Id, SPTYPE *, SPTYPE *)
void MSD_execVoronoi (void)
void MSD_lowVoronoi (char *name)
Variables
EXTERN int OutputPlanoCorte
EXTERN char OutputFile [12]
EXTERN SF spl_shellpos [MAXSHELLS]
EXTERN int spl_contshell
EXTERN VPTYPE spl_soov [MAXONVERTICES]
EXTERN int spl_nvtx
EXTERN EPTYPE spl_sone [MAXNULLEDGES]
EXTERN spl_NBR spl_nbr [MAXEDGESFORVERTEX]
EXTERN int spl_nnbr
EXTERN int spl_nedge
EXTERN FPTYPE spl_sonf [MAXNULLFACES *2]
EXTERN HPTYPE spl_ends [30]
EXTERN int spl_nfac
EXTERN int spl_nend
EXTERN int spl_null_edge_pointer
Define Documentation
#define ABOVE 1
Definition at line 96 of file splsplit.h.
Referenced by MSD_lowInsertNullEdges(), MSD_lowReclassifyOnEdges(), and MSD_lowReclassifyOnSectors().
#define BELOW -1
Definition at line 95 of file splsplit.h.
Referenced by MSD_lowInsertNullEdges(), MSD_lowReclassifyOnEdges(), and MSD_lowReclassifyOnSectors().
#define EXTERN extern
Definition at line 57 of file splsplit.h.
#define MAXEDGESFORVERTEX 100
Definition at line 133 of file splsplit.h.
#define MAXNULLEDGES 100
Definition at line 130 of file splsplit.h.
#define MAXNULLFACES 100
Definition at line 152 of file splsplit.h.
#define MAXONVERTICES 100
Definition at line 121 of file splsplit.h.
#define MAXSHELLS 50
Definition at line 107 of file splsplit.h.
#define ON 0
Definition at line 94 of file splsplit.h.
Referenced by MSD_lowReclassifyOnEdges().
Typedef Documentation
typedef struct edge ETYPE
Definition at line 83 of file splsplit.h.
typedef struct face FTYPE
Definition at line 75 of file splsplit.h.
typedef struct halfedge HTYPE
Definition at line 87 of file splsplit.h.
typedef int Id
Definition at line 63 of file splsplit.h.
typedef struct loop LTYPE
Definition at line 79 of file splsplit.h.
typedef struct sf SF
Definition at line 109 of file splsplit.h.
typedef struct _spl_nbr spl_NBR
Definition at line 138 of file splsplit.h.
typedef struct solid STYPE
Definition at line 71 of file splsplit.h.
typedef real vector[4]
Definition at line 67 of file splsplit.h.
typedef struct vertex VTYPE
Definition at line 91 of file splsplit.h.
Function Documentation
void MSD_execNameSplit (void)
Definition at line 60 of file splmain_.cpp.
References lineins(), MSD_highNameSplit(), and restbuf.
void MSD_execSplit (void)
void MSD_execVoronoi (void)
Definition at line 55 of file splvoron.cpp.
References lineins(), MSD_lowVoronoi(), and restbuf.
void MSD_highNameSplit (char * , char * , char * , real , real , real , real)
Definition at line 76 of file splmain_.cpp.
References MEN_NaoEncontrouSolidNome, MEN_SolidoJaExiste, MSD_getSolid(), MSD_getSolidIdFromName(), MSD_highName(), MSD_highSplit(), NAM_SplitSolid, SNIL, and SOLID.
Referenced by MSD_execNameSplit().
Id MSD_highSplit (Id , real , real , real , real)
Definition at line 128 of file splmain_.cpp.
References GNIL, makevec(), MEN_NaoEncontrouSolido, MSD_getMaxSolidId(), MSD_getSolid(), MSD_lowDisplayMonitor(), MSD_lowSplit(), NAM_SplitSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameSplit().
void MSD_lowAddSplitOnVertex (VPTYPE)
Definition at line 142 of file splstep1.cpp.
References spl_nvtx, SplSoov, and trace.
Referenced by MSD_lowSplitGenerate().
void MSD_lowBisector (HPTYPE , vector)
Definition at line 302 of file splstep2.cpp.
References HalNxt, HalPrv, HalVtx, veccopy(), vecminus(), vecplus(), and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), and MSD_lowSetOpVFGetNeighborhood().
HPTYPE MSD_lowCanJoin (HPTYPE)
Definition at line 114 of file splstep3.cpp.
References HNIL, HPTYPE, MSD_lowNeighbor(), spl_nend, SplEnds, trace, and trace_he().
Referenced by MSD_lowSplitConnect().
int MSD_lowCheckWideness (HPTYPE)
Definition at line 284 of file splstep2.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), and MSD_lowSetOpVFGetNeighborhood().
void MSD_lowCut (HPTYPE)
Definition at line 224 of file splstep3.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, LooLFace, MSD_lowKEF(), MSD_lowKEMR(), spl_nfac, SplSonf, trace, trace_f, and trace_he().
Referenced by MSD_lowSplitConnect().
real MSD_lowDistancePlanePoint (vector , VPTYPE)
Definition at line 313 of file splstep2.cpp.
References comp(), dot(), EPS, and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpVFGetNeighborhood(), MSD_lowSolVtxContainment(), MSD_lowSplit(), and MSD_lowSplitGenerate().
void MSD_lowGetNeighborhood (VPTYPE , vector)
Definition at line 127 of file splstep2.cpp.
References comp(), EPS, HalNxt, HalVtx, HPTYPE, mate, MAXEDGESFORVERTEX, MSD_getMemVirtual(), MSD_lowBisector(), MSD_lowCheckWideness(), MSD_lowDistancePlanePoint(), MSD_putMemVirtual(), spl_nnbr, SplNBRC1, SplNBRSector, VERTEX, VerVCoord, VerVEdge, and VPTYPE.
Referenced by MSD_lowSplitClassify().
EPTYPE MSD_lowGetNextNullEdge (void)
Definition at line 333 of file splstep3.cpp.
References ENIL, EPTYPE, spl_nedge, spl_null_edge_pointer, and SplSone.
Referenced by MSD_lowSplitConnect().
int MSD_lowGreater (int i, int j)
Definition at line 296 of file splstep3.cpp.
References comp(), EdgHe1, EdgHe2, EPS, HalVtx, SplSone, veccopy(), and VerVCoord.
Referenced by MSD_lowSortNullEdge().
void MSD_lowInsertNullEdges (void)
Definition at line 231 of file splstep2.cpp.
References ABOVE, BELOW, HalEdg, HalPrv, HalVtx, HPTYPE, maxv, MSD_lowMEV(), spl_nedge, spl_nnbr, SplNBRC1, SplNBRSector, SplSone, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSplitClassify().
int MSD_lowIsLoose (HPTYPE)
Definition at line 262 of file splstep3.cpp.
References FALSE, spl_nend, SplEnds, and TRUE.
Referenced by MSD_lowSplitConnect().
void MSD_lowJoin (HPTYPE , HPTYPE)
Definition at line 150 of file splstep3.cpp.
References FacFLoops, FNIL, FPTYPE, HalNxt, HalPrv, HalWLoop, LNIL, LooLFace, LooNextL, maxf, MSD_lowAllRingMove(), MSD_lowMEF(), MSD_lowMEKR(), trace, and trace_he().
Referenced by MSD_lowSplitConnect().
int MSD_lowNeighbor (HPTYPE , HPTYPE)
Definition at line 255 of file splstep3.cpp.
References EdgHe1, EdgHe2, HalEdg, HalWLoop, and LooLFace.
Referenced by MSD_lowCanJoin().
void MSD_lowReclassifyOnEdges (void)
Definition at line 210 of file splstep2.cpp.
References ABOVE, BELOW, ON, spl_nnbr, and SplNBRC1.
Referenced by MSD_lowSplitClassify().
void MSD_lowReclassifyOnSectors (vector)
Definition at line 181 of file splstep2.cpp.
References ABOVE, BELOW, comp(), cross(), dot(), EPS, FacFeq, FPTYPE, HalWLoop, LooLFace, spl_nnbr, SplNBRC1, and SplNBRSector.
Referenced by MSD_lowSplitClassify().
void MSD_lowSortNullEdge (void)
Definition at line 276 of file splstep3.cpp.
References MSD_lowGreater(), MSD_lowSwap(), and spl_nedge.
Referenced by MSD_lowSplitConnect().
int MSD_lowSplit (SPTYPE , vector , Id , Id , SPTYPE * , SPTYPE *)
Definition at line 160 of file splmain_.cpp.
References AllFacesShell, AllShellsSolid, CommandCount, comp(), dot(), DPTYPE, EPS, FacFeq, FacFLOut, FPTYPE, maxf, maxv, MEN_NaoAbriuArquivo, MSD_getMaxFaceId(), MSD_getMaxVertexId(), MSD_lowDistancePlanePoint(), MSD_lowFaceEq(), MSD_lowListSolid(), MSD_lowSetEdgeAngle(), MSD_lowSetInfo(), MSD_lowSetNormal(), MSD_lowSplitClassify(), MSD_lowSplitConnect(), MSD_lowSplitFinish(), MSD_lowSplitGenerate(), MSD_lowSplitInitiate(), MSD_lowSplitTerminate(), NAM_SplitSolid, NIL, normalize(), SheSVerts, SNIL, spl_contshell, spl_nedge, SplShellShell, SplShellSign, SUCCESS, trace, and TRUE.
Referenced by MSD_highSplit().
void MSD_lowSplitClassify (vector)
Definition at line 55 of file splstep2.cpp.
References MSD_lowGetNeighborhood(), MSD_lowInsertNullEdges(), MSD_lowReclassifyOnEdges(), MSD_lowReclassifyOnSectors(), spl_nedge, spl_nnbr, spl_nvtx, SplSone, SplSoov, trace, trace_e(), trace_nbr(), and trace_v.
Referenced by MSD_lowSplit().
void MSD_lowSplitConnect (void)
Definition at line 53 of file splstep3.cpp.
References EdgHe1, EdgHe2, ENIL, EPTYPE, HNIL, HPTYPE, mate, MSD_lowCanJoin(), MSD_lowCut(), MSD_lowGetNextNullEdge(), MSD_lowIsLoose(), MSD_lowJoin(), MSD_lowSortNullEdge(), spl_nend, spl_nfac, spl_null_edge_pointer, SplSonf, trace, and trace_f.
Referenced by MSD_lowSplit().
void MSD_lowSplitFinish (SPTYPE , Id , Id , SPTYPE * , SPTYPE *)
Definition at line 53 of file splstep4.cpp.
References FacFaceNo, FacFLOut, FacFShell, HalNxt, HalVtx, HPTYPE, InnerLoop, LooLEdg, maxd, maxf, MSD_getMaxShellId(), MSD_lowDetach(), MSD_lowMSFKR(), NIL, OutputFile, OutputPlanoCorte, spl_contshell, spl_nfac, SplShellShell, SplShellSign, SplSonf, trace, trace_f, VerVCoord, and VerVertexNo.
Referenced by MSD_lowSplit().
void MSD_lowSplitGenerate (SPTYPE , vector)
Definition at line 53 of file splstep1.cpp.
References AllEdgesShell, AllShellsSolid, comp(), DPTYPE, EdgHe1, EdgHe2, EPS, EPTYPE, HalNxt, HalPrv, HalVtx, HPTYPE, maxv, MSD_lowAddSplitOnVertex(), MSD_lowDistancePlanePoint(), MSD_lowMEV(), spl_nvtx, SplSoov, trace, trace_e(), trace_v, VerVCoord, and VPTYPE.
Referenced by MSD_lowSplit().
void MSD_lowSplitInitiate (void)
Referenced by MSD_lowSplit().
void MSD_lowSplitTerminate (void)
Referenced by MSD_lowSplit().
void MSD_lowSwap (int i, int j)
Definition at line 324 of file splstep3.cpp.
References EPTYPE, and SplSone.
Referenced by MSD_lowSortNullEdge().
void MSD_lowVoronoi (char * name)
Definition at line 70 of file splvoron.cpp.
References OutputFile, OutputPlanoCorte, and TRUE.
Referenced by MSD_execVoronoi().
Variable Documentation
EXTERN char OutputFile[12]
Definition at line 103 of file splsplit.h.
Referenced by MSD_lowSplitFinish(), and MSD_lowVoronoi().
EXTERN int OutputPlanoCorte
Definition at line 102 of file splsplit.h.
Referenced by maninit(), MSD_lowSplitFinish(), and MSD_lowVoronoi().
EXTERN int spl_contshell
Definition at line 118 of file splsplit.h.
Referenced by MSD_lowSplit(), and MSD_lowSplitFinish().
EXTERN HPTYPE spl_ends[30]
Definition at line 156 of file splsplit.h.
EXTERN spl_NBR spl_nbr[MAXEDGESFORVERTEX]
Definition at line 145 of file splsplit.h.
EXTERN int spl_nedge
Definition at line 148 of file splsplit.h.
Referenced by MSD_lowGetNextNullEdge(), MSD_lowInsertNullEdges(), MSD_lowSortNullEdge(), MSD_lowSplit(), and MSD_lowSplitClassify().
EXTERN int spl_nend
Definition at line 159 of file splsplit.h.
Referenced by MSD_lowCanJoin(), MSD_lowIsLoose(), and MSD_lowSplitConnect().
EXTERN int spl_nfac
Definition at line 158 of file splsplit.h.
Referenced by MSD_lowCut(), MSD_lowSplitConnect(), and MSD_lowSplitFinish().
EXTERN int spl_nnbr
Definition at line 147 of file splsplit.h.
Referenced by MSD_lowGetNeighborhood(), MSD_lowInsertNullEdges(), MSD_lowReclassifyOnEdges(), MSD_lowReclassifyOnSectors(), and MSD_lowSplitClassify().
EXTERN int spl_null_edge_pointer
Definition at line 160 of file splsplit.h.
Referenced by MSD_lowGetNextNullEdge(), and MSD_lowSplitConnect().
EXTERN int spl_nvtx
Definition at line 126 of file splsplit.h.
Referenced by MSD_lowAddSplitOnVertex(), MSD_lowSplitClassify(), and MSD_lowSplitGenerate().
EXTERN SF spl_shellpos[MAXSHELLS]
Definition at line 116 of file splsplit.h.
EXTERN EPTYPE spl_sone[MAXNULLEDGES]
Definition at line 136 of file splsplit.h.
EXTERN FPTYPE spl_sonf[MAXNULLFACES *2]
Definition at line 155 of file splsplit.h.
EXTERN VPTYPE spl_soov[MAXONVERTICES]
Definition at line 124 of file splsplit.h.