USPDesigner: C:/USPDesig/SPL/splstep4.cpp File Reference
C:/USPDesig/SPL/splstep4.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "vectorop.h"
#include "shpshape.h"
#include "splsplit.h"
Functions
void MSD_lowSplitFinish (SPTYPE s, Id sn1, Id sn2, SPTYPE *Above, SPTYPE *Below)
Function Documentation
void MSD_lowSplitFinish (SPTYPE s, Id sn1, Id sn2, SPTYPE * Above, SPTYPE * Below)
Definition at line 53 of file splstep4.cpp.
References FacFaceNo, FacFLOut, FacFShell, HalNxt, HalVtx, HPTYPE, InnerLoop, LooLEdg, maxd, maxf, MSD_getMaxShellId(), MSD_lowDetach(), MSD_lowMSFKR(), NIL, OutputFile, OutputPlanoCorte, spl_contshell, spl_nfac, SplShellShell, SplShellSign, SplSonf, trace, trace_f, VerVCoord, and VerVertexNo.
Referenced by MSD_lowSplit().