USPDesigner: C:/USPDesig/SPL/splstep2.cpp File Reference
C:/USPDesig/SPL/splstep2.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "vectorop.h"
#include "shpshape.h"
#include "splsplit.h"
Functions
void MSD_lowSplitClassify (vector SP)
void MSD_lowGetNeighborhood (VPTYPE v, vector SP)
void MSD_lowReclassifyOnSectors (vector SP)
void MSD_lowReclassifyOnEdges (void)
void MSD_lowInsertNullEdges (void)
int MSD_lowCheckWideness (HPTYPE he)
void MSD_lowBisector (HPTYPE he, vector bisect)
double MSD_lowDistancePlanePoint (vector SP, VPTYPE p)
Function Documentation
void MSD_lowBisector (HPTYPE he, vector bisect)
Definition at line 302 of file splstep2.cpp.
References HalNxt, HalPrv, HalVtx, veccopy(), vecminus(), vecplus(), and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), and MSD_lowSetOpVFGetNeighborhood().
int MSD_lowCheckWideness (HPTYPE he)
Definition at line 284 of file splstep2.cpp.
References cross(), dot(), EPS, FacFeq, HalNxt, HalPrv, HalVtx, HalWLoop, LooLFace, veccopy(), vecminus(), vecnull(), and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), and MSD_lowSetOpVFGetNeighborhood().
double MSD_lowDistancePlanePoint (vector SP, VPTYPE p)
Definition at line 313 of file splstep2.cpp.
References comp(), dot(), EPS, and VerVCoord.
Referenced by MSD_lowGetNeighborhood(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpVFGetNeighborhood(), MSD_lowSolVtxContainment(), MSD_lowSplit(), and MSD_lowSplitGenerate().
void MSD_lowGetNeighborhood (VPTYPE v, vector SP)
Definition at line 127 of file splstep2.cpp.
References comp(), EPS, HalNxt, HalVtx, HPTYPE, mate, MAXEDGESFORVERTEX, MSD_getMemVirtual(), MSD_lowBisector(), MSD_lowCheckWideness(), MSD_lowDistancePlanePoint(), MSD_putMemVirtual(), spl_nnbr, SplNBRC1, SplNBRSector, VERTEX, VerVCoord, VerVEdge, and VPTYPE.
Referenced by MSD_lowSplitClassify().
void MSD_lowInsertNullEdges (void)
Definition at line 231 of file splstep2.cpp.
References ABOVE, BELOW, HalEdg, HalPrv, HalVtx, HPTYPE, maxv, MSD_lowMEV(), spl_nedge, spl_nnbr, SplNBRC1, SplNBRSector, SplSone, trace, trace_e(), trace_he(), and VerVCoord.
Referenced by MSD_lowSplitClassify().
void MSD_lowReclassifyOnEdges (void)
Definition at line 210 of file splstep2.cpp.
References ABOVE, BELOW, ON, spl_nnbr, and SplNBRC1.
Referenced by MSD_lowSplitClassify().
void MSD_lowReclassifyOnSectors (vector SP)
Definition at line 181 of file splstep2.cpp.
References ABOVE, BELOW, comp(), cross(), dot(), EPS, FacFeq, FPTYPE, HalWLoop, LooLFace, spl_nnbr, SplNBRC1, and SplNBRSector.
Referenced by MSD_lowSplitClassify().
void MSD_lowSplitClassify (vector SP)
Definition at line 55 of file splstep2.cpp.
References MSD_lowGetNeighborhood(), MSD_lowInsertNullEdges(), MSD_lowReclassifyOnEdges(), MSD_lowReclassifyOnSectors(), spl_nedge, spl_nnbr, spl_nvtx, SplSone, SplSoov, trace, trace_e(), trace_nbr(), and trace_v.
Referenced by MSD_lowSplit().