USPDesigner: C:/USPDesig/SPL/splvoron.cpp File Reference
C:/USPDesig/SPL/splvoron.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "mancommd.h"
#include "shpshape.h"
#include "vectorop.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "splsplit.h"
Functions
void MSD_execVoronoi (void)
void MSD_lowVoronoi (char *name)
Function Documentation
void MSD_execVoronoi (void)
Definition at line 55 of file splvoron.cpp.
References lineins(), MSD_lowVoronoi(), and restbuf.
void MSD_lowVoronoi (char * name)
Definition at line 70 of file splvoron.cpp.
References OutputFile, OutputPlanoCorte, and TRUE.
Referenced by MSD_execVoronoi().