USPDesigner: C:/USPDesig/TOP/topclean.cpp File Reference
C:/USPDesig/TOP/topclean.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "vectorop.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "shpshape.h"
#include "mancommd.h"
Functions
int MSD_highNameCleanSolid (char *name)
int MSD_highCleanSolid (Id sn)
void MSD_lowCleanSolid (SPTYPE s)
Function Documentation
int MSD_highCleanSolid (Id sn)
Definition at line 101 of file topclean.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowCleanSolid(), NAM_CleanSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameCleanSolid().
int MSD_highNameCleanSolid (char * name)
Definition at line 71 of file topclean.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highCleanSolid(), and NAM_CleanSolid.
void MSD_lowCleanSolid (SPTYPE s)
Definition at line 114 of file topclean.cpp.
References AllFacesShell, AllShellsSolid, DPTYPE, EdgHe1, EdgHe2, EdgNextE, ENIL, EPS, EPTYPE, FacFeq, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, getdrop(), HalEdg, HalNxt, HalPrv, HalVtx, HalWLoop, HNIL, HPTYPE, LNIL, LooLEdg, LooLFace, LooNextL, LPTYPE, mate, MSD_lowEdgEdgColinear(), MSD_lowFacFacEqualEqs(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowLooVtxContainment(), MSD_lowMakeFaceToPoint(), MSD_lowMEKR(), MSD_lowSetEdgeAngle(), MSD_lowSetNormal(), MSD_lowVtxVtxContainment(), SheSEdges, SheSFaces, SheSVerts, TRUE, vecnull(), VerNextV, VerVEdge, VNIL, and VPTYPE.
Referenced by MSD_highCleanSolid(), MSD_highDifference(), MSD_highIntersection(), and MSD_highUnion().