USPDesigner: C:/USPDesig/TOP/topdetac.cpp File Reference
C:/USPDesig/TOP/topdetac.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highDetach (Id sn, Id sn1, Id dn, Id newd, int addf, int addv)
SPTYPE MSD_lowDetach (SPTYPE s, Id sn1, DPTYPE d, Id newd, int addf, int addv)
void MSD_lowShellDetach (SPTYPE s, SPTYPE s1, DPTYPE d, Id newd, int addf, int addv)
int MSD_execStructDetach (EulerOp *op)
void MSD_printStructDetach (FILE *f, EulerOp *op)
int MSD_readStructDetach (FILE *f, EulerOp *op)
int MSD_modifyStructDetach (EulerOp *op)
Function Documentation
int MSD_execStructDetach (EulerOp * op)
Definition at line 204 of file topdetac.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highDetach(), and eulerop::solidno.
int MSD_highDetach (Id sn, Id sn1, Id dn, Id newd, int addf, int addv)
Definition at line 72 of file topdetac.cpp.
References DNIL, DPTYPE, ERROR, MEN_NaoEncontrouShell, MEN_NaoEncontrouSolido, MSD_getShell(), MSD_getSolid(), MSD_lowDetach(), NAM_Detach, SNIL, and SPTYPE.
Referenced by MSD_execStructDetach().
SPTYPE MSD_lowDetach (SPTYPE s, Id sn1, DPTYPE d, Id newd, int addf, int addv)
Definition at line 90 of file topdetac.cpp.
References MSD_getSolid(), MSD_lowNewElement(), MSD_lowShellDetach(), NNIL, SheSSolids, SNIL, SOLID, SolSolidNo, and SPTYPE.
Referenced by MSD_highDetach(), MSD_lowSetOpFinish(), and MSD_lowSplitFinish().
void MSD_lowShellDetach (SPTYPE s, SPTYPE s1, DPTYPE d, Id newd, int addf, int addv)
Definition at line 107 of file topdetac.cpp.
References AllEdgesShell, AllFacesShell, AllLoopsFace, AllVerticesShell, DETACH, DNIL, EPTYPE, FacFaceNo, FPTYPE, Gdodirect, Gdoinversion, LPTYPE, MEN_MSDAbortou, MSD_addEulCoef(), MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelElement(), MSD_lowDelList(), NAM_Detach, NNIL, NPTYPE, SetTrace, SHELL, SheShellNo, SolEuCoef, SOLID, SolSolidNo, SolSShells, TraceSolid(), VerVertexNo, and VPTYPE.
Referenced by MSD_lowDetach(), and MSD_lowMerge().
int MSD_modifyStructDetach (EulerOp * op)
Definition at line 258 of file topdetac.cpp.
References eulerop::ip1, MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructDetach (FILE * f, EulerOp * op)
Definition at line 217 of file topdetac.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
int MSD_readStructDetach (FILE * f, EulerOp * op)
Definition at line 232 of file topdetac.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.