USPDesigner: C:/USPDesig/TOP/toplglue.cpp File Reference
C:/USPDesig/TOP/toplglue.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "lowgeome.h"
#include "mancommd.h"
Functions
int MSD_highGlue (Id sn1, Id sn2)
void MSD_lowGlue (SPTYPE s1, SPTYPE s2)
void MSD_lowFaceGlue (SPTYPE s1, SPTYPE s2, FPTYPE f1, FPTYPE f2)
int MSD_lowLoopGlue (FPTYPE f)
Function Documentation
int MSD_highGlue (Id sn1, Id sn2)
Definition at line 70 of file toplglue.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowGlue(), NAM_Glue, SNIL, SPTYPE, and SUCCESS.
void MSD_lowFaceGlue (SPTYPE s1, SPTYPE s2, FPTYPE f1, FPTYPE f2)
Definition at line 196 of file toplglue.cpp.
References MSD_lowKSFMR(), MSD_lowLoopGlue(), and MSD_lowMerge().
void MSD_lowGlue (SPTYPE s1, SPTYPE s2)
Definition at line 89 of file toplglue.cpp.
References AllFacesShell, AllShellsSolid, DNIL, DPTYPE, FacFShell, FacNextF, FNIL, FPTYPE, MSD_lowFacFacContainment(), MSD_lowFacFacIdentical(), MSD_lowFacFacOppositeEqs(), MSD_lowKFMRH(), MSD_lowKSFMR(), MSD_lowLoopGlue(), MSD_lowMerge(), SheNextD, and SheSFaces.
Referenced by MSD_highGlue().
int MSD_lowLoopGlue (FPTYPE f)
Definition at line 203 of file toplglue.cpp.
References assert, assert1, FacFLoops, FALSE, HalNxt, HalPrv, HalVtx, HPTYPE, LNIL, LooLEdg, LooNextL, mate, maxf, MSD_lowKEF(), MSD_lowKEV(), MSD_lowMEF(), MSD_lowMEKR(), MSD_lowVtxVtxContainment(), and SUCCESS.
Referenced by MSD_lowFaceGlue(), MSD_lowGlue(), MSD_lowMakeRotationalSweep(), and MSD_lowSetOpFinish().