USPDesigner: C:/USPDesig/TOP/topmodif.cpp File Reference
C:/USPDesig/TOP/topmodif.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highModifyIds (Id sn, Id snew)
void MSD_lowModifyIds (SPTYPE s, int sn)
int MSD_execStructModifyIds (EulerOp *op)
void MSD_printStructModifyIds (FILE *f, EulerOp *op)
int MSD_readStructModifyIds (FILE *f, EulerOp *op)
int MSD_modifyStructModifyIds (EulerOp *op)
Function Documentation
int MSD_execStructModifyIds (EulerOp * op)
Definition at line 100 of file topmodif.cpp.
References eulerop::ip1, eulerop::ip2, MSD_highModifyIds(), and eulerop::solidno.
int MSD_highModifyIds (Id sn, Id snew)
Definition at line 69 of file topmodif.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowModifyIds(), NAM_ModifyIds, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_execStructModifyIds().
void MSD_lowModifyIds (SPTYPE s, int sn)
Definition at line 82 of file topmodif.cpp.
References Gdodirect, Gdoinversion, MODIFYNAMES, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), and SolSolidNo.
Referenced by MSD_highDifference(), MSD_highIntersection(), MSD_highModifyIds(), and MSD_highUnion().
int MSD_modifyStructModifyIds (EulerOp * op)
Definition at line 146 of file topmodif.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructModifyIds (FILE * f, EulerOp * op)
Definition at line 110 of file topmodif.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::ip2.
int MSD_readStructModifyIds (FILE * f, EulerOp * op)
Definition at line 121 of file topmodif.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.