USPDesigner: C:/USPDesig/TOP/topmerge.cpp File Reference
C:/USPDesig/TOP/topmerge.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "genfunc_.h"
#include "disdispl.h"
#include "mancommd.h"
Functions
int MSD_highNameMerge (char *name1, char *name2)
int MSD_highMerge (Id sn1, Id sn2)
void MSD_lowMerge (SPTYPE s1, SPTYPE s2)
Function Documentation
int MSD_highMerge (Id sn1, Id sn2)
Definition at line 105 of file topmerge.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowMerge(), NAM_MergeSolid, SNIL, SPTYPE, and SUCCESS.
Referenced by MSD_highNameMerge().
int MSD_highNameMerge (char * name1, char * name2)
Definition at line 70 of file topmerge.cpp.
References ERROR, MEN_NaoEncontrouSolidNome, MSD_getSolidIdFromName(), MSD_highMerge(), and NAM_MergeSolid.
void MSD_lowMerge (SPTYPE s1, SPTYPE s2)
Definition at line 124 of file topmerge.cpp.
References DNIL, DPTYPE, maxd, maxf, maxv, MSD_getMaxFaceId(), MSD_getMaxShellId(), MSD_getMaxVertexId(), MSD_lowShellDetach(), and SolSShells.
Referenced by MSD_highMerge(), MSD_lowFaceGlue(), and MSD_lowGlue().