USPDesigner: C:/USPDesig/TOP/topnewlc.cpp File Reference
C:/USPDesig/TOP/topnewlc.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highNewVertexLocation (Id sn, Id vn, real x, real y, real z)
void MSD_lowNewVertexLocation (SPTYPE s, VPTYPE v, real x, real y, real z)
int MSD_execStructNewVertexLocation (EulerOp *op)
void MSD_printStructNewVertexLocation (FILE *f, EulerOp *op)
int MSD_readStructNewVertexLocation (FILE *f, EulerOp *op)
int MSD_modifyStructNewVertexLocation (EulerOp *op)
Function Documentation
int MSD_execStructNewVertexLocation (EulerOp * op)
Definition at line 117 of file topnewlc.cpp.
References eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, MSD_highNewVertexLocation(), and eulerop::solidno.
int MSD_highNewVertexLocation (Id sn, Id vn, real x, real y, real z)
Definition at line 70 of file topnewlc.cpp.
References AllShellsSolid, AllVerticesShell, DPTYPE, ERROR, MEN_NaoEncontrouSolido, MEN_NaoEncontrouVertice, MSD_getSolid(), MSD_lowNewVertexLocation(), NAM_NewLocation, SNIL, SPTYPE, SUCCESS, VerVertexNo, and VPTYPE.
Referenced by MSD_execStructNewVertexLocation().
void MSD_lowNewVertexLocation (SPTYPE s, VPTYPE v, real x, real y, real z)
Definition at line 96 of file topnewlc.cpp.
References Gdodirect, Gdoinversion, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NEWLOC, VerVCoord, and VerVertexNo.
Referenced by EdgeAttached_vertexfase1(), edv2(), and MSD_highNewVertexLocation().
int MSD_modifyStructNewVertexLocation (EulerOp * op)
Definition at line 171 of file topnewlc.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructNewVertexLocation (FILE * f, EulerOp * op)
Definition at line 130 of file topnewlc.cpp.
References eulerop::CommandCount, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::ip1, and eulerop::solidno.
int MSD_readStructNewVertexLocation (FILE * f, EulerOp * op)
Definition at line 145 of file topnewlc.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.