USPDesigner: C:/USPDesig/TOP/topremsf.cpp File Reference
C:/USPDesig/TOP/topremsf.cpp File Reference
#include <stdio.h>
#include <string.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highNameSoftRemove (char *name)
int MSD_highSoftRemove (Id sn)
int MSD_lowSoftRemove (SPTYPE s)
void MSD_lowShellRemove (SPTYPE s)
void MSD_lowEdgeRemove (SPTYPE s)
void MSD_lowFaceRemove (SPTYPE s)
Function Documentation
int MSD_highNameSoftRemove (char * name)
Definition at line 70 of file topremsf.cpp.
References FALSE, MEN_NaoEncontrouSolidNome, MSD_lowFindSolidByName(), MSD_lowSoftRemove(), NAM_SoftRemove, SNIL, and SPTYPE.
Referenced by MSD_highNameDeleteElement(), MSD_lowAreaProjetada(), and MSD_lowAreaProjetadaTotal().
int MSD_highSoftRemove (Id sn)
Definition at line 100 of file topremsf.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowSoftRemove(), NAM_SoftRemove, SNIL, and SPTYPE.
void MSD_lowEdgeRemove (SPTYPE s)
Definition at line 146 of file topremsf.cpp.
References EdgHe1, EdgHe2, ENIL, EPTYPE, FacFLOut, HalNxt, HalWLoop, LooLFace, LPTYPE, maxf, MSD_getMaxFaceId(), MSD_lowKEF(), MSD_lowKEMR(), MSD_lowKEV(), MSD_lowMFKRH(), SheSEdges, and SolSShells.
Referenced by MSD_lowSoftRemove().
void MSD_lowFaceRemove (SPTYPE s)
Definition at line 184 of file topremsf.cpp.
References AllFacesShell, FacFLoops, FacFLOut, FacNextF, FNIL, FPTYPE, HPTYPE, LNIL, LooLEdg, LooNextL, LPTYPE, mate, MSD_lowKEV(), MSD_lowKFMRH(), MSD_lowMEKR(), SheSFaces, and SolSShells.
Referenced by MSD_lowSoftRemove().
void MSD_lowShellRemove (SPTYPE s)
Definition at line 136 of file topremsf.cpp.
References DNIL, DPTYPE, MSD_lowKSFMR(), SheNextD, SheSFaces, and SolSShells.
Referenced by MSD_lowSoftRemove().
int MSD_lowSoftRemove (SPTYPE s)
Definition at line 112 of file topremsf.cpp.
References DNIL, GNIL, GrpGroupNo, MSD_highDesassociaGroupSolid(), MSD_lowEdgeRemove(), MSD_lowFaceRemove(), MSD_lowKVSF(), MSD_lowShellRemove(), MSD_lowSolidColor(), MSD_lowSolidName(), SolColor, SolGroup, SolName, SolSolidNo, SolSShells, and SUCCESS.
Referenced by MSD_highNameSoftRemove(), MSD_highSoftRemove(), MSD_lowCopySolid(), MSD_lowRemoveGroup(), MSD_lowSaveSolid(), and MSD_lowSetOp().