USPDesigner: C:/USPDesig/TOP/topringm.cpp File Reference
C:/USPDesig/TOP/topringm.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
#include "vectorop.h"
#include "lowgeome.h"
Functions
int MSD_highRingMove (Id sn, Id v1, Id v2, Id f1, Id f2, int out)
int MSD_lowRingMove (FPTYPE f1, FPTYPE f2, LPTYPE l, int out)
int MSD_execStructRingMove (EulerOp *op)
void MSD_printStructRingMove (FILE *f, EulerOp *op)
int MSD_readStructRingMove (FILE *f, EulerOp *op)
int MSD_modifyStructRingMove (EulerOp *op)
int MSD_highAllRingMove (Id sn, Id f1, Id f2)
int MSD_lowAllRingMove (FPTYPE f1, FPTYPE f2)
Function Documentation
int MSD_execStructRingMove (EulerOp * op)
Definition at line 160 of file topringm.cpp.
References eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, MSD_highRingMove(), and eulerop::solidno.
int MSD_highAllRingMove (Id sn, Id f1, Id f2)
Definition at line 241 of file topringm.cpp.
References ERROR, FNIL, FPTYPE, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getFace(), MSD_getSolid(), MSD_lowAllRingMove(), NAM_AllRingMove, SNIL, and SPTYPE.
int MSD_highRingMove (Id sn, Id v1, Id v2, Id f1, Id f2, int out)
Definition at line 74 of file topringm.cpp.
References ERROR, FNIL, FPTYPE, HPTYPE, LNIL, LPTYPE, MEN_NaoEncontrouArestaV, MEN_NaoEncontrouFace, MEN_NaoEncontrouSolido, MSD_getEdge(), MSD_getFace(), MSD_getLoop(), MSD_getSolid(), MSD_lowRingMove(), NAM_RingMove, SNIL, and SPTYPE.
Referenced by MSD_execStructRingMove().
int MSD_lowAllRingMove (FPTYPE f1, FPTYPE f2)
Definition at line 265 of file topringm.cpp.
References FacFaceNo, FacFeq, FacFLoops, FacFLOut, FacFShell, FALSE, Gdoinversion, getdrop(), HalEdg, HalNxt, HalVtx, LNIL, LooLEdg, LooNextL, LOOP, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddList(), MSD_lowDelList(), MSD_lowFaceEq(), MSD_lowFacVtxCoordContainment(), NAM_AllRingMove, NPTYPE, RMOVE, SetTrace, SheSSolids, SPTYPE, SUCCESS, TraceSolid(), TRUE, and VerVertexNo.
Referenced by MSD_highAllRingMove(), MSD_lowJoin(), and MSD_lowSetOpJoin().
int MSD_lowRingMove (FPTYPE f1, FPTYPE f2, LPTYPE l, int out)
Definition at line 107 of file topringm.cpp.
References ArrayBottom, assert, ENIL, FacFaceNo, FacFLOut, FacFShell, FALSE, Gdodirect, Gdoinversion, HalEdg, HalNxt, HalVtx, InnerLoop, LooLEdg, LooLFace, LOOP, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), MSD_lowAddList(), MSD_lowDelList(), NAM_RingMove, NPTYPE, RMOVE, SetTrace, SheSSolids, SOLID, SolSolidNo, SPTYPE, SUCCESS, TraceSolid(), TRUE, and VerVertexNo.
Referenced by MSD_highRingMove().
int MSD_modifyStructRingMove (EulerOp * op)
Definition at line 214 of file topringm.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructRingMove (FILE * f, EulerOp * op)
Definition at line 173 of file topringm.cpp.
References eulerop::CommandCount, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, and eulerop::solidno.
int MSD_readStructRingMove (FILE * f, EulerOp * op)
Definition at line 188 of file topringm.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.