USPDesigner: C:/USPDesig/TOP/topremhr.cpp File Reference
C:/USPDesig/TOP/topremhr.cpp File Reference
#include <stdio.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highHardRemove (Id sn)
int MSD_lowHardRemove (SPTYPE s)
int MSD_execStructHardRemove (EulerOp *op)
void MSD_printStructHardRemove (FILE *f, EulerOp *op)
int MSD_readStructHardRemove (FILE *f, EulerOp *op)
int MSD_modifyStructHardRemove (EulerOp *op)
Function Documentation
int MSD_execStructHardRemove (EulerOp * op)
Definition at line 130 of file topremhr.cpp.
References MSD_highHardRemove(), and eulerop::solidno.
int MSD_highHardRemove (Id sn)
Definition at line 69 of file topremhr.cpp.
References ERROR, MEN_NaoEncontrouSolido, MSD_getSolid(), MSD_lowHardRemove(), NAM_HardRemove, SNIL, and SPTYPE.
Referenced by MSD_execStructHardRemove().
int MSD_lowHardRemove (SPTYPE s)
Definition at line 81 of file topremhr.cpp.
References DNIL, DPTYPE, EDGE, EdgHe1, ENIL, FACE, FacFLoops, FALSE, FNIL, FPTYPE, HalEdg, HALFEDGE, HalNxt, HalVtx, HPTYPE, LNIL, LooLEdg, LOOP, LPTYPE, MSD_lowDelElement(), NNIL, NPTYPE, SetTrace, SHELL, SheSFaces, SOLID, SolSShells, SUCCESS, VERTEX, and VerVEdge.
Referenced by MSD_highHardRemove(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_highSetLine(), MSD_lowMakeCircle(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCube0(), MSD_lowMakeCylinder(), MSD_lowMakePolygon(), MSD_lowMakePrism(), MSD_lowMakePyramid(), MSD_lowMakeRevolve(), MSD_lowMakeSphere(), MSD_lowMakeSWEEP(), and MSD_lowMakeTorus().
int MSD_modifyStructHardRemove (EulerOp * op)
Definition at line 173 of file topremhr.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructHardRemove (FILE * f, EulerOp * op)
Definition at line 138 of file topremhr.cpp.
References eulerop::CommandCount, and eulerop::solidno.
int MSD_readStructHardRemove (FILE * f, EulerOp * op)
Definition at line 148 of file topremhr.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::ip7, eulerop::ip8, eulerop::solidno, and SUCCESS.