USPDesigner: C:/USPDesig/TOP/toprever.cpp File Reference
C:/USPDesig/TOP/toprever.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mensagem.h"
#include "memvirtu.h"
#include "lowparam.h"
#include "lowmacro.h"
#include "lowsolid.h"
#include "eulerops.h"
#include "mancommd.h"
Functions
int MSD_highRevert (Id sn, Id dn)
int MSD_lowRevert (DPTYPE d)
int MSD_execStructRevert (EulerOp *op)
void MSD_printStructRevert (FILE *f, EulerOp *op)
int MSD_readStructRevert (FILE *f, EulerOp *op)
int MSD_modifyStructRevert (EulerOp *op)
Function Documentation
int MSD_execStructRevert (EulerOp * op)
Definition at line 157 of file toprever.cpp.
References eulerop::ip1, MSD_highRevert(), and eulerop::solidno.
int MSD_highRevert (Id sn, Id dn)
Definition at line 71 of file toprever.cpp.
References DNIL, DPTYPE, ERROR, MEN_NaoEncontrouShell, MEN_NaoEncontrouSolido, MSD_getShell(), MSD_getSolid(), MSD_lowRevert(), NAM_Revert, SNIL, and SPTYPE.
Referenced by MSD_execStructRevert().
int MSD_lowRevert (DPTYPE d)
Definition at line 89 of file toprever.cpp.
References AllFacesShell, AllLoopsFace, FPTYPE, Gdodirect, Gdoinversion, HalNxt, HalPrv, HalVtx, HPTYPE, LooLEdg, LPTYPE, MEN_MSDAbortou, MSD_lowAddEulerOp(), MSD_lowAddEulerOpRedo(), NAM_Revert, REVERT, SetTrace, SheShellNo, SheSSolids, SPTYPE, SUCCESS, TraceSolid(), VerVEdge, and VPTYPE.
Referenced by MSD_highRevert(), MSD_lowRotate(), MSD_lowScale(), MSD_lowSetOpFinish(), and MSD_lowTransformation().
int MSD_modifyStructRevert (EulerOp * op)
Definition at line 190 of file toprever.cpp.
References MSD_lowCheckTranslatorTable(), SOLID, eulerop::solidno, and SUCCESS.
void MSD_printStructRevert (FILE * f, EulerOp * op)
Definition at line 162 of file toprever.cpp.
References eulerop::CommandCount, eulerop::ip1, and eulerop::solidno.
int MSD_readStructRevert (FILE * f, EulerOp * op)
Definition at line 167 of file toprever.cpp.
References eulerop::CommandCount, ERROR, eulerop::fp1, eulerop::fp2, eulerop::fp3, eulerop::fp4, eulerop::ip1, eulerop::ip2, eulerop::ip3, eulerop::ip4, eulerop::ip5, eulerop::ip6, eulerop::solidno, and SUCCESS.