USPDesigner: C:/USPDesig/VEC/vectorop.cpp File Reference
C:/USPDesig/VEC/vectorop.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "memvirtu.h"
#include "lowparam.h"
#include "lowsolid.h"
#include "vectorop.h"
Functions
void invmat (matrix mat, matrix inv, int n)
real cofactor (matrix mat, int dim, int i, int j)
real determ (matrix mat, int dim)
void matmult (matrix m, matrix m1, matrix m2)
void matminus (matrix m, matrix m1, matrix m2)
void matplus (matrix m, matrix m1, matrix m2)
void invrefine (matrix mat, matrix inv)
void matident (matrix m)
void matzer (matrix m)
int testident (matrix m, real eps)
void mattrans (matrix m, real tx, real ty, real tz)
void matrotat (matrix mat, real rx, real ry, real rz)
void matscale (matrix m, real sx, real sy, real sz)
void matcopy (matrix m1, matrix m2)
void vecmult (vector v1, vector v2, matrix m)
void matprint (matrix m)
void mattranspose (matrix m, matrix mtransp)
int comp (real f1, real f2, real tol)
real * makevec (vector v, real x, real y, real z, real w)
real dot (vector v1, vector v2)
real dot2 (vector v1, vector v2, int drop)
real vecd (vector v1, vector v2)
int vecnull (vector v, real tol)
int vecnull2 (vector vec, real eps, int drop)
int vecequal (vector v1, vector v2)
int veccolin (vector v1, vector v2, real eps)
real * cross (vector v1, vector v2, vector v3)
char normalize (vector v)
real * veccopy (vector v1, vector v2)
real * vecminus (vector res, vector v1, vector v2)
real * vecplus (vector res, vector v1, vector v2)
void vecesc (vector v, vector ve, real k)
int getdrop (vector vec)
void vecprint (vector v)
real * veczer (vector v)
real * vecpe (vector vs, vector ve, vector v, real k)
real * calc_p (vector v1, vector v2, real t, vector v)
real * vec2cp (vector v, vector o)
real vecd2 (vector v1, vector v2)
void rotmat (vector axis, real th, matrix rot)
Variables
static matrix I
FILE * trace
Function Documentation
real* calc_p (vector v1, vector v2, real t, vector v)
Definition at line 624 of file vectorop.cpp.
real cofactor (matrix mat, int dim, int i, int j)
Definition at line 74 of file vectorop.cpp.
References determ().
Referenced by determ(), and invmat().
int comp (real f1, real f2, real tol)
Definition at line 395 of file vectorop.cpp.
Referenced by angle_edge(), GenerationEdges_corners(), GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), line_inter(), MakeEdgeConvexCorner(), MakingEdges_tables(), MakingVertices_edges(), matrotat(), MSD_determinaDimensaoPrincipal(), MSD_lowDistancePlanePoint(), MSD_lowEdgEdgIntersection(), MSD_lowFaceEq(), MSD_lowFacFacEqualEqs(), MSD_lowFacFacOppositeEqs(), MSD_lowGetNeighborhood(), MSD_lowGreater(), MSD_lowImprimeListaEstudo(), MSD_lowLooVtxContainment(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowReclassifyOnSectors(), MSD_lowScale(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpGreater(), MSD_lowSetOpSectorWithin(), MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetVariaveisImpressao(), MSD_lowSolVtxContainment(), MSD_lowSplit(), MSD_lowSplitGenerate(), MSD_lowTouchAxis(), MSD_lowTouchWire(), normalize(), testident(), vecequal(), vecnull(), and vecnull2().
real* cross (vector v1, vector v2, vector v3)
Definition at line 504 of file vectorop.cpp.
References veccopy().
real determ (matrix mat, int dim)
Definition at line 103 of file vectorop.cpp.
References cofactor().
Referenced by cofactor(), invmat(), MSD_lowRotate(), MSD_lowScale(), and MSD_lowTransformation().
real dot (vector v1, vector v2)
Definition at line 419 of file vectorop.cpp.
real dot2 (vector v1, vector v2, int drop)
Definition at line 425 of file vectorop.cpp.
int getdrop (vector vec)
Definition at line 579 of file vectorop.cpp.
void invmat (matrix mat, matrix inv, int n)
Definition at line 58 of file vectorop.cpp.
References cofactor(), and determ().
Referenced by MSD_lowTransformation().
void invrefine (matrix mat, matrix inv)
Definition at line 165 of file vectorop.cpp.
References I, matminus(), matmult(), and matplus().
real* makevec (vector v, real x, real y, real z, real w)
Definition at line 409 of file vectorop.cpp.
void matcopy (matrix m1, matrix m2)
Definition at line 337 of file vectorop.cpp.
Referenced by mattranspose().
void matident (matrix m)
Definition at line 176 of file vectorop.cpp.
Referenced by MSD_execStructTransformation(), MSD_highAffine(), MSD_highRotaciona(), MSD_lowAffine(), MSD_lowMakeRotationalSweep(), MSD_lowRot90Dg(), MSD_lowRotate(), MSD_lowRotateSolidAxis(), MSD_lowRotateUsingAxis(), MSD_lowScale(), MSD_lowSetCameraTransformation(), MSD_lowTranslate(), and rotmat().
void matminus (matrix m, matrix m1, matrix m2)
Definition at line 133 of file vectorop.cpp.
Referenced by invrefine().
void matmult (matrix m, matrix m1, matrix m2)
Definition at line 122 of file vectorop.cpp.
References vecmult().
Referenced by invrefine(), and MSD_lowAffine().
void matplus (matrix m, matrix m1, matrix m2)
Definition at line 149 of file vectorop.cpp.
Referenced by invrefine(), and MSD_lowMatrizInerciaTotal().
void matprint (matrix m)
Definition at line 365 of file vectorop.cpp.
void matrotat (matrix mat, real rx, real ry, real rz)
Definition at line 244 of file vectorop.cpp.
References comp(), EPS, and PI.
Referenced by MSD_highRotaciona(), MSD_lowMakeRotationalSweep(), MSD_lowRot90Dg(), and MSD_lowRotate().
void matscale (matrix m, real sx, real sy, real sz)
Definition at line 320 of file vectorop.cpp.
Referenced by MSD_lowScale().
void mattrans (matrix m, real tx, real ty, real tz)
Definition at line 218 of file vectorop.cpp.
Referenced by MSD_lowAffine(), and MSD_lowTranslate().
void mattranspose (matrix m, matrix mtransp)
Definition at line 379 of file vectorop.cpp.
References matcopy().
void matzer (matrix m)
Definition at line 189 of file vectorop.cpp.
Referenced by MSD_lowMatrizInercia(), and MSD_lowMatrizInerciaTotal().
char normalize (vector v)
Definition at line 516 of file vectorop.cpp.
References comp(), dot(), and EPS.
void rotmat (vector axis, real th, matrix rot)
Definition at line 653 of file vectorop.cpp.
References matident().
Referenced by MSD_lowRebatePontoNoPlano(), MSD_lowRotateAxis(), MSD_lowRotateSolidAxis(), and MSD_lowRotateUsingAxis().
int testident (matrix m, real eps)
Definition at line 198 of file vectorop.cpp.
References comp(), FALSE, and SUCCESS.
real* vec2cp (vector v, vector o)
Definition at line 636 of file vectorop.cpp.
int veccolin (vector v1, vector v2, real eps)
Definition at line 494 of file vectorop.cpp.
References cross(), and vecnull().
real* veccopy (vector v1, vector v2)
Definition at line 531 of file vectorop.cpp.
real vecd (vector v1, vector v2)
Definition at line 442 of file vectorop.cpp.
real vecd2 (vector v1, vector v2)
Definition at line 644 of file vectorop.cpp.
int vecequal (vector v1, vector v2)
Definition at line 482 of file vectorop.cpp.
References comp(), and EPS.
void vecesc (vector v, vector ve, real k)
Definition at line 567 of file vectorop.cpp.
real* vecminus (vector res, vector v1, vector v2)
Definition at line 541 of file vectorop.cpp.
void vecmult (vector v1, vector v2, matrix m)
Definition at line 353 of file vectorop.cpp.
References veccopy().
Referenced by matmult(), MSD_highRotaciona(), MSD_lowInverseDisplayTransformation(), MSD_lowMakeRotationalSweep(), MSD_lowRebatePontoNoPlano(), MSD_lowRot90Dg(), MSD_lowRotate(), MSD_lowRotateAxis(), MSD_lowScale(), and MSD_lowTransformation().
int vecnull (vector v, real tol)
Definition at line 453 of file vectorop.cpp.
References comp(), and dot().
int vecnull2 (vector vec, real eps, int drop)
Definition at line 459 of file vectorop.cpp.
References comp(), FALSE, and TRUE.
real* vecpe (vector vs, vector ve, vector v, real k)
Definition at line 612 of file vectorop.cpp.
real* vecplus (vector res, vector v1, vector v2)
Definition at line 554 of file vectorop.cpp.
void vecprint (vector v)
Definition at line 600 of file vectorop.cpp.
real* veczer (vector v)
Definition at line 605 of file vectorop.cpp.
Variable Documentation
matrix I [static]
Initial value:
{
   { 1.0, 0.0, 0.0, 0.0 },
   { 0.0, 1.0, 0.0, 0.0 },
   { 0.0, 0.0, 1.0, 0.0 },
   { 0.0, 0.0, 0.0, 1.0 },
}
Definition at line 50 of file vectorop.cpp.
Referenced by invrefine().
FILE* trace