USPDesigner: C:/USPDesig/INC/vectorop.h File Reference
C:/USPDesig/INC/vectorop.h File Reference
Typedefs
typedef double real
typedef real vector [4]
typedef real matrix [4][4]
Functions
void invmat (matrix mat, matrix inv, int n)
real cofactor (matrix mat, int dim, int i, int j)
real determ (matrix mat, int dim)
void matmult (matrix m, matrix m1, matrix m2)
void matminus (matrix m, matrix m1, matrix m2)
void matplus (matrix m, matrix m1, matrix m2)
void invrefine (matrix mat, matrix inv)
void matident (matrix m)
int testident (matrix m, real eps)
void mattrans (matrix m, real tx, real ty, real tz)
void matrotat (matrix mat, real rx, real ry, real rz)
void matscale (matrix m, real sx, real sy, real sz)
void matcopy (matrix m1, matrix m2)
void vecmult (vector v1, vector v2, matrix m)
void matprint (matrix m)
void mattranspose (matrix m, matrix mtransp)
int comp (real f1, real f2, real tol)
real * makevec (real *v, real x, real y, real z, real w)
real dot (real *v1, real *v2)
real dot2 (real *v1, real *v2, int drop)
real vecd (real *v1, real *v2)
int vecnull (real *vec, real eps)
int vecnull2 (real *vec, real eps, int drop)
int vecequal (real *v1, real *v2)
int veccolin (real *v1, real *v2, real eps)
real * cross (real *v1, real *v2, real *v3)
char normalize (real *v)
real * veccopy (real *v1, real *v2)
real * vecminus (real *res, real *v1, real *v2)
real * vecplus (real *res, real *v1, real *v2)
void vecesc (real *v, real *ve, real k)
int getdrop (real *vec)
void vecprint (vector v)
real * veczer (real *v)
real vecdet (real *v1, real *v2, real *v3)
real * vecpe (real *vs, real *ve, real *v, real k)
real * calc_p (real *v1, real *v2, real t, real *v)
real * vec2cp (real *v, real *o)
real vecd2 (real *v1, real *v2)
void rotmat (vector axis, real th, matrix rot)
void matzer (matrix mat)
Typedef Documentation
typedef real matrix[4][4]
Definition at line 55 of file vectorop.h.
typedef double real
Definition at line 47 of file vectorop.h.
typedef real vector[4]
Definition at line 51 of file vectorop.h.
Function Documentation
real* calc_p (real * v1, real * v2, real t, real * v)
Referenced by MSD_lowClipingPlane(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowEdgeFaceIntersection(), MSD_lowEdgePlaneIntersection(), MSD_lowIntersectionFaceEdge(), and MSD_lowSetEdgeVisibility().
real cofactor (matrix mat, int dim, int i, int j)
Definition at line 74 of file vectorop.cpp.
References determ().
Referenced by determ(), and invmat().
int comp (real f1, real f2, real tol)
Definition at line 395 of file vectorop.cpp.
Referenced by angle_edge(), GenerationEdges_corners(), GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), line_inter(), MakeEdgeConvexCorner(), MakingEdges_tables(), MakingVertices_edges(), matrotat(), MSD_determinaDimensaoPrincipal(), MSD_lowDistancePlanePoint(), MSD_lowEdgEdgIntersection(), MSD_lowFaceEq(), MSD_lowFacFacEqualEqs(), MSD_lowFacFacOppositeEqs(), MSD_lowGetNeighborhood(), MSD_lowGreater(), MSD_lowImprimeListaEstudo(), MSD_lowLooVtxContainment(), MSD_lowMakeOpenRSweep(), MSD_lowMakeRotationalSweep(), MSD_lowReclassifyOnSectors(), MSD_lowScale(), MSD_lowSetOpDoGenerate(), MSD_lowSetOpGreater(), MSD_lowSetOpSectorWithin(), MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetVariaveisImpressao(), MSD_lowSolVtxContainment(), MSD_lowSplit(), MSD_lowSplitGenerate(), MSD_lowTouchAxis(), MSD_lowTouchWire(), normalize(), testident(), vecequal(), vecnull(), and vecnull2().
real* cross (real * v1, real * v2, real * v3)
Referenced by _line(), angle_edge(), GenerationEdges_nvertices(), line_inter(), line_parallel(), MSD_determinaDimensaoPrincipal(), MSD_lowCentroDeGravidade(), MSD_lowCheckWideness(), MSD_lowEdgEdgColinear(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowImprimeListaEstudo(), MSD_lowIntersectionCheckStep1(), MSD_lowIsInvertedEdge(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowMakeNewPoint(), MSD_lowMatrizInercia(), MSD_lowPositionalVisibility(), MSD_lowPropriedadeAreaLaco(), MSD_lowRebatePontoNoPlano(), MSD_lowReclassifyOnSectors(), MSD_lowSetEdgeAngle(), MSD_lowSetOpConvexEdge(), MSD_lowSetOpInside(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWide(), MSD_lowSetOpSectorWithin(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetVariaveisImpressao(), MSD_lowVolume(), point_perp(), and veccolin().
real determ (matrix mat, int dim)
Definition at line 103 of file vectorop.cpp.
References cofactor().
Referenced by cofactor(), invmat(), MSD_lowRotate(), MSD_lowScale(), and MSD_lowTransformation().
real dot (real * v1, real * v2)
Referenced by angle_edge(), MakingEdges_tables(), MSD_determinaDimensaoPrincipal(), MSD_determinaDimensaoPrincipalBarra(), MSD_determinaDistanciaParametrica(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakeTriangulo(), MSD_lowCalculaDimensoesRelativas(), MSD_lowCentroDeGravidade(), MSD_lowCheckWideness(), MSD_lowClipingPlane(), MSD_lowDistancePlanePoint(), MSD_lowEdgeFaceIntersection(), MSD_lowEdgePlaneIntersection(), MSD_lowEdgVtxIntersection(), MSD_lowImprimeListaEstudo(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionFaceEdge(), MSD_lowIntersectionParallelFaces(), MSD_lowIsFaceVisible(), MSD_lowIsInvertedEdge(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowMakeCone(), MSD_lowMakeCube(), MSD_lowMakeCylinder(), MSD_lowMakeNewPoint(), MSD_lowMakePrism(), MSD_lowMakePyramid(), MSD_lowMakeRotationalSweep(), MSD_lowMakeSWEEP(), MSD_lowMakeSweepNew(), MSD_lowMakeUnion(), MSD_lowMatrizInercia(), MSD_lowPositionalVisibility(), MSD_lowPropriedadeAreaLaco(), MSD_lowRebatePontoNoPlano(), MSD_lowReclassifyOnSectors(), MSD_lowSetEdgeAngle(), MSD_lowSetOpConvexEdge(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorWide(), MSD_lowSetOpSectorWithin(), MSD_lowSetOpVFReclassifyOnSectors(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetVariaveisImpressao(), MSD_lowSolidAreaProjetada(), MSD_lowSolidDimensaoPrincipal(), MSD_lowSplit(), MSD_lowTranslate(), MSD_lowVolume(), normalize(), and vecnull().
real dot2 (real * v1, real * v2, int drop)
int getdrop (real * vec)
Referenced by line_inter(), MSD_lowAllRingMove(), MSD_lowCleanSolid(), MSD_lowFacFacContainment(), MSD_lowFacVtxContainment(), and MSD_lowMakeFaceToPoint().
void invmat (matrix mat, matrix inv, int n)
Definition at line 58 of file vectorop.cpp.
References cofactor(), and determ().
Referenced by MSD_lowTransformation().
void invrefine (matrix mat, matrix inv)
Definition at line 165 of file vectorop.cpp.
References I, matminus(), matmult(), and matplus().
real* makevec (real * v, real x, real y, real z, real w)
Referenced by MSD_addCameraToMovementStructure(), MSD_CalculaParametrosInterferencia(), MSD_determinaDimensaoPrincipalBarra(), MSD_highAffine(), MSD_highCheckCamera(), MSD_highCreateAxisRotation(), MSD_highCreateAxisTranslation(), MSD_highDimensaoPrincipal(), MSD_highMoveAxis(), MSD_highMoveGroup(), MSD_highNameMakeCirculo(), MSD_highNameMakeCubo(), MSD_highNameMakeEsfera(), MSD_highNameMakePerfilI(), MSD_highNameMakePerfilL(), MSD_highNameMakePerfilT(), MSD_highNameMakePiramide(), MSD_highNameMakePlaca(), MSD_highNameMakePrisma(), MSD_highNameMakeQuadrado(), MSD_highNameMakeRetangulo(), MSD_highNameMakeROVCone(), MSD_highNameMakeTriangulo(), MSD_highNameNCopySolidSpiral(), MSD_highNameNCopySolidTranslate(), MSD_highRotateAxis(), MSD_highRotateGroup(), MSD_highRotateSolidAxis(), MSD_highSetCamera(), MSD_highSplit(), MSD_lowAlteraCamera(), MSD_lowAreaProjetada(), MSD_lowAreaProjetadaTotal(), MSD_lowCalculaDimensoesRelativas(), MSD_lowCriaListaEstudo(), MSD_lowImprimeListaEstudo(), MSD_lowRebatePontoNoPlano(), MSD_lowSetVariaveisImpressao(), MSD_lowSolidAreaProjetada(), MSD_middleCreateAxisRotation(), and MSD_middleCreateAxisTranslation().
void matcopy (matrix m1, matrix m2)
Definition at line 337 of file vectorop.cpp.
Referenced by mattranspose().
void matident (matrix m)
Definition at line 176 of file vectorop.cpp.
Referenced by MSD_execStructTransformation(), MSD_highAffine(), MSD_highRotaciona(), MSD_lowAffine(), MSD_lowMakeRotationalSweep(), MSD_lowRot90Dg(), MSD_lowRotate(), MSD_lowRotateSolidAxis(), MSD_lowRotateUsingAxis(), MSD_lowScale(), MSD_lowSetCameraTransformation(), MSD_lowTranslate(), and rotmat().
void matminus (matrix m, matrix m1, matrix m2)
Definition at line 133 of file vectorop.cpp.
Referenced by invrefine().
void matmult (matrix m, matrix m1, matrix m2)
Definition at line 122 of file vectorop.cpp.
References vecmult().
Referenced by invrefine(), and MSD_lowAffine().
void matplus (matrix m, matrix m1, matrix m2)
Definition at line 149 of file vectorop.cpp.
Referenced by invrefine(), and MSD_lowMatrizInerciaTotal().
void matprint (matrix m)
Definition at line 365 of file vectorop.cpp.
void matrotat (matrix mat, real rx, real ry, real rz)
Definition at line 244 of file vectorop.cpp.
References comp(), EPS, and PI.
Referenced by MSD_highRotaciona(), MSD_lowMakeRotationalSweep(), MSD_lowRot90Dg(), and MSD_lowRotate().
void matscale (matrix m, real sx, real sy, real sz)
Definition at line 320 of file vectorop.cpp.
Referenced by MSD_lowScale().
void mattrans (matrix m, real tx, real ty, real tz)
Definition at line 218 of file vectorop.cpp.
Referenced by MSD_lowAffine(), and MSD_lowTranslate().
void mattranspose (matrix m, matrix mtransp)
Definition at line 379 of file vectorop.cpp.
References matcopy().
void matzer (matrix mat)
Definition at line 189 of file vectorop.cpp.
Referenced by MSD_lowMatrizInercia(), and MSD_lowMatrizInerciaTotal().
char normalize (real * v)
Referenced by _line(), angle_edge(), GenerationEdges_nvertices(), lgeo_arc(), line_inter(), line_parallel(), MakingVertices_edges(), MSD_highNameNCopySolidSpiral(), MSD_highRotateGroup(), MSD_highRotateSolidAxis(), MSD_lowClip3Dimension(), MSD_lowDisplayHidden(), MSD_lowImprimeListaEstudo(), MSD_lowIntersectionCheckStep1(), MSD_lowIsEdgeVisible(), MSD_lowIsInvertedEdge(), MSD_lowMakeNewPoint(), MSD_lowMakeSweepNew(), MSD_lowRebatePontoNoPlano(), MSD_lowSetCameraTransformation(), MSD_lowSetEdgeAngle(), MSD_lowSplit(), and point_perp().
void rotmat (vector axis, real th, matrix rot)
Definition at line 653 of file vectorop.cpp.
References matident().
Referenced by MSD_lowRebatePontoNoPlano(), MSD_lowRotateAxis(), MSD_lowRotateSolidAxis(), and MSD_lowRotateUsingAxis().
int testident (matrix m, real eps)
Definition at line 198 of file vectorop.cpp.
References comp(), FALSE, and SUCCESS.
real* vec2cp (real * v, real * o)
Referenced by MSD_lowEdgeClip(), and MSD_lowEdgeEdgeIntersection().
int veccolin (real * v1, real * v2, real eps)
real* veccopy (real * v1, real * v2)
Referenced by AddCamAni(), angle_edge(), cont_point(), cross(), EdgeAttached_vertexfase1(), edv2(), edv3(), edv4(), GenerationEdges_nvertices(), GetNxtVertex(), GetPrvVertex(), MakeEdgeConcaveCorner(), MakeEdgeConvexCorner(), MakeEdgeFlatCorner(), MakingEdges_tables(), MakingVertices_edges(), MSD_determinaDimensaoPrincipal(), MSD_determinaDimensaoPrincipalBarra(), MSD_highRotaciona(), MSD_lowAddEdgeDivision(), MSD_lowAlteraCamera(), MSD_lowBisector(), MSD_lowCheckClipDisplay(), MSD_lowCheckWideness(), MSD_lowClipDisplayTransformation(), MSD_lowCreateAxisRotation(), MSD_lowCreateAxisTranslation(), MSD_lowCriaListaEstudo(), MSD_lowDisplayAllEdges(), MSD_lowDisplayHidden(), MSD_lowDisplayLocalHidden(), MSD_lowEdgeClip(), MSD_lowEdgEdgColinear(), MSD_lowEdgeEdgeIntersection(), MSD_lowEdgVtxIntersection(), MSD_lowFaceBox(), MSD_lowFacFacEqualEqs(), MSD_lowFacFacOppositeEqs(), MSD_lowGreater(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionClipDropCoord(), MSD_lowIntersectionFaceEdge(), MSD_lowIntersectionParallelFaces(), MSD_lowIsEdgeVisible(), MSD_lowIsFaceVisible(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowLooVtxContainment(), MSD_lowMakeNewPoint(), MSD_lowMakeSWEEP(), MSD_lowMakeSweepNew(), MSD_lowNameNCopySolidTranslate(), MSD_lowOrdenaListaEstudo(), MSD_lowPositionalVisibility(), MSD_lowPropriedadeAreaLaco(), MSD_lowSetCamera(), MSD_lowSetCamera3View(), MSD_lowSetEdgeAngle(), MSD_lowSetOpConnect(), MSD_lowSetOpConvexEdge(), MSD_lowSetOpInside(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWide(), MSD_lowSetOpVFGetNeighborhood(), MSD_lowSetOpVVGetNeighborhood(), MSD_lowSetOpVVReclassifySectors(), MSD_lowSetVariaveisImpressao(), MSD_lowShellBox(), MSD_lowSolidBox(), MSD_lowSolidDimensaoPrincipal(), MSD_lowSortDividedEdge(), MSD_lowVtxFacClassify(), MSD_lowVtxVtxContainment(), and vecmult().
real vecd (real * v1, real * v2)
Referenced by CLC(), cont_point(), MSD_lowCheckCamera(), MSD_lowEdgeEdgeIntersection(), MSD_lowImprimeListaEstudo(), MSD_lowSetCameraTransformation(), and MSD_lowSolidDimensaoPrincipal().
real vecd2 (real * v1, real * v2)
Referenced by MSD_lowSetCameraTransformation().
real vecdet (real * v1, real * v2, real * v3)
int vecequal (real * v1, real * v2)
Referenced by GenerationEdges_nvertices(), MakeEdgeConvexCorner(), MakingVertices_edges(), MSD_lowFacFacEqualEqs(), MSD_lowSetOpVVReclassifySectors(), and MSD_lowVtxVtxContainment().
void vecesc (real * v, real * ve, real k)
Referenced by _line(), calc_point(), GetNxtVertex(), InitListAni(), line_parallel(), MakeEdgeConcaveCorner(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_createAnimation(), MSD_determinaDimensaoPrincipalBarra(), MSD_lowCalculaDimensoesRelativas(), MSD_lowFaceCG(), MSD_lowLoopCG(), MSD_lowLooVtxContainment(), MSD_lowMakeNewPoint(), MSD_lowTransformUsingAxis(), and point_perp().
real* vecminus (real * res, real * v1, real * v2)
Referenced by _line(), angle_edge(), calc_point(), calc_t(), GenerationEdges_nvertices(), InitListAni(), lgeo_arc(), line_inter(), line_parallel(), MakingEdges_tables(), MakingVertices_edges(), MSD_createAnimation(), MSD_lowBisector(), MSD_lowCalculaDimensoesRelativas(), MSD_lowCentroDeGravidade(), MSD_lowCheckWideness(), MSD_lowDisplayHidden(), MSD_lowDisplayTransformation(), MSD_lowEdgEdgColinear(), MSD_lowEdgeEdgeCheckStep3(), MSD_lowEdgVtxIntersection(), MSD_lowIntersectionCheckStep1(), MSD_lowIntersectionParallelFaces(), MSD_lowIsEdgeVisible(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowMakeNewPoint(), MSD_lowMakeSWEEP(), MSD_lowMakeSweepNew(), MSD_lowMatrizInercia(), MSD_lowPropriedadeAreaLaco(), MSD_lowRotateAxis(), MSD_lowSetCameraTransformation(), MSD_lowSetEdgeAngle(), MSD_lowSetOpConvexEdge(), MSD_lowSetOpInside(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorWide(), MSD_lowVolume(), and point_perp().
void vecmult (vector v1, vector v2, matrix m)
Definition at line 353 of file vectorop.cpp.
References veccopy().
Referenced by matmult(), MSD_highRotaciona(), MSD_lowInverseDisplayTransformation(), MSD_lowMakeRotationalSweep(), MSD_lowRebatePontoNoPlano(), MSD_lowRot90Dg(), MSD_lowRotate(), MSD_lowRotateAxis(), MSD_lowScale(), and MSD_lowTransformation().
int vecnull (real * vec, real eps)
Referenced by MSD_determinaDimensaoPrincipal(), MSD_lowCheckWideness(), MSD_lowCleanSolid(), MSD_lowEdgEdgColinear(), MSD_lowFacFacOppositeEqs(), MSD_lowImprimeListaEstudo(), MSD_lowSetOpConvexEdge(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowSetOpSectorTest(), MSD_lowSetOpSectorWide(), MSD_lowSetOpSectorWithin(), MSD_lowSetVariaveisImpressao(), and veccolin().
int vecnull2 (real * vec, real eps, int drop)
real* vecpe (real * vs, real * ve, real * v, real k)
Referenced by MSD_lowEdgVtxIntersection(), and MSD_lowNameNCopySolidSpiral().
real* vecplus (real * res, real * v1, real * v2)
Referenced by _line(), calc_point(), CriaFrame(), line_parallel(), MakeEdgeFlatCorner(), MakingVertices_edges(), MSD_lowBisector(), MSD_lowCalculaDimensoesRelativas(), MSD_lowCentroCarenaTotal(), MSD_lowFaceCG(), MSD_lowFacFacOppositeEqs(), MSD_lowIntersectionParallelFaces(), MSD_lowInverseDisplayTransformation(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowLooVtxContainment(), MSD_lowMakeNewPoint(), MSD_lowMakeSweepNew(), MSD_lowMoveAxis(), MSD_lowNameNCopySolidTranslate(), MSD_lowPropriedadeAreaLaco(), MSD_lowRotateAxis(), MSD_lowSetOpNbaPreProcess(), MSD_lowSetOpNbbPreProcess(), MSD_lowTranslate(), MSD_lowVolume(), and point_perp().
void vecprint (vector v)
Definition at line 600 of file vectorop.cpp.
real* veczer (real * v)
Referenced by _line(), calc_t(), line_parallel(), MakingVertices_edges(), MSD_lowCentroCarenaTotal(), MSD_lowCentroDeGravidade(), MSD_lowCentroMassaTotal(), MSD_lowFaceCG(), MSD_lowFaceEq(), MSD_lowLoopArea(), MSD_lowLoopCG(), MSD_lowNameNCopySolidSpiral(), MSD_lowPropriedadeAreaLaco(), MSD_lowTranslate(), and point_perp().